### ISSUE TITLE
Help Translate Appwrite to Telugu Language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1543]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite's templates into **Telugu** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Telugu in `app/config/locale/translations/te.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Comment by vydyas** [comment]
Hey @Meldiron, I'm from India and my mother tongue is Telugu.I'm a passionate developer I would like to complete this as part of Hacktoberfest. please assign this to me

**Comment by Likith2000** [comment]
Hi @Meldiron, would love to work on this. Can you please assign the task?

**Comment by Haimantika** [comment]
> Hey @Meldiron, I'm from India and my mother tongue is Telugu.I'm a passionate developer I would like to complete this as part of Hacktoberfest. please assign this to me

Hi @vydyas would you still like to work on this?
