### ISSUE TITLE
Help improve Appwrite's Arabic language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1673]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Arabic** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Arabic in `app/config/locale/translations/ar.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by satyamgupta1495** [comment]
I wanna try working on this issue! could you please assign me this?

**Comment by arsangamal** [comment]
As an Egyptian and a native Arabic speaker, I am very happy to see this.
I will work on this @Meldiron, thank you so much!

**Comment by christyjacob4** [comment]
@arsangamal assgined it to you :)

**Comment by arsangamal** [comment]
@Meldiron @christyjacob4 issue done and opened a PR #1800

**Comment by Meldiron** [comment]
@arsangamal Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be release with **Appwrite 0.11**
