### ISSUE TITLE
Help improve Appwrite's Bengali language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1676]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Bengali** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Bengali in `app/config/locale/translations/bn.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by deepto98** [comment]
@Meldiron Hi, I'm a native Bengali speaker, from India and can help with this translation. Can you please assign this to me?

**Comment by RollingThunderSagnik** [comment]
@Meldiron I'm a native Bengali speaker from West Bengal, India. I would like to work on this. Can you assign this to me?

**Comment by Hard-Coder05** [comment]
@Meldiron I would like to work on this issue!

**Comment by christyjacob4** [comment]
@deepto98  All the best :rocket:

**Comment by christyjacob4** [comment]
@RollingThunderSagnik  We would love you to check out some of our other open issues and join us on discord if you need help finding some  https://appwrite.io/discord

**Comment by TasnimAnas** [comment]
I'm a native Bengali speaker from Bangladesh. I would like to work on this issue

**Comment by lohanidamodar** [comment]
@TasnimAnas We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by appledora** [comment]
> @deepto98 This issue would be reassigned soon if you're not actively working on it +1

@christyjacob4 Kindly, reassign me this, if possible.

**Comment by lohanidamodar** [comment]
> > @deepto98 This issue would be reassigned soon if you're not actively working on it +1
> 
> @christyjacob4 Kindly, reassign me this, if possible.

@appledora give us some time to validate that @deepto98 is not working on this 🙏🏻

**Comment by deepto98** [comment]
Hi, I'll try to complete this by tomorrow, was a bit busy with work, will keep you updated

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chandrikadeb7** [comment]
@lohanidamodar Please reassign this issue.

**Comment by lohanidamodar** [comment]
@chandrikadeb7 We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by lohanidamodar** [comment]
@deepto98 please check in regarding progress 🙏🏻

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!
