### ISSUE TITLE
Help improve Appwrite's German language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1680]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **German** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for German in `app/config/locale/translations/de.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by vincentrohde** [comment]
@Meldiron I am a native German speaker, if you want I could help you with the translations :)

**Comment by SoftCreatR** [comment]
Sorry for the hijacking. Didn't notice, that an issue already exists.
