### ISSUE TITLE
Help improve Appwrite's Greek language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1681]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Greek** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Greek in `app/config/locale/translations/el.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Red-0111** [comment]
Hi! I would like to work on this issue :D

**Comment by christyjacob4** [comment]
@Red-0111  We're looking for native Greek speakers for this issue. We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by PrerakMathur20** [comment]
Hello,
I would like to work on this issue. 
Here are 2 contributing reasons why I'd like to work on this issue:
1. Its October aka Hacktoberfest Month, and I want to increase my open source contributions.
2. My sister is a Greek Teacher, and can easily help me out on this one.

**Comment by kostapappas** [comment]
Hi! I would like to work on this issue. 
Native Greek speaker here.

**Comment by lohanidamodar** [comment]
@kostapappas assigned to you. All the best 🚀

**Comment by lohanidamodar** [comment]
@PrerakMathur20 We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by kostapappas** [comment]
> @kostapappas assigned to you. All the best 🚀

@lohanidamodar I have made the pull request -> https://github.com/appwrite/appwrite/pull/1869
but I can't connect it with this issue. Do I need to do anything more?

**Comment by christyjacob4** [comment]
@kostapappas  You need to edit the PR and update the PR description with all the required questions 

![Screenshot from 2021-10-06 00-47-59](https://user-images.githubusercontent.com/20852629/136088642-c3da7e34-9da2-4c31-b286-d87d61b3c079.png)

**Comment by kostapappas** [comment]
> @kostapappas You need to edit the PR and update the PR description with all the required questions
> 
> ![Screenshot from 2021-10-06 00-47-59](https://user-images.githubusercontent.com/20852629/136088642-c3da7e34-9da2-4c31-b286-d87d61b3c079.png)

thanks. I re-created the pull request with all the needed requirements. Thanks for you guidelines and time. :)

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**
