### ISSUE TITLE
Help improve Appwrite's Spanish language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1683]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Spanish** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Spanish in `app/config/locale/translations/es.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by ArmanChand** [comment]
hello @Meldiron ,
I can take this PR.

**Comment by christyjacob4** [comment]
@ArmanChand  We're looking for native Spanish speakers for this translation issue

**Comment by chuiizeet** [comment]
Hola!
I can take this 😊

**Comment by OscarRG** [comment]
I tried to push the translation but im getting the error: Permission to appwrite/appwrite.git denied to OscarRG. Could you give me access? Thx

**Comment by OscarRG** [comment]
I submitted my [PR](https://github.com/appwrite/appwrite/pull/1819)  :)

**Comment by isayas** [comment]
Here's my contribution @christyjacob4 
[PR](https://github.com/appwrite/appwrite/pull/1826)

**Comment by christyjacob4** [comment]
@chuiizeet  All the best :rocket:

**Comment by christyjacob4** [comment]
@OscarRG  @isayas  Please create your PR after you've been assigned to an issue.

**Comment by chuiizeet** [comment]
@christyjacob4 i submitted my [PR](https://github.com/appwrite/appwrite/pull/1833)

**Comment by OscarRG** [comment]
> @OscarRG  Please create your PR after you've been assigned to an issue.

Hi @christyjacob4 Sorry i submitted the PR because I saw that it was not assigned to anybody :S sorry
