### ISSUE TITLE
Help improve Appwrite's Finnish language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1685]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Finnish** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Finnish in `app/config/locale/translations/fi.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by minna-xD** [comment]
I'd be happy to contribute the Finnish translation for the missing parts but I'm not 100% confident I'm savvy enough to test it... The translation part I'm confident about. I lived and breathed SW translations for 15 years in my previous job. :)

**Comment by christyjacob4** [comment]
@minna-xD All the best :rocket:

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**
