### ISSUE TITLE
Help improve Appwrite's Gujarati language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1688]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Gujarati** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Gujarati in `app/config/locale/translations/gu.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by jaysudani** [comment]
Hi, I am beginner in Open-source, I am from Gujarat and I know Gujrati language very well. Can I work on this?

**Comment by honeykpatel** [comment]
Can you please assign this issue to me, I'm a native Gujarati speaker from Ahmedabad.

**Comment by sakshamgurbhele** [comment]
I am intrested in taking this issue, I am not a native speaker but I can speak and understand Gujarati well. Let me know If I can work on this. Thank You :)

**Comment by christyjacob4** [comment]
@honeykpatel  All the best :rocket:

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be release with **Appwrite 0.11**
