### ISSUE TITLE
Help improve Appwrite's Hindi language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1690]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Hindi** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Hindi in `app/config/locale/translations/hi.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by willtryagain** [comment]
Hi. I would like to work on this. Please assign it to me.

**Comment by shashank1503-cipher** [comment]
Hi, I would like to work on this. Would be great working on it if I get assigned to this :)

**Comment by lovetyagi-17** [comment]
नमस्ते, मुझे इस पर काम करना अच्छा लगेगा, कृपया यह काम मुझे सौंप दें।
धन्यवाद..

**Comment by suprabhasupi** [comment]
I would love to pick this up 😍

**Comment by Shrey-Nahar** [comment]
I would also like to work this issue

**Comment by Nikhil-1503** [comment]
I would like to work on this. Please assign it to me.

**Comment by agarwalraghav1687** [comment]
I would love to work on this one

**Comment by Hard-Coder05** [comment]
@Meldiron I would like to work on this issue! Please assign it to me!

**Comment by Vidushi-Gupta** [comment]
Hi! I hope the assignments for Hacktoberfest have begun. Could you please assign it to me for the hacktoberfest?

**Comment by dahiya-code** [comment]
Hi! I am from india and my mother tongue is Hindi! I believe I can do justice to this project

**Comment by christyjacob4** [comment]
@willtryagain  All the best :rocke

**Comment by christyjacob4** [comment]
@shashank1503-cipher We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by christyjacob4** [comment]
@lovetyagi-17  We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by christyjacob4** [comment]
@suprabhasupi  We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by christyjacob4** [comment]
@Shrey-Nahar  We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by christyjacob4** [comment]
@Nikhil-1503 We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by christyjacob4** [comment]
@agarwalraghav1687  We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by christyjacob4** [comment]
@Hard-Coder05  We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by christyjacob4** [comment]
@Vidushi-Gupta  We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by christyjacob4** [comment]
@dahiya-code  We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by Itashamodi** [comment]
I want to work on it.

**Comment by lohanidamodar** [comment]
@Itashamodi We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by Shubham56-droid** [comment]
i would  like to contribute i am native indian and know Hindi pls assign issue to me

**Comment by christyjacob4** [comment]
@Shubham56-droid  This issue has been fixed :+1:

**Comment by idivyanshbansal** [comment]
Sir may I help with this contribution as I made this request earlier but you marked it invalid because I was not assigned. 
Please give me a chance  

https://github.com/appwrite/appwrite/pull/1926

**Comment by lohanidamodar** [comment]
@mayankgoyal-13 @idivyanshbansal as you can see this was assigned and completed already. We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.
