### ISSUE TITLE
Help improve Appwrite's Hungarian language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1691]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Hungarian** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Hungarian in `app/config/locale/translations/hu.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by kristofkalocsai** [comment]
heyo, I'd love to contribute to this!

**Comment by lohanidamodar** [comment]
@kristofkalocsai can you confirm you are a Native speaker?

**Comment by kristofkalocsai** [comment]
I can assure you that Hungarian is my native tongue.
Biztosíthatlak róla, hogy a magyar az anyanyelvem.

**Comment by lohanidamodar** [comment]
@kristofkalocsai Assigned to you. All the best 🚀

**Comment by kristofkalocsai** [comment]
roger

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!
