### ISSUE TITLE
Help improve Appwrite's Armenian language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1692]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Armenian** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Armenian in `app/config/locale/translations/hy.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by Prakhar-Agarwal-byte** [comment]
Hi! I would like to contribute :) Can I have this issue assigned?

**Comment by Prakhar-Agarwal-byte** [comment]
I have added Armenian translations. 😀

**Comment by Prakhar-Agarwal-byte** [comment]
@lohanidamodar I understand, sorry for any inconvenience caused

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
