### ISSUE TITLE
Help improve Appwrite's Italian language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1695]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Italian** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Italian in `app/config/locale/translations/it.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by ilmalte** [comment]
Italian native speaker here, I would be happy to contribute! 😄

**Comment by christyjacob4** [comment]
@ilmalte  All the best :rocket:

**Comment by Defkon1** [comment]
https://github.com/appwrite/appwrite/pull/1809

**Comment by christyjacob4** [comment]
@Defkon1 Please create your PR after you've been assigned to an issue.

**Comment by Defkon1** [comment]
ok... so I have to delete the PR?

**Comment by ilmalte** [comment]
No problem @Defkon1 :)
Closed by [#1824](https://github.com/appwrite/appwrite/pull/1824)
