### ISSUE TITLE
Help improve Appwrite's Javanese language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1697]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Javanese** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Javanese in `app/config/locale/translations/jv.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by vancassa** [comment]
I can help with this. Please assign it to me.

**Comment by christyjacob4** [comment]
@vancassa All the best :rocke

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!
