### ISSUE TITLE
Help improve Appwrite's Korean language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1700]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Korean** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Korean in `app/config/locale/translations/ko.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by ssong** [comment]
I can take this up, noticed a few errors as well so can get those sorted.

**Comment by ssong** [comment]
Noticed I added my comment like a few min too early - could I get this assigned please? :) and is there any specific guidance around testing the email translations?

**Comment by christyjacob4** [comment]
@ssong  All the best :rocket:  

You can run Appwrite locally and run the e2e tests for the `Teams` or `Accounts` service. This will send the emails to the `maildev` server at `localhost:9503`
