### ISSUE TITLE
Help improve Appwrite's Malayalam language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1702]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Malayalam** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Malayalam in `app/config/locale/translations/ml.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by anoopmsivadas** [comment]
Hey, Can I work on this

**Comment by joeljose350** [comment]
I would love to work on this issue, I'm a native Malayalam speaker from Kochi, India.

**Comment by SpooderManEXE** [comment]
Can i be assigned to this task?

**Comment by alceil** [comment]
Can I be assigned to this task since I'm a native Malayalam speaker. I can help translate it better.

**Comment by vivekkj123** [comment]
Hi, I would like to work on this issue. Please assign this issue to me. I've translated various applications to my native language malayalam.

Thanks.

**Comment by cr1spyvada** [comment]
Hello, I would like to work on this task?

**Comment by christyjacob4** [comment]
@anoopmsivadas  All the best :rocket:

**Comment by christyjacob4** [comment]
@joeljose350  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
@SpooderManEXE  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
@alceil  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
@vivekkj123  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
@cr1spyvada  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by anandhu720** [comment]
@cr1spyvada  hey I would like to help you. I am a native malayalam speaker

**Comment by Meldiron** [comment]
@anandhu720 We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by anandhu720** [comment]
@Meldiron I joined.How can I contact you there

**Comment by Meldiron** [comment]
@anandhu720 You can message me, the same name as here `Meldiron`. Or just ask in `#hacktoberfest` channel.

**Comment by anandhu720** [comment]
sure

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**

**Comment by TorstenDittmann** [comment]
This got released now! Thanks a lot for your contribution @anoopmsivadas 👏🏻
