### ISSUE TITLE
Help improve Appwrite's Marathi language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1703]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Marathi** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Marathi in `app/config/locale/translations/mr.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by vj-codes** [comment]
@Meldiron hey I'm a native marathi speaker, would like to be assigned for this issue. Thankss in advance:)

**Comment by omnaladkar** [comment]
@Meldiron Hey , I have 18 years of experience in marathi language talking because I am from maharashtra and i know whole marathi.

**Comment by sakshamgurbhele** [comment]
I am also available to take upon this issue, I am a native speaker. Let me know If I can work on this. 
Thank you :)

**Comment by dishanttayade** [comment]
Is this issue still open? If it is please inform. I would like to contribute here.

**Comment by christyjacob4** [comment]
@omnaladkar  All the best :rocket:

**Comment by christyjacob4** [comment]
@vj-codes  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
@dishanttayade  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by vj-codes** [comment]
@christyjacob4 can this be assigned to me? I thought the first one to comment usually gets assigned? 
PS - I have created a PR #1786

**Comment by christyjacob4** [comment]
@vj-codes  I understand your concern but we have over a 100 open issues here https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues

Feel free to pick up any one of them :smile:

**Comment by omnaladkar** [comment]
@christyjacob4  Done

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
