### ISSUE TITLE
Help improve Appwrite's Nepali language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1705]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Nepali** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Nepali in `app/config/locale/translations/ne.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by TheLearneer** [comment]
Hi there 👋
I would like to take this task. For two reasons:
- It's **Hacktoberfest**
- Spread some love from Nepal

**Comment by TheLearneer** [comment]
Hi there 👋
I would like to take this task. For two reasons:
- It's **Hacktoberfest** season, contribution to open-source is the first thing that comes to mind
- Spread some love from Nepal

**Comment by christyjacob4** [comment]
@TheLearneer We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be release with **Appwrite 0.11**

**Comment by idivyanshbansal** [comment]
@lohanidamodar sir for this issue you need someone else 😁
