### ISSUE TITLE
Help improve Appwrite's Dutch language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1706]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Dutch** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Dutch in `app/config/locale/translations/nl.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by adavijit** [comment]
Hi , @Meldiron 
I am native Dutch speaker. Please assign this task to me

**Comment by christyjacob4** [comment]
@adavijit  Unfortunately your Github profile indicates a different region.

**Comment by ArtixAllMighty** [comment]
Hello, I'm a native Dutch speaker, I live in Belgium, i'd love to make a PR for the dutch language.

**Comment by lohanidamodar** [comment]
@ArtixAllMighty assigned to you. All the best.

**Comment by ArtixAllMighty** [comment]
A pr has been submitted
