### ISSUE TITLE
Help improve Appwrite's Oriya language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1708]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Oriya** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Oriya in `app/config/locale/translations/or.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by Rutam21** [comment]
@Meldiron Odia is my mother tongue. I would be happy to work on it. Thanks.

**Comment by Rutam21** [comment]
@Meldiron It's called `Odia` now. This is my mother tongue and I can definitely work on this ticket. Feel free to assign this to me. Thanks.

**Comment by christyjacob4** [comment]
@Rutam21 all the best
