### ISSUE TITLE
Help improve Appwrite's Panjabi / Punjabi language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1709]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Panjabi / Punjabi** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Panjabi / Punjabi in `app/config/locale/translations/pa.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by lovetyagi-17** [comment]
I have knowledge of Panjabi / Punjabi speaking, assign this task to me.

**Comment by Hard-Coder05** [comment]
@Meldiron I have worked on this issue. Kindly review it and merge the same!

**Comment by christyjacob4** [comment]
@lovetyagi-17  All the best :rocket:

**Comment by christyjacob4** [comment]
@Hard-Coder05 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Hard-Coder05** [comment]
@christyjacob4 I have not been assigned any of the issues yet!

**Comment by Hard-Coder05** [comment]
@Meldiron @christyjacob4 It's quite weird to see that a single person is assigned 4 issues at the same time.

https://github.com/appwrite/appwrite/issues/1782

https://github.com/appwrite/appwrite/issues/1780

https://github.com/appwrite/appwrite/issues/1757

https://github.com/appwrite/appwrite/issues/1708

**Comment by Meldiron** [comment]
@Hard-Coder05 If you truly haven't been assigned to anything, I am really sorry. It's hard to keep track of everything, we are humans, we do mistakes too.

This issue already has an assignee, please pick another one and I will mark you as assignee.

**Comment by Hard-Coder05** [comment]
@Meldiron Sure! No problem. I would go through the other issues!

**Comment by adsingh14** [comment]
Hi there ! 
If you need any help for Punjabi l10n, just reply. :)

**Comment by lohanidamodar** [comment]
@adsingh14 We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by paarthchhabra** [comment]
Can you please assign this issue? I've made the translation changes and made a pull request.

**Comment by lohanidamodar** [comment]
@idivyanshbansal @paarthchhabra as you can see the issue is already assigned. We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
