### ISSUE TITLE
Help improve Appwrite's Polish language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1710]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Polish** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Polish in `app/config/locale/translations/pl.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by achromik** [comment]
Hi. I'm a native Polish speaker. I'd like to work on this one :)

**Comment by christyjacob4** [comment]
@achromik  All the best :)

**Comment by KaminskiDaniell** [comment]
Hello, Is this task stiil available? I'm Polish, so I think, that I can handle the task :)

**Comment by christyjacob4** [comment]
@KaminskiDaniell  I'm sorry but this issue has already been assigned. We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by TorstenDittmann** [comment]
This got released now! Thanks a lot for your contribution @achromik 👏🏻
