### ISSUE TITLE
Help improve Appwrite's Portugal (Brazil) language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1711]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Portugal (Brazil)** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Portugal (Brazil) in `app/config/locale/translations/pt-br.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by renato04** [comment]
Hi!
Could you assign me to this issue?

**Comment by christyjacob4** [comment]
@renato04 All the best :rocket:

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**

**Comment by nataliarossini** [comment]
Hey I'm a native pt-br speaker, I've noticed some small spelling errors and grammar that could be improved, I'd be happy to help if that's ok :)

**Comment by lohanidamodar** [comment]
@nataliarossini feel free to submit another PR with the fixes. Thank you.

**Comment by nataliarossini** [comment]
@lohanidamodar Hey I've submitted a PR #2128, hope it's all good, thank you! 😊

**Comment by lohanidamodar** [comment]
@nataliarossini Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**
