### ISSUE TITLE
Help improve Appwrite's Russian language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1714]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Russian** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Russian in `app/config/locale/translations/ru.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by daniloff200** [comment]
hey!
I live in Ukraine, but, Russian is my second native language, i'm bilingual, for Ukraine it's common thing, so, I can pick this one too

**Comment by christyjacob4** [comment]
@daniloff200 all the best

**Comment by TorstenDittmann** [comment]
This got released now! Thanks a lot for your contribution @daniloff200 👏🏻
