### ISSUE TITLE
Help improve Appwrite's Sinhalese language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1715]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Sinhalese** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Sinhalese in `app/config/locale/translations/si.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by ChathushkaRodrigo** [comment]
i will give it a try

**Comment by christyjacob4** [comment]
@ChathushkaRodrigo  All the best

**Comment by anukindipa** [comment]
can i try it too?

**Comment by christyjacob4** [comment]
@anukindipa  This issue is already assigned. You can check back in a few days for the progress updates. We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
@ChathushkaRodrigo Unfortunately we'd have to reassign this issue as there has been no communication from your end
