### ISSUE TITLE
Help improve Appwrite's Tamil language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1719]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Tamil** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Tamil in `app/config/locale/translations/ta.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by Hard-Coder05** [comment]
@Meldiron I have worked on this issue! Do review and merge it!

**Comment by christyjacob4** [comment]
@Hard-Coder05  Are you a native Tamil Speaker ?

**Comment by christyjacob4** [comment]
![Screenshot from 2021-10-01 13-41-40](https://user-images.githubusercontent.com/20852629/135587388-a0627042-170f-4d59-aefb-2b0f613ecf6a.png)

**Comment by ilangorajagopal** [comment]
Hey. I'm a native Tamil speaker. I can double check the translations and make corrections if necessary?

**Comment by christyjacob4** [comment]
@ilangorajagopal  All the best :rocket:

**Comment by santhosh-chinnasamy** [comment]
Hi , I have changed few strings to most appropriate words.

**Comment by christyjacob4** [comment]
@santhosh-chinnasamy This issue is already assigned. We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by santhosh-chinnasamy** [comment]
@christyjacob4 okay I will.

**Comment by lohanidamodar** [comment]
@santhosh-chinnasamy please give them some time to work on. We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Shrey-Nahar** [comment]
Since there was no response from long time. I decided to work on the issue.
please review the code.
@christyjacob4 @lohanidamodar

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!
