### ISSUE TITLE
Help improve Appwrite's Thai language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1720]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Thai** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Thai in `app/config/locale/translations/th.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by teeradon43** [comment]
Hello, I am ready for this. Please assign this to me 🙂👍

**Comment by teeradon43** [comment]
@Meldiron

**Comment by christyjacob4** [comment]
@teeradon43  please confirm you are a native Thai speaker ?

**Comment by teeradon43** [comment]
@christyjacob4 Yeah sure. I am Thai, and I can help you with this.

**Comment by christyjacob4** [comment]
Awesome! All the best @teeradon43  :+1:

**Comment by teeradon43** [comment]
I've done all the tasks. Please check PR [#1851](https://github.com/appwrite/appwrite/pull/1851)

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**
