### ISSUE TITLE
Help improve Appwrite's Turkish language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1722]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Turkish** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Turkish in `app/config/locale/translations/tr.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by MohammedHamzaMalik** [comment]
Hey @Meldiron , I would like to work on this issue. Can you assign it to me?

**Comment by CilgaIscan** [comment]
Hi @Meldiron, I hope you are doing well, I am interested in this issue. As a native Turkish speaker, I hope I can complete this task :)

**Comment by christyjacob4** [comment]
@CilgaIscan All the best :rocket:

**Comment by christyjacob4** [comment]
@MohammedHamzaMalik As we mentioned the translation issues are specifically for folks who speak the language natively.

**Comment by dropkick-exe** [comment]
@christyjacob4 Can I be assigned, I'm a native Turkish speaker as well and already done translating.

**Comment by lohanidamodar** [comment]
@dropkick-exe Hey, as you can see it's already assigned to someone else. We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by malikdoksoz** [comment]
Why hasn't it been translated yet?
[https://github.com/appwrite/appwrite/blob/master/app/config/locale/translations/tr.json](https://github.com/appwrite/appwrite/blob/master/app/config/locale/translations/tr.json)

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
