### ISSUE TITLE
Help improve Appwrite's Ukrainian language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1723]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Ukrainian** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Ukrainian in `app/config/locale/translations/uk.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by daniloff200** [comment]
hey!
I'm native Ukrainian speaker and can pick this one!

**Comment by christyjacob4** [comment]
@daniloff200  All the best :rocket:

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be release with **Appwrite 0.11**
