### ISSUE TITLE
Help improve Appwrite's Urdu language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1724]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Urdu** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Urdu in `app/config/locale/translations/ur.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by Rutam21** [comment]
@Meldiron I have come greatly in the influence of Urdu Speaking folks during my 4 years of Engineering and I can definitely take care of those strings easily. Feel free to assign this to me.

**Comment by arsheelsheikh** [comment]
Hello, I would like to work on this issue.
I can very well read and write Urdu. 

Thank You, looking forward to work on this issue.

**Comment by christyjacob4** [comment]
@arsheelsheikh  All the best :rocket:

**Comment by christyjacob4** [comment]
@Rutam21  We require a native Urdu speaker to help with this translation task :) We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by arsheelsheikh** [comment]
Thank You @christyjacob4

**Comment by wal33dahmad** [comment]
Hello, @christyjacob4 I am a natural Urdu speaker who can write and speak Urdu fluently and proficiently. But, I am new to the open-source community. Is it possible for you to give this work to me as well?

**Comment by arsheelsheikh** [comment]
@christyjacob4 I have added PR translation for Urdu language https://github.com/appwrite/appwrite/pull/2013

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
