### ISSUE TITLE
Help improve Appwrite's Vietnamese language translation ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1725]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to improve them! 💪

Your task is to update Appwrite's **Vietnamese** language translations. We recently added new features, so some translations might be missing. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

This is what missing translation would look like:

```json
"emails.magicSession.footer": "",
```

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Update translations for Vietnamese in `app/config/locale/translations/vi.json`
- [ ] Test the translations
- [ ] Push changes and submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by hdkhoasgt** [comment]
Could you assign this issue to me?

**Comment by christyjacob4** [comment]
@hdkhoasgt  All the best :Rocket

**Comment by hdkhoasgt** [comment]
> @hdkhoasgt All the best :Rocket

@christyjacob4
Please help me check this pull request https://github.com/appwrite/appwrite/pull/1880

**Comment by lohanidamodar** [comment]
> > @hdkhoasgt All the best :Rocket
> 
> @christyjacob4 Please help me check this pull request #1880

Great work 🚀 No worries, our team will go through all the PRs, no one will be left out.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**

**Comment by lohanidamodar** [comment]
@idivyanshbansal We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.
