### ISSUE TITLE
Help Translate Appwrite to Assamese language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1728]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Assamese** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Assamese in `app/config/locale/translations/as.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by manojkrishnak** [comment]
Hey, i will take this up. 

There is no as.json as mentioned above in this path `app/config/locale/translations/as.json`

**Comment by christyjacob4** [comment]
@manojkrishnak  please confirm that you are a native Assamese speaker ?

**Comment by manojkrishnak** [comment]
My friend is a native Assamese speaker, he will help me.

**Comment by PrerakMathur20** [comment]
Hello, I'd like work on this issue. 
I know i little Assamese, and I also have 2 Assamese brothers who are willing to help me out here.

P.S. @manojkrishnak is right, there is no ```as.json``` in the path. But its not an issue, I can create a new file with exactly same layout as others, if assigned.

**Comment by christyjacob4** [comment]
@manojkrishnak  We're waiting to hear from you. Let us know if you are a native Assamese speaker and we can assign it to you. Else we'll assign this one to @PrerakMathur20

**Comment by manojkrishnak** [comment]
@christyjacob4, I'm not but a friend of mine is, same as @PrerakMathur20. You can assign this issue to @PrerakMathur20 .

**Comment by PrerakMathur20** [comment]
Thank you @manojkrishnak. Looking forward to it.

**Comment by christyjacob4** [comment]
@PrerakMathur20  All the best :+1:

**Comment by PrerakMathur20** [comment]
Thank you for assigning this issue to me. I'll start working on it immediately.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**
