### ISSUE TITLE
Help Translate Appwrite to Bihari language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1730]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Bihari** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Bihari in `app/config/locale/translations/bh.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by Hard-Coder05** [comment]
@Meldiron Please assign me this issue. I am native residence from Bihar. And just to clarify, people in bihar speak Maithili (not Bihari). Please do correct this in the issue name and description as well.

**Comment by dazzlerkumar** [comment]
@Meldiron Hi, How are you? 
You can assign me this task as well. Although, I want to correct few things. Bihari isn't the language of Bihar. 25% of Bihar People speak **Hindi** as well **Bhojpuri**. I guess creators want to target Bhojpuri-speaking people. I want to inform you that Bhojpuri is used in _East Uttar Pradesh_, _Bihar_, _Jharkhand_, and is the official language of Fiji as well as Suriname (South American Country). 
@Hard-Coder05 Hi, Maithili is only spoken by 12% of people residing in Bihar. 
Thank you for reading.

**Comment by starrohan999** [comment]
@Meldiron  Can I also work on this I am from Bihar sitamarhi.

**Comment by HarshitPandey251** [comment]
@Meldiron I am also from Bihar and this is my first issue can you assign to me. Please

**Comment by christyjacob4** [comment]
The ISO language code [`bh`](https://www.loc.gov/standards/iso639-2/php/code_list.php) refers to Bihari Languages which is a coalition of [Bhojpuri, Maithili and Magadhi](https://www.mapsofindia.com/bihar/bihar-at-a-glance/languages.html) . So this is the translation that we are expecting.

**Comment by christyjacob4** [comment]
@dazzlerkumar All the best :rocket:

**Comment by christyjacob4** [comment]
@HarshitPandey251 @starrohan999 @Hard-Coder05 We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by dazzlerkumar** [comment]
@christyjacob4 , Thank you! I've added translation for Maithili in bh.json but I want to inform you that Maithili has its own code `MAI` and I already made translations for Bhojpuri. Does appwrite will support Bhojpuri in future?

**Comment by christyjacob4** [comment]
@dazzlerkumar thank you for your contribution. We will review it in the coming days :+1: 

Right now we're following the ISO 639-1 codes which are 2 letter language codes and does not support `MAI` whereas ISO 639-2 standards use three letter codes. When we do perform a migration, we would love to include many more languages, but right now, we're confined to the [ISO 639-1 list](https://lingohub.com/academy/best-practices/iso-639-1-list)

**Comment by prasadsunny1** [comment]
More than surprised to see something being translated into bihari languages
