### ISSUE TITLE
Help Translate Appwrite to Esperanto language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1735]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Esperanto** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Esperanto in `app/config/locale/translations/eo.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by tacoelho** [comment]
Can I take this one?

**Comment by lohanidamodar** [comment]
@tacoelho Assigned to you. All the best 🚀

**Comment by fernandakawasaki** [comment]
Hey! I was looking at the json file and realized that the country and continent names were not translated. May I take it?
