### ISSUE TITLE
Help Translate Appwrite to Irish language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1737]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Irish** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Irish in `app/config/locale/translations/ga.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by ivernus** [comment]
I'm happy to take a look at this 👍

**Comment by lohanidamodar** [comment]
@ivernus can you please confirm you are a native irish speaker?

**Comment by ivernus** [comment]
> 
> 
> @ivernus can you please confirm you are a native irish speaker?

Yes indeed @lohanidamodar

**Comment by lohanidamodar** [comment]
@ivernus assigned to you. All the best 🚀

**Comment by TorstenDittmann** [comment]
This got released now! Thanks a lot for your contribution @ivernus 👏🏻

**Comment by ivernus** [comment]
Thanks @TorstenDittmann , could you also drag in #2198  also which is related?
