### ISSUE TITLE
Help Translate Appwrite to Latin language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1746]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Latin** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Latin in `app/config/locale/translations/la.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by fernandoamz** [comment]
heey @Meldiron, Can I take it?

**Comment by christyjacob4** [comment]
@fernandoamz  All the best :rocket:

**Comment by fernandoamz** [comment]
Can you help me to review it? Here is the PR https://github.com/appwrite/appwrite/pull/1830

**Comment by lohanidamodar** [comment]
@fernandoamz no worries, All the PRs will be reviewed.

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
