### ISSUE TITLE
Help Translate Appwrite to Luxembourgish language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1747]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Luxembourgish** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Luxembourgish in `app/config/locale/translations/lb.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by OscarRG** [comment]
Hi @Meldiron i would like to work on this, could you assign it to me? :)

**Comment by christyjacob4** [comment]
@OscarRG  Please confirm you're a native Luxembourgish speaker

**Comment by OscarRG** [comment]
Hey @christyjacob4 I can confirm that I have a good knowledge of luxembourgish. If you want I can update the names of the countries and if nobody is interested in doing the translation I can do it without problem :)

**Comment by lohanidamodar** [comment]
@OscarRG  Assigned to you. All the best 🚀

**Comment by OscarRG** [comment]
Hello @lohanidamodar you can find [here the PR](https://github.com/appwrite/appwrite/pull/1857) :)
