### ISSUE TITLE
Help Translate Appwrite to Norwegian Bokmål language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1755]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Norwegian Bokmål** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Norwegian Bokmål in `app/config/locale/translations/nb.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by Exouxas** [comment]
Hey! I'd like to do this task, could you assign it to me?

**Comment by lohanidamodar** [comment]
@Exouxas hi can you confirm you are native Norwegian Bokmål speaker?

**Comment by Exouxas** [comment]
@lohanidamodar Yes sir! Do you need any proof of it? I'm born and raised in Norway, and Bokmål is my way of writing.

**Comment by lohanidamodar** [comment]
@Exouxas assigned to you. All the best 🚀
