### ISSUE TITLE
Help Translate Appwrite to Sanskrit language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1757]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Sanskrit** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Sanskrit in `app/config/locale/translations/sa.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by Hard-Coder05** [comment]
@Meldiron I would like to take this issue!

**Comment by Rutam21** [comment]
@Meldiron I come from a family with Sanskrit background, even my Dad is a Professor in Sanskrit at the moment. I believe I can do justice to this ticket.

**Comment by Rutam21** [comment]
@Meldiron Well, my father is a Professor in Sanskrit. I feel I can do this justice with this ticket. Feel free to assign this to me.
(It's already 1st Oct in IST.😅 )

**Comment by agarwalraghav1687** [comment]
Hey! Would love to take this issue :)

**Comment by lohanidamodar** [comment]
@agarwalraghav1687  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**
