### ISSUE TITLE
Help Translate Appwrite to Sindhi language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1759]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Sindhi** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Sindhi in `app/config/locale/translations/sd.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by Hard-Coder05** [comment]
@Meldiron I would like to work on this issue!

**Comment by lohanidamodar** [comment]
@Meldiron Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Shrey-Nahar** [comment]
please assign this issue to me , I started working on it.

**Comment by Shrey-Nahar** [comment]
@Meldiron I have worked on this issue! Do review and merge it!

**Comment by lohanidamodar** [comment]
@Shrey-Nahar are you a native speaker of Sindhi Speaker?

**Comment by Shrey-Nahar** [comment]
@lohanidamodar I live in bangalore but  i am from rajasthan.
So i know sindhi

**Comment by Shrey-Nahar** [comment]
I know kannada and i am native speaker also can i work on that also @lohanidamodar

**Comment by Hard-Coder05** [comment]
> @Hard-Coder05 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

@lohanidamodar First of all, I haven't been assigned any issue at the moment! And also it's quite weird to see that a single person is assigned 4 issues at the same time. And You are not able to assign me even a single one.

4 issues for your reference:
https://github.com/appwrite/appwrite/issues/1782

https://github.com/appwrite/appwrite/issues/1780

https://github.com/appwrite/appwrite/issues/1757

https://github.com/appwrite/appwrite/issues/1708

**Comment by Shrey-Nahar** [comment]
@lohanidamodar please review the code and merge
