### ISSUE TITLE
Help Translate Appwrite to Slovak language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1760]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Slovak** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Slovak in `app/config/locale/translations/sk.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by harshagrawal2412** [comment]
Please assign this to me

**Comment by harshagrawal2412** [comment]
@Meldiron Please assign this to me

**Comment by harshagrawal2412** [comment]
@Meldiron I would like to work on this issue.
Please assign this to me.

**Comment by christyjacob4** [comment]
@harshagrawal2412  We're looking for a native Slovak speaker for this task.

**Comment by jakubhi** [comment]
@Meldiron Hi, native Slovak speaker here. You can assign this to me.

**Comment by lohanidamodar** [comment]
@jakubhi assigned to you. All the best 🚀
