### ISSUE TITLE
Help Translate Appwrite to Telugu language ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1764]
# Introduction

Did you know Appwrite's Locale API has support for returning responses in your own locale based on the value of the `X-Appwrite-Locale` header? 😮 We already support 56 languages and need your help to push it even further! 💪

Your task is to translate Appwrite into **Telugu** language. You can find a complete in-depth tutorial in our official [tutorial for adding translations](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-translations.md).

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Generate translations for Telugu in `app/config/locale/translations/te.json`
- [ ] Add language as supported into `app/config/locale/codes.php`, if not already presented
- [ ] Add language as supported into `app/init.php`, if not already presented
- [ ] Test the translations
- [ ] Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

---

**Comment by san-coding** [comment]
Hey, can you assign this issue to me ?

**Comment by harshagrawal2412** [comment]
I would like to work on this issue.
Kindly assign this to me.

**Comment by lohanidamodar** [comment]
@san-coding you are assigned. Good luck 👍

**Comment by san-coding** [comment]
Thanks, I am working on it

**Comment by Ln11211** [comment]
@lohanidamodar, can you assign this task to two people at a time ?, or is it not possible ?

**Comment by Meldiron** [comment]
@Ln11211 Technically possible, but it would be really hard to communicate properly. Please wait for san-coding to prepare a PR and then you can review the PR. Yes, reviewing is also considered as contribution 🤩

**Comment by Ln11211** [comment]
@Meldiron Sure !!, that would be a whole lot of new experience for me !! 🥳

**Comment by Ln11211** [comment]
@san-coding, Telugu ochha ?

**Comment by san-coding** [comment]
> @san-coding, Telugu ochha ?

Avunu bro

**Comment by san-coding** [comment]
Working on this, will open a PR soon

**Comment by Ln11211** [comment]
@san-coding No problem, take your time. _ALL THE BEST_ ..

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!
