### ISSUE TITLE
Help developers by building a demo app with Appwrite 🧱

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1773]
# Introduction

Appwrite has been and always will be a tool for developers. To emphasize this, we want to create the **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to build a demo application that will use Appwrite under the hood. **It can be anything!** Web app, mobile app, Flutter, Unity, CLI tool... You are limited only by your imagination!

### Requirements:

- Your repository has to be publicly available
- Your repository must use `appwrite` topic
- Your app must be built with Appwrite
- Your app needs to include [Built with Appwrite badge](https://appwrite.io/assets)

### Task summary:

- [ ]  Build a demo app using Appwrite and share it on your favorite VCS platform (GitHub / GitLab / Other)
- [ ]  Prepare nice-looking and informative `README.md` (screenshots more than welcome 🤩)
- [ ]  Submit PR to [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite) with a link to your repo

**This issue does not require assignment, and can be contributed by anyone! Just let us know you're working on it!**

If you need any help, reach out to us on our [Discord server](https://appwrite.io/discord).

Are you ready to work on this issue? Go ahead! We are accepting as many demo apps as the community can create. One note, **quality over quantity.**

**Happy Appwriting!**

**Comment by dro-1** [comment]
I would like to be assigned this issue.

**Comment by Rutam21** [comment]
@Meldiron I would also like to design a simple app using AppWrite

**Comment by Adi-Ski** [comment]
@Meldiron I would like to contribute a simple app using **AppWrite** :)

**Comment by asevarik** [comment]
i like to contribute

**Comment by lohanidamodar** [comment]
Hey folks, this issue does not require any assignment. You can build your demos with Appwrite and push it to GitHub. You can then use link to your demo project repository to raise a PR to https://github.com/appwrite/awesome-appwrite

@dro-1 @Rutam21 @Adi-Ski @asevarik

**Comment by codestronaut** [comment]
I would like to be assigned this issue

**Comment by eldadfux** [comment]
> I would like to be assigned this issue

Hey @codestronaut , anyone can work on this issue, just keep quality in mind - good luck!

**Comment by vencho-mdp** [comment]
Hi! I'd like to work on this for the next couple of days. Could I?

**Comment by Rutam21** [comment]
This ticket is open to all. However, make sure the demo apps add value for the community and are up to the quality standards.

**Comment by arp99** [comment]
I am new to appwrite, I would be happy to contribute 😀. Can anyone suggest resources to study? 😅

**Comment by lohanidamodar** [comment]
@arp99 here you go
https://appwrite.io/docs
https://30days.appwrite.io/
https://github.com/appwrite/awesome-appwrite

**Comment by Meldiron** [comment]
I have an idea, it would be great to create a demo app that would use Appwrite Database and show how you can implement infinite scroll paging... You can see this logic on pretty much any social media mobile app - you never see the end.

If anyone is interested, please comment so other people don't implement this in the exactly same language&framework as you.

**Comment by vencho-mdp** [comment]
That's a good one! I could do it with Vite + Vue 3

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
