### ISSUE TITLE
Help developers by writing a blog post about Appwrite🗞

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1774]
# Introduction

Appwrite has been and always will be a tool for developers. To emphasize this, we want to create the **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to write a blog post about Appwrite. **It can be anything! A s**tory about your Appwrite journey, what concepts you learned by using Appwrite, guide how to connect Appwrite to `something`... You are limited only by your imagination. **It can be anywhere!** We accept submissions of articles on any well-known platform, whether it is Medium, Dev.to, HashNode or something else.

### Requirements:

- Your article has to be publicly available
- Your article must tag `appwrite` in any way (hashtag, embedded, link...)
- Your article must be at least 1000 words long
- Your article should look nice 👀 (use titles, subtitles, screenshots, images, gifs, or even memes)

### Task summary:

- [ ]  Write a blog post about Appwrite
- [ ]  Publish an article on your favorite platform or website (Medium, Dev.to, HashNod...)
- [ ]  Share the article on social media (Reddit / HackerNews / Twitter / Facebook / Other) - **optional**
- [ ]  Submit PR to [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite) with a link to your article

**This issue does not require assignment, and can be contributed by anyone! Just let us know you're working on it!**

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? Go ahead! We are accepting as many articles as the community can create. One note, **quality over quantity.**

**Happy Appwriting!**

**Comment by theBeginner86** [comment]
I would like to work on this issue 🙌👨‍💻
Can you please assign it to me?

**Comment by muthuannamalai12** [comment]
I would like to work on this can you assign me this issue

**Comment by dro-1** [comment]
Hello, does this issue require assigning or more than one person can work on it ?

**Comment by christyjacob4** [comment]
Hey folks, this issue does not require any assignment. You can write your blog posts about Appwrite and publish it on your favourite  blogging platform. You can then use that link to raise a PR to https://github.com/appwrite/awesome-appwrite

**Comment by theBeginner86** [comment]
> Hey folks, this issue does not require any assignment. You can write your blog posts about Appwrite and publish it on your favourite blogging platform. You can then use that link to raise a PR to https://github.com/appwrite/awesome-appwrite
> 
> @theBeginner86 @muthuannamalai12 @dro-1

ok, thank you for your confirmation👍

**Comment by pooja-gera** [comment]
Such a fun issue to work on - learn and teach at once, getting on this one!

**Comment by muthuannamalai12** [comment]
> Hey folks, this issue does not require any assignment. You can write your blog posts about Appwrite and publish it on your favourite  blogging platform. You can then use that link to raise a PR to https://github.com/appwrite/awesome-appwrite 
> 
> @theBeginner86 @muthuannamalai12 @dro-1

Thank you for informing 😀

**Comment by shadowshot-x** [comment]
Great Initiative. I will definitely contribute an article to AppWrite! :dagger:

**Comment by sanjus-robotic-studio** [comment]
I am also contributing to Appwrite by writing a blogpost

**Comment by Asmit2952** [comment]
I'll be also contributing to Appwrite by publishing a  blog post!!

**Comment by noviicee** [comment]
This is amazing. I've always liked to write, and plus, this issue is a great example of 'open source is not just writing code'.
Thanks @Meldiron @christyjacob4 , will be making a PR for this :smile:

**Comment by priyanshu688** [comment]
I would like to contribute by publishing the article @Meldiron

**Comment by lohanidamodar** [comment]
> I would like to contribute by publishing the article @Meldiron

Sure @priyanshu688 you can. All the best 🚀

**Comment by priyanshu688** [comment]
@lohanidamodar thank you..

**Comment by DevanshK08** [comment]
I will be writing one ;-)

**Comment by arushmangal** [comment]
I would like to contribute as well @Meldiron

**Comment by lohanidamodar** [comment]
@arushmangal Sure. All the best 🚀

**Comment by MysticSeeker** [comment]
I Want to write a blog. Gimme a chance please... :happy:

**Comment by Meldiron** [comment]
@MysticSeeker Go ahead, anyone can work on this issue 😊 Can't wait to read your article.

**Comment by ashutosh887** [comment]
I wanted to start contributing to this respository
Can someone tell me where am  I supposed to write the Blog and how to proceed @lohanidamodar @Meldiron @christyjacob4 @shadowshot-x @dro-1

**Comment by rohiraanjali** [comment]
Would love to contribute on this to help fellow devs!! Coming soon with a blog

**Comment by MysticSeeker** [comment]
I Have Created And Posted The Blog.
Can Anyone Tell Me How Can I Add It To The Repo

**Comment by theBeginner86** [comment]
> I Have Created And Posted The Blog.
> Can Anyone Tell Me How Can I Add It To The Repo

You have to submit a PR with a link to your blog to this repo: https://github.com/appwrite/awesome-appwrite
🤓

**Comment by MysticSeeker** [comment]
> > I Have Created And Posted The Blog.
> > Can Anyone Tell Me How Can I Add It To The Repo
> 
> You have to submit a PR with a link to your blog to this repo: https://github.com/appwrite/awesome-appwrite
> 🤓

In what form?

**Comment by MysticSeeker** [comment]
https://hashnode.com/@MysticSeeker/joinme Here It Is...

**Comment by MysticSeeker** [comment]
O Thanks Bro😁

**Comment by mishmanners** [comment]
This is really good and should be included in the Contribution guide: https://github.com/appwrite/awesome-appwrite/blob/master/CONTRIBUTING.md

I opened a PR to include this information as well as info about IP rights/ownership.

**Comment by mishmanners** [comment]
I'll also be writing articles 😄

**Comment by lohanidamodar** [comment]
@mishmanners of course. At Appwrite we love articles, videos and tutorials. All the best 🚀

**Comment by Vidushi-Gupta** [comment]
Hi! This looks like such a great way to encourage people to get acquainted to Appwrite. I'll definitely write a blog post and get back soon :)

**Comment by eldadfux** [comment]
It's just amazing to see all this great blog posts! This is such a great way to help and push the project forward! Thank you everyone, we're excited to see what other great posts you'll come up with!! ❤️

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
