### ISSUE TITLE
Help developers by making an Appwrite Tutorial 🎥

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1775]
# Introduction

Appwrite has been and always will be a tool for developers. To emphasize this, we want to create the **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to create a tutorial regarding Appwrite. **It can be anything!** How to set up Appwrite, how to use Appwrite service, a demo of some features, presentation about Appwrite permissions... You are limited only by your imagination. **It can be in any form!** You could record a video on Youtube, stream on Twitch, write an article or host an event on the Discord server. As long as there is a record, we will accept your submission.

### Requirements:

- Your tutorial has to be publicly available
- Your tutorial must link to `appwrite` in some way (link, logo in overlay, description...)
- Your video must be at least 5 minutes long (shorter allowed if the quality is top-tier, for example, animation with voice-over)

### Task summary:

- [ ]  Make a tutorial (video, stream, article, presentation...)
- [ ]  Mention Appwrite in some form (link Twitter, website, logo in the video...)
- [ ]  Publish the video on your favorite video platform (Youtube / Vimeo / Other)
- [ ]  Share the video on social media (Reddit / HackerNews / Twitter / Facebook / Other) - optional
- [ ]  Submit PR to [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite) with a link to your resource

This issue does not require assignment, and can be contributed by anyone! Just let us know you're working on it!

If you need any help, reach out to us on our [Discord server](https://appwrite.io/discord).

Are you ready to work on this issue? Go ahead! We are accepting as many tutorials as the community can create. One note, **quality over quantity.**

**Happy Appwriting!**

**Comment by dro-1** [comment]
Hello, I'd love to be assigned this issue.

**Comment by christyjacob4** [comment]
@dro-1 this issue does not require any assignment. Just follow the instructions

**Comment by siddhiiguptaa** [comment]
Are there more than 1 blog posts required? 🤔

**Comment by 2002Bishwajeet** [comment]
@siddhiiguptaa  yeah. The more the merrier😍

**Comment by siddhiiguptaa** [comment]
Oh okay!! That is one great news 😁 Thank You @2002Bishwajeet

**Comment by Meldiron** [comment]
@srivastavaayu You can do one, you can do multiple. But please keep in mind,**quality over quantity** 🙏 If you really have a lot of time, you could (for example) code a demo app and then write an article about it. That would be considered as 2 submittions.

**Comment by maliaga-pantoja** [comment]
great tool, i am working for video tutorials in spanish 🍺

**Comment by SanjanaSogimatt** [comment]
Can I work on it? I am a complete beginner to open source so it will be great opportunity.

**Comment by symaticvisuals** [comment]
@Meldiron can I make a video of setting up Appwrite on Windows?

**Comment by eldadfux** [comment]
> @Meldiron can I make a video of setting up Appwrite on Windows?

Yes, sure.

**Comment by symaticvisuals** [comment]
> > @Meldiron can I make a video of setting up Appwrite on Windows?
> 
> Yes, sure.

Sure I'll start working on it.

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
