### ISSUE TITLE
Help by implementing Stripe OAuth 🛡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1779]
# Introduction

With Appwrite, it's super easy to set up many OAuth2 providers to allow your users to authenticate with their social accounts. Appwrite supports tons of OAuth2 providers including **Google, Facebook, Twitter, GitHub** and many more.

Your task is to implement **Stripe** OAuth provider into Appwrite. You can find a complete in-depth tutorial in our official [tutorial for adding new OAuth providers](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-oauth2-provider.md). To find out more about Stripe OAuth, check out their [API documentation](https://stripe.com/docs/connect/oauth-reference).

### Tasks summary:

- [ ]  Fork & clone Appwrite
- [ ]  Add new provider into array in `app/config/providers.php`
- [ ]  Add provider logo into `public/images/users/stripe.png`
- [ ]  Write OAuth communication in `src/Auth/OAuth/Stripe.php`
- [ ]  Test your provider
- [ ]  Push changes and submit a pull request
- [ ]  Add screenshots or GIF of a successful OAuth flow

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Comment by Emiliaaah** [comment]
I tried to implement the stripe OAuth a while back but it doesn't return the users email address from what I could find in the docs.

**Comment by san-coding** [comment]
Hey, can I work on this issue?

**Comment by subhradwip01** [comment]
Hey, can I work on this issue?

**Comment by sakshamgurbhele** [comment]
I am interested, Let me know If I can work :)

**Comment by lohanidamodar** [comment]
@subhradwip01 and @sakshamgurbhele We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by lohanidamodar** [comment]
@san-coding Assigned it to you. Good luck 👍

**Comment by san-coding** [comment]
Thank you , will start working on this

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
