### ISSUE TITLE
Help by implementing Mail.ru OAuth 🛡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1780]
# Introduction

With Appwrite, it's super easy to set up many OAuth2 providers to allow your users to authenticate with their social accounts. Appwrite supports tons of OAuth2 providers including **Google, Facebook, Twitter, GitHub** and many more.

Your task is to implement **Mail.ru** OAuth provider into Appwrite. You can find a complete in-depth tutorial in our official [tutorial for adding new OAuth providers](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-oauth2-provider.md). To find out more about Mail.ru OAuth, check out their [API documentation](https://api.mail.ru/docs/guides/oauth/).

### Tasks summary:

- [ ]  Fork & clone Appwrite
- [ ]  Add new provider into array in `app/config/providers.php`
- [ ]  Add provider logo into `public/images/users/Mailru.png`
- [ ]  Write OAuth communication in `src/Auth/OAuth/Mailru.php`
- [ ]  Test your provider
- [ ]  Push changes and submit a pull request
- [ ]  Add screenshots or GIF of a successful OAuth flow

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Comment by Rutam21** [comment]
@Meldiron I would like to work on this OAuth addition.

**Comment by sakshamgurbhele** [comment]
I am Interested, Let me know if I can work on this. :)

**Comment by christyjacob4** [comment]
@Rutam21  Assigned it to you! All the best :rocket:

**Comment by priyanshu688** [comment]
Can I still work on this?? @Meldiron

**Comment by lohanidamodar** [comment]
> Can I still work on this?? @Meldiron

As you can see this is already assigned to @Rutam21 so no. 
Thank you

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
