### ISSUE TITLE
Help by implementing Yammer OAuth 🛡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1781]
# Introduction

With Appwrite, it's super easy to set up many OAuth2 providers to allow your users to authenticate with their social accounts. Appwrite supports tons of OAuth2 providers including **Google, Facebook, Twitter, GitHub** and many more.

Your task is to implement **Yammer** OAuth provider into Appwrite. You can find a complete in-depth tutorial in our official [tutorial for adding new OAuth providers](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-oauth2-provider.md). To find out more about Yammer OAuth, check out their [API documentation](https://developer.yammer.com/docs/oauth-2).

### Tasks summary:

- [ ]  Fork & clone Appwrite
- [ ]  Add new provider into array in `app/config/providers.php`
- [ ]  Add provider logo into `public/images/users/yammer.png`
- [ ]  Write OAuth communication in `src/Auth/OAuth/Yammer.php`
- [ ]  Test your provider
- [ ]  Push changes and submit a pull request
- [ ]  Add screenshots or GIF of a successful OAuth flow

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Comment by TheShinoj** [comment]
Can I help in fixing this?

**Comment by Nikhil-1503** [comment]
I would like to work on this. Please assign it to me.

**Comment by christyjacob4** [comment]
@TheShinoj  Assigned it to you. All the best :rocket:

**Comment by christyjacob4** [comment]
@Nikhil-1503  We would love you to check out some of our other open issues and join us on discord if you need help finding some 
https://appwrite.io/discord

**Comment by TheShinoj** [comment]
> @TheShinoj Assigned it to you. All the best 🚀

Thank you so much 😊 I will do my best 🤘

**Comment by christyjacob4** [comment]
@AmreshSinha  All the best :+1:

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
