### ISSUE TITLE
Help by implementing Baidu OAuth 🛡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1782]
# Introduction

With Appwrite, it's super easy to set up many OAuth2 providers to allow your users to authenticate with their social accounts. Appwrite supports tons of OAuth2 providers including **Google, Facebook, Twitter, GitHub** and many more.

Your task is to implement **Baidu** OAuth provider into Appwrite. You can find a complete in-depth tutorial in our official [tutorial for adding new OAuth providers](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-oauth2-provider.md). To find out more about Baidu OAuth, check out their [API documentation](https://developer.baidu.com/wiki/index.php?title=docs/oauth/application).

### Tasks summary:

- [ ]  Fork & clone Appwrite
- [ ]  Add new provider into array in `app/config/providers.php`
- [ ]  Add provider logo into `public/images/users/baidu.png`
- [ ]  Write OAuth communication in `src/Auth/OAuth/Baudi.php`
- [ ]  Test your provider
- [ ]  Push changes and submit a pull request
- [ ]  Add screenshots or GIF of a successful OAuth flow

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Comment by sakshamgurbhele** [comment]
I am would like to give it a try, I don't understand Chinese but I might be able to do it by translating the API docs to English. Let me know If I can work on this. :)

**Comment by Rutam21** [comment]
I would love to work on this OAuth integration. Feel free to assign this to me.

**Comment by Rutam21** [comment]
@Meldiron I would love to work on this OAuth integration. Feel free to assign this to me.

**Comment by christyjacob4** [comment]
Hey @Rutam21 have assigned this to you. All the best :rocket:

**Comment by achintya-7** [comment]
I would like to do this task. Feel free to assign me for this problem.

**Comment by christyjacob4** [comment]
@achintya-7  We would love you to check out some of our other open issues and join us on discord if you need help finding some issue https://appwrite.io/discord

**Comment by achintya-7** [comment]
Yah sure

**Comment by Rutam21** [comment]
I will unassign this issue from my end as I have already completed 4 PRs so that other contributors get a chance to complete their goals.
@achintya-7 Feel free to ask about this issue if you're still looking for some.

CC: @Meldiron

**Comment by tusharjha44** [comment]
I would love to work on this issue. Please assign this to me

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
