### ISSUE TITLE
Help by implementing Zendesk OAuth 🛡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1783]
# Introduction

With Appwrite, it's super easy to set up many OAuth2 providers to allow your users to authenticate with their social accounts. Appwrite supports tons of OAuth2 providers including **Google, Facebook, Twitter, GitHub** and many more.

Your task is to implement **Zendesk** OAuth provider into Appwrite. You can find a complete in-depth tutorial in our official [tutorial for adding new OAuth providers](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-oauth2-provider.md). To find out more about Zendesk OAuth, check out their [API documentation](https://developer.zendesk.com/documentation/ticketing/working-with-oauth/creating-and-using-oauth-tokens-with-the-api/).

### Tasks summary:

- [ ]  Fork & clone Appwrite
- [ ]  Add new provider into array in `app/config/providers.php`
- [ ]  Add provider logo into `public/images/users/zendesk.png`
- [ ]  Write OAuth communication in `src/Auth/OAuth/Zendesk.php`
- [ ]  Test your provider
- [ ]  Push changes and submit a pull request
- [ ]  Add screenshots or GIF of a successful OAuth flow

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Comment by sahooankeeta** [comment]
Can I work on this?

**Comment by AmreshSinha** [comment]
@Meldiron Can I work on this issue?

**Comment by utkkarsh** [comment]
Hi @Meldiron,

I would love to contribute and work on this issue. 
Could you please assign this to me 😊

**Comment by christyjacob4** [comment]
@AmreshSinha Assigned it to you! All the best :rocket:

**Comment by christyjacob4** [comment]
@utkkarsh We would love you to check out some of our other open issues and join us on discord if you need help finding some issue https://appwrite.io/discord

**Comment by AmreshSinha** [comment]
Zendesk auth needs extra field other than appid and appsecret.
https://{your-subdomain}.zendesk.com/oauth/authorizations/new?{your-queries}

It needs a subdomain field. There is no API access on main zendesk website. Every company or org gets his own zendesk suite like https://your-company.zendesk.com from where he can use the API and other stuffs.

**Comment by lohanidamodar** [comment]
> Zendesk auth needs extra fields other than appid and appsecret. https://{your-subdomain}.zendesk.com/oauth/authorizations/new?{your-queries}
> 
> It needs a subdomain field. There is no API access on main zendesk website. Every company or org gets his own zendesk suite like [your-company.zendesk.com](https://your-company.zendesk.com) from where they can use the API and other stuffs.

@AmreshSinha you can add extra fields. For example how to check our Apple OAuth implementation. If you have more queries feel free to reachout.

**Comment by AmreshSinha** [comment]
Okay, so All the things are pretty much done. (Just have to document some things)

Just needed to state here that it needs a custom form like that in apple. It needs subdomain (company's zendesk suite subdomain name). So, should I wait till forms get implemented properly or should I try implementing like as in Apple. (As without forms the user will have to edit the subdomain field manually every time they set up appwrite on a new system {given that user wants to use zendesk})

**Comment by lohanidamodar** [comment]
> Okay, so All the things are pretty much done. (Just have to document some things)
> 
> Just needed to state here that it needs a custom form like that in apple. It needs subdomain (company's zendesk suite subdomain name). So, should I wait till forms get implemented properly or should I try implementing like as in Apple. (As without forms the user will have to edit the subdomain field manually every time they set up appwrite on a new system {given that user wants to use zendesk})

Do as Apple OAuth is doing.

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
