### ISSUE TITLE
Help by implementing Epic Games OAuth 🛡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1784]
# Introduction

With Appwrite, it's super easy to set up many OAuth2 providers to allow your users to authenticate with their social accounts. Appwrite supports tons of OAuth2 providers including **Google, Facebook, Twitter, GitHub** and many more.

Your task is to implement **Epic Games** OAuth provider into Appwrite. You can find a complete in-depth tutorial in our official [tutorial for adding new OAuth providers](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-oauth2-provider.md). To find out more about Epic Games OAuth, check out their [API documentation](https://dev.epicgames.com/docs/services/en-US/WebAPIRef/AuthWebAPI/index.html).

### Tasks summary:

- [ ]  Fork & clone Appwrite
- [ ]  Add new provider into array in `app/config/providers.php`
- [ ]  Add provider logo into `public/images/users/epic-games.png`
- [ ]  Write OAuth communication in `src/Auth/OAuth/EpicGames.php`
- [ ]  Test your provider
- [ ]  Push changes and submit a pull request
- [ ]  Add screenshots or GIF of a successful OAuth flow

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Comment by Flodur871** [comment]
Can I work on this?

**Comment by sakshamgurbhele** [comment]
I am interested to work on this, let me know if I can proceed! :)

**Comment by aniketh-varma** [comment]
Hello, I would like to work on this issue. Please assign me the same.

**Comment by christyjacob4** [comment]
@Flodur871  Assigned this to you . All the best :+1:

**Comment by christyjacob4** [comment]
@aniketh-varma  We would love you to check out some of our other open issues and join us on discord if you need help finding some issue https://appwrite.io/discord

**Comment by sshiv5768** [comment]
Can i work on this issue, i have already completed 3 tasks but having difficulty in 4th one?

**Comment by lohanidamodar** [comment]
Hi @sshiv5768 may be [this Epic Games API documentation](https://dev.epicgames.com/docs/services/en-US/WebAPIRef/AuthWebAPI/index.html) will be helpful for you to implement. And use any existing OAuth implementation as a reference

**Comment by sshiv5768** [comment]
Yeah, definitely  Can you assign me this work? @@lohanidamodar

**Comment by Meldiron** [comment]
@sshiv5768 This issue is already assigned 😞 We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Flodur871** [comment]
> Yeah, definitely Can you assign me this work? @lohanidamodar 

Unfortunately I won't be able to work on this in the near future, and since I saw you have already started, as far as I'm considered you can have it.

**Comment by aniketh-varma** [comment]
Hey, can I take up this issue.

**Comment by sshiv5768** [comment]
@Meldiron I already started working on this do can you assign this issue to me.

**Comment by sshiv5768** [comment]
Or else if it is possible to assign to both then @aniketh-varma and i both can work together on this issue and complete rest of the work.

**Comment by christyjacob4** [comment]
@aniketh-varma @sshiv5768 If you prefer, you can work together but the PR would count for only one of you.

**Comment by aniketh-varma** [comment]
@sshiv5768 You can go ahead in that case since you were already working on this :)

**Comment by sshiv5768** [comment]
Thanks, @aniketh-varma for this kind gesture. @christyjacob4 you can assign me this issue, I would love to complete the rest of the work.

**Comment by eldadfux** [comment]
@sshiv5768 I have assigned you 👍

**Comment by Sade28** [comment]
- [ ] - home

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!

**Comment by prestonwindfeldt** [comment]
Were you able to use Epic Games as an OAuth provider? I am not seeing the config in the repo.
