### ISSUE TITLE
Implement sendMessageBirdSMS() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1892]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `sendMessageBirdSMS` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `phoneNumber` and `text` as input, send request to send message using [MessageBird SMS API](https://developers.messagebird.com/api/sms-messaging/) and provide status as an input (if the SMS was successfully sent or not).

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-send-message-bird-sms-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/send-message-bird-sms/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| sendMessageBirdSMS  | ⚒️ manuelabarca   | ⚒ soumyo123-prog     | ⚒ ramdevcm  | ⚒ eigengravy     | ❌   |  ⚒ siddhantdixit    | ⚒️ pr0grammm   | ⚒️  zeroplusone   | ⚒️ Hardik Sachan     |

**Happy Appwriting!**

**Comment by eigengravy** [comment]
hi, i would love to work on the python implementation

**Comment by Meldiron** [comment]
@eigengravy Assigned it to you! All the best 🚀

**Comment by soumyo123-prog** [comment]
Can I work on the nodeJs implementation?

**Comment by achintya-7** [comment]
Can I work on this issue. I'll use python for this

**Comment by ramdevcm** [comment]
hi, I would like to work on PHP

**Comment by Meldiron** [comment]
@soumyo123-prog Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@ramdevcm Assigned it to you! Good luck 🚀

**Comment by Meldiron** [comment]
@eigengravy  @soumyo123-prog Great job 🥳 Please give us some time to review.

**Comment by lohanidamodar** [comment]
@zeroplusone assigned to you. All the best 🚀

**Comment by christyjacob4** [comment]
@adithyanandakumar  All the best :+1:

**Comment by adithyanandakumar** [comment]
@christyjacob4 thanks a lot for the assignment 😁

**Comment by lohanidamodar** [comment]
@adithyanandakumar no problem. Thank you for letting us know.

**Comment by hardiksachan** [comment]
Hey, I would like to work on this in kotlin. Can you please assign it to me?

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
