### ISSUE TITLE
Implement sendMessageBirdVoiceMessage() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1893]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `sendMessageBirdVoiceMessage` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `phoneNumber` and `text` as input, send request to make a call using [MessageBird Voice Messaging API](https://developers.messagebird.com/api/voice-messaging/#voice-messaging-api) and provide status as an input (if the call was successfully created).

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-send-message-bird-voice-msg-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/send-message-bird-voice-msg/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language         | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| --------------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| sendMessageBirdVoiceMessage | ⚒️ JubayerJoy    | ⚒ ayodejiAA     | ⚒️  ayodejiAA  | ⚒ siddhantdixit     | ⚒ pr0grammm   | ❌   | ⚒ PexWork   | ⚒️  Ansh Ganatra   | ⚒️ Amnx404     |

**Happy Appwriting!**

**Comment by achintya-7** [comment]
Can I work on this issue. I'll use python language for it.

**Comment by siddhantdixit** [comment]
Can u assign python to me?

**Comment by ayodejiAA** [comment]
Can you please assign Node.js to me?

**Comment by Meldiron** [comment]
@siddhantdixit @achintya-7 Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@ayodejiAA @achintya-7 Assigned it to you! Good luck 🚀

**Comment by ayodejiAA** [comment]
I will take PHP.

**Comment by lohanidamodar** [comment]
@ayodejiAA @anshganatra assigned to you. All the best 🚀

**Comment by Amnx404** [comment]
Hey can you assign me KotLin

**Comment by JubayerJoy** [comment]
Hi @Meldiron @lohanidamodar, want to work on Deno implementation
cheers.

**Comment by Meldiron** [comment]
@PexWork Assigned it to you! All the best 🚀

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
