### ISSUE TITLE
Implement backupToDropbox() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1897]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `backupToDropbox` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should export all data from all collections, generate an in-memory CSV file and save it to [Dropbox](https://www.dropbox.com/).

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository- [ ] Create `feat-implement-backup-to-dropbox-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| backupToDropbox            | ⚒️ kinkusuma   | ⚒️ papuruth   | ⚒️ piopi  | ⚒ achintya-7     | ❌   | ⚒ DonnC   | ❌   | ❌   | ⚒ alfiankan     |

**Happy Appwriting!**

**Comment by lohanidamodar** [comment]
@Emiliaaah I'm reopening the nodejs slot.

**Comment by papuruth** [comment]
@lohanidamodar I would like to try for node

**Comment by piopi** [comment]
@lohanidamodar Can I work on the PHP one?

**Comment by siddhantdixit** [comment]
Can I work in JAVA for this issue?

**Comment by achintya-7** [comment]
https://github.com/appwrite/demos-for-functions/pull/114

**Comment by achintya-7** [comment]
https://github.com/appwrite/demos-for-functions/pull/114
Fixes this issue in Python

**Comment by kinkusuma** [comment]
Hi, can i create this in deno

**Comment by Meldiron** [comment]
@kinkusuma Assigned it to you! All the best 🚀

**Comment by alfiankan** [comment]
hello @Meldiron apperently hacktoberfest has ended, but can i still working on this issue? i can create Implement backupToDropbox() Appwrite Function in kotlin. please assign to me

**Comment by Meldiron** [comment]
@alfiankan Assigned 🥳

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
