### ISSUE TITLE
Implement pruneDocuments() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1898]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `pruneDocuments` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should scan all documents in all collections to read their `createdAt` attribute. If a document has this attribute and it's older than 5 years, remove the document.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository- [ ] Create `feat-implement-prune-documents-X` branch where `X` is programming language you used
- [ ] Create folder named `prune-documents` in the language folder of your choice
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒  = In progress - Someone is already working on this language
❌ =  Unassigned yet - This language can be assigned to you

| Function / Language  | Deno    | NodeJS   | PHP     | Python  | Ruby   | Dart | .NET    | Java | Kotlin |
| -------------        | --------| ---------| --------|-------- |------- |------|---------|------|--------|
|pruneDocuments           | ⚒️ kinkusuma       | 🛠️ crossphoton        | 🛠️ MrJmpl3       | 🛠️ emilmerle       | 🛠️ foxy-eyed      |  ❌  | ❌      | ⚒ chandrikadeb7    | ⚒️ ks129      |

**Happy Appwriting!**

**Comment by Meldiron** [comment]
@crossphoton I just assigned you 2 different issues. Please do these, submit PR, then we can assign you to more. Sounds good? 😊

**Comment by foxy-eyed** [comment]
I apologize for duplicating my request, but I have not received response yet. Can I be assigned to this issue (`Ruby`)?
I have one other issue in progress, but it's almost done and does not involve Appwrite API itself. I am interested to try it out)
So if nobody wants it I would be glad)

**Comment by Meldiron** [comment]
@foxy-eyed I am so sorry, we didn't ignore it on purpose, we overlooked 😨

Just assigned to you, good luck 🚀 Sorry for the delay 🙏

**Comment by emilmerle** [comment]
I would like to work at this with python.

**Comment by lohanidamodar** [comment]
@kinkusuma assigned to you. All the best 🚀

**Comment by ks129** [comment]
Hi, can I try to solve it in Kotlin?

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
