### ISSUE TITLE
Implement addCreatedAt() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1899]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `addCreatedAt` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should trigger on `database.documents.create` event and fill `createdAt` attribute with the current time, if this rule for `createdAt` is configured on a specific collection.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository- [ ] Create `feat-implement-add-created-at-X` branch where `X` is programming language you used
- [ ] Create folder named `add-created-at` in the language folder of your choice
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒  = In progress - Someone is already working on this language
❌ =  Unassigned yet - This language can be assigned to you

| Function / Language  | Deno    | NodeJS   | PHP     | Python  | Ruby   | Dart | .NET    | Java | Kotlin | Swift |
| -------------        | --------| ---------| --------|-------- |------- |------|---------|------|--------|--------|
|addCreatedAt           | ⚒ didair       | ⚒ TheLearneer        | ⚒ pr0grammm       | ⚒ stnguyen90      | ❌      |  ⚒️ TafadzwaD  | ⚒ shujathkhan      | ⚒️ peterchu999    |❌      | ⚒ ks129 |

**Happy Appwriting!**

**Comment by peterchu999** [comment]
Hi can i work on `Java` implementation @Meldiron ? Thanks

**Comment by lohanidamodar** [comment]
@yuktea Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by lohanidamodar** [comment]
@TafadzwaD assigned to you. All the best 🚀

**Comment by lohanidamodar** [comment]
@stnguyen90 great questions. 
1. I think we can just try to update and check if it fails
2. It's nice to have the field configurable by using environment.

**Comment by siddhantdixit** [comment]
Can I work in PHP for this issue?

**Comment by rafaeelaudibert** [comment]
Hey, may I tackle Ruby's function?

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
