### ISSUE TITLE
Implement generateGoogleMap() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1905]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateGoogleMap` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `latitude` and `longitude` as an input, generate map preview using [Google Maps API](https://developers.google.com/maps) and save it into Appwrite Storage.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-generate-google-map-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateGoogleMap   | ⚒️  EduardoWeber   |  ❌     | ❌  | ⚒ GunjanDhanuka     | ❌   | ⚒ GunjanDhanuka   |  ❌  |  ❌  | ❌     |

**Happy Appwriting!**

**Comment by mbos2** [comment]
Hey.
Is NodeJS one done yet? I didn't see any PRs yet and followups.

I would do NodeJS function if current assignee isn't actively working on it.

**Comment by mbos2** [comment]
Alrighty.
I'd like to take over the issue, @Kokoden :) 

As soon as the team reassigns it.

**Comment by Meldiron** [comment]
@hardiksachan Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Meldiron** [comment]
@Atharva-Shinde Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@abnegate Unassigned

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
