### ISSUE TITLE
Implement generateUnsplashImage() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1908]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateUnsplashImage` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take a `keyword` as an input, use it as a keyword for Unsplash search, pick the first image and return `imageUrl` and `imageAuthor`.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository- [ ] Create `feat-implement-generate-unsplash-image-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language   | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| --------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateUnsplashImage | ⚒ crossphoton   | ⚒ bistaastha     | ⚒️ piopi  | ⚒ avats-dev     | ❌   | ⚒ DonnC   | ⚒ VictorLlanir   | ⚒ peterchu999   | ⚒️ Hardik Sachan      |

**Happy Appwriting!**

**Comment by Meldiron** [comment]
@crossphoton Assigned it to you! All the best 🚀

**Comment by peterchu999** [comment]
okay @Meldiron , actually i have request it but no confirmation https://github.com/appwrite/appwrite/issues/1908#issuecomment-934145694, next time i'll wait for the confirmation before code / solve it

**Comment by lohanidamodar** [comment]
@piopi assigned PHP to you. All the best 🚀

**Comment by hardiksachan** [comment]
Hey @Meldiron, I would like to work on the kotlin version, can you please assign it to me.

**Comment by piopi** [comment]
I finished the PR for PHP https://github.com/appwrite/demos-for-functions/pull/195

**Comment by lohanidamodar** [comment]
@piopi Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by hardiksachan** [comment]
Hey @lohanidamodar, I asked for `Kotlin` but you have assigned me `Ruby`. Can you please make the correction?

**Comment by lohanidamodar** [comment]
@hardiksachan sorry for the mix up, have corrected the error.

**Comment by hardiksachan** [comment]
Hey @lohanidamodar I have raised a PR. Please take a look! appwrite/demos-for-functions#199

**Comment by lohanidamodar** [comment]
@hardiksachan Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by crossphoton** [comment]
@papuruth I've already made an PR for Node
Waiting for review.

**Comment by Meldiron** [comment]
@siddhantdixit looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by rafaeelaudibert** [comment]
Hey guys! May I work on Ruby for this one?

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
