### ISSUE TITLE
Implement subscribeToMailchimp() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1914]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `subscribeToMailchimp` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take an `email` as input and register this email as a subscriber to [Mailchimp](https://mailchimp.com/) newsletter.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository- [ ] Create `feat-implement-subscribe-to-mailchimp-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language  | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| -------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| subscribeToMailchimp | ❌   |  ⚒ benceHornyak    | ⚒ YarinAyash1   | ❌     | ❌   | ❌   | ❌   | ⚒ Nikhil-1503   | ⚒ anmol-Git      |

**Happy Appwriting!**

**Comment by lohanidamodar** [comment]
@DoraTheExplorax assigned python to you. All the best 🚀

**Comment by JeisonSanches** [comment]
Hi, could I implement this in Dart?

**Comment by EduardoWeber** [comment]
Hello! Could you please assign this to me in Deno? Thanks!

**Comment by lohanidamodar** [comment]
@JeisonSanches @EduardoWeber assigned to you all the best 🚀
