### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1919]
# Introduction

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

Appwrite currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). Your task is to create **GitHub issue forms** for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a reference for this PR.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository- [ ] Prepare **bug report** issue form in `.github/ISSUE_TEMPLATE/bug.yaml`
- [ ] Prepare **documentation** issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare **feature request** issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to **master** and test issue forms on your fork
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**
