### ISSUE TITLE
Implement sendRequest() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1921]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `sendRequest` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should replace our current [Appwrite Tasks](https://appwrite.io/docs/tasks) feature. It should take the configuration of the HTTP request as input and send the HTTP request.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-send-request-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| sendRequest            | 🛠️ DjDeveloperr   | 🛠️ Sin-Sumit     | ⚒ ditsuke  | 🛠️ @shujathkhan     | ❌   | ❌   | 🛠️ @shujathkhan   | ⚒️ Cristina Sirbu   | ❌     |

**Happy Appwriting!**

**Comment by crossphoton** [comment]
Yeah just commented to omit further confusion to someone else.
@Meldiron @Sin-Sumit

**Comment by ditsuke** [comment]
Hi, can I work on the PHP version?

**Comment by lohanidamodar** [comment]
@ditsuke assigned PHP to you. All the best.

**Comment by anonymousr007** [comment]
Why not use rust anywhere ?

**Comment by Meldiron** [comment]
@anonymousr007 We do not have support for Rust language in Appwrite yet. Although, we plan to support bunch of new languages in our future updates 😊

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
