### ISSUE TITLE
Implement generateGiphyGif() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1922]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateGiphyGif` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take a `keyword` as an input, use it as a keyword for [Giphy API](https://developers.giphy.com/docs/api#quick-start-guide) search, pick the first gif and return gif url

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-generate-giphy-gif-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/generate-giphy-gif/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateGiphyGif    | 🛠️ bashovski    | ⚒ Emiliaaah     | ⚒ xgerhard  | ⚒ ayodejiAA      | 🛠️ siddhantdixit   | 🛠️ 2002Bishwajeet   | ⚒️ Valdas3   |  🛠️ zeroplusone   | ⚒️ Hardik Sachan      |

**Happy Appwriting!**

**Comment by Emiliaaah** [comment]
I can make the NodeJS function

**Comment by Meldiron** [comment]
@Emiliaaah Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@ayan-b Assigned it to you! All the best 🚀

**Comment by zeroplusone** [comment]
Hi, I would like to work on this issue in Java. Thanks.

**Comment by bashovski** [comment]
Hey @Meldiron, I'd like to make one for Deno. 
Cheers.

**Comment by christyjacob4** [comment]
@zeroplusone  @bashovski  Assigned it to you! all the best :+1:

**Comment by 2002Bishwajeet** [comment]
I can try making one using Dart😉

**Comment by lohanidamodar** [comment]
@2002Bishwajeet assigned dart to you. All the best 🚀

**Comment by xgerhard** [comment]
Hi, PHP please.

**Comment by lohanidamodar** [comment]
@xgerhard assigned PHP to you. All the best 🚀

**Comment by hardiksachan** [comment]
Hey, I would like to work on this in Kotlin, can you please assign it to me.

**Comment by Meldiron** [comment]
@siddhantdixit Assigned it to you! All the best 🚀

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
