### ISSUE TITLE
Implement getCovidStats() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1923]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `getCovidStats` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `country` as input, fetches summary from [Covid19 API](https://covid19api.com/) and provide today coronavirus stats in this country. If country is not provided, use global stats.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-get-covid-stats-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/get-covid-stats/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java |  Kotlin | Swift |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |  ------ |
| getCovidStats       |   🛠️ aggmoulik   |  🛠️  mendoza   | ⚒ xgerhard  | ⚒ PaulKovalov     | ⚒ akashgp09   | ⚒ Sangwan5688   | ⚒ VictorLlanir   | ⚒ Ansh Ganatra   | 🛠️ hardiksachan     | ⚒ ks129 |

**Happy Appwriting!**

**Comment by PaulKovalov** [comment]
Hi! Could you please assign python to me

**Comment by Meldiron** [comment]
@PaulKovalov Assigned it to you! All the best 🚀

**Comment by dcdunkan** [comment]
Please assign nodejs to me

**Comment by Ashwin-exe** [comment]
Hey @Meldiron , can you assign me for java.

**Comment by mendoza** [comment]
hi @Meldiron could you assign me the JavaScript version please

**Comment by aggmoulik** [comment]
Hi @Meldiron could you assign me the Deno version.

**Comment by christyjacob4** [comment]
@mendoza  @aggmoulik  All the best :+1:

**Comment by VictorLlanir** [comment]
Hello, @Meldiron could you please assign me the .NET version?

**Comment by Meldiron** [comment]
@VictorLlanir Assigned it to you! All the best 🚀

**Comment by Sangwan5688** [comment]
Hi @Meldiron, could you assign me the Dart Version

**Comment by akashgp09** [comment]
@Meldiron I am working on the ruby one.

**Comment by Meldiron** [comment]
@hardiksachan Assigned it to you! All the best 🚀


Wohooo, all languages assigned 🥳 🥳 🥳

**Comment by hardiksachan** [comment]
Hey @Meldiron I have raised a PR, please take a look

**Comment by lohanidamodar** [comment]
@hardiksachan Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
