### ISSUE TITLE
Implement generateWebsiteScreenshot() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1929]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateWebsiteScreenshot` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take `url` of a website as input, send it to [CloudConvert CaptureWebsite API](https://cloudconvert.com/api/v2/capture-website#capture-website-tasks), wait for the job to finish and save newly created screenshot image into Appwrite Storage. Finally, return ID of the new file.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-generate-website-screenshot-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/generate-website-screenshot/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language       | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateWebsiteScreenshot | ⚒ krishguptadev   | ⚒ luisorbaiceta     | ⚒️ piopi  | ⚒ siddhantdixit     | ❌   | ⚒️ highonweb   | ❌   |  🛠️ DevanshK08   | ⚒️ Ananya Misra    |

**Happy Appwriting!**

**Comment by luisorbaiceta** [comment]
Hey guys! I can implement this in NodeJS. I'll be glad to contribute to this amazing project!

**Comment by Meldiron** [comment]
@luisorbaiceta Assigned it to you! All the best 🚀

**Comment by siddhantdixit** [comment]
Can I work with Python on this issue?

**Comment by DevanshK08** [comment]
Hey @Meldiron can I work on it with java?

**Comment by christyjacob4** [comment]
@DevanshK08  All the best :+1:

**Comment by krishguptadev** [comment]
Can i make js implementation?

**Comment by luisorbaiceta** [comment]
> Can i make js implementation?

I'm already working on that @krishguptadev

**Comment by Meldiron** [comment]
@krishguptadev Would you like to work on Deno? It's similar to javascript (typescript) with a bit different system functions and the way how importing libraries works.

**Comment by luisorbaiceta** [comment]
> @Meldiron I was wondering that do I have to create a complete application or just implement it in a file like the other examples do?

I'm already finishing with the Node.js version. I'll let you know so you can mimic the code for the Deno part. Cheers!

**Comment by piopi** [comment]
Can I work on the PHP version?

**Comment by krishguptadev** [comment]
Everything works fine, but when I run the upload function:

I've added a file to the function with a typeof:

```
Uint8Array(240) [
   60,  63, 120, 109, 108,  32, 118, 101, 114, 115, 105, 111, 110,  61,
   34,  49,  46,  48,  34,  32, 101, 110,  99, 111, 100, 105, 110, 103,
   61,  34,  85,  84,  70,  45,  56,  34,  63,  62,  60,  69, 114, 114,
  111, 114,  62,  60,  67, 111, 100, 101,  62,  78, 111,  83, 117,  99,
  104,  66, 117,  99, 107, 101, 116,  60,  47,  67, 111, 100, 101,  62,
   60,  66, 117,  99, 107, 101, 116,  78,  97, 109, 101,  62, 101,  97,
   49,  49, 101,  57,  53,  52,  45,  51,  97,  55,  57,  45,  52,  50,
   55,  51,
  ... 140 more items
]
```

I get this error:

```
AppwriteException {
  message: "No file sent",
  code: 400,
  response: { message: "No file sent", code: 400, version: "0.10.4" }
}
```

How can I fix this? Is their a specific format required for uploading to the storage on Appwrite

**Comment by Meldiron** [comment]
@krishguptadev If I remember correctly, we discussed this on Discord. Let me know if you need any further assistance 🙏 For anyone else, this is a snippet in Deno to upload file from disk to Appwite:

```
 new File(
     [await Deno.readFile(`myfolder/myfile.tar.gz`)],
     "myfile.tar.gz"
    )
```

**Comment by piopi** [comment]
I finished the PR for PHP, https://github.com/appwrite/demos-for-functions/pull/181

**Comment by lohanidamodar** [comment]
@piopi Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by highonweb** [comment]
can I implement it in dart?

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
