### ISSUE TITLE
Implement optimizeCloudConvertFile() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1930]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `optimizeCloudConvertFile` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take an ID of the file in Appwrite Storage as input, send it to [CloudConvert Optimize API](https://cloudconvert.com/api/v2/optimize#optimize-tasks), wait for the job to finish and save newly created image into Appwrite Storage. Finally, return ID of the new file.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-optimize-cloud-convert-file-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/optimize-cloud-convert-file/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| optimizeCloudConvertFile            | ⚒️ codingsamurai-10   | ⚒ Amdbase1     | ⚒️ Ian-Yy   | ⚒ aniketh-varma     | ❌   | ❌   | ❌   | ⚒️ peterchu999   | ⚒ daniel-shuy     |

**Happy Appwriting!**

**Comment by aniketh-varma** [comment]
Hi, I would like to work on the Python implementation of this issue. Please assign :)

**Comment by Meldiron** [comment]
@aniketh-varma Assigned it to you! All the best 🚀

**Comment by Amdbase1** [comment]
Hello I would like to contribute in this issue through NodeJS. Assign me this.

**Comment by Meldiron** [comment]
@Amdbase1 Assigned it to you! All the best 🚀

**Comment by geryjuhasz** [comment]
I'd like to build the PHP version of this

**Comment by lohanidamodar** [comment]
@geryjuhasz Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by peterchu999** [comment]
Hi, I would like to try this issue on java, hope it's okay since my other task PR is being review

**Comment by lohanidamodar** [comment]
@peterchu999 assigned to you. All the best 🚀

**Comment by JubayerJoy** [comment]
Hi @Meldiron @lohanidamodar, want to work on PHP implementation
cheers.

**Comment by lohanidamodar** [comment]
@JubayerJoy  Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by Ian-Yy** [comment]
Hi, can I work on the PHP implementation of this?

**Comment by Ian-Yy** [comment]
@lohanidamodar I've created a PR. Please review and let me know if any changes is required. Thankss

**Comment by codingsamurai-10** [comment]
@lohanidamodar I'd like to implement this in deno. Plz assign it to me.

**Comment by lohanidamodar** [comment]
@Ian-Yy Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by lohanidamodar** [comment]
@lohanidamodar assigned to you. All the best 🚀

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
