### ISSUE TITLE
Implement mergeCloudConvertFiles() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1931]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `mergeCloudConvertFiles` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take a list of IDs of files in Appwrite Storage as input, send them to [CloudConvert Merge API](https://cloudconvert.com/api/v2/merge#merge-tasks), wait for the job to finish and save newly created file into Appwrite Storage. Finally, return ID of the new file.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-merge-cloud-convert-files-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/merge-cloud-convert-files/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| mergeCloudConvertFiles            | ⚒️ codingsamurai-10   | ⚒ bryanurizar      | ⚒️ geryjuhasz  | ⚒ Aakash-Raj-2001      | ❌   | ❌   | ❌   | ⚒️ lokeshn011101   | ⚒️ daniel-shuy      |

**Happy Appwriting!**

**Comment by Aakash-Raj-2001** [comment]
Can i work on this issue?

**Comment by Meldiron** [comment]
@Aakash-Raj-2001 Sure thing 😊 Using which language would you like to work on this?

**Comment by Aakash-Raj-2001** [comment]
I want to work on Python implementation

**Comment by Meldiron** [comment]
@Aakash-Raj-2001 Assigned it to you! All the best 🚀

**Comment by Aakash-Raj-2001** [comment]
ok @Meldiron :)

**Comment by bryanurizar** [comment]
Hey could I pick up on the NodeJS one?

**Comment by Meldiron** [comment]
@bryanurizar Assigned it to you! Good luck 🚀

**Comment by lohanidamodar** [comment]
@geryjuhasz Assigned to you. All the best 🚀

**Comment by lohanidamodar** [comment]
@geryjuhasz Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by JubayerJoy** [comment]
Hi @lohanidamodar, want to work on Deno implementation
cheers.

**Comment by lohanidamodar** [comment]
@JubayerJoy  Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by lokeshn011101** [comment]
@Meldiron @lohanidamodar I would like to work on this issue! Can I get assigned for Java?

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
