### ISSUE TITLE
Implement convertCloudConverterFile() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1933]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `convertCloudConverterFile` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take an ID of the file in Appwrite Storage as input, send it to [CloudConvert Convert API](https://cloudconvert.com/api/v2/convert#convert-tasks), wait for the job to finish and save newly created file into Appwrite Storage. Finally, return the ID of the new file. There are a bunch of options for this API endpoint, so let's limit the functionality of this function to images only.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-convert-cloud-convert-file-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/convert-cloud-convert-file/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| convertCloudConverterFile            | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

**Comment by Ankitlenka26** [comment]
Hey, I can do it in Java. Can you please assign this to me please?

**Comment by Meldiron** [comment]
@Ankitlenka26 Assigned it to you! Good luck 🚀

**Comment by christyjacob4** [comment]
@codingsamurai-10  Assigned :+1:  All the best

**Comment by oliver-pham** [comment]
Hi! I'd like to contribute to this in Python.

**Comment by deepto98** [comment]
@christyjacob4 I would like to contribute this function using PHP

**Comment by christyjacob4** [comment]
@deepto98 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by deepto98** [comment]
okay, sure. I'll complete those first

**Comment by verenaroe** [comment]
I'd like to build the PHP version.

**Comment by lohanidamodar** [comment]
@verenaroe Assigned to you. All the best 🚀

**Comment by JubayerJoy** [comment]
Hi @Meldiron @lohanidamodar, want to work on Deno implementation
cheers.
