### ISSUE TITLE
Implement createCloudConvertArchive() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1934]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `createCloudConvertArchive` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take a list of IDs of files in Appwrite Storage as input, send them to [CloudConvert Archives API](https://cloudconvert.com/api/v2/archive#archive-tasks), wait for the job to finish and save newly created archive into Appwrite Storage. Finally, return ID of the new file.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-create-cloud-convert-archive-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/create-cloud-convert-archive/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| createCloudConvertArchive            | ⚒  muskansingh2001   | ⚒ bryanurizar     | ⚒️ geryjuhasz  | ⚒ sakshamgurbhele     | ❌   | ❌   | ❌   | ⚒ Ankitlenka26   | ⚒️ Hardik Sachan     |

**Happy Appwriting!**

**Comment by Ankitlenka26** [comment]
Hey, I can do it in Java. Can you please assign this to me please?

**Comment by Meldiron** [comment]
@Ankitlenka26 Assigned it to you! All the best 🚀

**Comment by deepto98** [comment]
@christyjacob4 I would like to contribute this function using PHP

**Comment by christyjacob4** [comment]
@deepto98  Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by sakshamgurbhele** [comment]
I am Interested, Let me know If I can work :)

**Comment by Meldiron** [comment]
@sakshamgurbhele Assigned it to you! All the best 🚀

**Comment by geryjuhasz** [comment]
I'd like to build the PHP version of this

**Comment by lohanidamodar** [comment]
@geryjuhasz assigned PHP to you. All the best 🚀

**Comment by lohanidamodar** [comment]
@JubayerJoy  Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by codingsamurai-10** [comment]
@lohanidamodar I'd like to work on this in deno. Plz assign it to me.

**Comment by lohanidamodar** [comment]
@codingsamurai-10  Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by christyjacob4** [comment]
@gat786 If I recall, our .NET SDK is still not a 100% complete. So it might be better to wait until we release the .NET SDK officially

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
