### ISSUE TITLE
Implement generateCloudConvertThumbnail() Appwrite Function ⚡

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#1935]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `generateCloudConvertThumbnail` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should take an ID of the file in Appwrite Storage as input, send it to [CloudConvert Thumbnails API](https://cloudconvert.com/api/v2/thumbnails#thumbnail-tasks), wait for the job to finish and save newly created thumbnail image into Appwrite Storage. Finally, return ID of the new file.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-generate-cloud-convert-thumbnail-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/generate-cloud-convert-thumbnail/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| generateCloudConvertThumbnail            | 🛠️ papuruth   |  🛠️ papuruth    |  🛠️ deepto98   | ⚒ Amdbase1      | ❌   | ❌   | ❌   | ⚒️ zeroplusone   | ⚒️ Hardik Sachan    |

**Happy Appwriting!**

**Comment by Amdbase1** [comment]
Hi I would like to contribute in this through python. Assign me please

**Comment by Meldiron** [comment]
@Amdbase1 Assigned it to you! All the best 🚀

**Comment by papuruth** [comment]
Can I take for Node.JS?

**Comment by PaulKovalov** [comment]
Please assign Java to me

**Comment by Meldiron** [comment]
@PaulKovalov Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@papuruth I think CloudConvert is talking about their internal FileID, not Appwrite FileID. For that, I would guess this needs to be the flow:

1. Read a file from Appwrite Storage
2. Upload the file to CloudConvert
3. Wait for the upload to be finished and get CloudConvertFileID
4. Run the CloudConvert thumbnail function
5. Wait for the function to finish
6. Fetch the generated thumbnail from CloudConvert
7. Upload thumbnail to Appwrite Storage

Please let me know if this helped. If there are any further questions, I would gladly try to answer them. If the flow is not correct, please let me know and I will dive deeply into CloudConvert API to figure this out.

**Comment by papuruth** [comment]
@Meldiron I'm getting this error when I execute the function from AppWrite Console
```js
Thumbnail generation in progress. Please wait...
TypeError: Cannot read property 'statusText' of undefined
    at Client.call (/usr/local/src/node_modules/node-appwrite/lib/client.js:163:64)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Storage.getFileView (/usr/local/src/node_modules/node-appwrite/lib/services/storage.js:293:16)
    at async uploadToCloudConvert (/usr/local/src/index.js:73:19)
    at async generateCloudConvertThumbnail (/usr/local/src/index.js:149:7)
```

If I'm executing the function from CLI its fine

**Comment by papuruth** [comment]
> @papuruth you need to fix the error and successfully generate the converted thumbnail, save to Appwrite storage and response should be the File id of the newly created Appwrite storage file.

Should I fix the error happening in node-appwrite module? As I can clearly see that when the function is being run inside a docker container it seems it is unable to communicate with Appwrite.
```
// ignore env vars

docker run --rm --volume $(pwd):/usr/local/src:rw \
    --env MY_VALUE1="Hello World 1" \
    --env MY_VALUE2="Hello World 2" \
    appwrite/env-node-15.5:1.0.0 \
    node index.js
```
When I'm trying to run my function offline using the above command I get the following error. This is the error thrown by axios which is being used by node-appwrite module.
```
Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1138:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080,
  config: {
    url: 'http://localhost:8080/v1/storage/files',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'x-sdk-version': 'appwrite:nodejs:2.5.0',
      'X-Appwrite-Response-Format': '0.10.0',
      'x-appwrite-project': '61602cf0921da',
      'x-appwrite-key': '6eae38a760efa01d77cb34cdb725f5b9997b9a340c9ba78717ddf65f0c730b09d42db7aa5258f517b1c59704fc31c4cf6f62caffd10b1ddd6542c65b0c50505058ea2c8005921b48157294ce7f3ce2ee3eedbb5df1006b0087b184c318cddcb45944130b35766ff19390a8d8d4374f4b86bb532b1fa77c4eb7c51fdcde69a634',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.21.4'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'json',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/v1/storage/files',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '8080',
      nativeProtocols: [Object],
      pathname: '/v1/storage/files'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /v1/storage/files HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'x-sdk-version: appwrite:nodejs:2.5.0\r\n' +
        'X-Appwrite-Response-Format: 0.10.0\r\n' +
        'x-appwrite-project: 61602cf0921da\r\n' +
        'x-appwrite-key: 6eae38a760efa01d77cb34cdb725f5b9997b9a340c9ba78717ddf65f0c730b09d42db7aa5258f517b1c59704fc31c4cf6f62caffd10b1ddd6542c65b0c50505058ea2c8005921b48157294ce7f3ce2ee3eedbb5df1006b0087b184c318cddcb45944130b35766ff19390a8d8d4374f4b86bb532b1fa77c4eb7c51fdcde69a634\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Host: localhost:8080\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1/storage/files',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://localhost:8080/v1/storage/files',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
TypeError: Cannot read property 'statusText' of undefined
    at Client.call (/usr/local/src/node_modules/node-appwrite/lib/client.js:164:64)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Storage.listFiles (/usr/local/src/node_modules/node-appwrite/lib/services/storage.js:40:16)
```

**Comment by zeroplusone** [comment]
Hi, I would like to work on this issue in Java.

**Comment by lohanidamodar** [comment]
@Bunny77K9 you need to pick an open language.

**Comment by JubayerJoy** [comment]
Hi @lohanidamodar, want to work on Deno implementation
cheers.

**Comment by lohanidamodar** [comment]
@JubayerJoy  Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by hardiksachan** [comment]
Hey @lohanidamodar, I'm getting this error in `CloudConvert`.  Any solutions?

![image](https://user-images.githubusercontent.com/60518745/136752892-4cf4465f-36de-4638-b98e-775ff18467ad.png)

**Comment by lohanidamodar** [comment]
@hardiksachan Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by codingsamurai-10** [comment]
I'd like to take this up for deno. Plz assign it to me.

**Comment by Meldiron** [comment]
@papuruth Assigned it to you! All the best 🚀

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
