### ISSUE TITLE
Help us fix PSR issues in the Docker library [#master]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1942]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/master/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Docker`](https://github.com/appwrite/appwrite/tree/master/src/Appwrite/Docker) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Docker` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `master` branch
- [ ] Run PHP CS Fixer on all files in the [Docker](https://github.com/appwrite/appwrite/tree/master/src/Appwrite/Docker) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `master` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by mendoza** [comment]
I would love to help on this issue, if you could assign me that would be great, I will be setting the repo meanwhile

**Comment by christyjacob4** [comment]
@mendoza please consider picking a different type of issue so other contributors can try this one.

**Comment by mendoza** [comment]
sure! right now i'm trying one on the demo functions!

**Comment by divyanshkul** [comment]
@christyjacob4 is this still up for grabs? Would love to work on it

**Comment by christyjacob4** [comment]
@kaczmarekdaniel all the best :+1:

**Comment by christyjacob4** [comment]
@divyanshkul  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by kaczmarekdaniel** [comment]
Done by PR - #2008 Docker library psr issues fix
