### ISSUE TITLE
Help us fix PSR issues in the Event library [#master]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1943]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/master/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Event`](https://github.com/appwrite/appwrite/tree/master/src/Appwrite/Event) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Event` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `master` branch
- [ ] Run PHP CS Fixer on all files in the [Event](https://github.com/appwrite/appwrite/tree/master/src/Appwrite/Event) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `master` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by mendoza** [comment]
I would love to work on this, I will make a PR in a moment, assign me when you can please.

**Comment by christyjacob4** [comment]
@mendoza  all the best :+1:

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.11**

**Comment by TorstenDittmann** [comment]
This got released now! Thanks a lot for your contribution @mendoza 👏🏻
