### ISSUE TITLE
Help us fix PSR issues in the OpenSSL library [#master]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1962]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/master/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/OpenSSL`](https://github.com/appwrite/appwrite/tree/master/src/Appwrite/OpenSSL) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `OpenSSL` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `master` branch
- [ ] Run PHP CS Fixer on all files in the [OpenSSL](https://github.com/appwrite/appwrite/tree/master/src/Appwrite/OpenSSL) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `master` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by krishguptadev** [comment]
Can I fix this issue?

**Comment by christyjacob4** [comment]
@krishguptadev since you've already been assigned an issue of this type, please consider picking a different type of issue so other contributors can try this one.

**Comment by krishguptadev** [comment]
> @krishguptadev since you've already been assigned an issue of this type, please consider picking a different type of issue so other contributors can try this one.

@christyjacob4 Can you suggest some beginner friendly issues?

**Comment by Asmit2952** [comment]
Can I take this??

**Comment by Meldiron** [comment]
@Asmit2952 I just assigned an issue for your other request, please work on that, then we can assign more issues.

**Comment by Meldiron** [comment]
@krishguptadev

If you like coding, then all Appwrite function examples: https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen+Function&type=issues

If you like writing or recording, check out 3 pinned messages on https://github.com/appwrite/appwrite/issues

**Comment by g3offrey** [comment]
Hi 😄 
I'll be glad to work on that and open a pull request today.

**Comment by lohanidamodar** [comment]
@g3offrey Assigned to you. All the best 🚀
