### ISSUE TITLE
Help us fix PSR issues in the Specification library [#master]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1964]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/master/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Specification`](https://github.com/appwrite/appwrite/tree/master/src/Appwrite/Specification) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Specification` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `master` branch
- [ ] Run PHP CS Fixer on all files in the [Specification](https://github.com/appwrite/appwrite/tree/master/src/Appwrite/Specification) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `master` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by christyjacob4** [comment]
@Sin-Sumit Looks like you have an issue of this type assigned to you already. Please consider picking a different type of issue so other contributors can try this one.

**Comment by dipsam** [comment]
Hi @christyjacob4 please assign the issue to me

**Comment by sakshamgurbhele** [comment]
I am Interested, Let me know If I can proceed :)

**Comment by Meldiron** [comment]
@sakshamgurbhele I just assigned you to a different issue of this type. Let's leave this one for someone else.

**Comment by Meldiron** [comment]
@dipsam Assigned it to you! Good luck 🚀

**Comment by parzival272000** [comment]
I am interested in working on such an issue and getting started

**Comment by christyjacob4** [comment]
@parzival272000  This issue is already is taken.  We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
