### ISSUE TITLE
Help us fix PSR issues in the URL library [#master]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1967]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/master/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/URL`](https://github.com/appwrite/appwrite/tree/master/src/Appwrite/URL) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `URL` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `master` branch
- [ ] Run PHP CS Fixer on all files in the [URL](https://github.com/appwrite/appwrite/tree/master/src/Appwrite/URL) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `master` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by mqnguyen5** [comment]
Hi, could I give it a try?

**Comment by oovk** [comment]
@christyjacob4 I can make a PR here today. The issue is unattended since 4 days.
@mqnguyen5 you working on this?

**Comment by oovk** [comment]
@christyjacob4 I made a PR PTAL!

**Comment by mqnguyen5** [comment]
Hi, sorry for the late reply. Yes, I was working on but since I had a lot of assignments this week so my progress was very slow. @oovk if you already have a PR then I would gladly pass the issue to you. Thanks @christyjacob4 for the chance and sorry for being inactive and not completing it earlier.

**Comment by lohanidamodar** [comment]
@oovk assigning this to you as @mqnguyen5 was ok with it. Thank you.

**Comment by TorstenDittmann** [comment]
This got released now! Thanks a lot for your contribution @oovk 👏🏻
