### ISSUE TITLE
Help us fix PSR issues in the Auth library [#db]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1969]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Auth`](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite/Auth) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Auth` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `feat-database-indexing` branch
- [ ] Run PHP CS Fixer on all files in the [Auth](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite/Auth) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `feat-database-indexing` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by ErfanBahramali** [comment]
Hi i would like to work on this issue.

**Comment by Mogakamo** [comment]
@christyjacob4 please assign me this.

**Comment by sakshamgurbhele** [comment]
I am Interested, Let me know If I can work :)

**Comment by Meldiron** [comment]
@ErfanBahramali Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
@Mogakamo  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released with **Appwrite 0.12**
