### ISSUE TITLE
Help us fix PSR issues in the Docker library [#db]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1972]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Docker`](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite/Docker) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Docker` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `feat-database-indexing` branch
- [ ] Run PHP CS Fixer on all files in the [Docker](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite/Docker) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `feat-database-indexing` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by 1995YogeshSharma** [comment]
Hey, Can I get this assigned to me? Thanks!

**Comment by christyjacob4** [comment]
@1995YogeshSharma  :+1:  All the best

**Comment by 1995YogeshSharma** [comment]
@christyjacob4 Thanks!

**Comment by Meldiron** [comment]
Hey @1995YogeshSharma, before you submit your PR please note the update to this issue. Please raise your PR against the feat-database-indexing-mirror branch ONLY.

**Comment by oovk** [comment]
@1995YogeshSharma Are you working on this? or Should I go forward with the PR?

**Comment by 1995YogeshSharma** [comment]
HI @oovk , yup I am working on this, planning to submit PR tomorrow.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!
