### ISSUE TITLE
Help us fix PSR issues in the Event library [#db]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1973]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Event`](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite/Event) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Event` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `feat-database-indexing-mirror` branch
- [ ] Run PHP CS Fixer on all files in the [Event](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite/Event) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `feat-database-indexing-mirror` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by harshita214** [comment]
Hey, Can I try this?

**Comment by Meldiron** [comment]
@harshita214 Assigned it to you! All the best 🚀

**Comment by Meldiron** [comment]
Hey @harshita214, before you submit your PR please note the update to this issue. Please raise your PR against the feat-database-indexing-mirror branch ONLY.

**Comment by sakshamgurbhele** [comment]
If @harshita214 isn't working, let me know I am interested

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
