### ISSUE TITLE
Help us fix PSR issues in the Extend library [#db]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1974]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Extend`](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite/Extend) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Extend` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `feat-database-indexing` branch
- [ ] Run PHP CS Fixer on all files in the [Extend](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite/Extend) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `feat-database-indexing` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by PaulKovalov** [comment]
Please assign this to me

**Comment by christyjacob4** [comment]
@PaulKovalov  All the best :+1:

**Comment by PaulKovalov** [comment]
Hi @christyjacob4, please take a look at the PR

**Comment by Meldiron** [comment]
@PaulKovalov Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by Meldiron** [comment]
Hey @PaulKovalov, before you submit your PR please note the update to this issue. Please raise your PR against the feat-database-indexing-mirror branch ONLY.
