### ISSUE TITLE
Help us fix PSR issues in the Specification library [#db]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1979]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Specification`](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite/Specification) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Specification` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `feat-database-indexing-mirror` branch
- [ ] Run PHP CS Fixer on all files in the [Specification](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite/Specification) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `feat-database-indexing-mirror` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by yashikajotwani12** [comment]
I would like to work on this issue, please assign me.

**Comment by christyjacob4** [comment]
@yashikajotwani12  Looks like you have been assigned an issue of this type already. Please consider picking a different type of issue so other contributors can try this one.

**Comment by yashikajotwani12** [comment]
Okay, @christyjacob4

**Comment by vishal-codes** [comment]
Hey @christyjacob4 can I work on this issue?

**Comment by Meldiron** [comment]
@vishal-codes Assigned it to you! Good luck 🚀

**Comment by lohanidamodar** [comment]
> Hey @Meldiron @christyjacob4 ![Screenshot 2021-10-07 152635](https://user-images.githubusercontent.com/79784161/136415632-c9640810-5ed5-4a0a-a48a-611839474a19.jpg) I found that the path isn't set in `C:\Users\username\AppData\Roaming\Code\User\settings.json ` bcoz php isn't installed on my machine. How should I install it I googled it but of no avail. Can u help me?
> 
> Operating system - Windows 10

If you install Wampp or xampp, you should get PHP as well in windows.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
