### ISSUE TITLE
Help us fix PSR issues in the Stats library [#db]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1980]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Stats`](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite/Stats) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Stats` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `feat-database-indexing` branch
- [ ] Run PHP CS Fixer on all files in the [Stats](https://github.com/appwrite/appwrite/tree/feat-database-indexing/src/Appwrite/Stats) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `feat-database-indexing` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Sin-Sumit** [comment]
@christyjacob4 Please assign me to work on this.

**Comment by christyjacob4** [comment]
@Sin-Sumit Looks like you have an issue of this type assigned to you already. Please consider picking a different type of issue so other contributors can try this one.

**Comment by akshat-kumar2109** [comment]
Is there anything wrong with the above process?? @christyjacob4

**Comment by NeonSpork** [comment]
@christyjacob4 Can you assign me to this task please? I'd like to give it a try!

**Comment by NeonSpork** [comment]
Hmm. I think someone may have beaten me to the punch, @christyjacob4? 

I installed the `php-cs-fixer` tool linked in the issue, installed it and ran it according to their instructions and it seemed to run it without problems, but nothing changed.

```bash
D:\code\PHP-CS-Fixer\tools\php-cs-fixer\vendor\bin>php-cs-fixer fix D:\code\appwrite\src\Appwrite\Stats\Stats.php
Loaded config default.
   1) D:\code\appwrite\src\Appwrite\Stats\Stats.php

Fixed all files in 0.454 seconds, 12.000 MB memory used
```

Maybe the Stats library already follows the coding standards you wrote in the issue body? 🤔

**Comment by Meldiron** [comment]
@akshat-kumar2109 From what I can see in the screenshot of folder structure, it looks like you were not on `feat-database-indexing`. But yeah, I can see you checked out. I would need to see the full process of what you did to figure out what went wrong.

I understand it can be frustrating if stuff doesn't work as expected when learning, but we are always here to help 😨 It's impossible to answer immediately on GitHub, so if you need faster support, I would suggest you join our Discord server.

We would love to see you ask for assignments of different issu and help you on your way to your first pull request 🙏

**Comment by Meldiron** [comment]
@NeonSpork In theory, that might be the case... Could you try a different folder to make sure your setup is correct?

**Comment by NeonSpork** [comment]
@Meldiron It must be the case, I just ran the exact same lines of code, but on `src/Appwrite/Migration/Migration.php` and it removed some trailing white spaces. Same success message in `cmd` :)

**Comment by Meldiron** [comment]
@NeonSpork Thanks for the confirmation 🙏 I will share this with the team. We will most likely close the issue.

**Comment by christyjacob4** [comment]
Hey @NeonSpork  Thank you so much for helping us verify this :rocket:
