### ISSUE TITLE
Help us fix PSR issues in the Task library [#db]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1981]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Task`](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite/Task) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Task` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `feat-database-indexing-mirror` branch
- [ ] Run PHP CS Fixer on all files in the [Task](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite/Task) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `feat-database-indexing-mirror` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by maniSHarma7575** [comment]
@christyjacob4 I would like to try? Can you please assign me?

**Comment by aniketh-varma** [comment]
Hi @christyjacob4, I would like to work on this issue. Please assign me :)

**Comment by amanbedi1** [comment]
Hi @christyjacob4 , I am interested to fix this issue so could you assign me

**Comment by christyjacob4** [comment]
@amanbedi1  All the best :+1:

**Comment by ar-ankou** [comment]
I would love to participate

**Comment by Meldiron** [comment]
@ar-ankou Assigned it to you! All the best 🚀
