### ISSUE TITLE
Help us fix PSR issues in the Template library [#db]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1982]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/Template`](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite/Template) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `Template` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `feat-database-indexing-mirror` branch
- [ ] Run PHP CS Fixer on all files in the [Template](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite/Template) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `feat-database-indexing-mirror` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Sin-Sumit** [comment]
@christyjacob4 Please assign me to work on this.

**Comment by christyjacob4** [comment]
@Sin-Sumit  All the best :+1:

**Comment by Sin-Sumit** [comment]
Hey, @christyjacob4 how do run the tests?

**Comment by Meldiron** [comment]
@Sin-Sumit We have general information on tests in our [CONTRIBUTING.md](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md#tests) file. If you have any issues running tests this way, please let us know.

**Comment by Sin-Sumit** [comment]
@Meldiron In this issue I do not have to change anything in code right?

**Comment by Meldiron** [comment]
@Sin-Sumit It will most likely only create spacing changes, but it might add some code change too. Don't worry too much... 

Just submit what it made and we will see if there is anything odd. We will comment on PR if something is not right.

**Comment by Sin-Sumit** [comment]
Hey @christyjacob4 on creating pushing the changes. git wants to fetch  & merge all the changes fro the remote repo then push the changes to origin repo branch.
But on creating the PR there are 396 commits happen.

What to do?

**Comment by Sin-Sumit** [comment]
Hey, @Meldiron I created the PR according to the updated issue

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
