### ISSUE TITLE
Help us fix PSR issues in the URL library [#db]

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#1983]
## Introduction

Appwrite uses some custom libraries (and extensions of libraries) that are all stored in the [`src/Appwrite`](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite) folder. Some of these files may not be fully compliant with the [PSR coding standards](https://www.php-fig.org/psr/), and we need your help to fix those issues.

Don't worry, we have a neat little trick for you. The PHP Coding Standards Fixer [(PHP CS Fixer) tool](https://github.com/FriendsOfPHP/PHP-CS-Fixer) fixes your code to follow these standards.

If you'd like to use it with an editor of your choice, they have support for the most [popular editors](https://github.com/FriendsOfPHP/PHP-CS-Fixer#editor-integration) out there.

Your task as part of this issue is to use the PHP CS Fixer tool to check and fix coding standard related issues in the [`src/Appwrite/URL`](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite/URL) library.

### ⚠️ Note ⚠️

Ensure that you run PHP CS Fixer **ONLY** for files in the `URL` library.

### Tasks summary:

- [ ] Fork & clone Appwrite
- [ ] Checkout to the `feat-database-indexing-mirror` branch
- [ ] Run PHP CS Fixer on all files in the [URL](https://github.com/appwrite/appwrite/tree/feat-database-indexing-mirror/src/Appwrite/URL) library
- [ ] Run the tests locally
- [ ] Push changes and submit a pull request to the `feat-database-indexing-mirror` branch

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by fernandoamz** [comment]
Hey @christyjacob4  I would like to contribute on this, May you assign me?

**Comment by fernandoamz** [comment]
@christyjacob4, Thnks I will search for a new one

**Comment by christyjacob4** [comment]
@krishguptadev  All the best :+1:

**Comment by krishguptadev** [comment]
@christyjacob4 I had a question, Should I use the vscode editor extension or the cli?

**Comment by krishguptadev** [comment]
@christyjacob4 the URL library is just that one file in the src/APP/URL directory?

**Comment by krishguptadev** [comment]
@christyjacob4 I made a pr, but it doesn't show on linked prs here in this issue: https://github.com/appwrite/appwrite/pull/1986

**Comment by Meldiron** [comment]
Hey @krishguptadev, before you submit your PR please note the update to this issue. Please raise your PR against the feat-database-indexing-mirror branch ONLY.

**Comment by krishguptadev** [comment]
Can this issue be closed @christyjacob4 @Meldiron?

**Comment by eldadfux** [comment]
This fix is now available as part of Appwrite 0.12 which is now officially released. You can learn more at: https://dev.to/appwrite/its-here-announcing-the-release-of-appwrite-012-5c8b
