### ISSUE TITLE
Implement fileBackup() Appwrite Function  ⚡ 

### ISSUE THREAD

**Issue by lohanidamodar** [appwrite/appwrite#2028]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `fileBackup` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should get a list of all the files in the storage and upload them to dropbox.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-file-backup-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/file-backup/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| fileBackup            |  :hammer_and_pick:  krishguptadev   | ⚒️ geisterfurz007      | ⚒️  geryjuhasz  | ✅     | ⚒️  panuphanch   | ⚒️ geisterfurz007   | ⚒️ SIDDHANT DIXIT  |   :hammer_and_pick:  Abhinav-CHD   | :hammer_and_pick:  Prakhar-Agarwal-byte     |

**Happy Appwriting!**

**Comment by Abhinav-CHD** [comment]
@lohanidamodar Can you assign fileBackup function in Java to me?

**Comment by krishguptadev** [comment]
Can I work on deno?

**Comment by lohanidamodar** [comment]
@panuphanch assigned ruby to you. All the best 🚀

**Comment by geryjuhasz** [comment]
I'd like to build the PHP version of this

**Comment by lohanidamodar** [comment]
@geryjuhasz Assigned to you. All the best 🚀

**Comment by krishguptadev** [comment]
@lohanidamodar I've made the function: https://github.com/appwrite/demos-for-functions/pull/188

**Comment by lohanidamodar** [comment]
@krishguptadev Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by lohanidamodar** [comment]
@geisterfurz007 Thanks for identifying the issue. Assigned to you. All the best 🚀

**Comment by siddhantdixit** [comment]
Can I work in Java for this issue?

**Comment by geisterfurz007** [comment]
@krishguptadev which PR are you referring to? Searching for "node" and "backup" separately only brought up https://github.com/appwrite/demos-for-functions/pull/146 which implements backing up the collection to storage and not a file uploaded to storage to dropbox. I might be missing something though.

**Comment by geryjuhasz** [comment]
done https://github.com/appwrite/demos-for-functions/pull/301

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
