### ISSUE TITLE
Implement cloudmersiveDetectObject() Appwrite Function ⚡ 

### ISSUE THREAD

**Issue by lohanidamodar** [appwrite/appwrite#2029]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `cloudmersiveDetectObject` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

The function should trigger on `storage.files.create` event and if the file is an image, should detect and return objects in the image using cloudmersive image API

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-cloudmersive-detect-object-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/object-detection/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| cloudmersiveDetectObject            |  :hammer_and_pick:  aggmoulik  | :hammer_and_pick:   geisterfurz007    | ⚒️ JubayerJoy  | ✅     | ⚒️  panuphanch   | ⚒️ Nehansh10   | ❌   | :hammer_and_pick:  inomag   |  :hammer_and_pick:  Prakhar-Agarwal-byte  |

**Happy Appwriting!**

**Comment by geisterfurz007** [comment]
Hey, I would like to give this a shot for NodeJS later today or tomorrow if that's alright :)

**Comment by panuphanch** [comment]
Can I work on Ruby?

**Comment by Nehansh10** [comment]
Hey, i would be interested in trying to write the function in dart.

**Comment by lohanidamodar** [comment]
@Nehansh10 assigned dart to you. All the best 🚀

**Comment by lohanidamodar** [comment]
@geisterfurz007 @panuphanch Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by JubayerJoy** [comment]
Hi @lohanidamodar, I want to work on the PHP implementation.
cheers.

**Comment by lohanidamodar** [comment]
@JubayerJoy assigned to you. All the best 🚀

**Comment by abhijeet007rocks8** [comment]
@lohanidamodar  I would Like to work upon this issue in Python Language.

**Comment by Miksier** [comment]
@jacobprudhomme 
@lohanidamodar 

Pretty sure there's already a PR for this from me :D (for like half a year?)
https://github.com/appwrite/demos-for-functions/pull/73

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
