### ISSUE TITLE
Implement sendWelcomeEmail() Appwrite Function ⚡

### ISSUE THREAD

**Issue by lohanidamodar** [appwrite/appwrite#2030]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `sendWelcomeEmail` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

The function should trigger on `account.create` and `users.create` events and if the user has email (not anonymous account), you should send a welcome email to the user.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-send-welcome-email-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/welcome-email/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| sendWelcomeEmail            | ✅   | ✅     | :hammer_and_pick:  Prakhar-Agarwal-byte  | ✅     | :hammer_and_pick:  1n40    | ✅   | ✅   | ✅   | ✅     |

**Happy Appwriting!**

**Comment by parzival272000** [comment]
Brother I have left comment on two issue can you assign me to them I would really like to kickstart my journey towards contribution to this repo

**Comment by lohanidamodar** [comment]
@parzival272000 You should already be assigned to at lease one. If not please let us know via discord. Also,  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Meldiron** [comment]
@parzival272000 @1n40 Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by parzival272000** [comment]
Okay can we write about appwrite on medium or dev via a post

**Comment by Prakhar-Agarwal-byte** [comment]
@lohanidamodar I have created a PR for PHP. Please check it out 😀

**Comment by Meldiron** [comment]
@Prakhar-Agarwal-byte Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
