### ISSUE TITLE
Implement storageCleaner() Appwrite Function ⚡

### ISSUE THREAD

**Issue by lohanidamodar** [appwrite/appwrite#2031]
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `storageCleaner` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should scan all the files in the storage to read their `createdAt` attribute. If the file is older than `XX` days, remove the file. The `XX` days should be received via environment variable

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone Appwrite's [demos-for-function](https://github.com/appwrite/demos-for-functions) repository
- [ ] Create `feat-implement-storage-cleaner-X` branch where `X` is programming language you used
- [ ] Write code for the function in folder `X/storage-cleaner/` where `X` is programming language you used
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request to our [demos-for-function](https://github.com/appwrite/demos-for-functions) repository

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| storageCleaner            | ⚒️  manuelabarca   | ✅     | ✅  | ✅     | ⚒️ Jacob Prud'homme   | ✅   | ✅   | ⚒️  Prakhar-Agarwal-byte  | ✅     |

**Happy Appwriting!**

**Comment by vendz** [comment]
@christyjacob4, please assign this to me

**Comment by lohanidamodar** [comment]
@panuphanch you already have some similar issues assigned. Please complete them before.

**Comment by lohanidamodar** [comment]
@vendz which language?

**Comment by vendz** [comment]
> @vendz which language?

@lohanidamodar java

**Comment by lohanidamodar** [comment]
@manuelabarca assigned to you as you were the first one. Next please ask for assignment before creating a PR 🙏🏻

**Comment by lohanidamodar** [comment]
@jacobprudhomme  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by inomag** [comment]
@lohanidamodar, can you assign me the Java implementation if it is not done?

**Comment by lohanidamodar** [comment]
@jacobprudhomme Assigned ruby to you. All the best 🚀

**Comment by lohanidamodar** [comment]
@inomag it's already assigned. We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by codingsamurai-10** [comment]
I'd like to work on this in NodeJS. Plz assign this to me.

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
