### ISSUE TITLE
Help us add the Code of Conduct to analytics repository

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#2035]
## Introduction

Appwrite's **Code of Conduct** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md). We follow the same Code of Conduct across all our projects but some of them are missing the **CODE_OF_CONDUCT.md** file in the project.

Your task is to add the CODE_OF_CONDUCT.md file to [analytics](https://github.com/utopia-php/analytics).

You can take a look at [Code of Conduct](https://github.com/utopia-php/abuse/blob/master//CODE_OF_CONDUCT.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [analytics](https://github.com/utopia-php/analytics)
- [ ] Add the **Code of Conduct** in a `CODE_OF_CONDUCT.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by lohanidamodar** [comment]
@aniketh-varma you've already been assigned an issue of this type already. Please consider picking a different type of issue so other contributors can try this one.

**Comment by Goheljay** [comment]
@christyjacob4 @lohanidamodar can I work on this issue? Can you assign me this issue?
I have completed all my previous assigned issues.

**Comment by achromik** [comment]
@christyjacob4 @lohanidamodar I would like to work on this issue :)

**Comment by achromik** [comment]
@Meldiron Completed the task! Do review it and let me know if any changes are needed!

FYI: The second mentioned link is a part of work from a guy who wasn't assigned to this task.
