### ISSUE TITLE
Help us add the Code of Conduct to appwrite repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2040]
## Introduction

Appwrite's **Code of Conduct** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md). We follow the same Code of Conduct across all our projects but some of them are missing the **CODE_OF_CONDUCT.md** file in the project.

Your task is to add the CODE_OF_CONDUCT.md file to [appwrite](https://github.com/appwrite/appwrite).

You can take a look at [Code of Conduct](https://github.com/appwrite/benchmarks/blob/main//CODE_OF_CONDUCT.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [appwrite](https://github.com/appwrite/appwrite)
- [ ] Add the **Code of Conduct** in a `CODE_OF_CONDUCT.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by riyakushwaha** [comment]
Hi, please assign this issue to me

**Comment by lohanidamodar** [comment]
@vendz @ArmanChand  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by riyakushwaha** [comment]
@lohanidamodar The mentioned repository already contains  CODE_OF_CONDUCT.md file.

**Comment by Angelfirenze01** [comment]
Is this issue still up for the taking?

**Comment by Princeton21** [comment]
Please review and merge my pull request. #2182

**Comment by lohanidamodar** [comment]
@riyakushwaha Sorry for the misleading issue. Closing this issue!
