### ISSUE TITLE
Help us add the Contributing Guidelines to appwrite repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2041]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [appwrite](https://github.com/appwrite/appwrite).

You can take a look at [Contributing Guidelines](https://github.com/appwrite/benchmarks/blob/main//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [appwrite](https://github.com/appwrite/appwrite)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by ArmanChand** [comment]
@Meldiron , I can take this issue up

**Comment by lohanidamodar** [comment]
@ArmanChand @vendz You've already been assigned an issue of this type. Please consider picking a different type of issue so other contributors can try this one.

**Comment by anukindipa** [comment]
Can i try to work on this?

**Comment by mehabhalodiya** [comment]
Hey @Meldiron 
Should I create new branch other than main/master?

**Comment by christyjacob4** [comment]
@mehabhalodiya  Sorry but this issue is not relevant since appwrite/appwrite already has a `CONTRIBUTING.md` file and hence we would not be able to merge this. We will however accept your PR for your hard work. :slightly_smiling_face:

**Comment by mehabhalodiya** [comment]
Hey @christyjacob4 
So can you suggest other one?

**Comment by christyjacob4** [comment]
You can checkout the issue on `demos-for-functions` @mehabhalodiya
