### ISSUE TITLE
Help us add the Contributing Guidelines to demo-todo-with-nextjs repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2057]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [demo-todo-with-nextjs](https://github.com/appwrite/demo-todo-with-nextjs).

You can take a look at [Contributing Guidelines](https://github.com/appwrite/benchmarks/blob/main//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [demo-todo-with-nextjs](https://github.com/appwrite/demo-todo-with-nextjs)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by christyjacob4** [comment]
@parzival272000  All the best :+1:

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
