### ISSUE TITLE
Help us add the Code of Conduct to demo-todo-with-react repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2058]
## Introduction

Appwrite's **Code of Conduct** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md). We follow the same Code of Conduct across all our projects but some of them are missing the **CODE_OF_CONDUCT.md** file in the project.

Your task is to add the CODE_OF_CONDUCT.md file to [demo-todo-with-react](https://github.com/appwrite/demo-todo-with-react).

You can take a look at [Code of Conduct](https://github.com/appwrite/benchmarks/blob/main//CODE_OF_CONDUCT.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [demo-todo-with-react](https://github.com/appwrite/demo-todo-with-react)
- [ ] Add the **Code of Conduct** in a `CODE_OF_CONDUCT.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by lohanidamodar** [comment]
@mehmettokgoz Thank you for your contribution. We will review the PRs soon 👍🏻

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
