### ISSUE TITLE
Help us add the Code of Conduct to framework repository

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#2066]
## Introduction

Appwrite's **Code of Conduct** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md). We follow the same Code of Conduct across all our projects but some of them are missing the **CODE_OF_CONDUCT.md** file in the project.

Your task is to add the CODE_OF_CONDUCT.md file to [framework](https://github.com/utopia-php/framework).

You can take a look at [Code of Conduct](https://github.com/utopia-php/abuse/blob/master//CODE_OF_CONDUCT.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [framework](https://github.com/utopia-php/framework)
- [ ] Add the **Code of Conduct** in a `CODE_OF_CONDUCT.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by PrerakMathur20** [comment]
Hello,
I'd like to work on this issue. Kindly assign this one to me.
