### ISSUE TITLE
Help us add the Code Of Conduct Guidelines to ab repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2074]
## Introduction

Appwrite's **Code of Conduct** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md). We follow the same Code of Conduct across all our projects but some of them are missing the **CODE_OF_CONDUCT.md** file in the project.

Your task is to add the CODE_OF_CONDUCT.md file to [ab](https://github.com/utopia-php/ab).

You can take a look at [Code of Conduct](https://github.com/utopia-php/abuse/blob/master//CODE_OF_CONDUCT.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [ab](https://github.com/utopia-php/ab)
- [ ] Add the **Code of Conduct** in a `CODE_OF_CONDUCT.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by parzival272000** [comment]
Can i take this @Meldiron

**Comment by christyjacob4** [comment]
@parzival272000  You've been assigned an issue of this type already. Please consider picking a different type of issue so other contributors can try this one.

**Comment by daniloff200** [comment]
@christyjacob4 
hey!
Can I pick this one?

**Comment by vendz** [comment]
@christyjacob4, please assign this to me

**Comment by lohanidamodar** [comment]
@daniloff200 assigned to you all the best 🚀

**Comment by daniloff200** [comment]
related to https://github.com/utopia-php/ab/pull/5

**Comment by oovk** [comment]
@lohanidamodar Please review my PR.

**Comment by lohanidamodar** [comment]
@oovk please submit PR only after being assigned.
