### ISSUE TITLE
Help us add the Contributing Guidelines to abuse repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2075]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [abuse](https://github.com/utopia-php/abuse).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [abuse](https://github.com/utopia-php/abuse)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Sin-Sumit** [comment]
@christyjacob4 I'd like to work on this issue.

**Comment by honeykpatel** [comment]
Isn't there already a contributing.md in abuse one?

**Comment by christyjacob4** [comment]
Yes you're right. In that case this issue can be closed :+1:
