### ISSUE TITLE
Help us add the Contributing Guidelines to audit repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2077]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [audit](https://github.com/utopia-php/audit).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [audit](https://github.com/utopia-php/audit)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by KKVANONYMOUS** [comment]
@Meldiron I would like to work on this issue

**Comment by christyjacob4** [comment]
@KKVANONYMOUS  You've been assigned an issue of this type already. Please consider picking a different type of issue so other contributors can try this one.

**Comment by lohanidamodar** [comment]
@Rutam21  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by lohanidamodar** [comment]
@vendz assigned to you. All the best 🚀

**Comment by christyjacob4** [comment]
@yaya-usman  Check out `demos-for-functions`

**Comment by yaya-usman** [comment]
@christyjacob4 Thanks
