### ISSUE TITLE
Help us add the Contributing Guidelines to cli repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2079]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [cli](https://github.com/utopia-php/cli).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [cli](https://github.com/utopia-php/cli)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by PrerakMathur20** [comment]
Hello,
I'd like to work on this issue. Kindly assign this one to me.

**Comment by StarTrooper08** [comment]
@mairagee524 need any help to solve this issue?
Hacktoberfest is going to end I can assist for solving this issue!!

**Comment by StarTrooper08** [comment]
Can I solve this issue even if the hacktoberfest is over?
@lohanidamodar

**Comment by mairagee524** [comment]
> Can I solve this issue even if the hacktoberfest is over? @lohanidamodar

Hey, if you read up to my previous message, I am still working on it. Thanks.

**Comment by StarTrooper08** [comment]
Oh sorry

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
