### ISSUE TITLE
Help us add the Contributing Guidelines to demo repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2082]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [demo](https://github.com/utopia-php/demo).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [demo](https://github.com/utopia-php/demo)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by vendz** [comment]
@Meldiron @christyjacob4, please assign this to me

**Comment by lohanidamodar** [comment]
@PrerakMathur20 @Akshat-gour @vendz  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Goheljay** [comment]
@christyjacob4 @lohanidamodar can I work on this issue? Can you assign me this issue? 
I have completed all my previous assigned issues.

**Comment by lohanidamodar** [comment]
@Goheljay you've already been assigned an issue of this type already. Please consider picking a different type of issue so other contributors can try this one.

**Comment by appledora** [comment]
> @encodeArnab Assigned it to you! All the best rocket

@Meldiron I wasn't assigned to this officially, but I have made a PR already. Would this be problematic? I am sorry I hadn't seen the assigned tag before.

**Comment by appledora** [comment]
> @appledora Another contributor is already working on this +1

If in case it is available, kindly let me know :smiley:

**Comment by lohanidamodar** [comment]
@encodeArnab Thanks for the PR! 🤯 Please give us some time to review it.
