### ISSUE TITLE
Help us add the Contributing Guidelines to framework repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2084]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [framework](https://github.com/utopia-php/framework).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [framework](https://github.com/utopia-php/framework)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by christyjacob4** [comment]
@Akshat-gour , @rohiraanjali   You've been assigned an issue of this type already. Please consider picking a different type of issue so other contributors can try this one.

**Comment by vendz** [comment]
@christyjacob4, please assign this to me

**Comment by lohanidamodar** [comment]
@vendz  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Goheljay** [comment]
@christyjacob4 @lohanidamodar can I work on this issue? Can you assign me this issue?

**Comment by mohitahlawat2001** [comment]
@Meldiron  assign me issue please

**Comment by daniloff200** [comment]
@StarTrooper08  not cool, not cool....

**Comment by lohanidamodar** [comment]
@FinnKr Assigned to you all the best 🚀

**Comment by lohanidamodar** [comment]
@StarTrooper08 to keep it fair, this is assigned to @FinnKr as first to comment to get assigned and not assigned to another similar issue.  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by StarTrooper08** [comment]
Ok no issue .

**Comment by lohanidamodar** [comment]
@FinnKr Thanks for the PR! 🤯 Please give us some time to review it.
