### ISSUE TITLE
Help us add the Contributing Guidelines to image repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2085]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [image](https://github.com/utopia-php/image).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [image](https://github.com/utopia-php/image)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by parzival272000** [comment]
Can i take this one@christyjacob4

**Comment by christyjacob4** [comment]
@parzival272000  You've been assigned an issue of this type already. Please consider picking a different type of issue so other contributors can try this one.

**Comment by vendz** [comment]
@Meldiron @christyjacob4 please assign this to me

**Comment by neelshah2409** [comment]
@christyjacob4 could you please assign me the issue.

**Comment by lohanidamodar** [comment]
@neelshah2409 assigned to you. All the best 🚀

**Comment by lohanidamodar** [comment]
@neelshah2409 Thanks for the PR! 🤯 Please give us some time to review it.
