### ISSUE TITLE
Help us add the Contributing Guidelines to system repository

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2093]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [system](https://github.com/utopia-php/system).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [system](https://github.com/utopia-php/system)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by MMGOYAl** [comment]
@Meldiron Please assign me this issue. Thanks!

**Comment by srijit2002** [comment]
I would like to work on this issue. @Meldiron.

**Comment by lohanidamodar** [comment]
@vendz  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Goheljay** [comment]
@christyjacob4 @lohanidamodar can I work on this issue? Can you assign me this issue?

**Comment by Goheljay** [comment]
@lohanidamodar I have submitted Pull Request #11 in utopia-php/system
