### ISSUE TITLE
Help us add the Contributing Guidelines to cache repository

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#2102]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [cache](https://github.com/utopia-php/cache).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [cache](https://github.com/utopia-php/cache)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by aniketh-varma** [comment]
Hi @christyjacob4, can I work on this issue?

**Comment by christyjacob4** [comment]
@aniketh-varma  All the best :+1:

**Comment by christyjacob4** [comment]
@Prakhar-IIT-BHU You've been assigned an issue of this type already. Please consider picking a different type of issue so other contributors can try this one.
