### ISSUE TITLE
Help us add the Contributing Guidelines to domains repository

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#2108]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [domains](https://github.com/utopia-php/domains).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [domains](https://github.com/utopia-php/domains)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by kritika-srivastava** [comment]
@christyjacob4 can I work on this issue?

**Comment by lohanidamodar** [comment]
@Prachi8282 You have already been assigned a issue of this type.  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by lohanidamodar** [comment]
@kritika-srivastava assigned to you. All the best!

**Comment by lohanidamodar** [comment]
@1n40 please create a PR only after you are assigned. This is assigned to someone else.  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by lohanidamodar** [comment]
@kritika-srivastava Thank you for you contribution. We will review the PRs soon.
