### ISSUE TITLE
Help us add the Contributing Guidelines to locale repository

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#2111]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [locale](https://github.com/utopia-php/locale).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [locale](https://github.com/utopia-php/locale)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by parzival272000** [comment]
Can i take this

**Comment by qwe123coder** [comment]
Hey there could I work on this

**Comment by lohanidamodar** [comment]
@qwe123coder as you can this is assigned and already has active PR. We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.
