### ISSUE TITLE
Help us add the Contributing Guidelines to preloader repository

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#2114]
## Introduction

Appwrite's **Contributing Guidelines** are present in the main [Appwrite repository](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md). We follow the same Contributing Guidelines across all our projects but some of them are missing the **CONTRIBUTING.md** file in the project.

Your task is to add the CONTRIBUTING.md file to [preloader](https://github.com/utopia-php/preloader).

You can take a look at [Contributing Guidelines](https://github.com/utopia-php/abuse/blob/master//CONTRIBUTING.md) file which we already created for our other proejct as a reference.

### Tasks summary:

- [ ] Fork & clone [preloader](https://github.com/utopia-php/preloader)
- [ ] Add the **Contributing Guidelines** in a `CONTRIBUTING.md` file in the root of the project. (use the PR mentioned above as an example)
- [ ] Push changes and submit a pull request to the `main` or `master` branch depending on the default branch for the repository.

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Meldiron** [comment]
@Prakhar-Agarwal-byte @PrerakMathur20  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Akshat-gour** [comment]
can i work on this

**Comment by HVbajoria** [comment]
I have added the CONTRIBUTING.md for the preloader repo and raised a pull request from the same preloader repository.
Could you please check and let me know if any changes are required.
Thank you.

**Comment by lohanidamodar** [comment]
@kkhitesh assigned to you. All the best 🚀
