### ISSUE TITLE
Design a wallpaper for Appwrite 🖼

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2262]
# Introduction

Appwrite wallpaper is a community-made device background that refers to Appwrite in any way. We are thrilled about our rapidly growing community and we would love to have a library of wallpapers for anyone to enjoy.

Your task is to prepare a wallpaper about Appwrite, either for desktop or mobile devices. If you have an idea, please comment on this issue and we can confirm if the idea is valid. We would highly appreciate it if you share your progress on our [Discord server](https://discord.gg/GSeTUeA).

### Tasks summary:

- [ ]  Fork & clone [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite)
- [ ]  Create and switch to branch `feat-wallpaper-X` where `X` is the name of your wallpaper
- [ ]  Add your wallpaper into `/wallpaper/X.png` where `X` is the name of your wallpaper. Please provide a PNG version in the best format possible - ideally FullHD.
- [ ]  Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? Go ahead! We are accepting as many wallpapers as the community can create. One note, **quality over quantity.**

**Happy Appwriting!**

**Comment by NeonSpork** [comment]
> @Meldiron, could you kindly assign me this task?

The maintainers said in the discord that you can do this without being assigned! It's open to everyone, so have at it 🥳

**Comment by Lakshay-Pruthi** [comment]
@Meldiron Hey did you forgot mine https://github.com/appwrite/awesome-appwrite/pull/167

**Comment by aishurohatgi** [comment]
Hello, I have made a wallpaper for Appwrite. Please do check it out.
Link: [awesome-appwrite/pull/212](https://github.com/appwrite/awesome-appwrite/pull/212)

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
