### ISSUE TITLE
Design a fan art for Appwrite 🎨

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2263]
# Introduction

Appwrite Fan art is a community-made artwork that refers to Appwrite in any way. We are thrilled about our rapidly growing community and we would love to have a library of fan arts for anyone to enjoy.

Your task is to draw a fan art about Appwrite. If you have an idea, please comment on this issue and we can confirm if the idea is valid. We would highly appreciate it if you share your progress on our [Discord server](https://discord.gg/GSeTUeA).

### Tasks summary:

- [ ]  Fork & clone [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite)
- [ ]  Create and switch to branch `feat-fan-art-X` where `X` is the name of your fan art
- [ ]  Add your fan art into `/fan-art/X.png` where `X` is the name of your fan art. Please provide a PNG version in the best format possible - ideally FullHD.
- [ ]  Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? Go ahead! We are accepting as many fan arts as the community can create. One note, **quality over quantity.**

**Happy Appwriting!**

**Comment by Lakshay-Pruthi** [comment]
@Meldiron do check out #163 https://github.com/appwrite/awesome-appwrite/pull/163

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
