### ISSUE TITLE
Design a new Appwrite Discord emoji 🖌

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2264]
# Introduction

Did you know Appwrite's discord has over 4000 members and has been one of the fastest-growing Discord server in the last weeks? 😮 We currently have over 30 custom Discord emojis and we are looking forward to extending our server emoji library.

Your task is to create a Discord emoji for the Appwrite server. If you have an idea, please comment on this issue and we can confirm if the idea is valid.

### Tasks summary:

- [ ]  Fork & clone [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite)
- [ ]  Create and switch to branch `feat-discord-emoji-X` where `X` is the name of the emoji
- [ ]  Add your Discord emoji into `/discord-emoji/X.svg` where `X` is the name of the emoji. Please use `SVG` or `PNG` format only with resolution 128x128
- [ ]  Push changes and submit a pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? Go ahead! We are accepting as many Discord emojis as the community can create. One note, **quality over quantity.**

**Happy Appwriting!**

**Comment by Meldiron** [comment]
@ps-19 Anyone can work on this issue without assignment, go ahead 😊

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
