### ISSUE TITLE
Help developers by writing 'Appwrite + Siri Shortcuts' blog post 🗞

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2282]
# Introduction

Appwrite has been and always will be a tool for developers. To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to write a blog post `Appwrite + Siri Shortcuts`. The main topic of your article should be explaining how to use Appwrite in connection with Siri Shortcuts. It can be anywhere! We accept submissions of articles on any well-known platform, whether it is Medium, Dev.to, HashNode or something else.

### Requirements:

- Your article has to be publicly available
- Your article must tag `appwrite` in any way (hashtag, embedded, link...)
- Your article should be at least 1000 words long
- Your article should look nice 👀 (use titles, subtitles, screenshots, images, gifs, or even memes)

### Task summary:

- [ ] Write a blog post about `Appwrite + Siri Shortcuts`
- [ ] Publish an article on your favourite platform or website (Medium, Dev.to, HashNode...)
- [ ] Share the article on social media (Reddit / HackerNews / Twitter / Facebook / Other)
- [ ] Submit PR to [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite) with a link to your article

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! Stay tuned for a lot more amazing issues from the Appwrite team!
