### ISSUE TITLE
Help developers by writing 'Dart in Appwrite' blog post 🗞

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2302]
# Introduction

Appwrite has been and always will be a tool for developers. To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to write a blog post `Dart in Appwrite`. The main topic of your article should be explaining how to use Appwrites Dart SDK to write Appwrite Functions. It can be anywhere! We accept submissions of articles on any well-known platform, whether it is Medium, Dev.to, HashNode or something else.

### Requirements:

- Your article has to be publicly available
- Your article must tag `appwrite` in any way (hashtag, embedded, link...)
- Your article should be at least 1000 words long
- Your article should look nice 👀 (use titles, subtitles, screenshots, images, gifs, or even memes)

### Task summary:

- [ ] Write a blog post about `Dart in Appwrite`
- [ ] Publish an article on your favourite platform or website (Medium, Dev.to, HashNode...)
- [ ] Share the article on social media (Reddit / HackerNews / Twitter / Facebook / Other)
- [ ] Submit PR to [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite) with a link to your article

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by TafadzwaD** [comment]
@timothy22000 and @sambhavsaxena for this task you do not have to be assigned to it for you to work on it. You just need to write your blog post and then submit a PR to [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite) then voila!😃.. Happy AppWriting

**Comment by ekol-tech** [comment]
🙌

Ekrem Yılmaz
iPhone’umdan gönderildi

**Comment by timothy22000** [comment]
@TafadzwaD I have written my blogpost at [dev.to](https://dev.to/timothy22000/appwrite-with-dart-3knc) and I have made a reddit [post](https://www.reddit.com/r/programming/comments/qju9kk/using_dart_with_appwrite_which_provides_a_secure/) on it.

I had a lot of fun playing around with Appwrite to get content while working on the blogpost :) Let me know if there are any changes that you would like me to make.

**Comment by TafadzwaD** [comment]
@timothy22000 I am not part of the AppWrite team I was just telling you from my understanding.. The team will review your PR 🤞

**Comment by timothy22000** [comment]
@TafadzwaD Ah thanks. I appreciate it - hope you are having a great weekend and enjoying Hacktoberfest.

**Comment by TafadzwaD** [comment]
@timothy22000 You are most welcome😃. Thank you. I hope you are having a blast too

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! tuned for a lot more amazing issues from the Appwrite team!
