### ISSUE TITLE
Help developers by writing 'Python in Appwrite' blog post 🗞

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#2307]
# Introduction

Appwrite has been and always will be a tool for developers. To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to write a blog post `Python in Appwrite`. The main topic of your article should be explaining how to use Appwrites Python SDK to write Appwrite Functions. It can be anywhere! We accept submissions of articles on any well-known platform, whether it is Medium, Dev.to, HashNode or something else.

### Requirements:

- Your article has to be publicly available
- Your article must tag `appwrite` in any way (hashtag, embedded, link...)
- Your article should be at least 1000 words long
- Your article should look nice 👀 (use titles, subtitles, screenshots, images, gifs, or even memes)

### Task summary:

- [ ] Write a blog post about `Python in Appwrite`
- [ ] Publish an article on your favourite platform or website (Medium, Dev.to, HashNode...)
- [ ] Share the article on social media (Reddit / HackerNews / Twitter / Facebook / Other)
- [ ] Submit PR to [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite) with a link to your article

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by emilmerle** [comment]
Hey there. Is it also possible to post directly to Reddit for example?
If it is I would like to do it :)

**Comment by Meldiron** [comment]
@emilmerle Assigned it to you! All the best 🚀

We would prefer some blogging platform - for example Dev.To. Its really easy to create account and write articles in, please give it a shot 😊

**Comment by sohilkhanduja** [comment]
Hey I would like to work on this issue.

**Comment by Meldiron** [comment]
@RobiMez @sohilkhanduja Assigned you both, let's create 2 articles 😎 Good luck 🤘

**Comment by christyjacob4** [comment]
This issue has been resolved! 🥳 Thank you all so much for participating in Hacktoberfest 2021! We can't wait to welcome you all during HF 2022! tuned for a lot more amazing issues from the Appwrite team!
