### ISSUE TITLE
⚡ Write a sendMessage() Function using Deno

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3951]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendMessage()` function using **Deno**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

The function must send a message using a specific channel to a receiver. Make sure to introduce function variables as necessary regarding connection to 3rd party services. Supported channels must be `Email`, `SMS`, `Discord`, and `Twitter`.

Example function payload:

```jsx
{"type":"SMS","receiver":"+123456789","message":"Programming is fun!"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Receiver not in correct format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Deno**.
- Knowledge to implement **sendMessage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendMessage()` in `Deno/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**
