### ISSUE TITLE
⚡ Write a sendMessage() Function using Dart

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3952]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendMessage()` function using **Dart**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

The function must send a message using a specific channel to a receiver. Make sure to introduce function variables as necessary regarding connection to 3rd party services. Supported channels must be `Email`, `SMS`, `Discord`, and `Twitter`.

Example function payload:

```jsx
{"type":"SMS","receiver":"+123456789","message":"Programming is fun!"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Receiver not in correct format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Dart**.
- Knowledge to implement **sendMessage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendMessage()` in `Dart/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by sarkartanmay393** [comment]
I would like to work on it.

**Comment by stnguyen90** [comment]
@sarkartanmay393  thanks for reaching out! 🙏 To make things fair, we will be selecting the first commenter **after** Hacktoberfest officially starts to assign this issue. Feel free to comment again **after** Hacktoberfest starts.

**Comment by LiorBitton** [comment]
Hi, I would like to implement this.

**Comment by chinmayayy** [comment]
Hey @stnguyen90 I would love to work upon this. Thanks!

**Comment by stnguyen90** [comment]
@LiorBitton, thanks for your interest! 🙏 Good luck!

@chinmayayy, we're assigning people on a first come first serve basis. You can find other hacktoberfest issues to work on from our [website](https://hacktoberfest.appwrite.io/).

**Comment by Miyuru-Bhashitha-amarasiri** [comment]
Dear @LiorBitton , I would like to contribute to this issue, can you please assign it to me?

**Comment by Meldiron** [comment]
@Miyuru-Bhashitha-amarasiri , we're assigning people on a first come first serve basis. If @LiorBitton  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by sarkartanmay393** [comment]
@LiorBitton If you are not attempting this issue and let me contribute to it.
@Meldiron If he decides to stay inactive, I would like to take it.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
