### ISSUE TITLE
⚡ Write a sendMessage() Function using Node

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3954]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendMessage()` function using **Node**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

The function must send a message using a specific channel to a receiver. Make sure to introduce function variables as necessary regarding connection to 3rd party services. Supported channels must be `Email`, `SMS`, `Discord`, and `Twitter`.

Example function payload:

```jsx
{"type":"SMS","receiver":"+123456789","message":"Programming is fun!"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Receiver not in correct format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Node**.
- Knowledge to implement **sendMessage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendMessage()` in `Node/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by AmreshSinha** [comment]
Hey @christyjacob4 👋
I would love to work on this!

**Comment by christyjacob4** [comment]
Hey 👋  all issue assignments for Hacktoberfest will take place on a first come first serve basis starting on October 1st

**Comment by itsPriyanshuRaj** [comment]
Hey @christyjacob4 , I would like to contribute to this issue .

**Comment by rahulsunil2** [comment]
Hey @christyjacob4 I would like to work on this.

**Comment by chandankumar1307** [comment]
Hey @christyjacob4 
I have some experience with Node and used Appwrite too in my past projects.
After reading the issue details I have a clear idea of what and how things need to be implemented.
I would love it if you could assign me this issue so that I can start working on it ASAP

**Comment by stnguyen90** [comment]
@itsPriyanshuRaj, thanks for your interest! 🙏 Good luck!

@rahulsunil2, @chandankumar1307, we're assigning people on a first come first serve basis (after hacktoberfest starts). If @itsPriyanshuRaj, is unable to work on this issue, we'll reassign accordingly.

**Comment by itsPriyanshuRaj** [comment]
@stnguyen90 Thanks for assigning it to me. I give my best to complete it.

**Comment by darkblade2090** [comment]
Hello @christyjacob4 , i would like to contribute in this.

**Comment by stnguyen90** [comment]
@darkblade2090, we're assigning people on a first come first serve basis. If @itsPriyanshuRaj isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by shivam2562001** [comment]
@stnguyen90 if it is not assigned to anyone then can you assign this to me 

I have gone through above description and I am also have all skills listed in requirements.
I have proposed solution that for email message we can use nodemailer and for sms we can use twillio and for rest they already provided supported apis.

**Comment by shivam2562001** [comment]
once this sms pull request I will add other pull request too @stnguyen90

**Comment by codercatdev** [comment]
@shivam2562001 added you on this one so you can complete at the same time as #4164, thanks!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
