### ISSUE TITLE
⚡ Write a sendMessage() Function using Python

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3956]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendMessage()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

The function must send a message using a specific channel to a receiver. Make sure to introduce function variables as necessary regarding connection to 3rd party services. Supported channels must be `Email`, `SMS`, `Discord`, and `Twitter`.

Example function payload:

```jsx
{"type":"SMS","receiver":"+123456789","message":"Programming is fun!"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Receiver not in correct format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **sendMessage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendMessage()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Rinshin-Jalal** [comment]
I would like to do this...

**Comment by rahulsunil2** [comment]
Hey @christyjacob4 , I would love to work on this.

**Comment by SaurabhNandy** [comment]
Hey @christyjacob4, I would like to work on this!

**Comment by aryanlath** [comment]
Hi! I would love to work on this and contribute. Can you assign this to me ?

**Comment by subhani-syed** [comment]
Hey @christyjacob4 I have experience working with Python and Docker, I would love to work on this feature, Can you assign me to this issue ?

**Comment by stnguyen90** [comment]
@Rinshin-Jalal, thanks for your interest! 🙏 Happy hacking! 

@rahulsunil2, @SaurabhNandy, @aryanlath, @subhani-syed, we're assigning people on first come first serve basis. If @Rinshin-Jalal isn't able to complete this, we'll reassign accordingly. Feel free to find another hacktoberfest labeled issue!

**Comment by Meldiron** [comment]
@Rinshin-Jalal Regarding Discord, we meant webhooks, correct. Regarding Twitter, what we had in mind was creating a tweet. Just like one of those typical Twitter bots that send a tweet programmatically.

**Comment by Rinshin-Jalal** [comment]
@Meldiron OK
It is easier to do a tweet bot than a twitter DM bot!
thanks👍‍

**Comment by Rinshin-Jalal** [comment]
@Meldiron  

## I have a small doubt

How to post to the open runtimes function?

```
docker run -p 3000:3000 -e INTERNAL_RUNTIME_ENTRYPOINT=src/mod.ts -e INTERNAL_RUNTIME_KEY=secret-key --rm --interactive --tty --volume $PWD/code.tar.gz:/tmp/code.tar.gz:ro openruntimes/deno:1.14 sh /usr/local/src/start.sh
```

I run this command
It is working  

## But when I tried to send a post request to port `3000`
```json
{
    "variables": {
		"TWILIO_ACCOUNT_SID":"account_sid"
		,"TWILIO_AUTH_TOKEN":"auth_token",
		"TWILIO_SENDER": "sender_phone_number"
    },
    "payload": {
		"phoneNumber":"to_phone_number",
	         "text":"Hi, I am a fan of KBFC"
    },
    "headers": {
		"X-Internal-Challenge": "secret-key"
    }
}
```

It returns 
```json
{
    "code": 401,
    "message": "Unauthorized"
}
```

What is the issue??

**Comment by PineappleIOnic** [comment]
When you send the request, make sure you set the `X-Internal-Challenge` header to `secret-key`.

**Comment by Rinshin-Jalal** [comment]
> When you send the request, make sure you set the `X-Internal-Challenge` header to `secret-key`.

Already done that!

```json
{
    "variables": {
		"TWILIO_ACCOUNT_SID":"account_sid"
		,"TWILIO_AUTH_TOKEN":"auth_token",
		"TWILIO_SENDER": "sender_phone_number"
    },
    "payload": {
		"phoneNumber":"to_phone_number",
	         "text":"Hi, I am a fan of KBFC"
    },
    "headers": {
		"X-Internal-Challenge": "secret-key"
    }
}
```

**Comment by PineappleIOnic** [comment]
Headers should be set in the actual headers, not the the json body.  
![image](https://user-images.githubusercontent.com/26739219/193809708-8354c520-eb56-45ed-b9a0-8798842afb6f.png)

**Comment by Rinshin-Jalal** [comment]
What about the envs?

**Comment by PineappleIOnic** [comment]
Make sure you don't have that trailing comma at the end of the payload block, as that'll make it invalid JSON. Otherwise, that should be good.

**Comment by Rinshin-Jalal** [comment]
> 

Ok but it returns a  error

```json
{
	"code": 500,
	"message": "SyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at test (file:///usr/code-start/src/mod.ts:6:38)\n    at file:///usr/local/src/server.ts:45:11\n    at async dispatch (https://deno.land/x/oak@v10.1.0/middleware.ts:41:7)\n    at async EventTarget.#handleRequest (https://deno.land/x/oak@v10.1.0/application.ts:344:9)"
}
```

but when I remove the code `JSON.parse`
from the example code
```ts
  const payload = JSON.parse(req.payload); // not working

  const payload = JSON.parse(req.payload); //  working
```

**Comment by PineappleIOnic** [comment]
You shouldn't need to use JSON.parse, The server within the runtime does it for you. You just need to access req.payload directly

**Comment by Rinshin-Jalal** [comment]
> You shouldn't need to use JSON.parse, The server within the runtime does it for you. You just need to access req.payload directly


Ok, it was one of the examples from the openruntimes/exampes

**Comment by PineappleIOnic** [comment]
I'll update those examples soon

**Comment by Medhanshverma** [comment]
Hey i would like to contribute in this can you assign me this task

**Comment by stnguyen90** [comment]
@Medhanshverma We're assigning people on a first come first serve basis. If @Rinshin-Jalal isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Rinshin-Jalal** [comment]
> @Medhanshverma We're assigning people on a first come first serve basis. If @Rinshin-Jalal isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/). 

Check my pull request

**Comment by Nerotool** [comment]
Send a message to Nerotool_ on instagram for your hacking service.
