### ISSUE TITLE
⚡ Write a sendMessage() Function using Ruby

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3957]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendMessage()` function using **Ruby**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

The function must send a message using a specific channel to a receiver. Make sure to introduce function variables as necessary regarding connection to 3rd party services. Supported channels must be `Email`, `SMS`, `Discord`, and `Twitter`.

Example function payload:

```jsx
{"type":"SMS","receiver":"+123456789","message":"Programming is fun!"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Receiver not in correct format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Ruby**.
- Knowledge to implement **sendMessage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendMessage()` in `Ruby/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by AlgyJr** [comment]
Hey @christyjacob4 , I would like to contribute to this issue .

**Comment by stnguyen90** [comment]
@AlgyJr, thanks for your interest! 🙏 Happy hacking!

**Comment by NightHack36** [comment]
Hi @AlgyJr,  I would like to contribute to this issue, could you please assign this to me?

**Comment by Meldiron** [comment]
@NightHack36 , we're assigning people on a first come first serve basis. If @AlgyJr  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by AlgyJr** [comment]
Sorry @stnguyen90 , can you assing this issue to @NightHack36 , I already completed my hacktoberfest contributions target. I've tried to close this issue, but found it a lot things to do, I've implemented to send message type SMS only, was lefting Email, Discord and Twitter. Thanks for the opportunity.

@NightHack36 Happy Hacktoberfest.

**Comment by Meldiron** [comment]
@AlgyJr Thanks for letting us know 🙏

@NightHack36 Are you still interested in this issue?

**Comment by afzal442** [comment]
Hey @Meldiron I would like to take this up if none is into it. Thanks

**Comment by afzal442** [comment]
Can I be assigned? TY.

cc @Meldiron

**Comment by Meldiron** [comment]
@afzal442 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by stnguyen90** [comment]
@afzal442 are you still working on this or should we unassign you?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
