### ISSUE TITLE
⚡ Write a sendMessage() Function using Swift

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3958]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendMessage()` function using **Swift**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

The function must send a message using a specific channel to a receiver. Make sure to introduce function variables as necessary regarding connection to 3rd party services. Supported channels must be `Email`, `SMS`, `Discord`, and `Twitter`.

Example function payload:

```jsx
{"type":"SMS","receiver":"+123456789","message":"Programming is fun!"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Receiver not in correct format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Swift**.
- Knowledge to implement **sendMessage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendMessage()` in `Swift/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by chinmayayy** [comment]
Hey @christyjacob4 I would like to work upon this. Thanks!

**Comment by stnguyen90** [comment]
@chinmayayy thanks for you interest! 🙏 Happy hacking!

**Comment by rohit162** [comment]
Hey @christyjacob4 
Can u please assign me this issue I wanna work on it.

Thanks and Regards

**Comment by Meldiron** [comment]
@rohit162 , we're assigning people on a first come first serve basis. If @chinmayayy  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by LukeBerryCS** [comment]
Hi! I'm working with @zachspang and @davidNicolas-cecs on this issue for our CodeDay Labs summer open source experience. Thanks!

**Comment by Haimantika** [comment]
> Hi! I'm working with @zachspang and @davidNicolas-cecs on this issue for our CodeDay Labs summer open source experience. Thanks!

Thanks for your interest. I am assigning the issue to you.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
