### ISSUE TITLE
⚡ Write a sendMessage() Function using Java

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3959]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendMessage()` function using **Java**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

The function must send a message using a specific channel to a receiver. Make sure to introduce function variables as necessary regarding connection to 3rd party services. Supported channels must be `Email`, `SMS`, `Discord`, and `Twitter`.

Example function payload:

```jsx
{"type":"SMS","receiver":"+123456789","message":"Programming is fun!"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Receiver not in correct format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Java**.
- Knowledge to implement **sendMessage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendMessage()` in `Java/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by SaurabhNandy** [comment]
Hey @christyjacob4, I would like to work on this!

**Comment by ShubhamSinghgit** [comment]
I would like to work on this issue

**Comment by BabbarRaghav** [comment]
Hey, @christyjacob4, I would like to work on this!

**Comment by stnguyen90** [comment]
@SaurabhNandy, thanks for your interest! 🙏 Happy hacking!

@ShubhamSinghgit, @BabbarRaghav, we're assigning people on a first come first serve basis. If @SaurabhNandy isn't able to complete this, we'll reassign accordingly. Feel free to find another hacktoberfest issue!

**Comment by BabbarRaghav** [comment]
@SaurabhNandy all the best buddy I hope you will be able to complete this issue.

**Comment by Miyuru-Bhashitha-amarasiri** [comment]
Dear @ShubhamSinghgit , I would like to contribute to this issue, can you please assign it to me?

**Comment by Meldiron** [comment]
@Miyuru-Bhashitha-amarasiri , we're assigning people on a first come first serve basis. If @ShubhamSinghgit  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by stnguyen90** [comment]
@anushagupta1312, we're assigning people on a first come first serve basis. If @ShubhamSinghgit isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by zvikfir** [comment]
@stnguyen90 Can I work on this issue?

**Comment by stnguyen90** [comment]
@zvikfir, assigned! Thanks for your interest! 🙏🏼

**Comment by zvikfir** [comment]
I have implemented 3 of the 4 requests.

I have checked that the Discord request works using a private discord server.

However, checking the requests to Mailgun and Twilio is more difficult since I need an account with a token, and it requires credit card details as well.

What should I do about it?

Moreover, the Twitter request requires to generate an Oauth token, which is easiest with the Twitter SDK.

Does it matter which library I choose? Do you have a policy about it?

Here's the list I found:

https://developer.twitter.com/en/docs/twitter-api/tools-and-libraries/v2

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
