### ISSUE TITLE
⚡ Write a sendMessage() Function using Kotlin

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3960]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendMessage()` function using **Kotlin**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

The function must send a message using a specific channel to a receiver. Make sure to introduce function variables as necessary regarding connection to 3rd party services. Supported channels must be `Email`, `SMS`, `Discord`, and `Twitter`.

Example function payload:

```jsx
{"type":"SMS","receiver":"+123456789","message":"Programming is fun!"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Receiver not in correct format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Kotlin**.
- Knowledge to implement **sendMessage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendMessage()` in `Kotlin/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by RahulSoni0** [comment]
hey! can i contribute in this issue ? 
👀

**Comment by stnguyen90** [comment]
@RahulSoni0, assigned! Happy hacking!

**Comment by Miyuru-Bhashitha-amarasiri** [comment]
Dear @RahulSoni0, I would like to contribute to this issue, can you please assign it to me?

**Comment by Meldiron** [comment]
@Miyuru-Bhashitha-amarasiri , we're assigning people on a first come first serve basis. If @RahulSoni0  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by codercatdev** [comment]
Thanks for releasing the assignment @RahulSoni0, @Miyuru-Bhashitha-amarasiri I have assigned the issue to you.

**Comment by ArtP1** [comment]
Hello, I would like to work on this issue.

**Comment by stnguyen90** [comment]
@ArtP1, assigned! Thanks for your interest! 🙏🏼

**Comment by ArtP1** [comment]
Hello, PR has been submitted @stnguyen90 @christyjacob4, Thanks for the opportunity!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by ArtP1** [comment]
Hello,

Our team was wondering what will happen to our contribution for this issue? Will it be considered to be merged any time soon? What would be advised for us to do?
