### ISSUE TITLE
✍️ Write Article About Importing Netlify Users to Appwrite

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3961]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

We understand code contributions might not be your cup of tea, so we decided to prepare a series of blog posts related issues. This series of issues is here to let your writing skills shine, with close to 0 engineering skills required! ✨

Your task is to write a blog post about **How to import Netlify users into Appwrite**. The main topic of your article should be explaining how to export users from Netlify and import them into Appwrite. It can be posted anywhere! We accept submissions of articles on any well-known platform, for example, [Medium](https://medium.com/), [Dev.to](https://dev.to/), or [Hashnode](https://hashnode.com/).

### 🎯 Requirements

- Your article has to be publicly available.
- Your article must tag `appwrite` in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Write a blog post about **How to import Netlify users into Appwrite**.
- [ ]  Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Share the article on social media. (Reddit / HackerNews / Twitter / Facebook / Other)

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by tejasjaiswal07** [comment]
Sounds very Interesting! @christyjacob4 please assign me to this project as I have experience in blog writing and I can do it very well :)
Thank you for considering me.

**Comment by stnguyen90** [comment]
@tejasjaiswal07, thanks for your interest! 🙏 To keep things fair, we will be selecting the 1st commenter **after** Hacktoberfest officially starts. Feel free to comment again starting October 1st.

**Comment by tejasjaiswal07** [comment]
https://medium.com/@rehmanjaiswal/my-review-of-the-google-ux-design-course-6b0570d7727a
you check my new blog on medium

**Comment by stnguyen90** [comment]
@tejasjaiswal07, thanks for your interest! 🙏 Happy hacking!

**Comment by extinctsion** [comment]
I'm interested. @ @christyjacob4 can you assign it to me?

**Comment by stnguyen90** [comment]
@extinctsion Go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.
