### ISSUE TITLE
🎯 Enrich Appwrite Caching with Mcrouter Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3971]
# 💭 Introduction

Appwrite Databases allows you to store and read your application and users' data. Since most of the operations done in your app are querying the data, it’s important to have a good performance on reading. To achieve that, Appwrite uses the [Utopia PHP Cache](https://github.com/utopia-php/cache) library to prevent unnecessary database queries.

Cache library supports multiple adapters such as Redis or Filesystem, but there is always space for more. 😎 Each provider implements simple methods `save()`, `load()`, and `purge()`.

Your task is to implement support for **Mcrouter** in the Utopia PHP cache library. Please look at [existing cache adapters](https://github.com/utopia-php/cache/tree/master/src/Cache/Adapter) to see how a new adapter should be implemented, and make sure you understand it.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Mcrouter**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP cache adapter for **Mcrouter**.
- [ ]  Submit a pull request in [utopia-php/cache](https://github.com/utopia-php/cache).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by piopi** [comment]
@christyjacob4 I would like to take this issue please

**Comment by stnguyen90** [comment]
@piopi, thanks for your interest! 🙏 Happy hacking!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by thecoderishi** [comment]
Hi @christyjacob4 I would like to work on this issue.
Thanks.

**Comment by dishantzaveri** [comment]
Pls assign to me @eldadfux

**Comment by Haimantika** [comment]
> Hi @christyjacob4 I would like to work on this feature.
> Thanks.

Hi @thecoderishi have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
> Pls assign to me @eldadfux

Hi, we are assigning issues on first-come first-serve basis + only 2 issues one person at a time.

**Comment by thecoderishi** [comment]
> > Hi @christyjacob4 I would like to work on this feature.
> > Thanks.
> 
> Hi @thecoderishi have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃
> 
> Notes:
> 
> Please update us with your progress every 3 days, so that we know that you are working on it. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

Hi @Haimantika I have raised MR for this issue.

**Comment by Haimantika** [comment]
> > > Hi @christyjacob4 I would like to work on this feature.
> > > Thanks.
> > 
> > 
> > Hi @thecoderishi have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃
> > Notes:
> > Please update us with your progress every 3 days, so that we know that you are working on it. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!
> 
> Hi @Haimantika I have raised MR for this issue.

Where is it

**Comment by thecoderishi** [comment]
https://github.com/utopia-php/cache/pull/31

**Comment by Haimantika** [comment]
> [utopia-php/cache#31](https://github.com/utopia-php/cache/pull/31)

Steven is reviewing it. Can you also please add the description and mention the issue link?

**Comment by thecoderishi** [comment]
> > [utopia-php/cache#31](https://github.com/utopia-php/cache/pull/31)
> 
> Steven is reviewing it. Can you also please add the description and mention the issue link?

sure

**Comment by tessamero** [comment]
@thecoderishi time sensitive reply on the PR, can you please follow up :)

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
