### ISSUE TITLE
🎯 Enrich Appwrite Caching with Memcached Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3972]
# 💭 Introduction

Appwrite Databases allows you to store and read your application and users' data. Since most of the operations done in your app are querying the data, it’s important to have a good performance on reading. To achieve that, Appwrite uses the [Utopia PHP Cache](https://github.com/utopia-php/cache) library to prevent unnecessary database queries.

Cache library supports multiple adapters such as Redis or Filesystem, but there is always space for more. 😎 Each provider implements simple methods `save()`, `load()`, and `purge()`.

Your task is to implement support for **Memcached** in the Utopia PHP cache library. Please look at [existing cache adapters](https://github.com/utopia-php/cache/tree/master/src/Cache/Adapter) to see how a new adapter should be implemented, and make sure you understand it.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Memcached**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP cache adapter for **Memcached**.
- [ ]  Submit a pull request in [utopia-php/cache](https://github.com/utopia-php/cache).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by shtelzerartem** [comment]
@christyjacob4 hey! I would like to work on this!

**Comment by stnguyen90** [comment]
@shtelzerartem, thanks for you interest! 🙏 Good luck!
