### ISSUE TITLE
🎯 Enrich Appwrite Caching with Hazelcast IMDG Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3973]
# 💭 Introduction

Appwrite Databases allows you to store and read your application and users' data. Since most of the operations done in your app are querying the data, it’s important to have a good performance on reading. To achieve that, Appwrite uses the [Utopia PHP Cache](https://github.com/utopia-php/cache) library to prevent unnecessary database queries.

Cache library supports multiple adapters such as Redis or Filesystem, but there is always space for more. 😎 Each provider implements simple methods `save()`, `load()`, and `purge()`.

Your task is to implement support for **Hazelcast IMDG** in the Utopia PHP cache library. Please look at [existing cache adapters](https://github.com/utopia-php/cache/tree/master/src/Cache/Adapter) to see how a new adapter should be implemented, and make sure you understand it.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Hazelcast IMDG**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP cache adapter for **Hazelcast IMDG**.
- [ ]  Submit a pull request in [utopia-php/cache](https://github.com/utopia-php/cache).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by kaggrwal** [comment]
Hey @christyjacob4 - can i work on this issue, if no one else is working ?

**Comment by stnguyen90** [comment]
@kaggrwal, thanks for your interest! 🙏 Happy hacking!

**Comment by kaggrwal** [comment]
@stnguyen90 @christyjacob4 

I have done some changes in this [pull request](https://github.com/utopia-php/cache/pull/22). 
I don't have much knowledge about docker, though i have include the memcached extension and built the image and verified too. Kindly review and Let me know if there is any improvement that is required.

**Comment by kaggrwal** [comment]
@stnguyen90 Please review this and label it with accepted. 
https://github.com/utopia-php/cache/pull/28
