### ISSUE TITLE
🎯 Enrich Appwrite Caching with Varnish Cache Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3974]
# 💭 Introduction

Appwrite Databases allows you to store and read your application and users' data. Since most of the operations done in your app are querying the data, it’s important to have a good performance on reading. To achieve that, Appwrite uses the [Utopia PHP Cache](https://github.com/utopia-php/cache) library to prevent unnecessary database queries.

Cache library supports multiple adapters such as Redis or Filesystem, but there is always space for more. 😎 Each provider implements simple methods `save()`, `load()`, and `purge()`.

Your task is to implement support for **Varnish Cache** in the Utopia PHP cache library. Please look at [existing cache adapters](https://github.com/utopia-php/cache/tree/master/src/Cache/Adapter) to see how a new adapter should be implemented, and make sure you understand it.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Varnish Cache**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP cache adapter for **Varnish Cache**.
- [ ]  Submit a pull request in [utopia-php/cache](https://github.com/utopia-php/cache).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by shtelzerartem** [comment]
@christyjacob4 I would also like to work on this one! :)

**Comment by aadityaagrawal** [comment]
Hi, Can you please assign this issue to me?

**Comment by stnguyen90** [comment]
@aadityaagrawal Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by Yashsomalkar** [comment]
I would like to work on this issue

**Comment by Yashsomalkar** [comment]
@Haimantika  @christyjacob4  can anyone assign me this issue. It would be great.

**Comment by Haimantika** [comment]
> @Haimantika @christyjacob4 can anyone assign me this issue. It would be great.

Hi @Yashsomalkar , I've assigned this issue to you! Thanks your interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Yashsomalkar** [comment]
Sure thing !

**Comment by Yashsomalkar** [comment]
I have issue findinding php varnish cache extension

**Comment by Yashsomalkar** [comment]
I have researched some. And wrote a pseudo code i will create a draft pr today

**Comment by Haimantika** [comment]
> I have researched some. And wrote a pseudo code i will create a draft pr today

Hi, let us know whenever you PR is ready to be reviewed

**Comment by Haimantika** [comment]
Hi @Yashsomalkar is there any update on your PR?

**Comment by Yashsomalkar** [comment]
I am confused for what exact package i need to use can I get some help or should I leave this issue and let someone who knows do it?

**Comment by Yashsomalkar** [comment]
I am confused for what exact package i need to use can I get some help or should I leave this issue and let someone who knows do it?@Haimantika

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over and there's no activity/update on the PR/issue. Thank you to everyone who participated this year :)
