### ISSUE TITLE
🎯 Enrich Appwrite Caching with Apache Ignite Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3975]
# 💭 Introduction

Appwrite Databases allows you to store and read your application and users' data. Since most of the operations done in your app are querying the data, it’s important to have a good performance on reading. To achieve that, Appwrite uses the [Utopia PHP Cache](https://github.com/utopia-php/cache) library to prevent unnecessary database queries.

Cache library supports multiple adapters such as Redis or Filesystem, but there is always space for more. 😎 Each provider implements simple methods `save()`, `load()`, and `purge()`.

Your task is to implement support for **Apache Ignite** in the Utopia PHP cache library. Please look at [existing cache adapters](https://github.com/utopia-php/cache/tree/master/src/Cache/Adapter) to see how a new adapter should be implemented, and make sure you understand it.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Apache Ignite**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP cache adapter for **Apache Ignite**.
- [ ]  Submit a pull request in [utopia-php/cache](https://github.com/utopia-php/cache).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by MaheshAravindV** [comment]
Hey, can I work on this?
I have used docker and docker compose and I feel like I can read up the rest.

**Comment by stnguyen90** [comment]
@MaheshAravindV, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by tusqasi** [comment]
Hey @christyjacob4 I would love to work on this issue! Could you assign me this issue?

**Comment by VigneshMurugan** [comment]
I would like to work on this issue. Please assign it to me

**Comment by oussamabouchikhi** [comment]
Hi 👋🏻  @christyjacob4  I would love to work on this issue! Could you assign it to me please 👼🏻

**Comment by surya0180** [comment]
Hey @christyjacob4 , I would like to work on this issue. Can you please assign this to me ?

**Comment by Haimantika** [comment]
Hi @oussamabouchikhi @soumya-dash3 @surya0180 👋 thanks for your interest. We are assigning issues on a first-come, first-serve basis if @tusqasi decides to drop off, we will assign the issue to the next person in line.

**Comment by tusqasi** [comment]
Thanks for assigning the issue. I will be updating progress here.

**Comment by AryanParashar24** [comment]
hey @Haimantika can u assign this to me, i would luv to work on this issue 😃😄

**Comment by oussamabouchikhi** [comment]
Hi @Haimantika. I will unfortunately continue working on this feature. I am sorry. You re-assign another person

**Comment by Haimantika** [comment]
Hi @tusqasi is there any update?

**Comment by tusqasi** [comment]
I got started with writing the adaptor. I had some issues getting the tests running but they are now failing successful.

**Comment by nick2432** [comment]
can i work on this?

**Comment by Haimantika** [comment]
> I got started with writing the adaptor. I had some issues getting the tests running but they are now failing successful.

Hi, are you getting stuck somewhere? You can reach out to us on Discord

**Comment by tusqasi** [comment]
I will leave this issue, I have already taken much time. I was going to start learning PHP from here, but it seems a bit too ambitious for now.

Sorry for hogging on the issue this long.

**Comment by Haimantika** [comment]
> I will leave this issue, I have already taken much time. I was going to start learning PHP from here, but it seems a bit too ambitious for now.
> 
> Sorry for hogging on the issue this long.

No worries, thanks for letting us know :)

**Comment by Haimantika** [comment]
> I would like to work on this issue. Please assign it to me

Hi, you are next in-line, are you interested to work on it?

**Comment by Anurag-space** [comment]
@Haimantika 
i would like to work on this issue. Could you please assign me this issue.

**Comment by Haimantika** [comment]
Hi @soumya-dash3 you are next, are you interested to work on this issue?

**Comment by Haimantika** [comment]
> @Haimantika i would like to work on this issue. Could you please assign me this issue.

Hi, we are assigning issues on a first-come, first-serve basis. There is a queue for this issue, so you will need to wait.

**Comment by Anurag-space** [comment]
thank for assigning me this issue.
