### ISSUE TITLE
📄 Enhance Appwrite Databases with SurrealDB Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3976]
# 💭 Introduction

Appwrite Databases allows you to store your application and users' data. Not only that, it comes with query system that allows you to read those data. We put a lot of effort into making Appwrite Databases secure by default, and the whole security layer is truly easy to configure. 😇 You can learn more about [Appwrite Databases](https://appwrite.io/docs/databases) and [Appwrite Permissions](https://appwrite.io/docs/permissions) in our official docs.

Every collection and document in Appwrite Database needs to be stored somewhere, and for that, we have many different adapters such as MySQL or MongoDB. Each provider implements simple methods such as `createDocument()`, `deleteDocument()`, `find()`, etc...

Your task is to implement support for **SurrealDB** in the Utopia PHP database library. We have prepared detailed documentation on [how to create a Utopia PHP database adapter](https://github.com/utopia-php/database/blob/main/docs/add-new-adapter.md). Please read these documents and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **SurrealDB**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP database adapter for **SurrealDB**.
- [ ]  Submit a pull request in [utopia-php/database](https://github.com/utopia-php/database).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by koolgax99** [comment]
Hi @christyjacob4, i would like to work on this issue. Can you assign it to me?

**Comment by stnguyen90** [comment]
@koolgax99, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by faisalill** [comment]
Hey, @christyjacob4 can you please assign me this issue.

**Comment by Haimantika** [comment]
> Hey, @christyjacob4 can you please assign me this issue.

Hi @faisalill have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by surya0180** [comment]
Hey @christyjacob4 , I would like to work on this issue. Can you please assign this to me ?

**Comment by Haimantika** [comment]
> Hey @christyjacob4 , I would like to work on this issue. Can you please assign this to me ?

Hi, we are assigning issues on a first-come, first-serve basis, if @faisalill decides to drop off, we will assign it to you.

**Comment by HARSHALJETHWA19** [comment]
Hello, can you please assign this task to me for Hacktoberfest 2023

**Comment by HARSHALJETHWA19** [comment]
Hacktoberfest 2023

**Comment by Haimantika** [comment]
> Hello, can you please assign this task to me for Hacktoberfest 2023

Hi, we are assigning issues on a first-come, first-serve basis, if the other user decides to drop, we will assign it to you.

**Comment by faisalill** [comment]
@Haimantika @christyjacob4 
SurrealDB has no sdk for php, the only route as of now is to use the http endpoints provided by the database.
Should I use async http requests or sync ??? Coz in the end appwrite runs on swoole(guzzle http client works with swoole)

**Comment by christyjacob4** [comment]
@faisalill please check how their other SDKs are functioning. If they are interfacing directly with Surreal DBs HTTP API as well, then you can go ahead with that approach.

As for the HTTP client, you can use guzzle for now.

**Comment by faisalill** [comment]
@christyjacob4 
SurrealDB sdks ([python](https://github.com/surrealdb/surrealdb.py/blob/main/surrealdb/http.py), js) make async http requests to the database.
Guzze Async request block the main event loop [check this out for more context](https://github.com/guzzle/guzzle/issues/1127)
Tried to use swoole but the whole php app should be in a coroutine context for the 
code to work async and not block the code. 
Can't use sync since it can't handle multiple/heavy load of requests becuase of event blocking.

**Comment by faisalill** [comment]
@christyjacob4 @Haimantika 
SurrealDB SDK's ([python](https://github.com/surrealdb/surrealdb.py/blob/main/surrealdb/http.py), [js](https://github.com/surrealdb/surrealdb.js/blob/main/src/strategies/http.ts)) make async http requests.
Tried to do the same with Guzzle but async in php blocks the main thread. [check here for more info](https://github.com/guzzle/guzzle/issues/1127)
As of now [PHPSDK](https://github.com/surrealdb/surrealdb.php/pull/6) for surrealdb is on it's way.
Waiting for it would be a better option.

**Comment by christyjacob4** [comment]
@faisalill we don't need to make async requests inside the db library. They can be synchronous. You can continue to use guzzle or even our new http library https://github.com/utopia-php/fetch to make the blocking requests. 

As you can see even with the other adapters like MariaDB, Postgres etc, all the methods are indeed blocking..

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over and there's no pending PR or a draft PR attached. Thank you to everyone who participated this year :)
