### ISSUE TITLE
📄 Enhance Appwrite Databases with Redis Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3977]
# 💭 Introduction

Appwrite Databases allows you to store your application and users' data. Not only that, it comes with query system that allows you to read those data. We put a lot of effort into making Appwrite Databases secure by default, and the whole security layer is truly easy to configure. 😇 You can learn more about [Appwrite Databases](https://appwrite.io/docs/databases) and [Appwrite Permissions](https://appwrite.io/docs/permissions) in our official docs.

Every collection and document in Appwrite Database needs to be stored somewhere, and for that, we have many different adapters such as MySQL or MongoDB. Each provider implements simple methods such as `createDocument()`, `deleteDocument()`, `find()`, etc...

Your task is to implement support for **Redis** in the Utopia PHP database library. We have prepared detailed documentation on [how to create a Utopia PHP database adapter](https://github.com/utopia-php/database/blob/main/docs/add-new-adapter.md). Please read these documents and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Redis**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP database adapter for **Redis**.
- [ ]  Submit a pull request in [utopia-php/database](https://github.com/utopia-php/database).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by techytushar** [comment]
Hey @christyjacob4 ,
I can work on this, please assign this to me

**Comment by tessamero** [comment]
@techytushar , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by ArnabChatterjee20k** [comment]
I am having experience working with redis as a cache and docker for building applications. I know php but haven't used it for building anything. But I will learn on the go.
Can I work on this issue?
I will use the official [php_redis](https://developer.redis.com/develop/php/) as the binding.

**Comment by Haimantika** [comment]
> I am having experience working with redis as a cache and docker for building applications
> Can I work on this issue?
> I will use the official [php_redis](https://developer.redis.com/develop/php/) as the binding.

Hi @ArnabChatterjee20k have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by ArnabChatterjee20k** [comment]
Haven't make any progress till now.
Actually my exams are going on this week, I will try to setup the project locally today and if failed I will surely start from Saturday.

**Comment by tessamero** [comment]
Thank you for the update @ArnabChatterjee20k , the issue will stay assigned to you as long as you give proper updates, even if you mention you haven't started yet, that is fine, as long we know you still want to work on issue :)

**Comment by ArnabChatterjee20k** [comment]
I started working on it
Currently doing the local setup and resolving some regarding that
Will do the further update after I make a progress within next 3 days

**Comment by ArnabChatterjee20k** [comment]
I am still getting this issue from yesterday
```php
PHP 
Fatal error:  Uncaught TypeError: Utopia\Database\Adapter\Mongo::__construct(): Argument #1 ($client) must be of type Utopia\Mongo\Client, MongoDB\Client given, called in /home/arnab/Desktop/test.php on line 19 and defined in /home/arnab/Desktop/database/src/Database/Adapter/Mongo.php:53
Stack trace:
#0 /home/arnab/Desktop/test.php(19): Utopia\Database\Adapter\Mongo->__construct()
#1 {main}
  thrown in /home/arnab/Desktop/database/src/Database/Adapter/Mongo.php on line 53
```
Any help or a hint?

**Comment by ArnabChatterjee20k** [comment]
I solved the error
but now getting Swoole Client error although its present in the vendor file
Any clue?

**Comment by ArnabChatterjee20k** [comment]
Solved the issue I was getting.
Something I want to mention, some parts of local setup is missing.
So I am going to start implementing redis adaptar

**Comment by Haimantika** [comment]
> Solved the issue I was getting. Something I want to mention, some parts of local setup is missing. So I am going to start implementing redis adaptar

Cool, is there anything we can help with? Feel free to raise an issue for the missing parts :)

**Comment by ArnabChatterjee20k** [comment]
Started developing adaptar from today. Will updated tomorrow or within next 3 days

**Comment by ArnabChatterjee20k** [comment]
@Haimantika @tessamero @christyjacob4 
### Two confirmations -
* I am using the official php redis package installed with pecl
* Since redis is a key value based database we cant create tables. So I am implementing creating tables using hasmap.

### Question
* For searching and filtering shall I use community redis search packages or will I go with pattern based searching?

**Comment by ArnabChatterjee20k** [comment]
@christyjacob4 @Haimantika @tessamero 
I think this implementation will work?
The Adaptor abstract class is implementing the list method which is basically returning a list of databases.
* Redis is having only 0 to 15 number databases by default and to change databse number we need to update the .conf file and also restart the server
* So I think using a hashset will be a great choice instead
So the ultimate the lookup will look like
```
redis instance ={
    databaseName:{
           tableName:{}
     }
}
```
And for creating of the collections I am reffering to the mongodb adapter cause both redis and mongodb are schemaless. So some among them will be common

**Comment by ArnabChatterjee20k** [comment]
I unassigned myself due to some other important priorities and as a result I was not able to manage. After its get over I will again request for the assignment if its not get assigned to someone else
Thank you

**Comment by aoamusat** [comment]
@Haimantika kindly assign to me if no one's working on it.

**Comment by aoamusat** [comment]
Finished setting up the project on my local machine.
Currently implementing the abstract interfaces from `use Utopia\Database\Adapter;`

**Comment by aoamusat** [comment]
I finished implementing the RedisAdapter.
Currently writing test to test the class.

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over and there's no pending PR or a draft PR attached. Thank you to everyone who participated this year :) @aoamusat if you were still working on it, save the link to this closed issue and request to reopen it on our discord community
