### ISSUE TITLE
📄 Enhance Appwrite Databases with Apache Hbase Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3978]
# 💭 Introduction

Appwrite Databases allows you to store your application and users' data. Not only that, it comes with query system that allows you to read those data. We put a lot of effort into making Appwrite Databases secure by default, and the whole security layer is truly easy to configure. 😇 You can learn more about [Appwrite Databases](https://appwrite.io/docs/databases) and [Appwrite Permissions](https://appwrite.io/docs/permissions) in our official docs.

Every collection and document in Appwrite Database needs to be stored somewhere, and for that, we have many different adapters such as MySQL or MongoDB. Each provider implements simple methods such as `createDocument()`, `deleteDocument()`, `find()`, etc...

Your task is to implement support for **Apache Hbase** in the Utopia PHP database library. We have prepared detailed documentation on [how to create a Utopia PHP database adapter](https://github.com/utopia-php/database/blob/main/docs/add-new-adapter.md). Please read these documents and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Apache Hbase**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP database adapter for **Apache Hbase**.
- [ ]  Submit a pull request in [utopia-php/database](https://github.com/utopia-php/database).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by MaheshAravindV** [comment]
Hey! Can I work on this?
I have used Docker and Docker compose before and I would like to learn Hbase

**Comment by stnguyen90** [comment]
@MaheshAravindV, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by Cioraz** [comment]
Hello!
Im interesed in resolving this issue, can i work on this?

**Comment by Haimantika** [comment]
> Hello!
> Im interesed in resolving this issue, can i work on this?

Hi @Cioraz , I've assigned the issue to you! Happy Hacktoberfest 🎃!

Notes:

Please update us with your progress every 3 days, so that we know you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Cioraz** [comment]
Will look into other issues

**Comment by giovannism20** [comment]
Can I take the assignment @Haimantika ?

**Comment by brantheeman** [comment]
I would like to attempt this task as well. I know it's first come first serve, so I will wait and let @Haimantika go at it.

**Comment by Haimantika** [comment]
> Can I take the assignment @Haimantika ?

Have assigned the issue to you. Please remember to share updates every 3 days and ask your doubts/queries in [Discord](https://appwrite.io/docs), if any.

**Comment by Haimantika** [comment]
Hi @giovannism20 any update?

**Comment by giovannism20** [comment]
I've already started working on it @Haimantika

**Comment by giovannism20** [comment]
Hey @Haimantika, what are the task acceptance criteria?

**Comment by Haimantika** [comment]
> Hey @Haimantika, what are the task acceptance criteria?

You just need to follow the task summary:

 ```
Implement Utopia PHP database adapter for Apache Hbase.
 Submit a pull request in [utopia-php/database](https://github.com/utopia-php/database).
```

**Comment by nick2432** [comment]
Hi, I would like to work on this, please assign this task to me. Thanks!

**Comment by Haimantika** [comment]
Hi @giovannism20 are you still working on it?

**Comment by giovannism20** [comment]
Yes @Haimantika

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over and there's no pending PR. Thank you to everyone who participated this year :)
