### ISSUE TITLE
📄 Enhance Appwrite Databases with Apache Cassandra Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3979]
# 💭 Introduction

Appwrite Databases allows you to store your application and users' data. Not only that, it comes with query system that allows you to read those data. We put a lot of effort into making Appwrite Databases secure by default, and the whole security layer is truly easy to configure. 😇 You can learn more about [Appwrite Databases](https://appwrite.io/docs/databases) and [Appwrite Permissions](https://appwrite.io/docs/permissions) in our official docs.

Every collection and document in Appwrite Database needs to be stored somewhere, and for that, we have many different adapters such as MySQL or MongoDB. Each provider implements simple methods such as `createDocument()`, `deleteDocument()`, `find()`, etc...

Your task is to implement support for **Apache Cassandra** in the Utopia PHP database library. We have prepared detailed documentation on [how to create a Utopia PHP database adapter](https://github.com/utopia-php/database/blob/main/docs/add-new-adapter.md). Please read these documents and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Apache Cassandra**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP database adapter for **Apache Cassandra**.
- [ ]  Submit a pull request in [utopia-php/database](https://github.com/utopia-php/database).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by SuperMohit** [comment]
@christyjacob4 can you please assign this to me?

**Comment by Meldiron** [comment]
@SuperMohit , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by bitethecode** [comment]
@christyjacob4 Hey Chris, I noticed that this is unassigned. Could I try this?

**Comment by stnguyen90** [comment]
@bitethecode, we would love to have your contribution! However, since Hacktoberfest is over, you won't be eligible for any Hacktoberfest rewards. Let me know if you're still interested and I can assign you.

**Comment by bitethecode** [comment]
@stnguyen90 Oh, I don't need that. I simply want to contribute and learn :)

**Comment by stnguyen90** [comment]
Assigned! Thanks for the support!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by ajaykrathod** [comment]
Can I look into this one?

**Comment by Haimantika** [comment]
> Can I look into this one?

Hi @ajaykrathod have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
Hi @ajaykrathod any update?

**Comment by sidgaikwad** [comment]
Plz Assign this issue to me, i would like to work on this issue

**Comment by Haimantika** [comment]
> Plz Assign this issue to me, i would like to work on this issue

The issue is your now, please update us every 3 days

**Comment by Haimantika** [comment]
Hi @sidgaikwad please remember to share your updates every 3 days

**Comment by sidgaikwad** [comment]
@Haimantika  yes

**Comment by Haimantika** [comment]
> @Haimantika yes

Hi, is there any updates?

**Comment by sidgaikwad** [comment]
@Haimantika yess i'll try to push the code between todsy or tommorow 
i have added the docker image of cassendra and wruting the code for cassendra adaptor

**Comment by sidgaikwad** [comment]
@Haimantika yess i'll try to push the code between Today or tommorow 
i have added the docker image of cassendra and writing the code for cassendra adaptor

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over and there's no pending PR. Thank you to everyone who participated this year :)
