### ISSUE TITLE
📄 Enhance Appwrite Databases with Apache CouchDB Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3981]
# 💭 Introduction

Appwrite Databases allows you to store your application and users' data. Not only that, it comes with query system that allows you to read those data. We put a lot of effort into making Appwrite Databases secure by default, and the whole security layer is truly easy to configure. 😇 You can learn more about [Appwrite Databases](https://appwrite.io/docs/databases) and [Appwrite Permissions](https://appwrite.io/docs/permissions) in our official docs.

Every collection and document in Appwrite Database needs to be stored somewhere, and for that, we have many different adapters such as MySQL or MongoDB. Each provider implements simple methods such as `createDocument()`, `deleteDocument()`, `find()`, etc...

Your task is to implement support for **Apache CouchDB** in the Utopia PHP database library. We have prepared detailed documentation on [how to create a Utopia PHP database adapter](https://github.com/utopia-php/database/blob/main/docs/add-new-adapter.md). Please read these documents and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Apache CouchDB**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP database adapter for **Apache CouchDB**.
- [ ]  Submit a pull request in [utopia-php/database](https://github.com/utopia-php/database).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by stnguyen90** [comment]
@TheOjasSingh, thanks for your interest! 🙏 Happy hacking!

**Comment by TheOjasSingh** [comment]
where should I find the other adapters in the repo for an example.

**Comment by Meldiron** [comment]
@TheOjasSingh you could follow the [tutorial](https://github.com/utopia-php/database/blob/main/docs/add-new-adapter.md) or look at [MariaDB adapter](https://github.com/utopia-php/database/blob/main/src/Database/Adapter/MariaDB.php).

**Comment by TheOjasSingh** [comment]
Can you help me with the setup of the .envrc file

**Comment by stnguyen90** [comment]
@TheOjasSingh, can you try following this: https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md#code-autocompletion

**Comment by TheOjasSingh** [comment]
I am following the above tutorial for setting up the repo utopia-php/database but It is still showing the error.
![Screenshot 2022-10-08 184449](https://user-images.githubusercontent.com/55990400/194709493-b4e567ef-32af-4895-a206-ee01190f7e3e.png)

**Comment by Meldiron** [comment]
@TheOjasSingh Hey there 👋 Where are you trying to install this library? To contribute new adapter, ideally, you would implement it in the library and write tests to ensure it works. You should not need to make a side project to do manual testing.

**Comment by stnguyen90** [comment]
@TheOjasSingh, are you still working on this or should we unassign you?

**Comment by TheOjasSingh** [comment]
You can unassign me

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by Ratangulati** [comment]
I'm not so sure about my ability to do this, but can I try to work on this?

**Comment by bannu0snake** [comment]
Hi, can you assign this Issue to me ?

**Comment by Haimantika** [comment]
> I'm not so sure about my ability to do this, but can I try to work on this?

Hi @ayan-joshi have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
Hi @Ratangulati any update?

**Comment by sidgaikwad** [comment]
plz Assign this to me, I would like to work on this issue

**Comment by Haimantika** [comment]
> plz Assign this to me, I would like to work on this issue

I have already assigned one issue to you, would you still like to take this one up?

**Comment by Tushar98644** [comment]
@Haimantika i would like to take this up

**Comment by sidgaikwad** [comment]
@Tushar98644 I am currently working on this issue

**Comment by KholoodS** [comment]
Hello, I would love to contribute on this issue.

**Comment by Tushar98644** [comment]
@Haimantika When can we expect new issues to drop ?

**Comment by Haimantika** [comment]
> @Tushar98644 I am currently working on this issue

Are you working? Then I will be assigning this issue to you.

**Comment by Tushar98644** [comment]
> > @Haimantika When can we expect new issues to drop ?
> 
> We already dropped new issues this week

So new issues will be added next week ig ?

**Comment by Haimantika** [comment]
> > > @Haimantika When can we expect new issues to drop ?
> > 
> > 
> > We already dropped new issues this week
> 
> So new issues will be added next week ig ?

Hi, thank you for your interest in participating in Hacktoberfest!

We really appreciate your enthusiasm.

So this year, we’re focused on quality contributions. This doesn’t just mean we want quality code from contributors; we also want to foster a quality relationship with the contributors through extensive reviews and support so they can tackle more meaningful and difficult projects.

With that said, we have a small team with limited capacity. So we’re careful about how many active issues we post for Hacktoberfest, so we can review and support each contributor adequately. 

That said, if you find a reasonably sized issue on the Appwrite repo that you’d like to tackle, you can pitch your solution to the problem and message us on Discord. We will review and label the issue Hacktoberfest if it makes sense.

We also have community rewards every month for everything from cool projects, helpful community members, and even just sick memes. If you’re interested in contributing, being an active community member is also a good way to go.

**Comment by tessamero** [comment]
hi @sidgaikwad , I have assigned the issue to you, you may start contributing to it :) Reminder to check-in every 3 days so we know you are still working on it so it doesn't get reassigned. Thank you and happy hacking :)

**Comment by Tushar98644** [comment]
@tessamero Can you pls reassign the issue , there is no update from the current assignee for more than 3 days

**Comment by Haimantika** [comment]
Hi @sidgaikwad are you still working on it? If you have any updates, please let us know. We will be reassigning the issue to the next person soon due to inactivity

**Comment by sidgaikwad** [comment]
@Haimantika you can assign it to other person i am working on the cassendra adapter

**Comment by Haimantika** [comment]
@Tushar98644 you are next, but you have already requested to be assigned to some more issues. Let me know which issues you would like to work on, also, we are assigning 2 issues at max per person

**Comment by jaysomani** [comment]
Hello, can i work on this issue ?

**Comment by jaysomani** [comment]
🚀 Just a Quick update:
✅Done setting up locally
✅ Read and understood CouchDB docs 📖 and adapter guide 🛠️.
✅ Approach planned for enhancing Appwrite DB with CouchDB, 
coding part started! 🚀

**Comment by jaysomani** [comment]
update:

getting errors clearing them out

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over and there's no pending PR and no activity in the last 3 days. Thank you to everyone who participated this year :)
