### ISSUE TITLE
📄 Enhance Appwrite Databases with Microsoft SQL Server Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3982]
# 💭 Introduction

Appwrite Databases allows you to store your application and users' data. Not only that, it comes with query system that allows you to read those data. We put a lot of effort into making Appwrite Databases secure by default, and the whole security layer is truly easy to configure. 😇 You can learn more about [Appwrite Databases](https://appwrite.io/docs/databases) and [Appwrite Permissions](https://appwrite.io/docs/permissions) in our official docs.

Every collection and document in Appwrite Database needs to be stored somewhere, and for that, we have many different adapters such as MySQL or MongoDB. Each provider implements simple methods such as `createDocument()`, `deleteDocument()`, `find()`, etc...

Your task is to implement support for **Microsoft SQL Server** in the Utopia PHP database library. We have prepared detailed documentation on [how to create a Utopia PHP database adapter](https://github.com/utopia-php/database/blob/main/docs/add-new-adapter.md). Please read these documents and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Microsoft SQL Server**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP database adapter for **Microsoft SQL Server**.
- [ ]  Submit a pull request in [utopia-php/database](https://github.com/utopia-php/database).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by plumsirawit** [comment]
I'm not so sure about my ability to do this, but can I try to work on this?

**Comment by stnguyen90** [comment]
@plumsirawit, you got this! We can always unassign you if you're unable to complete this.

**Comment by stnguyen90** [comment]
@plumsirawit are you still working on this or should we unassign you?

**Comment by abnegate** [comment]
@plumsirawit Any update here?

**Comment by 2002Bishwajeet** [comment]
Can I be assigned please??

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by akshatmishra25** [comment]
Though I have less experience in PHP but I can try my best to contribute to this issue.
So, can you assign me this issue?

**Comment by Haimantika** [comment]
> Though I have less experience in PHP but I can try my best to contribute to this issue.
> So, can you assign me this issue?

Hi @akshatmishra25 , I've assigned the issue to you! Happy Hacktoberfest 🎃!

Notes:

Please update us with your progress every 3 days, so that we know you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by soumyadeeproychowdhury** [comment]
Hi ! can I also work on this issue!

**Comment by Haimantika** [comment]
> Hi ! can I also work on this issue!

Hi, we are assigning issues on a first-come, first-serve basis, if the other user decides to drop, we will assign it to you.

**Comment by Haimantika** [comment]
Hi @akshatmishra25 any update? The issue will go to the next person due to inactivity on your end

**Comment by akshatmishra25** [comment]
Yeah so I took part in the last pr review party as I had some confusions with mssql and how to start coding up. So I have started now, will take a little time.

**Comment by nick2432** [comment]
can i work on it?

**Comment by akash47angadi** [comment]
@Haimantika can you assign me this issue

**Comment by Haimantika** [comment]
@akshatmishra25 do you have an update? Any update about your progress / queries will help us know that you are still working on it.

**Comment by Haimantika** [comment]
> @Haimantika can you assign me this issue

Hi, we are assigning issues on a first-come, first-serve basis.

**Comment by akshatmishra25** [comment]
> @akshatmishra25 do you have an update? Any update about your progress / queries will help us know that you are still working on it. 

I am extremely sorry as I have been absolutely busy due to some work in my college. I couldn't find the time to work on the PR although I did start working on it. You may assign it to someone else as I won't be able to get any time due to a very hectic schedule.

**Comment by nick2432** [comment]
@Haimantika, could you please assign this to me?

**Comment by Haimantika** [comment]
> @Haimantika, could you please assign this to me?

Let's wait a few more hours for Soumyadeep to respond, if not, will assign it to you.

**Comment by nick2432** [comment]
@Haimantika I think now you should assign this to me. :)

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over and there's no pending PR. Thank you to everyone who participated this year :)
