### ISSUE TITLE
📄 Enhance Appwrite Databases with Neo4j Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3983]
# 💭 Introduction

Appwrite Databases allows you to store your application and users' data. Not only that, it comes with query system that allows you to read those data. We put a lot of effort into making Appwrite Databases secure by default, and the whole security layer is truly easy to configure. 😇 You can learn more about [Appwrite Databases](https://appwrite.io/docs/databases) and [Appwrite Permissions](https://appwrite.io/docs/permissions) in our official docs.

Every collection and document in Appwrite Database needs to be stored somewhere, and for that, we have many different adapters such as MySQL or MongoDB. Each provider implements simple methods such as `createDocument()`, `deleteDocument()`, `find()`, etc...

Your task is to implement support for **Neo4j** in the Utopia PHP database library. We have prepared detailed documentation on [how to create a Utopia PHP database adapter](https://github.com/utopia-php/database/blob/main/docs/add-new-adapter.md). Please read these documents and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Neo4j**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP database adapter for **Neo4j**.
- [ ]  Submit a pull request in [utopia-php/database](https://github.com/utopia-php/database).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by polarvoid** [comment]
Hey @christyjacob4 I would love to work on this. I've worked with Neo4j, and have experience with PHP (though it's been a few years since I've used it last)

**Comment by stnguyen90** [comment]
@polarvoid, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by polarvoid** [comment]
Hey, that guide is super helpful. I'm working on it now :)

**Comment by polarvoid** [comment]
Going through some of the Neo4j documentation for PHP, it looks like I may have to use their `ne4j-php-client` [from here](https://github.com/neo4j-php/neo4j-php-client).

I browsed around looking for other possible solutions, but this seems like the most feature-rich and maintainable option.

Would it be alright to add this so I can integrate Neo4j as an `Adapter`?

**Comment by codercatdev** [comment]
@polarvoid The client is a community-maintained project and not official. I would recommend using their HTTP API and resorting to the client only if it fails and doesn't work.

**Comment by polarvoid** [comment]
@codercatdev Okay, I can do that :)

**Comment by polarvoid** [comment]
So progress has been a little slow, but I am still working on this. So far, I've written a class called Neo4jClient that's a small wrapper around cURL requests, and some Adapter functions, which I haven't had time to test yet.

Would it be cool for me to open up a Draft PR up, because I would appreciate further help :)

**Comment by Meldiron** [comment]
@polarvoid Thanks for keeping us updated 😇 This task is not a small one, there is nothing wrong with taking your time.

I would love if you opened a draft PR and mentioned all points where you feel stuck. We would gladly point you to the right direction.

**Comment by stnguyen90** [comment]
@polarvoid are you still working on this or should we unassing you?

**Comment by polarvoid** [comment]
Hey, I'm still working on this :)

I opened up a draft at utopia-php/database/pull/209 and asked for additional help there.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by Sukriti-sood** [comment]
@christyjacob4 I would like to work on this. Can you assign it to me?

**Comment by Haimantika** [comment]
> @christyjacob4 I would like to work on this. Can you assign it to me?

Hi @Sukriti-sood  , I've assigned this issue to you! Thanks your interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Sukriti-sood** [comment]
I have gone through already built adapter and their usage. I will create pr this weekend.

**Comment by Haimantika** [comment]
> I have gone through already built adapter and their usage. I will create pr this weekend.

Hi, any update? If you are not working on it, we will be assigning the issue to the next person

**Comment by Sukriti-sood** [comment]
Hello @Haimantika , Thank you for giving me chance but unfortunately I will not be able to complete it.

**Comment by rizwan-io** [comment]
Hi @Haimantika 
I would like to work on this :)

**Comment by tessamero** [comment]
hi @rizwan-io , I have assigned the issue to you. You may start contributing :) Happy hacking. Please check-in every 3 days so we know you are still working on this, and when you create the PR, link the issue to it. Thank you so much :)

**Comment by rizwan-io** [comment]
Hi @Haimantika, Sorry, I did not get a chance to look into it. I will unassign myself. Sorry again :(

**Comment by krishnaa192** [comment]
Can I work on this issue?

**Comment by shivanshu814** [comment]
Hi @christyjacob4 I'm interested in working on this issue. Can you assign me this pls?

**Comment by boomlion8** [comment]
can i work on this issue

**Comment by nishchay-veer** [comment]
Hi @Haimantika . If no one is working on this issue , I would love to work on it. I have some experience with php and docker compose

**Comment by Haimantika** [comment]
> Can I work on this issue?

Are you still interested to work on it?

**Comment by Haimantika** [comment]
Hi @shivanshu814 @boomlion8 @nishchay-veer we are assigning issues on a first-come, first-serve basis. So you will need to wait for your turn.

**Comment by krishnaa192** [comment]
> > Can I work on this issue?
> 
> Are you still interested to work on it?

Yeah
