### ISSUE TITLE
🗄️ Extend Appwrite Storage with Aruba Cloud Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3985]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`, etc...

Your task is to implement support for **Aruba Cloud** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Aruba Cloud**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Aruba Cloud**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Aruba Cloud**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by gagandeepp** [comment]
@christyjacob4 Interested,please assign

**Comment by tessamero** [comment]
@gagandeepp , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by bannu0snake** [comment]
Hi @christyjacob4 , can you assign this issue to me?

**Comment by Haimantika** [comment]
> Hi @christyjacob4 , can you assign this issue to me?

Hi @bannu0snake have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by bannu0snake** [comment]
hi @Haimantika , I am updating my status here:

- created a local branch of the storage adapter code after reading all the docs and understanding problem statement. 
- created new class for Aruba cloud and wrote boiler plate code for all the methods which are needed to be implemented in the class and implemented logic for few methods which return static data [(GitHub link).](https://github.com/bannu0snake/storage/tree/feat-3985-arubacloud-storage-adapter) 
- exploring the Aruba cloud and its storage APIs and APIs docs url seems broken for it. https://www.arubacloud.com/object-storage/interface-api.aspx. 
- I am also try if I am able to find docs after creating Aruba Cloud account which I will be doing next.

**Comment by bannu0snake** [comment]
hi @Haimantika , in implementation guide it is mentioned that we need to extend the basic Device abstract class to create a new adaptor class.  but I think we can also achieve that by extending s3 adaptor and also I have seen DOS adaptor is implemented extending S3 adaptor. can I follow similar approach ?

**Comment by christyjacob4** [comment]
@bannu0snake Yes, please extend the S3 class and override the functions that need changes.

**Comment by bannu0snake** [comment]
@christyjacob4 can you please suggest or give me any reference to test my code locally? ( I am not mentioning about how to run unit test cases , rather local testing of my code )

**Comment by christyjacob4** [comment]
@bannu0snake the easiest way is actually is to write a single new test case for the scenario you want to test and run that function alone. For example, you can follow the instructions here 
https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md#3-test-your-adapter

and setup a new file for your adapter's tests. 

Within that test file you would create a new function called `testSomething`  and write your code in there. 

Then you can run your test alone with `vendor/bin/phpunit /tests/Storage/Device/YourFile.php`

**Comment by Haimantika** [comment]
Hi @bannu0snake do you have any update?

**Comment by bannu0snake** [comment]
Hi @Haimantika . Sorry for the delay in update . I am facing issue with local setup for running Tests.  I will re install the setup again and Test the code . Other than that development part and test cases are already completed

**Comment by Haimantika** [comment]
> Hi @Haimantika . Sorry for the delay in update . I am facing issue with local setup for running Tests. I will re install the setup again and Test the code . Other than that development part and test cases are already completed

Maybe you can raise a PR and work on the tests with help from the community

**Comment by bannu0snake** [comment]
okay @Haimantika  , I will do that

**Comment by jaysomani** [comment]
Hey @stnguyen90 can i work on this issue ?

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
