### ISSUE TITLE
🗄️ Extend Appwrite Storage with Azure Blob Storage Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3986]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`, etc...

Your task is to implement support for **Azure Blob Storage** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Azure Blob Storage**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Azure Blob Storage**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Azure Blob Storage**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aloks98** [comment]
Hi, If it is still open can I take this issue?

**Comment by Meldiron** [comment]
@aloks98 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by aloks98** [comment]
Hey, I apologize - I feel this issue a hard for me as I do not have significant experience with PHP. Feel free to unassign, I will take up some other issue :)

**Comment by jamesrcramos** [comment]
Hello, I am a CodeDay participant. May my team, @ArtP1 and @softTam, and I participate in this issue?

**Comment by stnguyen90** [comment]
@jamesrcramos, assigned! Thanks for your interest! 🙏

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
