### ISSUE TITLE
🗄️ Extend Appwrite Storage with Vultr Object Storage Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3991]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`, etc...

Your task is to implement support for **Vultr Object Storage** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Vultr Object Storage**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Vultr Object Storage**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Vultr Object Storage**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by devblin** [comment]
Hey @christyjacob4 , I would like to work on this issue. Can you please assign this to me ?

**Comment by Meldiron** [comment]
@devblin , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by oussamabouchikhi** [comment]
Hi 👋🏻 @christyjacob4  I would love to work on this issue! Could you assign it to me please 👼🏻

**Comment by soumya-dash3** [comment]
Hi @christyjacob4 , can I be assigned this issue to work upon please. Thanks.

**Comment by surya0180** [comment]
Hey @christyjacob4 , I would like to work on this issue. Can you please assign this to me ?

**Comment by Haimantika** [comment]
Hi @soumya-dash3 @surya0180 👋 , we are assigning issues on a first-come, first-serve basis if @oussamabouchikhi  decides to drop off, we will assign it to you.

**Comment by soumya-dash3** [comment]
Ok sure, @Haimantika.

**Comment by Haimantika** [comment]
Hi @oussamabouchikhi any update? The issue will go to the next person due to inactivity from your end

**Comment by Haimantika** [comment]
Hi @oussamabouchikhi we are unassigning the issue from you due to inactivity. @soumya-dash3 the issue is yours now

**Comment by surya0180** [comment]
Hi @Haimantika mam, I am still ready to work on this issue. I would like to take up this issue in case if the person before me doesn't respond on time. Just sharing my availability.

**Comment by surya0180** [comment]
Hi @Haimantika! Is this issue active?

**Comment by Haimantika** [comment]
Hi @soumya-dash3 are you working on it? If not, we will be assigning the issue to @surya0180

**Comment by soumya-dash3** [comment]
You can reassign this issue @Haimantika

**Comment by Haimantika** [comment]
> Hi @Haimantika! Is this issue active?

The issue is yours now. Please update us with your progress every 3 days and reach out to us on [Discord](https://appwrite.io/discord) if you have any questions

**Comment by surya0180** [comment]
Ok mam

**Comment by surya0180** [comment]
I am going through the docs and studying a few things. Will post an update by tonight

**Comment by surya0180** [comment]
#### UPDATE @Haimantika 

In the past 3 days, I've reviewed documentation and a few learnings. I was pulled off by some other work yesterday. I will be working on this issue completely this weekend.

**Comment by surya0180** [comment]
#### UPDATE @Haimantika 

In the past 3 days, I have created the class for Vultr Object in the devices part of the storage repository. Currently I am stuck in the test cases part. I will resolve them and submit a PR by tomorrow EOD.
