### ISSUE TITLE
🗄️ Extend Appwrite Storage with IBM Cloud Object Storage Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3992]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`, etc...

Your task is to implement support for **IBM Cloud Object Storage** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **IBM Cloud Object Storage**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **IBM Cloud Object Storage**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **IBM Cloud Object Storage**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by anudeeps0306** [comment]
Can you assign this issue to me?

**Comment by gewenyu99** [comment]
@anudeeps0306 I've assigned this to you. You may work on this issue 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by thebugsyy** [comment]
Hi, I would like to give a try. can you please assign this task to me.
Thanks

**Comment by dishantzaveri** [comment]
Hi, I would like to give a try. can you please assign this task to me.
Thanks

**Comment by Haimantika** [comment]
> Hi, I would like to give a try. can you please assign this task to me. Thanks

Hi, we are assigning issues on first-come first-serve basis, if @thebugsyy is unresponsive/drops off, I will assign it to you.

**Comment by thebugsyy** [comment]
thanks @Haimantika & @gewenyu99 for assigning me the issue. I'll start working on it now and will also update as per the progress :)

**Comment by Haimantika** [comment]
@thebugsyy any update?

**Comment by malay5** [comment]
@Haimantika could you assign this issue to me?

**Comment by Haimantika** [comment]
Hi @thebugsyy thank you for showing interest to contribute to Appwrite, we will have to unassign the issue from you due to inactivity. @dishantzaveri you already have issues assigned to you, do you have the bandwidth to take this one up?

**Comment by Haimantika** [comment]
@malay5 assigning the issue to you, please update us every 3 days.

**Comment by tessamero** [comment]
@malay5 please follow up with the Pending PR :)

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
