### ISSUE TITLE
🗄️ Extend Appwrite Storage with Rackspace Cloud Files Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3993]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`, etc...

Your task is to implement support for **Rackspace Cloud Files** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Rackspace Cloud Files**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Rackspace Cloud Files**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Rackspace Cloud Files**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by BajajAyush** [comment]
Hey, I would like to try this

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by Aryan8912** [comment]
please assign it to me, so I can work on this issue, and give more detail about this issue

**Comment by Haimantika** [comment]
> please assign it to me, so I can work on this issue, and give more detail about this issue

Hi @Aryan8912 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by KanniShashankh** [comment]
Can i be assigned this issue?

**Comment by dishantzaveri** [comment]
pls assign me

**Comment by Haimantika** [comment]
> Can i be assigned this issue?

Hi @KanniShashankh have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
> pls assign me

Hi, we are assigning on first-come first-serve basis. If @KanniShashankh is unresponsive, will assign it to you.

**Comment by dishantzaveri** [comment]
ok

**Comment by KanniShashankh** [comment]
Unassigning myself as Rackspace Cloud doesn't look like it is open for public, i do not have the credentials to test out my soltution. The solution is fairly simple tho, here is some documentation which will help u
https://docs-ospc.rackspace.com/cloud-files/quickstart/

**Comment by dishantzaveri** [comment]
pls assign me @Haimantika

**Comment by kartiksaxena532** [comment]
HI I WOULD LIKE TO WORK ON IT

**Comment by Haimantika** [comment]
> pls assign me @Haimantika

Assigned it to you

**Comment by Haimantika** [comment]
> HI I WOULD LIKE TO WORK ON IT

Hi, we assign issues on a first-come, first-serve basis. If @dishantzaveri is unable to do it, you will be the next person :)

**Comment by Haimantika** [comment]
> pls assign me @Haimantika

Is there an update? The issue will go to the next person due to inactivity from your end

**Comment by Haimantika** [comment]
Hi @dishantzaveri we are unassigning the issue from you due to inactivity. @kartiksaxena532 the issue is yours now, please remember to update us every 3 days

**Comment by Haimantika** [comment]
> 😭

You have other issues assigned, please work on them :)

We want to give everyone a fair chance in participating in Hacktoberfest, since you didn’t respond when I asked for an update last week, I assumed that you are not working on it.

**Comment by Haimantika** [comment]
Hi @kartiksaxena532 are you working on it? I fear we will have to reassign it to the next person due to inactivity from your end.
