### ISSUE TITLE
🗄️ Extend Appwrite Storage with Google Cloud Storage Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3994]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`, etc...

Your task is to implement support for **Google Cloud Storage** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Google Cloud Storage**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Google Cloud Storage**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Google Cloud Storage**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by NightHack36** [comment]
Hi @christyjacob4  I would like to contribute to this issue, could you please assign this to me?

**Comment by tessamero** [comment]
@NightHack36 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by eigengravy** [comment]
hi, i would love to have a go at this issue

**Comment by Meldiron** [comment]
@eigengravy , looks like you have some issues assigned to you already. Please allow us some time to review them before assigning you more issues. In the meantime, you could work on our issues for writing articles and building demo apps - those do not require assignments.

**Comment by gagandeepp** [comment]
interested please assign

**Comment by Meldiron** [comment]
@gagandeepp , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by gagandeepp** [comment]
@Meldiron I already have raised PR to the issues assigned to me

**Comment by codercatdev** [comment]
@eigengravy it looks like you are the next person with all issues having PR's in, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by pomarec** [comment]
My 2 cents : google cloud storage is compatible with S3 API.
Wouldn't it be easier to just allow a custom endpoint url (eg: https://storage.googleapis.com) to the AWS library ?

See relevant code :  https://github.com/utopia-php/storage/blob/main/src/Storage/Device/S3.php#L117
See option in [Google Cloud Console](https://console.cloud.google.com/) : Cloud Storage > Settings > Interoperability

**Comment by eigengravy** [comment]
oh, i will look into that. thanks for the tip.

**Comment by pomarec** [comment]
Hi, if no one is working on it. I'm up for it. I'll implement S3 API of Google Storage.

**Comment by stnguyen90** [comment]
@pomarec, assigned! Thanks for your interest! 🙏🏼

**Comment by pomarec** [comment]
I've spend some time looking into it but can't make it work.
I'm not familiar enough with PHP and Curl.
My understanding is that changing only the url endpoint (see @eigengravy https://github.com/utopia-php/storage/pull/64) does not workout. Google returns an http 400 error.

I leave the assignement as I wont be able to make it work.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by SiddharthJadhav99** [comment]
hey @christyjacob4, can you assign this issue to me? I think I'll be able to do this.

**Comment by Haimantika** [comment]
> hey @christyjacob4, can you assign this issue to me? I think I'll be able to do this.

Hi @SiddharthJadhav99 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by soumyadeeproychowdhury** [comment]
Hi ! could I also work on this issue!

**Comment by prabhakaran-jm** [comment]
I would like to work on this. Can you assign it to me?

**Comment by SiddharthJadhav99** [comment]
hey @Haimantika, just a quick update. I am able to implement read, write, listobjects, move within the adaptor. However, it is taking longer for me to implement the rest of functions cause of limited gcp storage client resources in php. 

And also wanted to know, currently I am using Credential Json file path for authentication since authenticating via client Id or secret is not present. I hope it is fine. Let me know if you have any suggestions it would be really helpful :)

**Comment by christyjacob4** [comment]
@SiddharthJadhav99 you can proceed with the json file approach as it appears to be the recommended way to authenticate to use google services 👍

**Comment by Haimantika** [comment]
@SiddharthJadhav99 do you have an update? We will have to reassign the issue to the next person due to inactivity from your end.

**Comment by tessamero** [comment]
Closing this issue since the PR was closed
