### ISSUE TITLE
🗜️ Refine Appwrite Storage with bzip2 Compression

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3996]
# 💭 Introduction

Appwrite Storage lets you upload and store images, videos, or any kind of file. One of its features is compression which lets you pick an algorithm that makes your files take less storage space. We currently support gzip and ZStandard compressions but aim to support more! ✨

Every compression algorithm is based on the [Utopia PHP storage](https://github.com/utopia-php/storage/blob/main/src/Storage/Compression/Compression.php) compression adapter that implements simple methods such as `compress()` and `decompress()`.

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods `compress()` and `decompress()`.

Your task is to implement support for **bzip2** in Appwrite and the Utopia PHP storage library. To learn how a new adapter should look like, please check out some of our [existing compression adapters](https://github.com/utopia-php/storage/tree/main/src/Storage/Compression/Algorithms). To learn how such an adapter can be added into Appwrite, please look at how [existing compression (for instance `Gzip`) is being added](https://github.com/appwrite/appwrite/pull/3737). Make sure you understand existing examples before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **bzip2** compression.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage compression adapter for **bzip2**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **bzip2**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Luke-Shepp** [comment]
Hi @christyjacob4! It'd be great if I could pick this one up

**Comment by Luke-Shepp** [comment]
Hi @christyjacob4! It'd be great if I could pick this one up

**Comment by Meldiron** [comment]
@Luke-Shepp , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by AkhileshJyotishi** [comment]
@christyjacob4 can you assign this to me!

**Comment by tessamero** [comment]
hi @AkhileshJyotishi , you've been assigned to the issue. You may now start working on it. :) Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by Haimantika** [comment]
> @tessamero can you what to do next

Hi, our team will review your PR soon and get back to you.

**Comment by krishnaa192** [comment]
Can I Work on this issue?

**Comment by AkhileshJyotishi** [comment]
@Haimantika  can you give hacktoberfest accepted label , as the pr is still not reviewed. Thanks!

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
