### ISSUE TITLE
🗜️ Refine Appwrite Storage with lzip Compression

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3997]
# 💭 Introduction

Appwrite Storage lets you upload and store images, videos, or any kind of file. One of its features is compression which lets you pick an algorithm that makes your files take less storage space. We currently support gzip and ZStandard compressions but aim to support more! ✨

Every compression algorithm is based on the [Utopia PHP storage](https://github.com/utopia-php/storage/blob/main/src/Storage/Compression/Compression.php) compression adapter that implements simple methods such as `compress()` and `decompress()`.

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods `compress()` and `decompress()`.

Your task is to implement support for **lzip** in Appwrite and the Utopia PHP storage library. To learn how a new adapter should look like, please check out some of our [existing compression adapters](https://github.com/utopia-php/storage/tree/main/src/Storage/Compression/Algorithms). To learn how such an adapter can be added into Appwrite, please look at how [existing compression (for instance `Gzip`) is being added](https://github.com/appwrite/appwrite/pull/3737). Make sure you understand existing examples before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **lzip** compression.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage compression adapter for **lzip**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **lzip**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aloks98** [comment]
Hello, can I take up this feature implementation?

**Comment by Unickorn** [comment]
Hey! I haven't yet used Appwrite personally, though I am quite experienced in PHP, Docker and Docker Compose. Could I give this issue a shot?

**Comment by stnguyen90** [comment]
@Unickorn Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by Unickorn** [comment]
Hmm there seems to be no lzip extension for PHP and I doubt I have the skillset to write one out of scratch, I'll go ahead and try implementing the xz one since I could find an extension for it already made.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by Yashsomalkar** [comment]
Hey I would like to work on this.

**Comment by dishantzaveri** [comment]
Pls assign to me @eldadfux @christyjacob4

**Comment by Haimantika** [comment]
> Pls assign to me @eldadfux @christyjacob4

Hi @dishantzaveri have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by malay5** [comment]
Please assign this issue to me, in case it becomes open again

**Comment by dishantzaveri** [comment]
I am working on it , its pretty challenging

**Comment by malay5** [comment]
Can we work on it together?

**Comment by Haimantika** [comment]
> I am working on it , its pretty challenging

If you need any help, please ask your queries in Discord :)

**Comment by Haimantika** [comment]
Hi @dishantzaveri are you still working on it?

**Comment by Rutam21** [comment]
@Haimantika I would like to pick this up if there's no update from the contributor's end. Thanks.

**Comment by tessamero** [comment]
Closing the issue due to inactivity and hacktoberfest being over :)
