### ISSUE TITLE
🗜️ Refine Appwrite Storage with lzma Compression

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#3999]
# 💭 Introduction

Appwrite Storage lets you upload and store images, videos, or any kind of file. One of its features is compression which lets you pick an algorithm that makes your files take less storage space. We currently support gzip and ZStandard compressions but aim to support more! ✨

Every compression algorithm is based on the [Utopia PHP storage](https://github.com/utopia-php/storage/blob/main/src/Storage/Compression/Compression.php) compression adapter that implements simple methods such as `compress()` and `decompress()`.

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods `compress()` and `decompress()`.

Your task is to implement support for **lzma** in Appwrite and the Utopia PHP storage library. To learn how a new adapter should look like, please check out some of our [existing compression adapters](https://github.com/utopia-php/storage/tree/main/src/Storage/Compression/Algorithms). To learn how such an adapter can be added into Appwrite, please look at how [existing compression (for instance `Gzip`) is being added](https://github.com/appwrite/appwrite/pull/3737). Make sure you understand existing examples before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **lzma** compression.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage compression adapter for **lzma**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **lzma**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by NightHack36** [comment]
Hi @christyjacob4  I would like to contribute to this issue, could you please assign this to me?

**Comment by tessamero** [comment]
@NightHack36 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by toukirkhan** [comment]
@christyjacob4 I want to work on this

**Comment by toukirkhan** [comment]
I do not find any extensions for lzma compression hence am unassigning myself and would work on another issue.

**Comment by stnguyen90** [comment]
@toukirkhan, yes, it seems whoever picks this up will need to write an extension for lzma compression.

**Comment by benceHornyak** [comment]
Hi there :wave: 

I'd like to work on this issue

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by toth2000** [comment]
@christyjacob4  Can I look into this?

**Comment by Haimantika** [comment]
> @christyjacob4 Can I look into this?

Hi @toth2000  have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by toth2000** [comment]
@Haimantika Thanks. Sure, I'll update the progress soon.

**Comment by toth2000** [comment]
@Haimantika I was not able to find any lzma extensions. Hence,  unassigning myself.

**Comment by Shanta-11** [comment]
Hello, i'd like to take up this challenge. Seems like no one has been able to do it, Time to give it a shot

**Comment by sidgaikwad** [comment]
assign me this, i would like to work on this

**Comment by Tushar98644** [comment]
I would like to work on this issue

**Comment by ShrutiSingh04503** [comment]
Hey @christyjacob4 , I would like work on this issue plz assign me this

**Comment by Haimantika** [comment]
> assign me this, i would like to work on this

Hi, have assigned the issue to you. Please remember to update us every 3 days so that we know that you are working on it :)

**Comment by Haimantika** [comment]
Hi @Tushar98644 @ShrutiSingh04503 we are assigning issues on a first-come, first-serve basis, we can assign the issue to you if the assigned user decides to drop

**Comment by Rutam21** [comment]
@Haimantika I would like to pick this up if there's no update from the contributor's end. Thanks.

**Comment by Tushar98644** [comment]
@Haimantika pls reassign as there is been no update from the current assignee and it has been a lot more than 3 days

**Comment by Haimantika** [comment]
Hi @sidgaikwad any updates? We have assigned 2 issues to you, and there isn't any update from your end. Will be reassigning the issue to the next person due to inactivity

**Comment by sidgaikwad** [comment]
@Haimantika you can assign it to next person, i am currently working with the cassendra adapter

**Comment by Rutam21** [comment]
@Haimantika I would love to take this up. Thanks.

**Comment by Haimantika** [comment]
> I would like to work on this issue

You are next, would you like to work on it?

**Comment by Haimantika** [comment]
> @Haimantika I would love to take this up. Thanks.

We are assigning on a first-come, first-serve basis. You are third in the queue, if the other two users decides to not take this issue, it will go to you.

**Comment by mschandana16** [comment]
> @Tushar98644 I have already commented on two issues for you. So I will ask the next person, @ShrutiSingh04503 are you interested to work on this?

I would like to work on this issue. In case, the other contributors don't reply, please assign this issue to me, @Haimantika

**Comment by shivanshu814** [comment]
Hi @christyjacob4 I'm interested in working on this issue. Can you assign me this pls?

**Comment by nishchay-veer** [comment]
Hi @Haimantika I have some good experience working on php and docker compose and would love to work on this issue if no is assigned .

**Comment by Haimantika** [comment]
> @Haimantika I would like to pick this up if there's no update from the contributor's end. Thanks.

Hi, you are next, would you like to take this one up?

**Comment by Rutam21** [comment]
@Haimantika Yes, I will take this. Thanks.

**Comment by Haimantika** [comment]
@mschandana16 @shivanshu814 @NightHack36 we are assigning issues on a first-come, first-serve basis. So you will need to wait a little for your turn.

**Comment by Haimantika** [comment]
> @Haimantika Yes, I will take this. Thanks.

Assigned. Please remember to update us with your progress before 31st, and reach out to is on Discord for any queries

**Comment by Rutam21** [comment]
I am working on it and it should be done by EOD.

**Comment by tessamero** [comment]
closing issue as there is no PR

@Rutam21  if you happen to still be working on it, you can reopen a new issue with the same title, reference this, and let us know :)
