### ISSUE TITLE
🗜️ Refine Appwrite Storage with lzop Compression

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4000]
# 💭 Introduction

Appwrite Storage lets you upload and store images, videos, or any kind of file. One of its features is compression which lets you pick an algorithm that makes your files take less storage space. We currently support gzip and ZStandard compressions but aim to support more! ✨

Every compression algorithm is based on the [Utopia PHP storage](https://github.com/utopia-php/storage/blob/main/src/Storage/Compression/Compression.php) compression adapter that implements simple methods such as `compress()` and `decompress()`.

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods `compress()` and `decompress()`.

Your task is to implement support for **lzop** in Appwrite and the Utopia PHP storage library. To learn how a new adapter should look like, please check out some of our [existing compression adapters](https://github.com/utopia-php/storage/tree/main/src/Storage/Compression/Algorithms). To learn how such an adapter can be added into Appwrite, please look at how [existing compression (for instance `Gzip`) is being added](https://github.com/appwrite/appwrite/pull/3737). Make sure you understand existing examples before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **lzop** compression.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage compression adapter for **lzop**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **lzop**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by dsuarezlogans** [comment]
Hello, can I help on this?

**Comment by stnguyen90** [comment]
@dsuarezlogans Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by Chandram-Dutta** [comment]
I would like to try this... :-)

**Comment by Susmita-Dey** [comment]
Hey @christyjacob4 I'm currently learning PHP and Docker. I'd like to take up this issue and give it a try.

**Comment by Haimantika** [comment]
> Hey @christyjacob4 I'm currently learning PHP and Docker. I'd like to take up this issue and give it a try.

Hi @Susmita-Dey have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Susmita-Dey** [comment]
Hey @Haimantika will surely update! I'm already there on discord as a moderator.

**Comment by Susmita-Dey** [comment]
Update: Started working on it.

**Comment by Haimantika** [comment]
Hi @Susmita-Dey do you have an update?

**Comment by Susmita-Dey** [comment]
Hey @Haimantika Kindly assign it to someone else

**Comment by cereal-hecker** [comment]
hey, i would like to work on this issue. could you assign this to me?

**Comment by tessamero** [comment]
hi @cereal-hecker , I have assigned the issue to you. Thank you for being part of our hacktoberfest event this year. happy hacking :)

**Comment by cereal-hecker** [comment]
thanks for assigning @tessamero

**Comment by Rutam21** [comment]
@Haimantika I would like to pick this up if there's no update from the contributor's end. Thanks.

**Comment by drraghavendra** [comment]
> hey @Haimantika @tessamero @christyjacob4 iam interested to contribute please assign me

Looking forward for your reply @tessamero @christyjacob4 @Haimantika

**Comment by Haimantika** [comment]
Hi @cereal-hecker are you still working on it? Any updates about your progress/queries will help us know that you are working on it.  😄

**Comment by cereal-hecker** [comment]
> Hi @cereal-hecker are you still working on it? Any updates about your progress/queries will help us know that you are working on it. 😄

hey, im still working on it, wrote the php code for izop but still figuring stuff out. i will create a pr in utopia-php/storage soon!

**Comment by Haimantika** [comment]
> > Hi @cereal-hecker are you still working on it? Any updates about your progress/queries will help us know that you are working on it. 😄
> 
> hey, im still working on it, wrote the php code for izop but still figuring stuff out. i will create a pr in utopia-php/storage soon!

Cool! If you have any questions, please ask us on Discord :)

**Comment by tessamero** [comment]
Closing the issue as there is no activity in a month
