### ISSUE TITLE
🗜️ Refine Appwrite Storage with rzip Compression

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4001]
# 💭 Introduction

Appwrite Storage lets you upload and store images, videos, or any kind of file. One of its features is compression which lets you pick an algorithm that makes your files take less storage space. We currently support gzip and ZStandard compressions but aim to support more! ✨

Every compression algorithm is based on the [Utopia PHP storage](https://github.com/utopia-php/storage/blob/main/src/Storage/Compression/Compression.php) compression adapter that implements simple methods such as `compress()` and `decompress()`.

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods `compress()` and `decompress()`.

Your task is to implement support for **rzip** in Appwrite and the Utopia PHP storage library. To learn how a new adapter should look like, please check out some of our [existing compression adapters](https://github.com/utopia-php/storage/tree/main/src/Storage/Compression/Algorithms). To learn how such an adapter can be added into Appwrite, please look at how [existing compression (for instance `Gzip`) is being added](https://github.com/appwrite/appwrite/pull/3737). Make sure you understand existing examples before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **rzip** compression.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage compression adapter for **rzip**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **rzip**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by NightHack36** [comment]
Hi @christyjacob4  I would like to contribute to this issue, could you please assign this to me?

**Comment by tessamero** [comment]
@NightHack36 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by h1t35h** [comment]
Hi, I would like to contribute to this. Could you please assign this to me?

**Comment by Meldiron** [comment]
@h1t35h , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by vasu-1** [comment]
Hey @christyjacob4 
I want to work on this issue!!
Can you please assign this to me?

**Comment by srujan0404** [comment]
hey @christyjacob4 I would like to work on this issue.
please assign this issue to me

**Comment by heysagnik** [comment]
hey Appwrite team , I would like to work on this issue.
Please assign me .

**Comment by Haimantika** [comment]
> Hey @christyjacob4
> I want to work on this issue!!
> Can you please assign this to me?

Hi @vasu-1 , I've assigned this issue to you! Thanks your interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
Hi @srujan0404 @heysagnik 👋, we are assigning issues on firet-come first-serve basis. If @vasu-1 is unresponsive or decides to drop off, you are next in line 😊

**Comment by Haimantika** [comment]
Hi @vasu-1 is there an update?

**Comment by vasu-1** [comment]
> Hi @vasu-1 is there an update?

Hii! Working on it 👍🏻

**Comment by Haimantika** [comment]
> > Hi @vasu-1 is there an update?
> 
> Hii! Working on it 👍🏻

Let us know on Discord if you have any queries

**Comment by Rutam21** [comment]
@Haimantika I would like to pick this up if there's no update from the contributor's end. Thanks.

**Comment by Haimantika** [comment]
Hi @vasu-1 are you still working on this issue? We will have to reassign the issue to the next person due to inactivity from your end.

**Comment by vasu-1** [comment]
> Hi @vasu-1 are you still working on this issue? We will have to reassign the issue to the next person due to inactivity from your end.

Hey, I'm working on it, finalized the code, I've raised the query in appwrite discord server, can you please check that out ?

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over and there's no pending PR. Thank you to everyone who participated this year :)
