### ISSUE TITLE
🗜️ Refine Appwrite Storage with xz Compression

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4003]
# 💭 Introduction

Appwrite Storage lets you upload and store images, videos, or any kind of file. One of its features is compression which lets you pick an algorithm that makes your files take less storage space. We currently support gzip and ZStandard compressions but aim to support more! ✨

Every compression algorithm is based on the [Utopia PHP storage](https://github.com/utopia-php/storage/blob/main/src/Storage/Compression/Compression.php) compression adapter that implements simple methods such as `compress()` and `decompress()`.

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods `compress()` and `decompress()`.

Your task is to implement support for **xz** in Appwrite and the Utopia PHP storage library. To learn how a new adapter should look like, please check out some of our [existing compression adapters](https://github.com/utopia-php/storage/tree/main/src/Storage/Compression/Algorithms). To learn how such an adapter can be added into Appwrite, please look at how [existing compression (for instance `Gzip`) is being added](https://github.com/appwrite/appwrite/pull/3737). Make sure you understand existing examples before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **xz** compression.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage compression adapter for **xz**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **xz**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by shtelzerartem** [comment]
@christyjacob4 I would like to contribute here :)

**Comment by Meldiron** [comment]
@shtelzerartem , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by shtelzerartem** [comment]
@Meldiron actually I'm waiting for them to be reviewed, but yes, you're right I will look into another type of issues. Thanks!

**Comment by aloks98** [comment]
Hi, I was working on LZ4 and it was accepted today. Can I please take this issue now? :)

**Comment by Unickorn** [comment]
Could I give this a shot?

**Comment by Meldiron** [comment]
@Unickorn , thanks for your interest! 🙏 Happy hacking! 🎃
