### ISSUE TITLE
🗞 Help Developers by Writing Article About Netlify

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4004]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

We understand code contributions might not be your cup of tea, so we decided to prepare a series of blog posts related issues. This series of issues is here to let your writing skills shine, with close to 0 engineering skills required! ✨

Your task is to write a blog post about **Appwrite + Netlify**. The main topic of your article should be explaining how to use Appwrite in connection with Netlify. It can be posted anywhere! We accept submissions of articles on any well-known platform, for example, [Medium](https://medium.com/), [Dev.to](https://dev.to/), or [Hashnode](https://hashnode.com/).

### 🎯 Requirements

- Your article has to be publicly available.
- Your article must tag `appwrite` in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Write a blog post about **Appwrite + Netlify**.
- [ ]  Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Share the article on social media. (Reddit / HackerNews / Twitter / Facebook / Other)

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by harshchandwani** [comment]
I can work on this, please assign it to me.

**Comment by christyjacob4** [comment]
Hey 👋  all issue assignments for Hacktoberfest will take place on a first come first serve basis starting on October 1st

**Comment by Asmit2952** [comment]
Hey, can I work on this?

**Comment by chinmayayy** [comment]
Hey @christyjacob4 I would like to work upon this. Kindly assign it to me.

**Comment by MrKrishnaAgarwal** [comment]
@stnguyen90 I will work on this

**Comment by Shreyas-SAS** [comment]
@stnguyen90 if its not mandatory to have only 1 person writing the article then I would like to work on the issue too. would it be ok if I do?

**Comment by SaiRev0** [comment]
I m new to the contribution, I think it will be good first work for me, so can you please assign me this? It, would be great

**Comment by aharna** [comment]
I would like to work on this issue

**Comment by devstardude** [comment]
Hello @christyjacob4, I have good experience with Netlify, Can I work on this? Thanks.

**Comment by Goheljay** [comment]
hi @christyjacob4 , I want to work on this issue can you assign me?

**Comment by PineappleIOnic** [comment]
@harshchandwani @Asmit2952 @chinmayayy @MrKrishnaAgarwal @Shreyas-SAS @SaiRev0 @aharna @devstardude @Goheljay This task is now open for everyone; you can all work on this individually and release your own versions! 😄

**Comment by Asmit2952** [comment]
Hey @PineappleIOnic can we take an already published Appwrite example for our blog posts? From awesome-appwrite repository?

**Comment by PineappleIOnic** [comment]
@Asmit2952 If you created it yourself, then yes. otherwise, we would prefer it if you created it all yourself.

**Comment by Meldiron** [comment]
@Asmit2952 We would prefer the owner of the app to write an article for it.

**Comment by Praj2002933** [comment]
I would like to work upon this, please assign it to me @christyjacob4

**Comment by MrKrishnaAgarwal** [comment]
> I would like to work upon this, please assign it to me @christyjacob4

This task does not require any assignment but please comment on this issue mentioning you are working on it.

**Comment by Shruti700** [comment]
I would like to work on this.
