### ISSUE TITLE
🗞 Help Developers by Writing Article About Vercel

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4005]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

We understand code contributions might not be your cup of tea, so we decided to prepare a series of blog posts related issues. This series of issues is here to let your writing skills shine, with close to 0 engineering skills required! ✨

Your task is to write a blog post about **Appwrite + Vercel**. The main topic of your article should be explaining how to use Appwrite in connection with Vercel. It can be posted anywhere! We accept submissions of articles on any well-known platform, for example, [Medium](https://medium.com/), [Dev.to](https://dev.to/), or [Hashnode](https://hashnode.com/).

### 🎯 Requirements

- Your article has to be publicly available.
- Your article must tag `appwrite` in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Write a blog post about **Appwrite + Vercel**.
- [ ]  Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Share the article on social media. (Reddit / HackerNews / Twitter / Facebook / Other)

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by stnguyen90** [comment]
@krupalitrivedi, thanks for reaching out! 🙏 To give everyone a fair chance, we will assign the first commenter after Hacktoberfest officially starts.

**Comment by Keshraf** [comment]
Hey, I would like to write an article on this topic. I think it would go perfectly with this issue #4035. I would like to make Almost Trello using Appwrite and then deploy it on Vercel. Please assign this issue to me 😄

**Comment by MrKrishnaAgarwal** [comment]
@stnguyen90 I will work on this

**Comment by Shreyas-SAS** [comment]
@stnguyen90 if its not mandatory to have only 1 person writing the article then I would like to work on the issue too. would it be ok if I do?

**Comment by SaiRev0** [comment]
I m new to the contribution, I think it will be good first work for me, so can you please assign me this? It would be great

**Comment by aharna** [comment]
hey! I would like to work on this isssue

**Comment by Sneha421** [comment]
Hey @christyjacob4
I would love to work on this article. I have prior experience in writing technical articles!
Here is a link - https://medium.com/face-amrita-bangalore/whats-the-difference-between-ar-vr-and-mr-126aa1f06811

**Comment by PineappleIOnic** [comment]
@krupalitrivedi @Keshraf @MrKrishnaAgarwal @Shreyas-SAS @SaiRev0 @aharna @Sneha421 This task is now open for everyone; you can all work on this individually and release your own versions! 😄

**Comment by aadii0408** [comment]
Hi @christyjacob4 ,
I would like to work on this article. I have prior experience in writing articles, so can you please assign me this?

**Comment by Meldiron** [comment]
@aadii0408 This task does not require any assignment. Feel free to go ahead and work on this issue 😇

**Comment by dagilleland** [comment]
@stnguyen90 - Can you comment on any articles that were actually written?
