### ISSUE TITLE
🗞 Help Developers by Writing Article About Google Cloud

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4007]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

We understand code contributions might not be your cup of tea, so we decided to prepare a series of blog posts related issues. This series of issues is here to let your writing skills shine, with close to 0 engineering skills required! ✨

Your task is to write a blog post about **Appwrite + Google Cloud**. The main topic of your article should be explaining how to use Appwrite in connection with Google Cloud. It can be posted anywhere! We accept submissions of articles on any well-known platform, for example, [Medium](https://medium.com/), [Dev.to](https://dev.to/), or [Hashnode](https://hashnode.com/).

### 🎯 Requirements

- Your article has to be publicly available.
- Your article must tag `appwrite` in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Write a blog post about **Appwrite + Google Cloud**.
- [ ]  Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Share the article on social media. (Reddit / HackerNews / Twitter / Facebook / Other)

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by vj-codes** [comment]
Hey I would like to work on this please!

**Comment by stnguyen90** [comment]
@vj-codes, thanks for reaching out! 🙏 To make things fair, we will be selecting the first commenter **after** Hacktoberfest officially starts to assign this issue. Feel free to comment again **after** Hacktoberfest starts.

**Comment by vj-codes** [comment]
@stnguyen90 heyyo now is it okay to comment? I would like to work on this!

**Comment by BAGEERADHAN** [comment]
I would like to contribute to this. Can I get assigned for this repo?

**Comment by MrKrishnaAgarwal** [comment]
@stnguyen90 I will work on this, I have worked on Google Cloud a lot.

cc @christyjacob4

**Comment by aryanlath** [comment]
Hi! I would love to work on this and contribute. Can you assign this to me ?

**Comment by stnguyen90** [comment]
@vj-codes, thanks for your interest! 🙏 Happy hacking!

@BAGEERADHAN, @MrKrishnaAgarwal, @aryanlathwe're assigning issues on a first come first serve basis. If @vj-codes isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by PineappleIOnic** [comment]
@vj-codes @BAGEERADHAN @MrKrishnaAgarwal @aryanlath This task is now open for everyone; you can all work on this individually and release your own versions! 😄

**Comment by PineappleIOnic** [comment]
@vj-codes You have been unassigned as this issue is now an open one, you can continue working on it though. Nothing changes for you.

**Comment by MrKrishnaAgarwal** [comment]
I am working on it!

**Comment by neelshah2409** [comment]
I also wanted to work on this and already published blog regarding it .
