### ISSUE TITLE
🗞 Help Developers by Writing Article About Amazon Web Services

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4008]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

We understand code contributions might not be your cup of tea, so we decided to prepare a series of blog posts related issues. This series of issues is here to let your writing skills shine, with close to 0 engineering skills required! ✨

Your task is to write a blog post about **Appwrite + Amazon Web Services**. The main topic of your article should be explaining how to use Appwrite in connection with Amazon Web Services. It can be posted anywhere! We accept submissions of articles on any well-known platform, for example, [Medium](https://medium.com/), [Dev.to](https://dev.to/), or [Hashnode](https://hashnode.com/).

### 🎯 Requirements

- Your article has to be publicly available.
- Your article must tag `appwrite` in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Write a blog post about **Appwrite + Amazon Web Services**.
- [ ]  Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Share the article on social media. (Reddit / HackerNews / Twitter / Facebook / Other)

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by thefool76** [comment]
hey there! Would like to work on it. please assign me

**Comment by christyjacob4** [comment]
Hey 👋  all issue assignments for Hacktoberfest will take place on a first come first serve basis starting on October 1st

**Comment by thefool76** [comment]
> Hey wave all issue assignments for Hacktoberfest will take place on a first come first serve basis starting on October 1st

Ok thanks

**Comment by BAGEERADHAN** [comment]
I would also like to contribute to this. Can I also get assigned to this repo?

**Comment by deep-poharkar** [comment]
I would love to contribute, please assign.

**Comment by MrKrishnaAgarwal** [comment]
@stnguyen90 I will work on this

**Comment by aryanlath** [comment]
Hi! I would love to work on this and contribute. Can you assign this to me ?

**Comment by stnguyen90** [comment]
@thefool76, thanks for your interest! 🙏 Happy hacking!

@BAGEERADHAN, @deep-poharkar, @MrKrishnaAgarwal, @aryanlath, we're assigning issues on a first come first serve basis. If @thefool76 isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/). 🎃

**Comment by thefool76** [comment]
@stnguyen90 thanks for assigning it. Can I know till which duration I should submit the PR?

**Comment by Sneha421** [comment]
Hey @thefool76!
May I help you with this article? I have some experience in AWS as well as technical writing. Although I am a novice at Appwrite, I think this would definitely help me learn as well.
Maybe we can make the blog a 2 parter if that is allowed @christyjacob4 

Here is a sample of my writing - https://medium.com/face-amrita-bangalore/whats-the-difference-between-ar-vr-and-mr-126aa1f06811

**Comment by PineappleIOnic** [comment]
@thefool76 @aryanlath @deep-poharkar @BAGEERADHAN @MrKrishnaAgarwal @Sneha421 This task is now open for everyone; you can all work on this individually and release your own versions! 😄

**Comment by thefool76** [comment]
@PineappleIOnic ok that means everyone can PR on this issue? there is no longer a criteria ?

**Comment by Meldiron** [comment]
@thefool76 All PRs should follow the `Requirements` mentioned in the issue. With that said, yes, anyone can work on this issue, and multiple people can work on it separately. In the end, we all have different writing styles, and there is no harm in having multiple articles on the same topic.  Don't worry, you can continue working on this.

**Comment by thefool76** [comment]
> @thefool76 All PRs should follow the `Requirements` mentioned in the issue. With that said, yes, anyone can work on this issue, and multiple people can work on it separately. In the end, we all have different writing styles, and there is no harm in having multiple articles on the same topic. Don't worry, you can continue working on this.

Thanks for clarifying it.

**Comment by coder-harsh** [comment]
hi, I want to work on this, please assign me.

**Comment by stnguyen90** [comment]
@coder-harsh, go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.
