### ISSUE TITLE
🗞 Help Developers by Writing Article About Linode

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4011]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

We understand code contributions might not be your cup of tea, so we decided to prepare a series of blog posts related issues. This series of issues is here to let your writing skills shine, with close to 0 engineering skills required! ✨

Your task is to write a blog post about **Appwrite + Linode**. The main topic of your article should be explaining how to use Appwrite in connection with Linode. It can be posted anywhere! We accept submissions of articles on any well-known platform, for example, [Medium](https://medium.com/), [Dev.to](https://dev.to/), or [Hashnode](https://hashnode.com/).

### 🎯 Requirements

- Your article has to be publicly available.
- Your article must tag `appwrite` in any way (hashtag, embedded, link...).
- Your article should be at least 1000 words long.
- Your article should look nice. 👀 Use titles, subtitles, screenshots, images, gifs, or even memes.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Write a blog post about **Appwrite + Linode**.
- [ ]  Publish an article on your favorite platform or website. (Medium, Dev.to, Hashnode...)
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Share the article on social media. (Reddit / HackerNews / Twitter / Facebook / Other)

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Arjun2905** [comment]
Hey I would like to work upon this.
Please assign this to me @christyjacob4

**Comment by ppap1771** [comment]
Hey @christyjacob4 , I would love to work on this.

**Comment by Sneha421** [comment]
Hey @christyjacob4 
I would love to work on this article. I have prior experience in writing technical articles!
Here is a link - https://medium.com/face-amrita-bangalore/whats-the-difference-between-ar-vr-and-mr-126aa1f06811

**Comment by sarkartanmay393** [comment]
> 
@PineappleIOnic Will that be accepted as `hacktoberfest` PR ?

**Comment by Meldiron** [comment]
@sarkartanmay393 That is correct 😇 As long as the quality is there (not a few lines article made from copy&pasting sentences from docs), PR will be accepted in awesome-appwrite repo. That will be a valid contribution to both Appwrite Hacktoberfest, as well as official Hacktoberfest.

**Comment by aashishpanthi** [comment]
I am working on this issue

**Comment by Meldiron** [comment]
@aashishpanthi Thanks for letting us know 😇 Happy hacking! 🎃
