### ISSUE TITLE
🤖 Improve Appwrite Functions with Bash Support

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4013]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), a project built to enable serverless cloud computing. Open Runtimes support many different programming languages, but we all know there are never enough programming languages! 🔥

Your task is to implement support for **Bash** in Open Runtimes. We have prepared detailed documentation on [how to create a new function's runtime](https://github.com/open-runtimes/open-runtimes/blob/main/docs/add-runtime.md). Please read this document and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with **Bash**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement support for **Bash**.
- [ ]  Implement tests for **Bash**.
- [ ]  Submit a pull request in [open-runtimes/open-runtimes](https://github.com/open-runtimes/open-runtimes).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by RahulSurwade08** [comment]
Hey @christyjacob4 , I would love to contribute to this issue under Hacktoberfest. How can I get started as I am new to Open Source Contributions?

**Comment by subhani-syed** [comment]
Hey @christyjacob4 , I would love to contribute to this issue. Can you assign this to me?

**Comment by stnguyen90** [comment]
@RahulSurwade08, thanks for your interest! 🙏 Happy hacking!

@subhani-syed, we're assigning people on a first come first serve basis. If @RahulSurwade08 isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/). 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
