### ISSUE TITLE
🤖 Improve Appwrite Functions with Perl Support

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4014]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), a project built to enable serverless cloud computing. Open Runtimes support many different programming languages, but we all know there are never enough programming languages! 🔥

Your task is to implement support for **Perl** in Open Runtimes. We have prepared detailed documentation on [how to create a new function's runtime](https://github.com/open-runtimes/open-runtimes/blob/main/docs/add-runtime.md). Please read this document and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with **Perl**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement support for **Perl**.
- [ ]  Implement tests for **Perl**.
- [ ]  Submit a pull request in [open-runtimes/open-runtimes](https://github.com/open-runtimes/open-runtimes).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by sudiptog81** [comment]
Trying to take a dig at this!

**Comment by stnguyen90** [comment]
@sudiptog81, shall I assign this to you or would you like to leave this for someone else?

**Comment by sudiptog81** [comment]
Yeah, please assign this to me :)

**Comment by stnguyen90** [comment]
@sudiptog81, assigned! Good luck!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
