### ISSUE TITLE
🤖 Improve Appwrite Functions with Elixir Support

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4016]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), a project built to enable serverless cloud computing. Open Runtimes support many different programming languages, but we all know there are never enough programming languages! 🔥

Your task is to implement support for **Elixir** in Open Runtimes. We have prepared detailed documentation on [how to create a new function's runtime](https://github.com/open-runtimes/open-runtimes/blob/main/docs/add-runtime.md). Please read this document and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with **Elixir**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement support for **Elixir**.
- [ ]  Implement tests for **Elixir**.
- [ ]  Submit a pull request in [open-runtimes/open-runtimes](https://github.com/open-runtimes/open-runtimes).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by tibi77** [comment]
@christyjacob4 I have never written Elixir, but I was thinking of picking it up as a challenge.
Used to work in a company that had the backend in Elixir and I read a bit of that code. I am feeling that this might be a fun challenge for me to learn the language or at least to get a taste of it. So if you could assign it to me I'd be grateful.

**Comment by stnguyen90** [comment]
@tibi77, thanks for your interest! 🙏 Happy hacking!

**Comment by ChandanChainani** [comment]
@tibi77 are you still working on the issue if not can I work on the issue?

**Comment by Meldiron** [comment]
@tibi77 Hey there 👋 Can you please confirm with me if you are working on this issue?

**Comment by Azanul** [comment]
@Meldiron Please assign it to me if neither @tibi77 or @ChandanChainani are on it anymore.

**Comment by stnguyen90** [comment]
Assigning to @ChandanChainani as next in the queue. Please confirm you're still interested in working on this within 24 hours or I'll reassign to @Azanul

**Comment by ChandanChainani** [comment]
@stnguyen90, I am interested, thanks

**Comment by stnguyen90** [comment]
@ChandanChainani are you still working on this or should we unassign you?

**Comment by ChandanChainani** [comment]
@stnguyen90 I am almost done their is stdout capturing that I am not able to figure out will raise PR as soon I resolve the issue or will raise the PR with the changes I have done

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
