### ISSUE TITLE
🤖 Improve Appwrite Functions with C Support

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4017]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), a project built to enable serverless cloud computing. Open Runtimes support many different programming languages, but we all know there are never enough programming languages! 🔥

Your task is to implement support for **C** in Open Runtimes. We have prepared detailed documentation on [how to create a new function's runtime](https://github.com/open-runtimes/open-runtimes/blob/main/docs/add-runtime.md). Please read this document and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with **C**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement support for **C**.
- [ ]  Implement tests for **C**.
- [ ]  Submit a pull request in [open-runtimes/open-runtimes](https://github.com/open-runtimes/open-runtimes).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by gitatractivo** [comment]
Hi @christyjacob4  I am handy with c, docker, docker compose and would love to work contribute to this project

**Comment by stnguyen90** [comment]
@Panda-Abhisek , thanks for your interest! 🙏 Happy hacking! 🎃

@gitatractivo , we're assigning people on a first come first serve basis. If @Panda-Abhisek isn't able to complete this issue, well reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Panda-Abhisek** [comment]
@stnguyen90 Thanks for assigning. I'm on it.
