### ISSUE TITLE
🤖 Improve Appwrite Functions with Go Support

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4018]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), a project built to enable serverless cloud computing. Open Runtimes support many different programming languages, but we all know there are never enough programming languages! 🔥

Your task is to implement support for **Go** in Open Runtimes. We have prepared detailed documentation on [how to create a new function's runtime](https://github.com/open-runtimes/open-runtimes/blob/main/docs/add-runtime.md). Please read this document and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with **Go**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement support for **Go**.
- [ ]  Implement tests for **Go**.
- [ ]  Submit a pull request in [open-runtimes/open-runtimes](https://github.com/open-runtimes/open-runtimes).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Pradyuman7** [comment]
Hey @christyjacob4 I'd like to work on this issue, could you please assign this to me?

**Comment by stnguyen90** [comment]
@Pradyuman7, thanks for your interest! 🙏 To be fair, we will be selecting the 1st commenter after Hacktoberfest officially starts. Feel free to comment again on October 1st.

**Comment by Panda-Abhisek** [comment]
@christyjacob4 I would like to contribute to this issue.
Can you assign this issue to me?

**Comment by RahulSurwade08** [comment]
Hey @christyjacob4 , I would love to contribute to this issue as well. How can I get started?

**Comment by Pradyuman7** [comment]
> Hey @christyjacob4 I'd like to work on this issue, could you please assign this to me?

Replying to my comment earlier, can I please get this issue assigned to me?

**Comment by stnguyen90** [comment]
@Pradyuman7, actually, you did comment after hacktoberfest started so I'll assign it to you. 

@Panda-Abhisek, @RahulSurwade08, we're assigning issues on a first come first serve basis. If @Pradyuman7 isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by PMohanJ** [comment]
Hi @stnguyen90! It's been two weeks since @Pradyuman7 made any updates to his PR. If it's okay, I would like to take up this issue from where he left off , if his due time is over. Also I've completed my previous assigned task, waiting for review.

**Comment by stnguyen90** [comment]
@Pradyuman7, how's your progress on this?

**Comment by Pradyuman7** [comment]
@stnguyen90 unfortunately I've not been able to gather enough time to continue with this. Apologies for this, and please feel free to reassign. I have an incomplete PR which can also be reused if needed.

**Comment by Meldiron** [comment]
@Pradyuman7 Thanks for letting us know 🙏 I am re-assigning to @PMohanJ . Ill keep the draft PR open as it might he great guidance for PMohanJ.

**Comment by PMohanJ** [comment]
Thanks @Meldiron! I'll try to finish it fast as I can.

**Comment by PMohanJ** [comment]
Hi @Meldiron I've made the PR. Please review it and let me know if any changes needed. Good day!
