### ISSUE TITLE
🤖 Improve Appwrite Functions with Lua Support

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4022]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), a project built to enable serverless cloud computing. Open Runtimes support many different programming languages, but we all know there are never enough programming languages! 🔥

Your task is to implement support for **Lua** in Open Runtimes. We have prepared detailed documentation on [how to create a new function's runtime](https://github.com/open-runtimes/open-runtimes/blob/main/docs/add-runtime.md). Please read this document and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with **Lua**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement support for **Lua**.
- [ ]  Implement tests for **Lua**.
- [ ]  Submit a pull request in [open-runtimes/open-runtimes](https://github.com/open-runtimes/open-runtimes).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by RahulSurwade08** [comment]
Hey @christyjacob4 , I would love to contribute to this issue under Hacktoberfest. How can I get started as I am new to Open Source Contributions?

**Comment by NightHack36** [comment]
Hi @christyjacob4  I would like to contribute to this issue, could you please assign this to me?

**Comment by NightHack36** [comment]
Hi @christyjacob4  I would like to contribute to this issue, could you please assign this to me?

**Comment by Azanul** [comment]
@stnguyen90 If @NightHack36 is no longer working on it, can you assign it to me?

**Comment by stnguyen90** [comment]
@NightHack36, how's our progress on this? Please let us know within 24 hours so we can reassign accordingly.

**Comment by stnguyen90** [comment]
Reassigning to @Azanul due to inactivity.

**Comment by Azanul** [comment]
I'll raise the PR in a couple of weeks as the hacktoberfest is over, there's no rush. I hope that's fine.

**Comment by stnguyen90** [comment]
@Azanul are you still working on this or should we unassign you?

**Comment by Azanul** [comment]
@stnguyen90 I'm on it.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
