### ISSUE TITLE
🦸 Make a Dream Contribution. What Is It? You Tell Us!

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4024]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to allow **anyone** to contribute to our project, no matter your background.

We understand coding is not for everyone, and even though we have many no-code and low-code issues, we believe there are many new opportunities for all of you to contribute. We also believe it’s important for every contributor to feel confident with the issue.

With this in mind, we decided to introduce the **✨ Dream Contribution ✨**

Your task is to comment on this issue with your idea of a perfect Appwrite contribution. We will review all of your ideas, pick the best ones and create separate issues assigned to you that you can start working on immediately! 

To ensure all issues are quality contributions, please make sure you meet the requirements listed below 🙏

### 🎯 Requirements

- The contribution has to involve [Appwrite](https://github.com/appwrite), [Utopia](https://github.com/utopia-php/), or [Open Runtimes](https://github.com/open-runtimes) in one way or another.
- The result of the contribution has to be public, ideally under an MIT license.
- The contribution has to have a positive impact on the project or its community.
- The task must not be tiny or huge. Let’s avoid extremes.
- The task must require a reasonable amount of effort.

### ✅ Task Summary

- [ ]  Write a comment with your dream contribution idea.
- [ ]  Wait for the Appwrite team to review and accept your idea.
- [ ]  Work on the GitHub issue.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by jyotirmaya907** [comment]
Hey I want to show case my idea and contribute to this issue. Can you assign to me please ?

**Comment by itsPriyanshuRaj** [comment]
Hey @2002Bishwajeet , I would like to make my dream contribution by writing a blog based on Appwrite and Open Runtimes.

**Comment by chinmayayy** [comment]
Hello, I would like to contribute by writing beginner-friendly documentation for the appwrite package available on PyPI with code snippets. Thanks!

**Comment by VoidCupboard** [comment]
Hi!
Since a bunch of app clones is already listed, I would like to also tell you about another app clone that can be made - Google Classroom. This can help new Appwrite users know about Authentication (for students and teachers), Databases (for storing classes and messages), Buckets (for storing assignments and responses), etc.
I will be making a video on it most probably. If I cannot make one, I would be at least writing a blog with different chapters including the explanation for all the parts being made.

**Comment by FarhanAliRaza** [comment]
Hi! I want to upgrade appwrite hacktoberfest to new version of sveltekit . @christyjacob4  .Should i do it for hacktoberfest 22?

**Comment by FarhanAliRaza** [comment]
And i can also build a sveltekit demo app with appwrite . How should i proceed with that?

**Comment by marshalmiller** [comment]
I'd like to contribute a GitHub action that checks for language that might make people feel attacked or unsafe in this repo when comments are posted on issues and PRs, as well as when pull request reviews are submitted.

**Comment by Sneha421** [comment]
Hello @christyjacob4!
I am a beginner at Appwrite and I am quite intrigued by the Almost Series. I would like to build an Almost Instagram and I am interested in writing a blog about it as well.
Through this, I am sure I can grasp the main features of Appwrite while also teaching the community about it!

**Comment by Arpan-206** [comment]
I want to make an Almost Bitly with an Appwrite backend.

**Comment by codercatdev** [comment]
@Sneha421 I would suggest jumping on the issue we have for that 😃

https://github.com/appwrite/appwrite/issues/4286

**Comment by srini047** [comment]
Hi! I would like to work on `🧑‍🏫 Help Developers by Coding Demo of Appwrite + Telegram (bot)`. The one similar to Discord (bot).

**Comment by Meldiron** [comment]
> Hello, I would like to contribute by writing beginner-friendly documentation for the appwrite package available on PyPI with code snippets. Thanks!

Hey there @chinmayayy  👋 Looking at the Appwrite PyPI library, I don't see any description. This sounds like a valid concern. I have created an issue for you: https://github.com/appwrite/appwrite/issues/4304
Looks like I cannot assign it to you - you need to comment on it first. Please do that and Ill give you the issue 🙏 Happy hacking! 🎃

**Comment by Meldiron** [comment]
> Hi! Since a bunch of app clones is already listed, I would like to also tell you about another app clone that can be made - Google Classroom. This can help new Appwrite users know about Authentication (for students and teachers), Databases (for storing classes and messages), Buckets (for storing assignments and responses), etc. I will be making a video on it most probably. If I cannot make one, I would be at least writing a blog with different chapters including the explanation for all the parts being made.

Heyyy @VoidCupboard  👋 This idea sounds great! Regarding chat, classes, accounts, and all you can easily use Appwrite! 💪 Keep in mind that the main feature of Google Classroom is video streaming. That is done over WebRTC, a peer-to-peer communication. Please confirm with me if you would also be able to implement this. If yes, I will go ahead and create an issue for you.

**Comment by Meldiron** [comment]
> And i can also build a sveltekit demo app with appwrite . How should i proceed with that?

Hello @FarhanAliRaza 👋 I can see how an article about using Appwrite with Svelte (and Svelte Kit) would be useful. I have created an issue for that: https://github.com/appwrite/appwrite/issues/4305
Feel free to go ahead and start working on this 😇 Anyone can work on this Svelte Kit issue, so no need to be assigned.

**Comment by Meldiron** [comment]
> I'd like to contribute a GitHub action that checks for language that might make people feel attacked or unsafe in this repo when comments are posted on issues and PRs, as well as when pull request reviews are submitted.

Hey @marshalmiller 👋 I appreciate your idea! 🙏 I ran this over our DevRel team and we would prefer to do the moderation manually instead of automating this process. It helps us keep our community feeling more human-like.

**Comment by VoidCupboard** [comment]
Thanks a bunch @Meldiron!

**Comment by Meldiron** [comment]
> Hello @christyjacob4! I am a beginner at Appwrite and I am quite intrigued by the Almost Series. I would like to build an Almost Instagram and I am interested in writing a blog about it as well. Through this, I am sure I can grasp the main features of Appwrite while also teaching the community about it!

Hello @Sneha421 👋 Great point, we missed this huuuuge platform 🙈 A different community member already pointed it out and we created this issue: https://github.com/appwrite/appwrite/issues/4286
Feel free to work on your version of Almost Instagram based on this issue 😇 We are not assigning it, anyone can work on it.

**Comment by Meldiron** [comment]
> Hi! I would like to work on `🧑‍🏫 Help Developers by Coding Demo of Appwrite + Telegram (bot)`. The one similar to Discord (bot).

Heyyy @srini047 👋 Great idea! I created issue for it: https://github.com/appwrite/appwrite/issues/4308
You can go ahead and work on this, no need to get assigned. Happy hacking! 🎃

**Comment by ishan-siddiqui** [comment]
Hi! I would like to work on this issue. Could I please be assigned this issue?

**Comment by yaakov123** [comment]
Hey, I would like to build an "Almost Whatsapp Web". In reality I've already completed it as I've been creating a tutorial series on how to create Whatsapp with Appwrite and VueJS.

This clone already uses the following Appwrite features:

- Authentication
- Functions (user-triggered and event-triggered)
- Database
- Realtime

Could you point me in the right direction in terms of where to add this? If you'd like to take a look at the repo, it's located here - https://github.com/yaakov123/whatsapp-clone

The YouTube series is located here - https://www.youtube.com/playlist?list=PL03bmqtntNbe9Ad9IT5JYGvi1Ecbcn4Rk

**Comment by 2002Bishwajeet** [comment]
Hey @yaakov123 , This PR should be made in the [awesome-appwrite](https://github.com/appwrite/awesome-appwrite). But I would recommend to wait for the maintainer to approve this first🙂.

**Comment by dcowan-london** [comment]
Hey, I'd like to work on getting the [Appwrite VSCode extension](https://github.com/streamlux/vscode-appwrite) up to date (currently has not been maintained for over a year and is completely broken). I've started [here](https://github.com/dcowan-london/vscode-appwrite/tree/update-appwrite-v1)

**Comment by stnguyen90** [comment]
> Hey, I'd like to work on getting the [Appwrite VSCode extension](https://github.com/streamlux/vscode-appwrite) up to date (currently has not been maintained for over a year and is completely broken). I've started [here](https://github.com/dcowan-london/vscode-appwrite/tree/update-appwrite-v1)

@dcowan-london, have you reached out to the maintainer about contributing to their repo?

**Comment by yaakov123** [comment]
> Hey, I would like to build an "Almost Whatsapp Web". In reality I've already completed it as I've been creating a tutorial series on how to create Whatsapp with Appwrite and VueJS.
> 
> This clone already uses the following Appwrite features:
> 
> * Authentication
> * Functions (user-triggered and event-triggered)
> * Database
> * Realtime
> 
> Could you point me in the right direction in terms of where to add this? If you'd like to take a look at the repo, it's located here - https://github.com/yaakov123/whatsapp-clone
> 
> The YouTube series is located here - https://www.youtube.com/playlist?list=PL03bmqtntNbe9Ad9IT5JYGvi1Ecbcn4Rk

@Meldiron - Any updates regarding this?

**Comment by itsPriyanshuRaj** [comment]
> > Hey @2002Bishwajeet , I would like to make my dream contribution by writing a blog based on Appwrite and Open Runtimes.
> 
> Hey there 👋 That sounds interesting! 👀 Could you please be more specific about the article? What would the article be about - could you please share a simple outline with us?

Blog on appwrite will be about...what is appwrite and how it helps different developers with backend development.

**Comment by Rinshin-Jalal** [comment]
I would like to build the `Almost Youtube`  web using Solidjs and Appwrite

there is no demos for solidjs and rn

**Comment by Arpan-206** [comment]
I want to build an `almost Bit.ly` Discord bot.

**Comment by stnguyen90** [comment]
> I want to build an `almost Bit.ly` Discord bot.

@Arpan-206 what exactly would this do?

**Comment by Arpan-206** [comment]
> > I want to build an `almost Bit.ly` Discord bot.
> 
> @Arpan-206 what exactly would this do?

I mean a URL shortener Discord bot using Appwrite

**Comment by stnguyen90** [comment]
@yaakov123, you can go ahead and comment on this with your interest: https://github.com/appwrite/appwrite/issues/4508

**Comment by stnguyen90** [comment]
@Arpan-206, that sounds like a great idea! Go ahead and work on the bot! Make sure to implement it as interactive commands so that you don't need a long-running function. You may need a proxy to translate the data from Discord into the format Appwrite expects. For that, you can use this [Webhook Proxy](https://github.com/Meldiron/railway-webhook-proxy).

**Comment by yaakov123** [comment]
> @yaakov123, you can go ahead and comment on this with your interest: #4508

I've already created the clone and added the PR in the awesome-appwrite repo a while ago, but nobody took a look at it. https://github.com/appwrite/awesome-appwrite/pull/435/files

**Comment by letsintegreat** [comment]
Hey! I would like to make a Diary app using Appwrite as backend. The app would be helpful for those who like to maintain a personal Diary. An app will help them write it daily on the go!

The app will demonstrate the usage of Appwrite Users and Databases, and how to connect them to a flutter app.
