### ISSUE TITLE
🧱 Build Almost Twitter. Be Creative!

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4026]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to provide Appwriters with a **huge amount** of example projects that many use as learning resources.

We understand Appwrite’s tech stack might not be your cup of tea, so we decided to prepare a series of `Almost (something)` projects. This series of issues is here to let your creativity shine! ✨

Your task is to create **Almost Twitter**. This should be a website that copies the functionality of Twitter, but uses Appwrite as a backend. We understand that Twitter is a huge project, so don’t worry about implementing every single feature - make sure to only focus on the most well-known features of this platform. Regarding design, please try not to copy the official one - feel free to use UI libraries to help you out.

You can check out [Almost Reddit](https://github.com/Meldiron/almost-reddit-place) as a reference project. This project meets all the requirements.

### 🎯 Requirements

- You must replicate the most iconic features of Twitter.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be a web or Flutter application. Regarding the web, use any JavaScript technology.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build Almost Twitter as a web or Flutter app. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Write an article about how you built Almost Twitter on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Abhijnan-Bajpai** [comment]
Hey @christyjacob4! Excited to work on this for my Hacktoberfest contribution! Could I be assigned?

**Comment by esau-morais** [comment]
I'd like to be assigned to this issue

**Comment by MSamiDev** [comment]
I would like to be assigned to this issue, And work on the project.

**Comment by flynnzler** [comment]
I'd love to be assigned to this issue!

**Comment by exitflynn** [comment]
I would love to be assigned this issue and build an Almost Twitter using AppWrite!

**Comment by amelia2802** [comment]
Hello I would like to work on this issue

**Comment by hridaya423** [comment]
I would like to work on this @christyjacob4

**Comment by Summiedev** [comment]
Hello, @christyjacob4! i would love to take up on this task, I have an experience using flutter in building apps/websites. May I be assigned this issue please?

**Comment by sarkartanmay393** [comment]
@christyjacob4 I would also like to work on it.

**Comment by Jyoti050402** [comment]
I would like to work on this issue.

**Comment by Meldiron** [comment]
@MSamiDev @exitflynn @amelia2802 @hridaya423 @Summiedev @sarkartanmay393 @Jyoti050402 Hey everyone 👋

We have updated this issue. We decided to allow anyone to work on this issue. All of you can start working on your own version of Almost Twitter 🥳

**Comment by Animesht1008** [comment]
hi @christyjacob4 can you please assign me this issue as a part of hacktoberfest?

**Comment by gewenyu99** [comment]
@Animesht1008 Please read above comment. No need to be assigned, you can start right away!

**Comment by EshaanAgg** [comment]
Hi! I would also love to work on this. I would be using Vue.js to make the same!
