### ISSUE TITLE
🧱 Build Almost Dev.to. Be Creative!

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4030]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to provide Appwriters with a **huge amount** of example projects that many use as learning resources.

We understand Appwrite’s tech stack might not be your cup of tea, so we decided to prepare a series of `Almost (something)` projects. This series of issues is here to let your creativity shine! ✨

Your task is to create **Almost Dev.to**. This should be a website that copies the functionality of Dev.to, but uses Appwrite as a backend. We understand that Dev.to is a huge project, so don’t worry about implementing every single feature - make sure to only focus on the most well-known features of this platform. Regarding design, please try not to copy the official one - feel free to use UI libraries to help you out.

You can check out [Almost Reddit](https://github.com/Meldiron/almost-reddit-place) as a reference project. This project meets all the requirements.

### 🎯 Requirements

- You must replicate the most iconic features of Dev.to.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be a web or Flutter application. Regarding the web, use any JavaScript technology.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build Almost Dev.to as a web or Flutter app. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Write an article about how you built Almost Dev.to on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by MukulKolpe** [comment]
Hey @christyjacob4, can I work on this issue ?

**Comment by christyjacob4** [comment]
Hey 👋  all issue assignments for Hacktoberfest will take place on a first come first serve basis starting on October 1st

**Comment by sbiswas2209** [comment]
Hi, @christyjacob4 I would like to work on this issue. Can you please assign this to me?

**Comment by Saurav-Singh-Rauthan** [comment]
Hi @christyjacob4 can you please assign this to me

**Comment by vish-han** [comment]
Hi @christyjacob4 i have already started working on this project can u please assign me🚀😀

**Comment by hridaya423** [comment]
I would like to work on this @christyjacob4

**Comment by Arpan-206** [comment]
Can you assign this to me? @christyjacob4

**Comment by Meldiron** [comment]
@MukulKolpe @sbiswas2209 @Saurav-Singh-Rauthan @vish-han @hridaya423 @Arpan-206 Hey everyone 👋

We have updated this issue. We decided to allow anyone to work on this issue. All of you can start working on your own version of Almost Dev.to 🥳

**Comment by RajdeepDs** [comment]
@Meldiron 
If I contribute to this issue, did my PR get counted in Appwrite Hacktoberfest.

**Comment by Meldiron** [comment]
@RajdeepDs Yes, all PRs made based on Appwrite issues count towards Appwrite Hacktoberfest. You would be making a PR into awesome-appwrite repository where you add a link to your GitHub repo with the Almost Dev.to. That will be a valid contribution for both Appwrite, and the official Hacktoberfest.
