### ISSUE TITLE
🧱 Build Almost Reddit. Be Creative!

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4031]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to provide Appwriters with a **huge amount** of example projects that many use as learning resources.

We understand Appwrite’s tech stack might not be your cup of tea, so we decided to prepare a series of `Almost (something)` projects. This series of issues is here to let your creativity shine! ✨

Your task is to create **Almost Reddit**. This should be a website that copies the functionality of Reddit, but uses Appwrite as a backend. We understand that Reddit is a huge project, so don’t worry about implementing every single feature - make sure to only focus on the most well-known features of this platform. Regarding design, please try not to copy the official one - feel free to use UI libraries to help you out.

You can check out [Almost Reddit](https://github.com/Meldiron/almost-reddit-place) as a reference project. This project meets all the requirements.

### 🎯 Requirements

- You must replicate the most iconic features of Reddit.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be a web or Flutter application. Regarding the web, use any JavaScript technology.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build Almost Reddit as a web or Flutter app. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Write an article about how you built Almost Reddit on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by chiragkhatri19** [comment]
Can you please assign this to me ?

**Comment by VoidCupboard** [comment]
Since it has already been asked, I would like to work on this issue if Chirag is not able to do it or resigns from doing

**Comment by chiragkhatri19** [comment]
We can work on this together @VoidCupboard 
You can do the backend part and Frontend is all on me

**Comment by VoidCupboard** [comment]
Wait can we?
But actually there isnt anything to do in the backend part IMO, since it will be all handled by Appwrite and the SDK

**Comment by chiragkhatri19** [comment]
So can you help me in that ?

**Comment by VoidCupboard** [comment]
Sure I would love to, do you have a discord id by which we can chat?

**Comment by chiragkhatri19** [comment]
> Sure I would love to, do you have a discord id by which we can chat?
> 
> Wait what about the rewards?

Yeah you can get it on my profile's readme file

**Comment by VoidCupboard** [comment]
I actually don't see your discord id in your readme. Nonetheless, here is my discord id - VoidCupboard#7880, add me :D

**Comment by iShelar** [comment]
If in case frontend requires any help. Please let me know I'll be happy to help @chiragkhatri19

**Comment by Meldiron** [comment]
@chiragkhatri19 @VoidCupboard Hey both of you 👋

We have updated this issue. We decided to allow anyone to work on this issue. All of you can start working on your own version of Almost Reddit 🥳

I also noticed you wanted to work on this together. Feel free to do that, I love the passion 😊

**Comment by VoidCupboard** [comment]
Wooooooo! Thats really cool! Thanks @Meldiron!

**Comment by chiragkhatri19** [comment]
One of my family member got a bit ill 
I'll start working on it tomorrow with @VoidCupboard
