### ISSUE TITLE
🧱 Build Almost Notion. Be Creative!

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4032]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to provide Appwriters with a **huge amount** of example projects that many use as learning resources.

We understand Appwrite’s tech stack might not be your cup of tea, so we decided to prepare a series of `Almost (something)` projects. This series of issues is here to let your creativity shine! ✨

Your task is to create **Almost Notion**. This should be a website that copies the functionality of Notion, but uses Appwrite as a backend. We understand that Notion is a huge project, so don’t worry about implementing every single feature - make sure to only focus on the most well-known features of this platform. Regarding design, please try not to copy the official one - feel free to use UI libraries to help you out.

You can check out [Almost Reddit](https://github.com/Meldiron/almost-reddit-place) as a reference project. This project meets all the requirements.

### 🎯 Requirements

- You must replicate the most iconic features of Notion.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be a web or Flutter application. Regarding the web, use any JavaScript technology.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build Almost Notion as a web or Flutter app. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Write an article about how you built Almost Notion on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Rinshin-Jalal** [comment]
This issue is repeation of #4027
![image](https://user-images.githubusercontent.com/88965873/193259527-1fb6d735-136c-4660-8a37-e73f79bb9821.png)

#4027

**Comment by shubhamlakheraa** [comment]
Hey, I would like to work on this.
Please assign this to me @christyjacob4

**Comment by Sneha421** [comment]
Hello @christyjacob4!
I would love to work on this issue by making a Flutter App. I have a few ideas for improving a few Notion Features, that I would like to incorporate here. 
I am also interested in writing a Medium article about the same.

**Comment by hridaya423** [comment]
I would like to work on this @christyjacob4

**Comment by Rinshin-Jalal** [comment]
> @Rinshin-Jalal Hey there wave All of those issues are asking you to build a different platform, for example, Twitter, Facebook, Asana, ProductHunt... Feel free to pick a platform that you know the best and build a copy of it innocent Even tho titles and descriptions look similar, these are all different issues.


Hi

@Meldiron I mean there are two issues for Almost notion
#4027 #4032

**Comment by Meldiron** [comment]
@Rinshin-Jalal I see now, great catch! We will tackle this, thanks.
