### ISSUE TITLE
🧱 Build Almost Discord. Be Creative!

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4034]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to provide Appwriters with a **huge amount** of example projects that many use as learning resources.

We understand Appwrite’s tech stack might not be your cup of tea, so we decided to prepare a series of `Almost (something)` projects. This series of issues is here to let your creativity shine! ✨

Your task is to create **Almost Discord**. This should be a website that copies the functionality of Discord, but uses Appwrite as a backend. We understand that Discord is a huge project, so don’t worry about implementing every single feature - make sure to only focus on the most well-known features of this platform. Regarding design, please try not to copy the official one - feel free to use UI libraries to help you out.

You can check out [Almost Reddit](https://github.com/Meldiron/almost-reddit-place) as a reference project. This project meets all the requirements.

### 🎯 Requirements

- You must replicate the most iconic features of Discord.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be a web or Flutter application. Regarding the web, use any JavaScript technology.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build Almost Discord as a web or Flutter app. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Write an article about how you built Almost Discord on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by nown1ne** [comment]
would love to work on this project. Can you please assign me the issue

**Comment by copyNinja1219** [comment]
@christyjacob4 May I work on this issue ?

**Comment by AniqJaved** [comment]
It looks awesome to start with. Can I work on this project?

**Comment by Summiedev** [comment]
Hello, @christyjacob4!  i would love to take up on this task, I have an experience using flutter in building apps. May I be assigned this issue please?

**Comment by Meldiron** [comment]
@RahulSurwade08 @nown1ne @copyNinja1219 @AniqJaved @Summiedev Hey everyone 👋

We have updated this issue. We decided to allow anyone to work on this issue. All of you can start working on your own version of Almost Evernote 🥳

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by codercatdev** [comment]
@anushagupta1312 no need for assignment on this one feel free to work on this 🎉

We have updated this issue. We decided to allow anyone to work on this issue.

**Comment by Animesht1008** [comment]
hi @christyjacob4 can you please assign me this issue as a part of hacktoberfest?

**Comment by gewenyu99** [comment]
> hi @christyjacob4 can you please assign me this issue as a part of hacktoberfest?

No need to be assigned. Anyone can work on this issue :) Good luck!

**Comment by Meldiron** [comment]
@arnu515 Thanks for letting us know 😇 You can go ahead and start working on this.
