### ISSUE TITLE
⚡ Write a sendMessage() Function using .NET

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4037]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendMessage()` function using **.NET**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

The function must send a message using a specific channel to a receiver. Make sure to introduce function variables as necessary regarding connection to 3rd party services. Supported channels must be `Email`, `SMS`, `Discord`, and `Twitter`.

Example function payload:

```jsx
{"type":"SMS","receiver":"+123456789","message":"Programming is fun!"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Receiver not in correct format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **.NET**.
- Knowledge to implement **sendMessage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendMessage()` in `.NET/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by vishnus17** [comment]
Hi @christyjacob4. I would like to work on this issue. Can you assign it to me?
Thanks.

**Comment by stnguyen90** [comment]
@vishnus17, thanks for your interest! 🙏 Happy hacking!

**Comment by Kaushalrr006** [comment]
I am interested in this task please assign me THIS TASK

**Comment by vishnus17** [comment]
Hi @Kaushalrr006 . I'm working on this task and have already completed a few parts. I was off due to my exams and will continue it this week. 
Thanks.

**Comment by stnguyen90** [comment]
@vishnus17 are you still working on this or should we unassign you?

**Comment by vishnus17** [comment]
Hi @stnguyen90 . Sorry about it. I had previously completed the function for Email and its testing. I was completely off due to my college and internship busy schedule. You may unassign me as I'm having my final exams coming up next week.
I will take up issues once I'm free.
Thanks.

**Comment by Muasya0254** [comment]
Hi @Haimantika.I'm working on this.

**Comment by Oluwafemisire** [comment]
Hi @Haimantika. I will be working on this issue with @Muasya0254 @gyamposudodzi.

**Comment by Haimantika** [comment]
Hi, @Muasya0254 and @Oluwafemisire I am assigning this issue to both of you.

**Comment by gyamposudodzi** [comment]
Hi @Haimantika I was also assigned this project under code-day, worked on the project with @Muasya0254 and @Oluwafemisire  hope you add me to the assignees later if it is really needed

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
