### ISSUE TITLE
⚡ Write a getPrice() Function using Kotlin

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4085]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `getPrice()` function using **Kotlin**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Get the price of crypto, stocks, and commodities. Feel free to use 3rd party services and introduce their secret keys as function variables. The type of goods should be provided as payload, and the price in dollars should be returned. Supported goods should include (at least) Bitcoin, Ethereum, Google, Amazon, gold, and silver.

Example function payload:

```jsx
{"type":"gold"}
```

Successful function response:

```jsx
{"success":true,"price":1666.81}
```

Error function response:

```jsx
{"success":false,"message":"Type is not supported."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Kotlin**.
- Knowledge to implement **getPrice** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `getPrice()` in `Kotlin/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by hardiksachan** [comment]
Hey there! I'd like to work on this

**Comment by Meldiron** [comment]
@hardiksachan Happy to see participating in Hacktoberfest this year again 😇

Assigned to you, happy hacking 🎃

**Comment by hardiksachan** [comment]
Hey there! How can I apply plugins to my code?

I'm using `kotlinx.serialization` for content negotiation and it requires me to apply a plugin which I cannot do since plugins block is not allowed in `deps.gradle` file.

**Comment by abnegate** [comment]
Hey @hardiksachan :wave:  It's possible to add plugins in `deps.gradle`, but you have to use the old application method instead of the `plugins` block, as well as use the fully qualified class name of the plugin when applying. You can use `kotlinx.serialization` like so:

```groovy
buildscript {
    repositories { 
        mavenCentral() 
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-serialization:1.6+"
    }
}

apply plugin: org.jetbrains.kotlinx.serialization.gradle.SerializationGradleSubplugin

dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.0"
}
```

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
