### ISSUE TITLE
⚡ Write a getPrice() Function using .NET

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4086]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `getPrice()` function using **.NET**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Get the price of crypto, stocks, and commodities. Feel free to use 3rd party services and introduce their secret keys as function variables. The type of goods should be provided as payload, and the price in dollars should be returned. Supported goods should include (at least) Bitcoin, Ethereum, Google, Amazon, gold, and silver.

Example function payload:

```jsx
{"type":"gold"}
```

Successful function response:

```jsx
{"success":true,"price":1666.81}
```

Error function response:

```jsx
{"success":false,"message":"Type is not supported."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **.NET**.
- Knowledge to implement **getPrice** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `getPrice()` in `.NET/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Harindulk** [comment]
I want to work on this issue can you please assign me and guide me?

**Comment by rafaelbubach** [comment]
Could you guys assign me to this issue?

**Comment by tessamero** [comment]
@rafaelbubach , thanks for your interest! You may work on this issue🙏 Happy hacking! 🎃

**Comment by rafaelbubach** [comment]
Hey @tessamero, I'm sorry, but I'll not be able to work on this issue for the next few weeks.
If you want to assign it to another developer, please feel free!
Again, sorry for holding it for so long. :disappointed:

**Comment by Meldiron** [comment]
@rafaelbubach No worries 😇 Reassigning to @codingmickey

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
