### ISSUE TITLE
⚡ Write a generateInvoice() Function using Deno

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4089]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateInvoice()` function using **Deno**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a PDF invoice. Please avoid using 3rd party services, but feel free to use a library. The payload must provide all invoice details, and a PDF in base64 format should be returned. Regarding customer and issuer, please support `
` as a symbol for breaking lines. Invoices usually have 4-5 lines of information for both which include for instance name, address, and phone number.

Example function payload:

```jsx
{"currency":"EUR","items":[{"name":"Web development","price":15}],"issuer":"Some\nIssuer","customer":"Some\nCustomer","vat":21}
```

Successful function response:

```jsx
{"success":true,"invoice":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a currency."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Deno**.
- Knowledge to implement **generateInvoice** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateInvoice()` in `Deno/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by camperjett** [comment]
Hi @PineappleIOnic 😀 Can I take up this issue?

**Comment by tessamero** [comment]
@camperjett , thanks for your interest! You may work on this issue🙏 Happy hacking! 🎃

**Comment by camperjett** [comment]
Hi. I have made a PR for this issue. https://github.com/open-runtimes/examples/pull/46

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
