### ISSUE TITLE
⚡ Write a generateInvoice() Function using Node

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4090]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateInvoice()` function using **Node**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a PDF invoice. Please avoid using 3rd party services, but feel free to use a library. The payload must provide all invoice details, and a PDF in base64 format should be returned. Regarding customer and issuer, please support `
` as a symbol for breaking lines. Invoices usually have 4-5 lines of information for both which include for instance name, address, and phone number.

Example function payload:

```jsx
{"currency":"EUR","items":[{"name":"Web development","price":15}],"issuer":"Some\nIssuer","customer":"Some\nCustomer","vat":21}
```

Successful function response:

```jsx
{"success":true,"invoice":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a currency."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Node**.
- Knowledge to implement **generateInvoice** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateInvoice()` in `Node/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by partik03** [comment]
@PineappleIOnic I want to work on this issue ,kindly assign it to me

**Comment by Meldiron** [comment]
@partik03 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by partik03** [comment]
@PineappleIOnic can you help me by providing some more info about what this function should do actually

**Comment by Meldiron** [comment]
Hey there 👋 The issue description should explain everything, as well as provide examples of input and output. You pretty much generate a PDF invoice and return it as a base64 string. To generate PDFs you can use any library of your choice. For example, in Node, you could simply use this to make the pdf: https://www.npmjs.com/package/pdfkit

**Comment by HimanshT** [comment]
Hey,I would like to work on this issue

**Comment by Meldiron** [comment]
@HimanshT , we're assigning people on a first come first serve basis. If @partik03  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).
