### ISSUE TITLE
⚡ Write a generateInvoice() Function using Python

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4092]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateInvoice()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a PDF invoice. Please avoid using 3rd party services, but feel free to use a library. The payload must provide all invoice details, and a PDF in base64 format should be returned. Regarding customer and issuer, please support `
` as a symbol for breaking lines. Invoices usually have 4-5 lines of information for both which include for instance name, address, and phone number.

Example function payload:

```jsx
{"currency":"EUR","items":[{"name":"Web development","price":15}],"issuer":"Some\nIssuer","customer":"Some\nCustomer","vat":21}
```

Successful function response:

```jsx
{"success":true,"invoice":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a currency."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **generateInvoice** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateInvoice()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by KingFire25** [comment]
!assign

**Comment by tessamero** [comment]
> !assign

@KingFire25 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by KingFire25** [comment]
Will the input be a JSON or CSV file?

**Comment by Meldiron** [comment]
@KingFire25 Hey there 👋 Please use JSON format with both input `req.payload` and output `req.json()`. You can find expected values under `Function Details` title in the description of the issue.

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by tessamero** [comment]
@anushagupta1312 , we are assigning people on a first come first serve basis. If @KingFire25  isn't able to complete this issue, we will reassign accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by KingFire25** [comment]
Sorry to say this but I would like this issue to be reassigned to somenody else as I am unable to do this even after many tries.

**Comment by Meldiron** [comment]
@KingFire25 So sorry to hear that. Please feel free to pick up a different type of issue, we have multiple code, as well as low/no code.

Thanks for letting us know 🙏 Unassigning you from the issue.

**Comment by suryaa62** [comment]
I would like to work on this

**Comment by stnguyen90** [comment]
@anushagupta1312, looks like you already have 4 PRs. Would it be okay to assign this to @suryaa62?

**Comment by toukirkhan** [comment]
@stnguyen90 can I work on this?

**Comment by stnguyen90** [comment]
@toukirkhan, @anushagupta1312 and @suryaa62 are next up for this issue. If neither of them are able to work on the issue, we'll assign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Shivansh-yadav13** [comment]
anyone working on this issue?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
