### ISSUE TITLE
⚡ Write a generateInvoice() Function using Java

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4095]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateInvoice()` function using **Java**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a PDF invoice. Please avoid using 3rd party services, but feel free to use a library. The payload must provide all invoice details, and a PDF in base64 format should be returned. Regarding customer and issuer, please support `
` as a symbol for breaking lines. Invoices usually have 4-5 lines of information for both which include for instance name, address, and phone number.

Example function payload:

```jsx
{"currency":"EUR","items":[{"name":"Web development","price":15}],"issuer":"Some\nIssuer","customer":"Some\nCustomer","vat":21}
```

Successful function response:

```jsx
{"success":true,"invoice":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a currency."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Java**.
- Knowledge to implement **generateInvoice** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateInvoice()` in `Java/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Goheljay** [comment]
hi @PineappleIOnic, I want to work on this issue can you assign me?

**Comment by Meldiron** [comment]
@Goheljay , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Goheljay** [comment]
Hi @Meldiron , can I use the pdfBox Library to generate a pdf?
[pdfBox website](https://pdfbox.apache.org/)

**Comment by Meldiron** [comment]
@Goheljay Hey there 👋 You can use any library of your choice to generate the PDF. You like it? You use it 😎

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by tessamero** [comment]
@anushagupta1312 , we are assigning people on a first come first serve basis. If @Goheljay  isn't able to complete this issue, we will reassign accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Goheljay** [comment]
@Meldiron  i could not complete this issue for some reson. sorry for that. 
please reassigne to other people. 
thank you.

**Comment by tessamero** [comment]
@anushagupta1312 would you like to work on this issue? Let us know and we will assign you.

**Comment by sahalsaad** [comment]
Hi, I would like to work on this issue. Thanks

**Comment by stnguyen90** [comment]
Assigning to @sahalsaad as there was no response. Happy hacking!
