### ISSUE TITLE
⚡ Write a wipeAppwriteCollection() Function using Node

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4098]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `wipeAppwriteCollection()` function using **Node**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Delete all documents inside an Appwrite Database collection. Make sure to introduce `APPWRITE_FUNCTION_PROJECT_ID`, `APPWRITE_FUNCTION_ENDPOINT` and `APPWRITE_FUNCTION_API_KEY` function variables. Database ID and Collection ID should be received as payload.

Example function payload:

```jsx
{"databaseId":"stage","collectionId":"profiles"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Collection not found."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Node**.
- Knowledge to implement **wipeAppwriteCollection** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `wipeAppwriteCollection()` in `Node/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by kritikash18** [comment]
Hi @PineappleIOnic, can you please assign me this issue?

**Comment by Meldiron** [comment]
@kritikash18 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by kritikash18** [comment]
raised and linked a PR for this
