### ISSUE TITLE
⚡ Write a wipeAppwriteCollection() Function using Python

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4100]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `wipeAppwriteCollection()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Delete all documents inside an Appwrite Database collection. Make sure to introduce `APPWRITE_FUNCTION_PROJECT_ID`, `APPWRITE_FUNCTION_ENDPOINT` and `APPWRITE_FUNCTION_API_KEY` function variables. Database ID and Collection ID should be received as payload.

Example function payload:

```jsx
{"databaseId":"stage","collectionId":"profiles"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Collection not found."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **wipeAppwriteCollection** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `wipeAppwriteCollection()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by FarhanAliRaza** [comment]
Please this to me. I want to work on this. I have three years of experience with python

**Comment by tessamero** [comment]
@FarhanAliRaza , we are assigning people on a first come first serve basis. If @FarhanAliRaza  isn't able to complete this issue, we will reassign accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by sarkartanmay393** [comment]
@PineappleIOnic I see no assigns here. I would like to work on it.

**Comment by FarhanAliRaza** [comment]
Please assign this to me

**Comment by abnegate** [comment]
@FarhanAliRaza @sarkartanmay393  We are assigning people on a first come first serve basis. If @anushagupta1312  isn't able to complete this issue, we will reassign accordingly. In the meantime, you can find issues to work on [here](https://github.com/appwrite/appwrite/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee) :grin:

**Comment by Azanul** [comment]
@abnegate if @anushagupta1312 is no longer working on it, can I take this up?

**Comment by stnguyen90** [comment]
@anushagupta1312, how's your progress on this issue? Please let us know within 24 hours so we can reassign it accordingly.

@FarhanAliRaza and @sarkartanmay393 are you interested in working on this if @anushagupta1312 is unable to?

@Azanul, we're going in order of commenters so if @FarhanAliRaza and @sarkartanmay393 aren't able to work on this, you'll be next up in line.

**Comment by sarkartanmay393** [comment]
> @anushagupta1312, how's your progress on this issue? Please let us know within 24 hours so we can reassign it accordingly.
> 
> @FarhanAliRaza and @sarkartanmay393 are you interested in working on this if @anushagupta1312 is unable to?
> 
> @Azanul, we're going in order of commenters so if @FarhanAliRaza and @sarkartanmay393 aren't able to work on this, you'll be next up in line.

Yes, I can give it a shot but I need a little more time.

**Comment by stnguyen90** [comment]
@sarkartanmay393 are you still working on this or should we unassign you?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
