### ISSUE TITLE
⚡ Write a generateWebsiteScreenshot() Function using Dart

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4107]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateWebsiteScreenshot()` function using **Dart**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a PNG screenshot of a website. Feel free to use 3rd party services and introduce their secret keys as function variables. An URL of the website should be received as payload, and a screenshot should be returned in base64 format.

Example function payload:

```jsx
{"url":"https://google.com/"}
```

Successful function response:

```jsx
{"success":true,"screenshot":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Website could not be reached."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Dart**.
- Knowledge to implement **generateWebsiteScreenshot** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateWebsiteScreenshot()` in `Dart/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by devtayade** [comment]
@PineappleIOnic hey i really want to work on this issue. i have good experience in dart. this can be my first step towards open source. can you please assign me this issue ?

**Comment by tessamero** [comment]
@devtayade Looks like you have some issues assigned to you already (which was just recently). We request you complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by letsintegreat** [comment]
Hey! I would like to work on this issue.

**Comment by Meldiron** [comment]
@letsintegreat , looks like you have some issues assigned to you already. Please allow us some time to review them before assigning you more issues. In the meantime, you could work on our issues for writing articles and building demo apps - those do not require assignments.

**Comment by 35C4n0r** [comment]
@Meldiron I'm intrested in this issue please assign it to me.

**Comment by codercatdev** [comment]
@35C4n0r , looks like you have some issues assigned to you already. Please allow us some time to review them before assigning you more issues. I believe #4164 is still pending.

**Comment by 35C4n0r** [comment]
@codercatdev i was actuall about to ask to unassign issue #4164 as even for enabling the google cloud services it's asking for my credit card and other details.

**Comment by codercatdev** [comment]
@35C4n0r completely understand, I have removed that assignment and added you here.

**Comment by codercatdev** [comment]
@35C4n0r I think a single service will suffice. If we could find an open source one that would be preferable. I found this searching for the same.

http://screeenly.com/
