### ISSUE TITLE
⚡ Write a generateWebsiteScreenshot() Function using Deno

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4108]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateWebsiteScreenshot()` function using **Deno**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a PNG screenshot of a website. Feel free to use 3rd party services and introduce their secret keys as function variables. An URL of the website should be received as payload, and a screenshot should be returned in base64 format.

Example function payload:

```jsx
{"url":"https://google.com/"}
```

Successful function response:

```jsx
{"success":true,"screenshot":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Website could not be reached."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Deno**.
- Knowledge to implement **generateWebsiteScreenshot** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateWebsiteScreenshot()` in `Deno/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by FarhanAliRaza** [comment]
Please this to me. I want to work on this.

**Comment by tessamero** [comment]
@FarhanAliRaza , thanks for your interest! You may work on this issue🙏 Happy hacking! 🎃

**Comment by FarhanAliRaza** [comment]
@tessamero  
I have opened a pull request about this issue. I completed the function https://github.com/open-runtimes/examples/pull/52

**Comment by tessamero** [comment]
@FarhanAliRaza Thanks for the PR! 🤯 Please give us some time to review it.
