### ISSUE TITLE
⚡ Write a generateWebsiteScreenshot() Function using Java

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4114]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateWebsiteScreenshot()` function using **Java**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a PNG screenshot of a website. Feel free to use 3rd party services and introduce their secret keys as function variables. An URL of the website should be received as payload, and a screenshot should be returned in base64 format.

Example function payload:

```jsx
{"url":"https://google.com/"}
```

Successful function response:

```jsx
{"success":true,"screenshot":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Website could not be reached."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Java**.
- Knowledge to implement **generateWebsiteScreenshot** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateWebsiteScreenshot()` in `Java/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by unrealsoul007** [comment]
This looks cool! Can you assign this to me?

**Comment by Meldiron** [comment]
@unrealsoul007 , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by Samridhi-98** [comment]
hey @PineappleIOnic, I would like to take this one, kindly assign it to me.

**Comment by stnguyen90** [comment]
@anushagupta1312, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by stnguyen90** [comment]
@Samridhi-98, we're assigning people on a first come first serve basis. If @anushagupta1312 isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by stnguyen90** [comment]
@anushagupta1312 Looks like you have some issues assigned to you already. Please complete those before requesting assignments on new ones.

@Samridhi-98, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by ShizhanLiu** [comment]
> Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

Hello Eldadfux, I am a codeday Lab intern for this summer, I have implemented 95% percent of this function. I think I can submit the PR shortly. Could you please reopen this issue for me? 

Thanks so much,
Shizhan Liu

**Comment by harshalkh** [comment]
@ShizhanLiu - are you still working on this one, or can I pick this up?

**Comment by suryanshsoni120** [comment]
If the issue hasn't been resolved, I would like to work on this. Can you assign it to me?

**Comment by mrinal-kumar-1** [comment]
I would like to work on this. Can you assign it to me?

**Comment by harshalkh** [comment]
> @ShizhanLiu - are you still working on this one, or can I pick this up?

@stnguyen90 - looks like there is no response from assignee, can I pick this up...

**Comment by harshalkh** [comment]
> > @ShizhanLiu - are you still working on this one, or can I pick this up?
> 
> @stnguyen90, @eldadfux - looks like there is no response from assignee. The last response from assignee was on 26th Aug. So can I pick this up...

@PineappleIOnic basis above conversation can I pick this up.

**Comment by RaghavenderSingh** [comment]
This looks fun!! Can you assign it to me?

**Comment by AliYar-Khan** [comment]
I am interested in working on this? Can I work on this? One question as well. The screenshot shpuld be long screenshot or just the visible part? like the page can be scrollable and have content that are not visible, need to scroll down to bottom to make them visible !!!

**Comment by Joelute** [comment]
Hi @stnguyen90, I'm an open source contributor for projects like Zulip and I am looking to find a nice issue to start on with this project.

It seems like this issue and the existing PR at [#178](https://github.com/open-runtimes/examples/pull/178) hasn't have had much attention. I've been going over the project requirements for this issue and I am interested in working on this, continuing the work [#178](https://github.com/open-runtimes/examples/pull/178) that's been done with this issue. 

May I be assigned to this issue and get the party started :)

**Comment by eldadfux** [comment]
This issue is no longer relevant
