### ISSUE TITLE
⚡ Write a compressImage() Function using Dart

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4118]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `compressImage()` function using **Dart**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Perform a lossless compression of an image. Introduce support for `tinypng`, as well as `krakenio`. If nessessary, introduce their secret keys as function variables. Provider to use and image to compress should be received as payload in base64 format, and a compressed version should be returned in base64 format.

Example function payload:

```jsx
{"provider":"tinypng","image":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Successful function response:

```jsx
{"success":true,"image":"iVBORw0KGgoAAAANSUhE...o6Ie+UAAAAASU5CYII="}
```

Error function response:

```jsx
{"success":false,"message":"Input file is not an image."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Dart**.
- Knowledge to implement **compressImage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `compressImage()` in `Dart/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by TakshPanchal** [comment]
Hey, I am quite interested in this issue. I wanted to help.

**Comment by stnguyen90** [comment]
@FarhanAliRaza Looks like you have some issues assigned to you already. Please complete those before requesting assignments on new ones.

@TakshPanchal, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by Aadeesh11** [comment]
@TakshPanchal are you still working on this issue? 
@stnguyen90, If not can I be assigned to it?

**Comment by stnguyen90** [comment]
@TakshPanchal how's your progress on this issue?

**Comment by TakshPanchal** [comment]
Hey, apologies for my late work. I will PR today it self.

**Comment by TakshPanchal** [comment]
hey @stnguyen90 , for `krakenio` I am unable to get `200` response for this `upload` request.
```dart
Future<void> _krakenio(
    final res, final Uint8List binaryImage, final Map auth) async {
  try {
    final request = http.MultipartRequest(
        'POST', Uri.parse('https://api.kraken.io/v1/upload'));
    request.fields['data'] = jsonEncode({...auth, 'wait': true});

    request.files.add(http.MultipartFile.fromBytes('upload', binaryImage,
        contentType: MediaType.parse('image/png')));

    print(request.files);
    final response = await request.send();
    print("response $response");
    print("code ${response.statusCode}");
    print(await response.stream.bytesToString());

    if (response.statusCode == 200) {
      print(await response.stream.bytesToString());
    } else {
      print(response.reasonPhrase);
    }
  } catch (e) {
    print(e);
  }
}
```
I am getting `No files found in the request` error with 400 status code. I need help on this.
