### ISSUE TITLE
⚡ Write a compressImage() Function using Deno

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4119]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `compressImage()` function using **Deno**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Perform a lossless compression of an image. Introduce support for `tinypng`, as well as `krakenio`. If nessessary, introduce their secret keys as function variables. Provider to use and image to compress should be received as payload in base64 format, and a compressed version should be returned in base64 format.

Example function payload:

```jsx
{"provider":"tinypng","image":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Successful function response:

```jsx
{"success":true,"image":"iVBORw0KGgoAAAANSUhE...o6Ie+UAAAAASU5CYII="}
```

Error function response:

```jsx
{"success":false,"message":"Input file is not an image."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Deno**.
- Knowledge to implement **compressImage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `compressImage()` in `Deno/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by MoskalykA** [comment]
I would also like to take this

**Comment by Meldiron** [comment]
@MoskalykA , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by MoskalykA** [comment]
> @MoskalykA , thanks for your interest! 🙏 Happy hacking! 🎃

Here I am again, when I run my function I get this error, is it possible to pass the limit?
![image](https://user-images.githubusercontent.com/100430077/193889474-7c9d7f91-aa7d-4788-9089-5dc826c4da7d.png)

**Comment by gewenyu99** [comment]
@MoskalykA I'm curious how you've managed to hit this limit.

If you're trying to pass binary strings of the image in and out of the function, we recommend you use a storage server (like Appwrite Storage or S3). 

If there's something else, please elaborate, I've very curious how you've managed to get a string that long!

Thanks ❤️

**Comment by MoskalykA** [comment]
> @MoskalykA I'm curious how you've managed to hit this limit.
> 
> If you're trying to pass binary strings of the image in and out of the function, we recommend you use a storage server (like Appwrite Storage or S3).
> 
> If there's something else, please elaborate, I've very curious how you've managed to get a string that long!
> 
> Thanks ❤️

Thank you, for the moment I was passing the image in base64 in the payload that's why there is this error

**Comment by MoskalykA** [comment]
So the payload must also take the image storage provider? Do you have an idea for a name?

**Comment by gewenyu99** [comment]
@MoskalykA You can use something like AWS S3, GCP buckets, imgur, or any other online media storage as a buffer and pass in a URL to the image instead.

When returning, return a link to the buffered image.

Passing large binaries through a function runtime can be an IO and resource hog, which is not great for scalability.

Give this a try and lmk if you have more questions ❤️

**Comment by MoskalykA** [comment]
Hi, I just finished the code, I'm going to make the pull request however in the payload I'm asking for the image link and not its provider, is that correct?

**Comment by abnegate** [comment]
@MoskalykA Yep that sounds good for the `image`! Keep in mind you should still require the compression provider in the payload; supporting both `tinypng` and `krakenio` ☺️
