### ISSUE TITLE
⚡ Write a compressImage() Function using Node

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4120]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `compressImage()` function using **Node**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Perform a lossless compression of an image. Introduce support for `tinypng`, as well as `krakenio`. If nessessary, introduce their secret keys as function variables. Provider to use and image to compress should be received as payload in base64 format, and a compressed version should be returned in base64 format.

Example function payload:

```jsx
{"provider":"tinypng","image":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Successful function response:

```jsx
{"success":true,"image":"iVBORw0KGgoAAAANSUhE...o6Ie+UAAAAASU5CYII="}
```

Error function response:

```jsx
{"success":false,"message":"Input file is not an image."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Node**.
- Knowledge to implement **compressImage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `compressImage()` in `Node/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by 35C4n0r** [comment]
@PineappleIOnic i'm intrested in this issue please assign this issue to me.

**Comment by Meldiron** [comment]
@35C4n0r Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by codespirit7** [comment]
Hey @PineappleIOnic , Can you please assign this issue to me. I already started working on that and like to contribute.

**Comment by tessamero** [comment]
> Hey @PineappleIOnic , Can you please assign this issue to me. I already started working on that and like to contribute.

@codespirit7 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by farhanpro** [comment]
Hello,
I am interested in solving this problem please assign me this task

**Comment by stnguyen90** [comment]
@farhanpro, we're assigning people on a first come first serve basis. If @codespirit7 isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Emiliaaah** [comment]
This issue has been stagnant for 17 day, could it be reassigned to me?

**Comment by stnguyen90** [comment]
@codespirit7, how's your progress on this? Are you still working on it?

**Comment by codespirit7** [comment]
You can reassign to other, I was working but could not figure it out successfully. I will try some other issues.

**Comment by Emiliaaah** [comment]
@stnguyen90 Could I take over then?

**Comment by Meldiron** [comment]
@Emiliaaah Glad to see you this year's Hacktoberfest 😇 Re-assigning to you. Happy hacking! 🎃

**Comment by shivam2562001** [comment]
Hi, @stnguyen90 , can you assign this issue to me ? it looks like no one working on this issue.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
