### ISSUE TITLE
⚡ Write a compressImage() Function using Python

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4122]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `compressImage()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Perform a lossless compression of an image. Introduce support for `tinypng`, as well as `krakenio`. If nessessary, introduce their secret keys as function variables. Provider to use and image to compress should be received as payload in base64 format, and a compressed version should be returned in base64 format.

Example function payload:

```jsx
{"provider":"tinypng","image":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Successful function response:

```jsx
{"success":true,"image":"iVBORw0KGgoAAAANSUhE...o6Ie+UAAAAASU5CYII="}
```

Error function response:

```jsx
{"success":false,"message":"Input file is not an image."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **compressImage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `compressImage()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by tessamero** [comment]
> hi, i would like to work on this

@eigengravy Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by AstroOrbis** [comment]
Hi, I'd like to try my hand at this! Could I be assigned?

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by nabroleonx** [comment]
@tessamero I have already tried to implement this issue, I was able to do so for `tinypng` but `krakenio` doesn't provide a free plan. Do we have to implement both or is one of them enough considering `krakenio` is premium service.

**Comment by stnguyen90** [comment]
@AstroOrbis, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

@anushagupta1312, we're assigning people on a first come first serve basis. If @AstroOrbis isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/). 

@nabroleonx, where are you having trouble? Their [pricing](https://kraken.io/pricing) says:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1477010/193939694-3decde74-69ec-45f2-9c0b-dca56e81e6cc.png">

In addition, the [Sign Up](https://kraken.io/signup) link here:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/1477010/193939768-3b6254cd-663b-40dd-99e5-53ddc670aa1d.png">

let me create an account without a credit card.

**Comment by nabroleonx** [comment]
@stnguyen90 You are right my mind was focused on the pricing cards I must have looked over that detail. Thanks for the reminder.

**Comment by stnguyen90** [comment]
@nabroleonx, I'm glad it's cleared up! Happy hacking! 🎃

**Comment by nabroleonx** [comment]
@stnguyen90 The issue is already assigned but if he/she were to quit, I would love to work on it since I did most of the things already.

**Comment by gewenyu99** [comment]
@nabroleonx If this happens, we'll let you know :)

**Comment by Mushmou** [comment]
@stnguyen90 hello @rubynguyen1510 and I would like to work on this issue as part of Codeday Summer Open Source Experience.

**Comment by Mushmou** [comment]
@stnguyen90 also, we are currently implementing the function. Do we need to introduce both tinypng and krakenio? KrakenIO has not been updated recently, and has errors with pythons latest builds regarding cStringIO.

**Comment by stnguyen90** [comment]
> @stnguyen90 also, we are currently implementing the function. Do we need to introduce both tinypng and krakenio? KrakenIO has not been updated recently, and has errors with pythons latest builds regarding cStringIO.

Yes, it should support krakenIO too. Maybe you can manually make the API calls, then?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
