### ISSUE TITLE
⚡ Write a compressImage() Function using Kotlin

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4126]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `compressImage()` function using **Kotlin**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Perform a lossless compression of an image. Introduce support for `tinypng`, as well as `krakenio`. If nessessary, introduce their secret keys as function variables. Provider to use and image to compress should be received as payload in base64 format, and a compressed version should be returned in base64 format.

Example function payload:

```jsx
{"provider":"tinypng","image":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Successful function response:

```jsx
{"success":true,"image":"iVBORw0KGgoAAAANSUhE...o6Ie+UAAAAASU5CYII="}
```

Error function response:

```jsx
{"success":false,"message":"Input file is not an image."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Kotlin**.
- Knowledge to implement **compressImage** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `compressImage()` in `Kotlin/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aayushpathak11** [comment]
@PineappleIOnic sir,I would like to contribute to this issue

**Comment by tessamero** [comment]
@aayushpathak11 , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by maxslimb** [comment]
Hey, can you assign an issue to more than one people?

**Comment by maxslimb** [comment]
Hey, can you assign this issue to more than one people?

**Comment by abnegate** [comment]
@maxslimb Thanks for the interest, this issue is for one assignee only. You can check out all the issues still available to work on [here](https://github.com/appwrite/appwrite/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee) :grin:

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
