### ISSUE TITLE
⚡ Write a wipeAppwriteBucket() Function using Python

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4128]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `wipeAppwriteBucket()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Delete all files inside an Appwrite Storage bucket. Make sure to introduce `APPWRITE_FUNCTION_PROJECT_ID`, `APPWRITE_FUNCTION_ENDPOINT` and `APPWRITE_FUNCTION_API_KEY` function variables. Bucket ID should be received as payload.

Example function payload:

```jsx
{"bucketId":"profilePictures"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Bucket not found."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **wipeAppwriteBucket** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `wipeAppwriteBucket()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by RedHeadphone** [comment]
I would like to contribute

**Comment by Meldiron** [comment]
@RedHeadphone , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by stnguyen90** [comment]
@anushagupta1312, we're assigning people on a first come first serve basis. If @RedHeadphone isn't able to complete this issue, we'll reassign it accordingly. Also, it looks like you have some issues assigned to you already. Please complete those before requesting assignments on new ones.

**Comment by RedHeadphone** [comment]
yeah, I am working on it

**Comment by RedHeadphone** [comment]
Hey I am getting an error while getting all files in bucket
```
appwrite.exception.AppwriteException: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /v1/storage/buckets/wipeBucket/files (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7801952340>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
the API key has all the scopes yet I am getting error, can you help me with it?

**Comment by Meldiron** [comment]
For example, this is what my LAN IP address looks like:

![CleanShot 2022-10-11 at 10 11 17](https://user-images.githubusercontent.com/19310830/195035160-02b8ea8e-543e-43f2-9bd5-116b6288d66f.png)

**Comment by RedHeadphone** [comment]
nvm it was appwrite installation issue, it's solved now

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
