### ISSUE TITLE
⚡ Write a generateMap() Function using Python

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4133]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateMap()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a screenshot of map location. Introduce support for `openstreets`. If necessary, introduce their secret keys as function variables. Provider to use, latitude and longitude should be received as payload, and a screenshot in base64 format should be returned.

Example function payload:

```jsx
{"provider":"openstreets","lat":41.909986,"lng":12.3959136}
```

Successful function response:

```jsx
{"success":true,"image":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Latitude must be a valid number between -90 and 90."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **generateMap** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateMap()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by partik03** [comment]
@PineappleIOnic I would love to implement this

**Comment by tessamero** [comment]
> @PineappleIOnic I would love to implement this

@partik03 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by partik03** [comment]
@tessamero I do not have the api keys for googlemaps or openstreets so kindly tell me how to actually proceed with this work

**Comment by PineappleIOnic** [comment]
Google Maps requires a GCP account with billing enabled, however looking into openstreets I did find this: https://wiki.openstreetmap.org/wiki/Static_map_images which could be of help to you.

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by stnguyen90** [comment]
@anushagupta1312, we're assigning people on a first come first serve basis. If @partik03 isn't able to complete this issue, we'll reassign it accordingly. Also, it looks like you have some issues assigned to you already. Please complete those before requesting assignments on new ones.

**Comment by Meldiron** [comment]
@partik03 I have updated the description of the issue a little. I have removed the requirement for `googlemaps` provider - you only need to implement OpenStreets. If you already have Google Maps finished, feel free to include it. We removed it as a requirement since some contributors didn't like the fact their API is behind a paywall - they require you to add a credit card to access the API. And that is a valid concern!

Happy hacking 😇
