### ISSUE TITLE
⚡ Write a generateMap() Function using Ruby

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4134]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateMap()` function using **Ruby**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a screenshot of map location. Introduce support for `openstreets`. If necessary, introduce their secret keys as function variables. Provider to use, latitude and longitude should be received as payload, and a screenshot in base64 format should be returned.

Example function payload:

```jsx
{"provider":"openstreets","lat":41.909986,"lng":12.3959136}
```

Successful function response:

```jsx
{"success":true,"image":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Latitude must be a valid number between -90 and 90."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Ruby**.
- Knowledge to implement **generateMap** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateMap()` in `Ruby/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Shivansh-yadav13** [comment]
I would like to contribute

**Comment by Meldiron** [comment]
@Shivansh-yadav13 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Meldiron** [comment]
@Shivansh-yadav13 I have updated the description of the issue a little. I have removed the requirement for `googlemaps` provider - you only need to implement OpenStreets. If you already have Google Maps finished, feel free to include it. We removed it as a requirement since some contributors didn't like the fact their API is behind a paywall - they require you to add a credit card to access the API. And that is a valid concern!

Happy hacking 😇

**Comment by Shivansh-yadav13** [comment]
Hello @Meldiron I'm using https://github.com/WebGents/open_street_map
which gives a responses like postal code, address, road etc..
for screenshot I will have to use https://gitlab.com/Qwertie/osm_tile_grabber
I was not able to find any other which will generate a screenshot.

**Comment by Meldiron** [comment]
@Shivansh-yadav13 Hey there 👋 Looking at the source code of this library, it seems it uses the following endpoint: https://gitlab.com/Qwertie/osm_tile_grabber/-/blob/master/lib/osm_tile_grabber/osm_tile_grabber.rb#L55

Can we try to replicate the logic without using the library? It should be as simple as sending a proper request and parsing the response.

If it seems too complicated, you can use the library.

**Comment by Shivansh-yadav13** [comment]
@Meldiron I have tried implementing it
there is one thing 
open street will only allow if a `User-Agent` header exists so should we also take this from the users? like an env var?
![Screenshot from 2022-10-18 14-36-42](https://user-images.githubusercontent.com/87603425/196387644-af59bb35-fdf4-4897-9525-9487be48bd66.png)

**Comment by Meldiron** [comment]
@Shivansh-yadav13 Great point! 🔥 Yes, let's please create an env var for this.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
