### ISSUE TITLE
⚡ Write a generateMap() Function using Java

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4136]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateMap()` function using **Java**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a screenshot of map location. Introduce support for `openstreets`. If necessary, introduce their secret keys as function variables. Provider to use, latitude and longitude should be received as payload, and a screenshot in base64 format should be returned.

Example function payload:

```jsx
{"provider":"openstreets","lat":41.909986,"lng":12.3959136}
```

Successful function response:

```jsx
{"success":true,"image":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Latitude must be a valid number between -90 and 90."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Java**.
- Knowledge to implement **generateMap** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateMap()` in `Java/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by codercatdev** [comment]
@anushagupta1312 @nik132-eng  I have you on #4080 and #4158 if no one else picks this up we can assign to you as Hacktoberfest progresses. Thanks again for your help 🙏

**Comment by tessamero** [comment]
@anushagupta1312 I'm assigning this to you since it hasn't been picked up in a bit. Enjoy and happy hacking :)

**Comment by Anjali2312-Thombare** [comment]
I would like to solve this issue. Can you please assign me this issue?

**Comment by ShizhanLiu** [comment]
I think I can work on this issue. Can you assign to me?

**Comment by Haimantika** [comment]
> I think I can work on this issue. Can you assign to me?

Hi, are you a part of Code Day mentorship?

**Comment by ShizhanLiu** [comment]
Hello，I am a participant for codeDay Lab intern this summer. I have finished most of my intern tasks, so I think I can take more responsibilities now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Haimantika** [comment]
> Hello，I am a participant for codeDay Lab intern this summer. I have finished most of my intern tasks, so I think I can take more responsibilities now. Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

Okay. Assigning this to you now

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
