### ISSUE TITLE
⚡ Write a translateText() Function using Ruby

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4145]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `translateText()` function using **Ruby**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Translate a text from a source language to a target language. Introduce support for `google`, `aws`, as well as `azure` APIs. If necessary, introduce their secret keys as function variables. Provider to use, source language, target language, and a text to translate should be received as payload, and a translated version should be returned. If no source language is provided, the source language should be automatically figured out (if possible). Please use `iso639-2` format for language codes.

Example function payload:

```jsx
{"provider":"aws","from":"cs","to":"en","text":"Ahoj svet."}
```

Successful function response:

```jsx
{"success":true,"message":"Hello world.","from":"cs"}
```

Error function response:

```jsx
{"success":false,"message":"Target language does not exist in iso639-2 format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Ruby**.
- Knowledge to implement **translateText** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `translateText()` in `Ruby/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by camperjett** [comment]
I Appwrite 😸 I would like to take up this issue!

**Comment by Meldiron** [comment]
@camperjett , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by mohakgupt** [comment]
Hi! I would like to work on this issue

**Comment by gewenyu99** [comment]
@mohakgupt Go ahead!

You may work on this issue 🙏 Happy hacking! 🎃 Thanks for contributing!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
