### ISSUE TITLE
⚡ Write a wipeAppwriteBucket() Function using Swift

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4150]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `wipeAppwriteBucket()` function using **Swift**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Delete all files inside an Appwrite Storage bucket. Make sure to introduce `APPWRITE_FUNCTION_PROJECT_ID`, `APPWRITE_FUNCTION_ENDPOINT` and `APPWRITE_FUNCTION_API_KEY` function variables. Bucket ID should be received as payload.

Example function payload:

```jsx
{"bucketId":"profilePictures"}
```

Successful function response:

```jsx
{"success":true}
```

Error function response:

```jsx
{"success":false,"message":"Bucket not found."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Swift**.
- Knowledge to implement **wipeAppwriteBucket** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `wipeAppwriteBucket()` in `Swift/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by prathamesh10346** [comment]
can you assign me this task?

**Comment by gewenyu99** [comment]
@prathamesh10346, thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
