### ISSUE TITLE
⚡ Write a textToSpeech() Function using Dart

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4151]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `textToSpeech()` function using **Dart**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate spoken audio from a written text. Introduce support for `google`, `aws`, as well as `azure` APIs. If necessary, introduce their secret keys as function variables. Provider to use, language, and a text to convert into audio should be received as payload, and an audio version should be returned in base64 format. If no language is provided, the language should be automatically figured out (if possible). Please use `iso639-2` format for language codes.

Example function payload:

```jsx
{"provider":"aws","language":"en","text":"Hello world."}
```

Successful function response:

```jsx
{"success":true,"audio":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Target language does not exist in iso639-2 format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Dart**.
- Knowledge to implement **textToSpeech** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `textToSpeech()` in `Dart/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by devtayade** [comment]
can you please assign me this task ?

**Comment by codercatdev** [comment]
@devtayade , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by devtayade** [comment]
@codercatdev thank you so much, Update you soon

**Comment by TomerPacific** [comment]
Hey @codercatdev , let me know if @devtayade doesn't get to finishing this. I'd be happy to help out.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
