### ISSUE TITLE
⚡ Write a textToSpeech() Function using Python

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4155]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `textToSpeech()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate spoken audio from a written text. Introduce support for `google`, `aws`, as well as `azure` APIs. If necessary, introduce their secret keys as function variables. Provider to use, language, and a text to convert into audio should be received as payload, and an audio version should be returned in base64 format. If no language is provided, the language should be automatically figured out (if possible). Please use `iso639-2` format for language codes.

Example function payload:

```jsx
{"provider":"aws","language":"en","text":"Hello world."}
```

Successful function response:

```jsx
{"success":true,"audio":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Target language does not exist in iso639-2 format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **textToSpeech** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `textToSpeech()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by zadilkhwaja** [comment]
I'm interested pls assign!

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by zadilkhwaja** [comment]
> Hey I would like to work on this issue. Can you please assign me this?

Hi I've already been assigned this issue. Please checkout there are a lot of other issues open. Thanks!

**Comment by zadilkhwaja** [comment]
> @zadilkhwaja , thanks for your interest! 🙏 Happy hacking! 🎃

Thanks I'm working on it!

**Comment by anushagupta1312** [comment]
> > Hey I would like to work on this issue. Can you please assign me this?
> 
> Hi I've already been assigned this issue. Please checkout there are a lot of other issues open. Thanks!

Sure

**Comment by shashwatSrivastava-official** [comment]
Hey! Interested in the issue, please assign!
Thanks (:

**Comment by Meldiron** [comment]
@shashwatSrivastava-official , we're assigning people on a first come first serve basis. If @zadilkhwaja  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by letsintegreat** [comment]
Hey! As it has already been almost 3 weeks since this issue was assigned and it is still not solved, I would like to solve this issue.

**Comment by stnguyen90** [comment]
@zadilkhwaja how's your progress on this? Would you please let us know so we can reassign this if needed?

**Comment by shashwatSrivastava-official** [comment]
Hey!
Do go ahead and assign this to someone else.
Thanks for considering (:

**Comment by Player256** [comment]
@stnguyen90 can u assign me this issue?

**Comment by Mushmou** [comment]
Hello! can you please assign me this issue. I would like to work on this issue as part of Code Day Summer Experience.

**Comment by rubynguyen1510** [comment]
Hello, @Mushmou and I work as a team in Code Day. We already submitted a pull request for issue 4122 and would love to continue with this issue.

**Comment by stnguyen90** [comment]
@Player256, are you still interested in working on this issue?

**Comment by Mushmou** [comment]
@stnguyen90 Hello, we are finished with this function Text To Speech #4155 and we are ready to send a pull request to open runtimes. But my partner and I @rubynguyen1510 are not assigned this issue. We would like to be assigned to this issue and merge our current code.

**Comment by Mushmou** [comment]
@stnguyen90 we are also with CodeDayLabs as interns.

**Comment by Player256** [comment]
> @Player256, are you still interested in working on this issue?
Thanks for asking. I am currently tied in other works, so you can assign other people.

**Comment by stnguyen90** [comment]
@Mushmou, assigned! Thanks for your interest! 🙏🏼

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
