### ISSUE TITLE
⚡ Write a textToSpeech() Function using Kotlin

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4159]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `textToSpeech()` function using **Kotlin**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate spoken audio from a written text. Introduce support for `google`, `aws`, as well as `azure` APIs. If necessary, introduce their secret keys as function variables. Provider to use, language, and a text to convert into audio should be received as payload, and an audio version should be returned in base64 format. If no language is provided, the language should be automatically figured out (if possible). Please use `iso639-2` format for language codes.

Example function payload:

```jsx
{"provider":"aws","language":"en","text":"Hello world."}
```

Successful function response:

```jsx
{"success":true,"audio":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Error function response:

```jsx
{"success":false,"message":"Target language does not exist in iso639-2 format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Kotlin**.
- Knowledge to implement **textToSpeech** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `textToSpeech()` in `Kotlin/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by yokwejuste** [comment]
This seems to be a duplicate issue, 


Can you assign it to me please

**Comment by Meldiron** [comment]
@yokwejuste Hey there 👋 What issue does this seem to be a duplicate of?

**Comment by tessamero** [comment]
@yokwejuste I think it sounds similar to an old issue https://github.com/appwrite/appwrite/issues/1916 but i think this is specific to Kotlin. I will assign it to you now :) You may work on this issue 🙏 Happy hacking! 🎃

**Comment by letsintegreat** [comment]
Hey! As it has already been 2 weeks since this issue was assigned and it is still not solved, I would like to solve this issue.

**Comment by stnguyen90** [comment]
@yokwejuste how's your progress on this? Would you please let us know so we can reassign this if needed?

**Comment by yokwejuste** [comment]
Working on it

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
