### ISSUE TITLE
⚡ Write a speechToText() Function using Dart

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4162]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `speechToText()` function using **Dart**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a written text from spoken audio. Introduce support for `google`, `aws`, as well as `azure` APIs. If necessary, introduce their secret keys as function variables. Provider to use, language, and a base64 of audio to convert into the text should be received as payload, and a written transcribe should be returned. If no language is provided, the language should be automatically figured out (if possible). Please use `iso639-2` format for language codes.

Example function payload:

```jsx
{"provider":"aws","language":"en","audio":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Successful function response:

```jsx
{"success":true,"text":"Hello world."}
```

Error function response:

```jsx
{"success":false,"message":"Target language does not exist in iso639-2 format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Dart**.
- Knowledge to implement **speechToText** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `speechToText()` in `Dart/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by InfiniteVerma** [comment]
I'd like to work on this.

**Comment by codercatdev** [comment]
@InfiniteVerma , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by bhattabhi013** [comment]
@InfiniteVerma, are you still working on it?
If not, can I work on this?

**Comment by InfiniteVerma** [comment]
Hey @bhattabhi013, still working on it.

**Comment by bhattabhi013** [comment]
Sure @InfiniteVerma, let me know if you need some help.

**Comment by letsintegreat** [comment]
Hey! As it has already been almost 3 weeks since this issue was assigned and it is still not solved, I would like to solve this issue.

**Comment by stnguyen90** [comment]
@InfiniteVerma how's your progress on this? Would you please let us know so we can reassign this if needed?

**Comment by InfiniteVerma** [comment]
@stnguyen90 I'm still working on it. Will let you know if I would like this to be reassigned.

**Comment by InfiniteVerma** [comment]
Hey @stnguyen90, I'm struggling to call the google APIs required for this feature. Please reassign this issue to someone else.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
