### ISSUE TITLE
⚡ Write a speechToText() Function using Node

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4164]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `speechToText()` function using **Node**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a written text from spoken audio. Introduce support for `google`, `aws`, as well as `azure` APIs. If necessary, introduce their secret keys as function variables. Provider to use, language, and a base64 of audio to convert into the text should be received as payload, and a written transcribe should be returned. If no language is provided, the language should be automatically figured out (if possible). Please use `iso639-2` format for language codes.

Example function payload:

```jsx
{"provider":"aws","language":"en","audio":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Successful function response:

```jsx
{"success":true,"text":"Hello world."}
```

Error function response:

```jsx
{"success":false,"message":"Target language does not exist in iso639-2 format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Node**.
- Knowledge to implement **speechToText** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `speechToText()` in `Node/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by 35C4n0r** [comment]
@PineappleIOnic i'm intrested in this issue, please assign this issue to me.

**Comment by Meldiron** [comment]
@35C4n0r , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by rohit162** [comment]
HI @PineappleIOnic 
Can u please me this task I wanna work on it.

Thanks and Regards

**Comment by Meldiron** [comment]
@rohit162 , we're assigning people on a first come first serve basis. If @35C4n0r  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by GenMech** [comment]
Hi @PineappleIOnic, Can you pls assign this issue to me. I want to work on this issue

**Comment by stnguyen90** [comment]
@GenMech Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by GenMech** [comment]
@stnguyen90 Thanks for assigning it to me!

**Comment by GenMech** [comment]
@stnguyen90 Sorry I am taking some time doing this due to some of my college stuff but I will work on this issue by this week.

**Comment by stnguyen90** [comment]
@GenMech are you still working on this or should we unassign you?

**Comment by GenMech** [comment]
> @GenMech are you still working on this or should we unassign you?

I am working on this, superb busy with something which was sudden, I will take 2 more days only, If i was not able to do it by friday, I will unassign myself. And take a fresh issue to work on.
Sorry for this much delay!

**Comment by stnguyen90** [comment]
@GenMech, no worries! You can take your time! Just let us know if you no longer want to work on it so we can unassign you.

**Comment by GenMech** [comment]
@stnguyen90 Sorry But I am not able to give required time for the issue.

**Comment by shivam2562001** [comment]
Hi @stnguyen90  , Can you pls assign this issue to me. I want to work on this issue.

**Comment by codercatdev** [comment]
Hi @shivam2562001 thanks for taking a look, I have assigned it to you.

**Comment by shivam2562001** [comment]
ok I will start working.

@codercatdev I have recently raised a pr for this issue : https://github.com/appwrite/appwrite/issues/3954
can you pls take a look?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
