### ISSUE TITLE
⚡ Write a speechToText() Function using Python

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4166]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `speechToText()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a written text from spoken audio. Introduce support for `google`, `aws`, as well as `azure` APIs. If necessary, introduce their secret keys as function variables. Provider to use, language, and a base64 of audio to convert into the text should be received as payload, and a written transcribe should be returned. If no language is provided, the language should be automatically figured out (if possible). Please use `iso639-2` format for language codes.

Example function payload:

```jsx
{"provider":"aws","language":"en","audio":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Successful function response:

```jsx
{"success":true,"text":"Hello world."}
```

Error function response:

```jsx
{"success":false,"message":"Target language does not exist in iso639-2 format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **speechToText** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `speechToText()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by nabroleonx** [comment]
I will work on this issue, can you assign it to me?

**Comment by Meldiron** [comment]
@nabroleonx , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by PineappleIOnic** [comment]
@nabroleonx Do you no longer want to do this issue?

**Comment by nabroleonx** [comment]
@PineappleIOnic I tried to make it work and I was able to do it with google speech recognition using speech recognition API, but I couldn't get API keys for azure and aws that is why I removed the assignment. I am still trying to solve the issue, but I didn't want to stop anyone from contributing in case I couldn't get the API keys or anything related to that. That's why.

**Comment by PineappleIOnic** [comment]
Alright, No Worries. Thank you for clearing that up for us :)

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by rahulnegi20** [comment]
I am interested in this, can I get assigned?

**Comment by sahil2311sharma** [comment]
I will work on this issue, can you assign it to me?

**Comment by codercatdev** [comment]
@anushagupta1312 I have you on #4158 so I am going to jump to @rahulnegi20 

@rahulnegi20 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by rahulnegi20** [comment]
Hi @codercatdev @PineappleIOnic, 

I have a doubt regarding the encoding format of the audio, will it be the same always or not? 
If yes can you please share the **encoding, sample_heartz, and audio channel**?

Thanks

**Comment by Meldiron** [comment]
@rahulnegi20 Hey there 👋 Are these parameters required, or optional? Ideally, we would support any kind of MP3 file and do our best to extract text from it. If this is information that is required by Google API to do the request, feel free to add these as parameters in `payload`.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
