### ISSUE TITLE
⚡ Write a speechToText() Function using Swift

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4168]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `speechToText()` function using **Swift**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a written text from spoken audio. Introduce support for `google`, `aws`, as well as `azure` APIs. If necessary, introduce their secret keys as function variables. Provider to use, language, and a base64 of audio to convert into the text should be received as payload, and a written transcribe should be returned. If no language is provided, the language should be automatically figured out (if possible). Please use `iso639-2` format for language codes.

Example function payload:

```jsx
{"provider":"aws","language":"en","audio":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Successful function response:

```jsx
{"success":true,"text":"Hello world."}
```

Error function response:

```jsx
{"success":false,"message":"Target language does not exist in iso639-2 format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Swift**.
- Knowledge to implement **speechToText** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `speechToText()` in `Swift/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by the-kaushal-agrawal** [comment]
pls assign this issue to me

**Comment by PineappleIOnic** [comment]
@the-kaushal-agrawal thanks for your interest! 🙏 Happy hacking!

**Comment by akarsh-jain-790** [comment]
@the-kaushal-agrawal are you still working on it ? If not @PineappleIOnic can u assign this issue to me?

**Comment by Meldiron** [comment]
@the-kaushal-agrawal Hey there 👋 Are you still working on this issue? No need to rush, you have a whole month 😇 I just need to confirm with you if you are still active on this assignment.

**Comment by the-kaushal-agrawal** [comment]
Yes

**Comment by Meldiron** [comment]
Thanks for confirming 🙏 @akarsh-jain-790 I would recommend you to look at our [website](https://hacktoberfest.appwrite.io/), there are many more unassigned issues yo could take on 😇

**Comment by stnguyen90** [comment]
@the-kaushal-agrawal are you still working on this or should we unassign you?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
