### ISSUE TITLE
⚡ Write a speechToText() Function using Java

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4169]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `speechToText()` function using **Java**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a written text from spoken audio. Introduce support for `google`, `aws`, as well as `azure` APIs. If necessary, introduce their secret keys as function variables. Provider to use, language, and a base64 of audio to convert into the text should be received as payload, and a written transcribe should be returned. If no language is provided, the language should be automatically figured out (if possible). Please use `iso639-2` format for language codes.

Example function payload:

```jsx
{"provider":"aws","language":"en","audio":"iVBORw0KGgoAAAANSUhEUgAAAaQAAALiCAY...QoH9hbkTPQAAAABJRU5ErkJggg=="}
```

Successful function response:

```jsx
{"success":true,"text":"Hello world."}
```

Error function response:

```jsx
{"success":false,"message":"Target language does not exist in iso639-2 format."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Java**.
- Knowledge to implement **speechToText** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `speechToText()` in `Java/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by AniketTewari** [comment]
Hello sir, I have completed the task...kindly assign to me this issue.

**Comment by codercatdev** [comment]
@devtayade , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by codercatdev** [comment]
@devtayade I missed that @AniketTewari already did the PR, would you mind if we assignee you to another issue?

@AniketTewari thank you for jumping in so quickly.

**Comment by codercatdev** [comment]
@devtayade I gave you #4151 as requested ❤️

**Comment by SanifKandel** [comment]
Hey @codercatdev , I couldn't find any issue remain to be assigned . Can you check and assign me with any of the issue if any single person is working on two issues ?

**Comment by Meldiron** [comment]
@SanifKandel Hey there 👋 We have many yet unassigned issues, you can find the list here: https://github.com/appwrite/appwrite/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee

Feel free to find one that you would enjoy the most, and request to be assigned 😇

**Comment by Vishrut19** [comment]
Hey @AniketTewari I would like to help/contribute ? Can I do it ?

**Comment by AniketTewari** [comment]
@Vishrut19 The Task is already completed, just waiting for the PR getting merged....
We can work together on any other issue if you want.

**Comment by Vishrut19** [comment]
yes @AniketTewari Please let me know that we can connect and do some work together
This is my Discord Id - Vishrut19#8641

**Comment by PineappleIOnic** [comment]
@AniketTewari, let us know if you'd like to continue this issue or if we should reassign it based on the comment from your PR.

**Comment by letsintegreat** [comment]
Hey! As it has already been almost 3 weeks since this issue was assigned and it is still not solved, I would like to solve this issue.

**Comment by stnguyen90** [comment]
@anushagupta1312, @nik132-eng, @SanifKandel, @Vishrut19, or @letsintegreat, would you like to pick this up?

**Comment by SanifKandel** [comment]
> @anushagupta1312, @nik132-eng, @SanifKandel, @Vishrut19, or @letsintegreat, would you like to pick this up?

If that's fine if I take it over ?

**Comment by Vishrut19** [comment]
I would like to give it a try and if someone else wants we can work together if that's okay with you @stnguyen90

**Comment by stnguyen90** [comment]
Going in order, @SanifKandel is up next in the queue! Reassigning!

**Comment by stnguyen90** [comment]
@SanifKandel are you still working on this or should we unassign you?

**Comment by SanifKandel** [comment]
Hey @stnguyen90 , Sorry for the delay. I am on it and will complete it as soon as possible.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
