### ISSUE TITLE
⚡ Write a sendHTTPRequest() Function using Dart

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4173]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendHTTPRequest()` function using **Dart**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Send a HTTP request. All configurations should be received as a payload. Supported options must be `method`, `url`, `body`, and `headers`. Status code, response body, and response headers should be returned. No function variables are necessary.

Example function payload:

```jsx
{"url":"https://demo.appwrite.io/v1/locale/countries/eu","method":"GET","headers":{"x-client-version":"1.0.0"},"body":""}
```

Successful function response:

```jsx
{"success":true,"response":{"headers":{},"code":200,"body":"{\"total\":27,\"countries\":[]}"}}
```

Error function response:

```jsx
{"success":false,"message":"URL could not be reached."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Dart**.
- Knowledge to implement **sendHTTPRequest** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendHTTPRequest()` in `Dart/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by sarkartanmay393** [comment]
@PineappleIOnic Hello Pineapple, I would like to work on it.

**Comment by Meldiron** [comment]
@sarkartanmay393 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by sarkartanmay393** [comment]
@Meldiron Hey Meldiron, Kindly look at my screenshot. 
<img width="1440" alt="Screenshot 2022-10-06 at 4 30 11 PM" src="https://user-images.githubusercontent.com/84321236/194296654-346dd803-c4cb-4ace-aaa7-4bf576f5556b.png">

I have created `lib/main.dart`, `pubspec.yaml` and `README.md`.
Now the problem is what to do next ?

And I having a serious issue - 
Appwrite is running on Docker and I am using appwrite-cli
When I command `appwrite init function`
It asks for **name** and **runtime**.
Which runtime to select for Dart function ?
And when I select any four of them, it show `Server error`
And after that, if I visit `localhost:80`, it also stops working and shows this message 
`{"message":"Error: Server Error","code":500,"version":"1.0.1"}`

**Kindly show me a path to proceed forward.**

**Comment by PineappleIOnic** [comment]
Please send us your logs by performing `docker compose logs appwrite` in the directory where you first installed Appwrite.

**Comment by Meldiron** [comment]
@sarkartanmay393 Amazing, glad to hear that 🤩 Can you please write a comment here with a link to the PR? That way, it's easier for us to do proper checks during the review process.

**Comment by sarkartanmay393** [comment]
Opened PR for this issue: [open-runtimes/examples/pull/58](https://github.com/open-runtimes/examples/pull/58)

**Comment by Yavnik** [comment]
@PineappleIOnic Since this PR isn't resolved yet, can I work on this?

**Comment by Mithran-04** [comment]
I would like to work on this issue and would be glad if it is assigned to me.

**Comment by stnguyen90** [comment]
@Yavnik, are you still interested in working on this?

@Mithran-04, if @Yavnik doesn't work on this, are you still interested?

**Comment by Mithran-04** [comment]
Yes I am interested to work on this issue.

**Comment by Yavnik** [comment]
Hi @stnguyen90,

Yes, I would like to work on this.

**Comment by stnguyen90** [comment]
@Yavnik, sorry for the delay! I've assigned the issue to you. Please let me know if you won't be able to work on it.

**Comment by Yavnik** [comment]
@stnguyen90 Opened PR for this issue: https://github.com/open-runtimes/examples/pull/150

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
