### ISSUE TITLE
⚡ Write a sendHTTPRequest() Function using PHP

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4176]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendHTTPRequest()` function using **PHP**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Send a HTTP request. All configurations should be received as a payload. Supported options must be `method`, `url`, `body`, and `headers`. Status code, response body, and response headers should be returned. No function variables are necessary.

Example function payload:

```jsx
{"url":"https://demo.appwrite.io/v1/locale/countries/eu","method":"GET","headers":{"x-client-version":"1.0.0"},"body":""}
```

Successful function response:

```jsx
{"success":true,"response":{"headers":{},"code":200,"body":"{\"total\":27,\"countries\":[]}"}}
```

Error function response:

```jsx
{"success":false,"message":"URL could not be reached."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **PHP**.
- Knowledge to implement **sendHTTPRequest** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendHTTPRequest()` in `PHP/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by PineappleIOnic** [comment]
@Yordaniss, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Yordaniss** [comment]
open-runtimes/examples#38

**Comment by tessamero** [comment]
@Yordaniss Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by codercatdev** [comment]
@appwrite/owners please review PR for merge.
