### ISSUE TITLE
⚡ Write a sendHTTPRequest() Function using Python

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4177]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendHTTPRequest()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Send a HTTP request. All configurations should be received as a payload. Supported options must be `method`, `url`, `body`, and `headers`. Status code, response body, and response headers should be returned. No function variables are necessary.

Example function payload:

```jsx
{"url":"https://demo.appwrite.io/v1/locale/countries/eu","method":"GET","headers":{"x-client-version":"1.0.0"},"body":""}
```

Successful function response:

```jsx
{"success":true,"response":{"headers":{},"code":200,"body":"{\"total\":27,\"countries\":[]}"}}
```

Error function response:

```jsx
{"success":false,"message":"URL could not be reached."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **sendHTTPRequest** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendHTTPRequest()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by ppap1771** [comment]
Hey I would love to work on this issue.

**Comment by Meldiron** [comment]
@dejmedus , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Meldiron** [comment]
@ppap1771 , we're assigning people on a first come first serve basis. If @XYZ isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by ppap1771** [comment]
Ok sure.

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by codercatdev** [comment]
@anushagupta1312 , we are assigning people on a first come first serve basis. If @dejmedus  isn't able to complete this issue, we will reassign accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by tessamero** [comment]
@dejmedus Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by stnguyen90** [comment]
@VanmoelJr We're assigning people on a first come first serve basis. You can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).
