### ISSUE TITLE
⚡ Write a sendHTTPRequest() Function using Swift

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4179]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendHTTPRequest()` function using **Swift**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Send a HTTP request. All configurations should be received as a payload. Supported options must be `method`, `url`, `body`, and `headers`. Status code, response body, and response headers should be returned. No function variables are necessary.

Example function payload:

```jsx
{"url":"https://demo.appwrite.io/v1/locale/countries/eu","method":"GET","headers":{"x-client-version":"1.0.0"},"body":""}
```

Successful function response:

```jsx
{"success":true,"response":{"headers":{},"code":200,"body":"{\"total\":27,\"countries\":[]}"}}
```

Error function response:

```jsx
{"success":false,"message":"URL could not be reached."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Swift**.
- Knowledge to implement **sendHTTPRequest** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendHTTPRequest()` in `Swift/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Anudeep-313** [comment]
I can help in writing a sendHTTPRequest() Function using Swift.
- Assign this issue to me.

**Comment by codercatdev** [comment]
@Anudeep-313, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by the-kaushal-agrawal** [comment]
@codercatdev pls assign this issue to me

**Comment by PineappleIOnic** [comment]
@the-kaushal-agrawal, we're assigning people on a first come first serve basis. If [@czlucius](https://github.com/czlucius) isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by ks129** [comment]
Can I please get assigned to this?

**Comment by stnguyen90** [comment]
@the-kaushal-agrawal are you still interested in working on this? If not, I'll assign to @ks129.

**Comment by stnguyen90** [comment]
@ks129 Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by stnguyen90** [comment]
@ks129 are you still working on this or should we unassign you?

**Comment by ks129** [comment]
Sorry, looks like I don't have time to finish it anymore. School has began again.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
