### ISSUE TITLE
⚡ Write a sendHTTPRequest() Function using .NET

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4182]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `sendHTTPRequest()` function using **.NET**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Send a HTTP request. All configurations should be received as a payload. Supported options must be `method`, `url`, `body`, and `headers`. Status code, response body, and response headers should be returned. No function variables are necessary.

Example function payload:

```jsx
{"url":"https://demo.appwrite.io/v1/locale/countries/eu","method":"GET","headers":{"x-client-version":"1.0.0"},"body":""}
```

Successful function response:

```jsx
{"success":true,"response":{"headers":{},"code":200,"body":"{\"total\":27,\"countries\":[]}"}}
```

Error function response:

```jsx
{"success":false,"message":"URL could not be reached."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **.NET**.
- Knowledge to implement **sendHTTPRequest** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `sendHTTPRequest()` in `.NET/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by NiX3r** [comment]
Could you please assign this to me?

**Comment by Meldiron** [comment]
@NiX3r , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by NiX3r** [comment]
Thanks. One more question. Should be there four basic methods such as GET, PUT, UPDATE and DELETE? Or should it contains more of them?

**Comment by Meldiron** [comment]
@NiX3r I would say let's try to support all HTTP methods: GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD.

**Comment by NiX3r** [comment]
Done. Here's my pull request
https://github.com/open-runtimes/examples/pull/45

**Comment by NiX3r** [comment]
I'm done here. Waiting for your approved 👍
https://github.com/open-runtimes/examples/pull/51

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
