### ISSUE TITLE
⚡ Write a generateShortUrl() Function using Dart

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4184]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateShortUrl()` function using **Dart**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a short URL. Introduce support for `bitly` and `tinyurl` APIs. If necessary, introduce their secret keys as function variables. URL and provider to use must be provided as payload, and shortened URL should be returned.

Example function payload:

```jsx
{"provider":"bitly","url":"https://google.com/"}
```

Successful function response:

```jsx
{"success":true,"url":"https://bit.ly/3y3HDkC"}
```

Error function response:

```jsx
{"success":false,"message":"Entered URL is not a valid URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Dart**.
- Knowledge to implement **generateShortUrl** function.
- Experience with **Docker**.

### ✅ Task Summary

- [x]  Ask to be assigned to the issue.
- [x]  Implement function `generateShortUrl()` in `Dart/` folder.
- [x]  Manually execute the newly implemented function to ensure it works.
- [x]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by letsintegreat** [comment]
Hey! I would like to work on this issue. Could you please assign it to me?

**Comment by xinkin** [comment]
Hey, I have been learning Flutter recently, have experience in Dart and Docker, would love to contribute here.
Can I be assigned to this.

**Comment by Meldiron** [comment]
@letsintegreat , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Meldiron** [comment]
@xinkin , we're assigning people on a first come first serve basis. If @letsintegreat isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by letsintegreat** [comment]
@Meldiron I am done with bitly and tinyurl parts. For the owly part, it seems its API is not free to use, as mentioned here in the docs:
![image](https://user-images.githubusercontent.com/37345795/193785488-dc1d7ac4-b066-4d44-8d77-eae76cec090b.png)

Should I skip it?

**Comment by Meldiron** [comment]
@letsintegreat We investigated and noticed this provider is oriented toward businesses. Due to this, it looks like they don't have a free plan that you could test your implementation on.

I will update the issue description. Please ignore Ow.ly, you don't need to implement this adapter.

**Comment by letsintegreat** [comment]
@Meldiron Thanks for the update. I have already opened a PR implementing `bitly` and `tinyurl`. Kindly review whenever time permits.

**Comment by codercatdev** [comment]
@letsintegreat issue https://github.com/open-runtimes/examples/pull/34 looks like it solves all of this, thank you so much!!

**Comment by letsintegreat** [comment]
@codercatdev Sure! I am looking forward to contributing to more of those issues.

Also, I think there has been a mistake - you were supposed to add the `hacktoberfest-accepted` label to the [PR}(https://github.com/open-runtimes/examples/pull/34) instead of the issue. That is how hacktoberfest detects that PR has been accepted.

**Comment by codercatdev** [comment]
@letsintegreat thank you, too many tabs open today :D
