### ISSUE TITLE
⚡ Write a generateShortUrl() Function using Node

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4186]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateShortUrl()` function using **Node**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a short URL. Introduce support for `bitly` and `tinyurl` APIs. If necessary, introduce their secret keys as function variables. URL and provider to use must be provided as payload, and shortened URL should be returned.

Example function payload:

```jsx
{"provider":"bitly","url":"https://google.com/"}
```

Successful function response:

```jsx
{"success":true,"url":"https://bit.ly/3y3HDkC"}
```

Error function response:

```jsx
{"success":false,"message":"Entered URL is not a valid URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Node**.
- Knowledge to implement **generateShortUrl** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateShortUrl()` in `Node/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by MoskalykA** [comment]
> @MoskalykA thanks for your interest! 🙏 Happy hacking! 🎃

I can't find the owly provider, do you have a link ?

**Comment by Abhishek-thakur1** [comment]
Hi! i would like to implement that

**Comment by Meldiron** [comment]
@MoskalykA  Hey there 👋 Here is a link to the API: https://developer.hootsuite.com/docs/owly-api-reference

Please let me know if there is anything else I can help with.

**Comment by Meldiron** [comment]
@Abhishek-thakur1 , we're assigning people on a first come first serve basis. If @MoskalykA isn't able to complete this issue, well reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by MoskalykA** [comment]
> @MoskalykA Hey there 👋 Here is a link to the API: https://developer.hootsuite.com/docs/owly-api-reference
> 
> Please let me know if there is anything else I can help with.

I have finished implementing the first two providers however I don't understand how to get an ow.ly api key?

**Comment by Meldiron** [comment]
@MoskalykA We investigated and noticed this provider is oriented toward businesses. Due to this, it looks like they don't have a free plan that you could test your implementation on.

I will update the issue description. Please ignore Ow.ly, you don't need to implement this adapter.
