### ISSUE TITLE
⚡ Write a generateShortUrl() Function using PHP

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4187]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateShortUrl()` function using **PHP**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a short URL. Introduce support for `bitly` and `tinyurl` APIs. If necessary, introduce their secret keys as function variables. URL and provider to use must be provided as payload, and shortened URL should be returned.

Example function payload:

```jsx
{"provider":"bitly","url":"https://google.com/"}
```

Successful function response:

```jsx
{"success":true,"url":"https://bit.ly/3y3HDkC"}
```

Error function response:

```jsx
{"success":false,"message":"Entered URL is not a valid URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **PHP**.
- Knowledge to implement **generateShortUrl** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateShortUrl()` in `PHP/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by TheSylwio** [comment]
Hello 👋 I would like to be assigned to this issue 😉

**Comment by TheSylwio** [comment]
@PineappleIOnic 
Is it necessary to implement the `owly` service support? I'm not sure if I want to provide my personal credit card details to create an Owly account.

**Comment by tessamero** [comment]
> Hello @PineappleIOnic 👋 I would like to be assigned to this issue 😉

@TheSylwio , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Meldiron** [comment]
I updated the issue description. We decided to remove `ow.ly` from the list of providers you need to support. Please only work on `bitly` and `tinyurl` support.

**Comment by TheSylwio** [comment]
Pull Request is waiting to be reviewed https://github.com/open-runtimes/examples/pull/36. Is anyone able to take up this? 🤔

**Comment by Meldiron** [comment]
@TheSylwio Ooof we must have missed this PR 😔 I am putting it on my priority list.
