### ISSUE TITLE
⚡ Write a generateShortUrl() Function using Python

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4188]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateShortUrl()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a short URL. Introduce support for `bitly` and `tinyurl` APIs. If necessary, introduce their secret keys as function variables. URL and provider to use must be provided as payload, and shortened URL should be returned.

Example function payload:

```jsx
{"provider":"bitly","url":"https://google.com/"}
```

Successful function response:

```jsx
{"success":true,"url":"https://bit.ly/3y3HDkC"}
```

Error function response:

```jsx
{"success":false,"message":"Entered URL is not a valid URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **generateShortUrl** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateShortUrl()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by 35C4n0r** [comment]
@PineappleIOnic i'm intrested in this can you please assign this issue to me.

**Comment by PineappleIOnic** [comment]
@35C4n0r, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Meldiron** [comment]
I updated the issue description. We decided to remove `ow.ly` from the list of providers you need to support. Please only work on `bitly` and `tinyurl` support.

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by FarhanAliRaza** [comment]
Please assign this to me.

**Comment by codercatdev** [comment]
@anushagupta1312 @FarhanAliRaza, we are assigning people on a first come first serve basis. If @35C4n0r isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by 35C4n0r** [comment]
> I updated the issue description. We decided to remove `ow.ly` from the list of providers you need to support. Please only work on `bitly` and `tinyurl` support.

Sure.

**Comment by VanmoelJr** [comment]
Hi, I would like to work on this. Can you assign this to me?

**Comment by stnguyen90** [comment]
@VanmoelJr We're assigning people on a first come first serve basis. You can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).
