### ISSUE TITLE
⚡ Write a generateShortUrl() Function using Java

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4191]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateShortUrl()` function using **Java**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a short URL. Introduce support for `bitly` and `tinyurl` APIs. If necessary, introduce their secret keys as function variables. URL and provider to use must be provided as payload, and shortened URL should be returned.

Example function payload:

```jsx
{"provider":"bitly","url":"https://google.com/"}
```

Successful function response:

```jsx
{"success":true,"url":"https://bit.ly/3y3HDkC"}
```

Error function response:

```jsx
{"success":false,"message":"Entered URL is not a valid URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Java**.
- Knowledge to implement **generateShortUrl** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateShortUrl()` in `Java/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Pooja444** [comment]
@PineappleIOnic I would like to work on this issue, can it be assigned to me?

**Comment by stnguyen90** [comment]
@Pooja444, thanks for your interest! 🙏 Happy hacking!

> The open-runtime repository has no existing Java/ folder. Should I create one?

You can go ahead and make a `java` folder (convention is very important when you're jumping into an existing codebase. If you look at existing folders, you'll see they're all lowercase). 

> Since there are no Java example templates in the open-runtimes/examples I am referring to these files - Example and Usage, is that correct?

Yes you can start with those templates. Nice resourcefulness looking through for samples!

**Comment by Meldiron** [comment]
I updated the issue description. We decided to remove `ow.ly` from the list of providers you need to support. Please only work on `bitly` and `tinyurl` support.

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by ranodeepbanerjee** [comment]
Please assign this to me. Thanks

**Comment by Pooja444** [comment]
@ranodeepbanerjee @anushagupta1312 I was already assigned this issue yesterday and have started working on it

**Comment by Pooja444** [comment]
@stnguyen90 @Meldiron thanks again for your response. I have submitted a pull request for this issue - https://github.com/open-runtimes/examples/pull/42

**Comment by Meldiron** [comment]
@anushagupta1312 @ranodeepbanerjee , we're assigning people on a first come first serve basis. If @Pooja444  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Vishrut19** [comment]
Hi @Pooja444 do you need any help I can try to contribute/help you?

**Comment by Pooja444** [comment]
Hello @Vishrut19 thanks for offering! I have completed working on this and have raised a PR which was reviewed by @Meldiron at the PR review party last week. I will let you know if I need any help though, thanks again!
