### ISSUE TITLE
⚡ Write a generateShortUrl() Function using Kotlin

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4192]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateShortUrl()` function using **Kotlin**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a short URL. Introduce support for `bitly` and `tinyurl` APIs. If necessary, introduce their secret keys as function variables. URL and provider to use must be provided as payload, and shortened URL should be returned.

Example function payload:

```jsx
{"provider":"bitly","url":"https://google.com/"}
```

Successful function response:

```jsx
{"success":true,"url":"https://bit.ly/3y3HDkC"}
```

Error function response:

```jsx
{"success":false,"message":"Entered URL is not a valid URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Kotlin**.
- Knowledge to implement **generateShortUrl** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `generateShortUrl()` in `Kotlin/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Meldiron** [comment]
@PGautam27 , thanks for your interest! 🙏 Happy hacking! 🎃

The easiest way to run a function is to deploy it to Appwrite as Appwrite Function. Alternatively, you could use Open Runtimes to build the code, start HTTP server from it, and send a request to execute it. All documented here: https://github.com/open-runtimes/open-runtimes/tree/main/runtimes/kotlin-1.6#usage

**Comment by Meldiron** [comment]
I updated the issue description. We decided to remove `ow.ly` from the list of providers you need to support. Please only work on `bitly` and `tinyurl` support.

**Comment by PGautam27** [comment]
Sure I'll do it. It'll take me some time. But I'll finish it up.😁

**Comment by codercatdev** [comment]
Awesome thanks so much @PGautam27! If you need any help please jump on https://appwrite.io/discord

**Comment by DurveshKumarPal** [comment]
Hey, this issue is still pending then assign me.

**Comment by PGautam27** [comment]
I am working on this. I am kinda done. I'll do PR soon.

**Comment by letsintegreat** [comment]
Hey! As it has already been almost 2 weeks since this issue was assigned and it is still not solved, I would like to solve this issue.

**Comment by stnguyen90** [comment]
@PGautam27 how's your progress on this? Would you please let us know so we can reassign this if needed?

**Comment by PGautam27** [comment]
you could reassign to someone else

**Comment by ks129** [comment]
Could I please get assigned to this?

**Comment by Ritzy-NCode** [comment]
Can you please assign this issue to me

**Comment by stnguyen90** [comment]
@Ritzy-NCode assigned! Thanks for your interest!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
