### ISSUE TITLE
⚡ Write a generateShortUrl() Function using .NET

### ISSUE THREAD

**Issue by PineappleIOnic** [appwrite/appwrite#4193]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `generateShortUrl()` function using **.NET**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a short URL. Introduce support for `bitly` and `tinyurl` APIs. If necessary, introduce their secret keys as function variables. URL and provider to use must be provided as payload, and shortened URL should be returned.

Example function payload:

```jsx
{"provider":"bitly","url":"https://google.com/"}
```

Successful function response:

```jsx
{"success":true,"url":"https://bit.ly/3y3HDkC"}
```

Error function response:

```jsx
{"success":false,"message":"Entered URL is not a valid URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **.NET**.
- Knowledge to implement **generateShortUrl** function.
- Experience with **Docker**.

### ✅ Task Summary

- [x]  Ask to be assigned to the issue.
- [x]  Implement function `generateShortUrl()` in `.NET/` folder.
- [x]  Manually execute the newly implemented function to ensure it works.
- [x]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by eulercb** [comment]
Hello guys! 👋 Could you assign this issue to me? 🙌

**Comment by Add00w** [comment]
Hello, @PineappleIOnic if @eulercb changes their mind you can assign this to me thanks.

**Comment by codercatdev** [comment]
@eulercb, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by eulercb** [comment]
Hey @codercatdev, I'm sorry but I'll not be able to work on this issue for the next couple of weeks. So please, assign it to another developer!

Sorry for holding it for so long. 😔

**Comment by Meldiron** [comment]
@eulercb No worries, thanks for letting us know 🙏

**Comment by adityaoberai** [comment]
@Meldiron Created the [PR](https://github.com/open-runtimes/examples/pull/120) here
