### ISSUE TITLE
🚨 Improve Appwrite Logging with Datadog Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4204]
# 💭 Introduction

Unexpected errors go hand-in-hand with any software. Whether they are caused by a bug in the code or downtime of service your code relies on, it’s important to get informed about it as soon as possible. Services such as Sentry help you overcome this problem by providing cloud solutions for your error logging and an amazing set of integrations to keep your engineering team informed about all that went wrong.

Appwrite uses the Utopia PHP logger library to automatically log any 500 errors into the cloud error logger of your choice.

The logger library supports multiple adapters such as Sentry, AppSignal, Raygun, Log Owl etc. but there is always space for more. 😎 Each provider implements a simple method `push()`, alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Datadog** in the Utopia PHP logger library. We have prepared detailed documentation on [how to create a Utopia PHP logger adapter](https://github.com/utopia-php/logger/blob/main/docs/tutorials/add-logger-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Datadog**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Datadog**.
- [ ]  Submit a pull request in [utopia-php/logger](https://github.com/utopia-php/logger).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Anudeep-313** [comment]
I can help in improving Appwrite Logging with Datadog Adapter.
- @christyjacob4 Assign this issue to me.

**Comment by tessamero** [comment]
@Anudeep-313 , thanks for your interest! You may work on this.🙏 Happy hacking! 🎃

**Comment by ks129** [comment]
Would like to get assigned to this issue.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by professorabhay** [comment]
Hey @christyjacob4, I would like to work on this !

**Comment by Haimantika** [comment]
> Hey @christyjacob4, I would like to work on this !

Hi @professorabhay have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by professorabhay** [comment]
Hey @Haimantika, Thanks for assigning. 
I am working on it but as my mid-sems are ongoing, I'm busy with them also. I'll definitely raise a PR till the end of the next week !

**Comment by professorabhay** [comment]
Hey @nick2432, it's assigned to me and I'm working on it !

**Comment by professorabhay** [comment]
> > Hey @Haimantika, Thanks for assigning. I am working on it but as my mid-sems are ongoing, I'm busy with them also. I'll definitely raise a PR till the end of the next week !
> 
> Hi, is there any update?

Hey, [PR](https://github.com/utopia-php/logger/pull/31
)

**Comment by Haimantika** [comment]
> > > Hey @Haimantika, Thanks for assigning. I am working on it but as my mid-sems are ongoing, I'm busy with them also. I'll definitely raise a PR till the end of the next week !
> > 
> > 
> > Hi, is there any update?
> 
> Hey, [PR](https://github.com/utopia-php/logger/pull/31)

Thanks, please also link the issue in the PR description

**Comment by tessamero** [comment]
hi @professorabhay the PR is still awaiting your follow up before we can merge so we can send you appwrite hoodie and swag :)

**Comment by professorabhay** [comment]
Hey @tessamero, I already made the changes and raised PR. What should I have to do next ?
Kindly guide me a bit 🙂

**Comment by tessamero** [comment]
@professorabhay awesome, if you are able to link the issue to the PR, that would help. Our engineers will review as soon as they can, they are still reviewing other PRs which is taking a lot of time, but trust we see it here :)

**Comment by professorabhay** [comment]
@tessamero I tried to do so but not able to do. 
If you can help then it will be great -> https://github.com/utopia-php/logger/pull/31

**Comment by tessamero** [comment]
@professorabhay ahh okay, our engineers will link it once they review. (I am unable to)

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
