### ISSUE TITLE
🚨 Improve Appwrite Logging with LogRocket Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4205]
# 💭 Introduction

Unexpected errors go hand-in-hand with any software. Whether they are caused by a bug in the code or downtime of service your code relies on, it’s important to get informed about it as soon as possible. Services such as Sentry help you overcome this problem by providing cloud solutions for your error logging and an amazing set of integrations to keep your engineering team informed about all that went wrong.

Appwrite uses the Utopia PHP logger library to automatically log any 500 errors into the cloud error logger of your choice.

The logger library supports multiple adapters such as Sentry, AppSignal, Raygun, Log Owl etc. but there is always space for more. 😎 Each provider implements a simple method `push()`, alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **LogRocket** in the Utopia PHP logger library. We have prepared detailed documentation on [how to create a Utopia PHP logger adapter](https://github.com/utopia-php/logger/blob/main/docs/tutorials/add-logger-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **LogRocket**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **LogRocket**.
- [ ]  Submit a pull request in [utopia-php/logger](https://github.com/utopia-php/logger).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by dsuarezlogans** [comment]
Hello, can I help on this issue?

**Comment by oriolbv** [comment]
Hi! Can I help with this issue??

**Comment by mustansirgodhrawala** [comment]
@tessamero Can I take a shot at this?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by ajaykrathod** [comment]
Can I work on this issue?

**Comment by Haimantika** [comment]
> Can I work on this issue?

Hi @ajaykrathod  have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
Hi @ajaykrathod is there an update?

**Comment by Haimantika** [comment]
> I can give this a try.

Assigning the issue to you, please update us every 3 days and incase of any doubts, you can reach out to us on Discord - appwrite.io/discord

**Comment by nick2432** [comment]
Can I work on this issue?

**Comment by Haimantika** [comment]
> Just an update. Still looking into this.

Perfect! For any help, please feel free to reach out to us on Discord

**Comment by Haimantika** [comment]
> Do you know where I can find the resources for logrocket. I tried going through their docs but cant figure out what logger I would need to implement

The docs is the only resource I know. Did you figure it out?

**Comment by varunTarone** [comment]
Hi @Haimantika 👋 I am new to Open Source.
Can u assign me this issue?, I will give it a shot.

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over and there's no pending PR. Thank you to everyone who participated this year :)
