### ISSUE TITLE
🚨 Improve Appwrite Logging with Scout Error Monitoring Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4206]
# 💭 Introduction

Unexpected errors go hand-in-hand with any software. Whether they are caused by a bug in the code or downtime of service your code relies on, it’s important to get informed about it as soon as possible. Services such as Sentry help you overcome this problem by providing cloud solutions for your error logging and an amazing set of integrations to keep your engineering team informed about all that went wrong.

Appwrite uses the Utopia PHP logger library to automatically log any 500 errors into the cloud error logger of your choice.

The logger library supports multiple adapters such as Sentry, AppSignal, Raygun, Log Owl etc. but there is always space for more. 😎 Each provider implements a simple method `push()`, alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Scout Error Monitoring** in the Utopia PHP logger library. We have prepared detailed documentation on [how to create a Utopia PHP logger adapter](https://github.com/utopia-php/logger/blob/main/docs/tutorials/add-logger-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Scout Error Monitoring**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Scout Error Monitoring**.
- [ ]  Submit a pull request in [utopia-php/logger](https://github.com/utopia-php/logger).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by InfiniteVerma** [comment]
I'd like to work on this.

**Comment by stnguyen90** [comment]
@InfiniteVerma Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by vasucp1207** [comment]
@stnguyen90, I would like to work on this issue.

**Comment by stnguyen90** [comment]
@InfiniteVerma, are you still working on this? Please let us know so we can reassign accordingly.

**Comment by stnguyen90** [comment]
Assigning to @vasucp1207 due to inactivity.

**Comment by stnguyen90** [comment]
@vasucp1207 are you still working on this or should we unassign you?

**Comment by vasucp1207** [comment]
@stnguyen90 I am not comfortable with Scout Monitoring so you can unassign me.

**Comment by FrodoBaggins74524** [comment]
Can I work on this?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by ksgokul2501** [comment]
Hi @christyjacob4 
I would like to work on this issue. 
I am currently looking into the contributing guidelines for PHP and API docs of Scout APM. 
Please let mw know any other resource that may be helpful.

**Comment by Haimantika** [comment]
> Hi @christyjacob4
> I would like to work on this issue.
> I am currently looking into the contributing guidelines for PHP and API docs of Scout APM.
> Please let mw know any other resource that may be helpful.

Hi @ksgokul2501 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by nick2432** [comment]
can i work on this?

**Comment by ksgokul2501** [comment]
Currently working on this. @nick2432 
@Haimantika do I have to register and use test emails for Scout APM API testing or api-key is available. Could not locate any.

**Comment by Haimantika** [comment]
> Currently working on this. @nick2432 @Haimantika do I have to register and use test emails for Scout APM API testing or api-key is available. Could not locate any.

We do not have any keys, so you will have to register :)

**Comment by jaysomani** [comment]
Hey @ksgokul2501 are you still working on it ?

**Comment by ksgokul2501** [comment]
Sorry for the late response, had some irl issues. Will be submitting a PR soon.

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over. Thank you to everyone who participated this year :)
