### ISSUE TITLE
🚨 Improve Appwrite Logging with Instabug Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4207]
# 💭 Introduction

Unexpected errors go hand-in-hand with any software. Whether they are caused by a bug in the code or downtime of service your code relies on, it’s important to get informed about it as soon as possible. Services such as Sentry help you overcome this problem by providing cloud solutions for your error logging and an amazing set of integrations to keep your engineering team informed about all that went wrong.

Appwrite uses the Utopia PHP logger library to automatically log any 500 errors into the cloud error logger of your choice.

The logger library supports multiple adapters such as Sentry, AppSignal, Raygun, Log Owl etc. but there is always space for more. 😎 Each provider implements a simple method `push()`, alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Instabug** in the Utopia PHP logger library. We have prepared detailed documentation on [how to create a Utopia PHP logger adapter](https://github.com/utopia-php/logger/blob/main/docs/tutorials/add-logger-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Instabug**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Instabug**.
- [ ]  Submit a pull request in [utopia-php/logger](https://github.com/utopia-php/logger).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Alcadeus0** [comment]
Hello! could i work on this issue?

**Comment by abnegate** [comment]
@Alcadeus0 Thanks for your interest! Happy hacking 🎃

**Comment by vasucp1207** [comment]
@Alcadeus0, I would like to work on this issue.

**Comment by Alcadeus0** [comment]
Sure you can take it

**Comment by stnguyen90** [comment]
Reassigned to @vasucp1207! Thank you @Alcadeus0!

**Comment by stnguyen90** [comment]
@vasucp1207 are you still working on this or should we unassign you?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by nick2432** [comment]
Hi, I would like to work on this, please assign this task to me. Thanks!

**Comment by tessamero** [comment]
hi @nick2432 , you've been assigned to the issue. You may now start working on it. :) Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by nick2432** [comment]
Instabug does not have public API yet, only  SDKs are  available. How can I proceed with this?

**Comment by soumyadeeproychowdhury** [comment]
Hi ! could I also work on this issue!

**Comment by nick2432** [comment]
@tessamero Without a REST API, I won't be able to complete this task, so please unassign me.

**Comment by Haimantika** [comment]
@nick2432 unassigning you, @soumyadeeproychowdhury this issue is yours now

**Comment by soumyadeeproychowdhury** [comment]
@Haimantika thank you for assigning me this issue will be updating my progress on it!

**Comment by Haimantika** [comment]
> @Haimantika thank you for assigning me this issue will be updating my progress on it!

Hi, it has been 4 days, do you have an update? If not, we will have to reassign the issue to the next person due to inactivity from your end.

**Comment by soumyadeeproychowdhury** [comment]
@Haimantika I am really sorry for the delay I was unwell for the past few days and was on high medication! Please assign it to someone else! will contribute once I get better. Sorry for the inconvenience caused!!

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over. Thank you to everyone who participated this year :)
