### ISSUE TITLE
🚨 Improve Appwrite Logging with Rollbar Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4208]
# 💭 Introduction

Unexpected errors go hand-in-hand with any software. Whether they are caused by a bug in the code or downtime of service your code relies on, it’s important to get informed about it as soon as possible. Services such as Sentry help you overcome this problem by providing cloud solutions for your error logging and an amazing set of integrations to keep your engineering team informed about all that went wrong.

Appwrite uses the Utopia PHP logger library to automatically log any 500 errors into the cloud error logger of your choice.

The logger library supports multiple adapters such as Sentry, AppSignal, Raygun, Log Owl etc. but there is always space for more. 😎 Each provider implements a simple method `push()`, alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Rollbar** in the Utopia PHP logger library. We have prepared detailed documentation on [how to create a Utopia PHP logger adapter](https://github.com/utopia-php/logger/blob/main/docs/tutorials/add-logger-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Rollbar**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Rollbar**.
- [ ]  Submit a pull request in [utopia-php/logger](https://github.com/utopia-php/logger).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by gagandeepp** [comment]
Interested please assign

**Comment by Meldiron** [comment]
@gagandeepp , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by zmiftah** [comment]
Can you assign this to me?

**Comment by stnguyen90** [comment]
@zmiftah Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by ChandanChainani** [comment]
@stnguyen90 Please can you assign me this issue?

**Comment by stnguyen90** [comment]
@zmiftah, how's your progress on this issue? Please let us know if you're still working on this within 24 hours so that we may reassign it if necessary. 🙏

**Comment by pranjalg13** [comment]
@stnguyen90, please assign this to me, already had done some research and getting a PR ready

Thanks

**Comment by pranjalg13** [comment]
PR for the same: https://github.com/utopia-php/logger/pull/25

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
