### ISSUE TITLE
🚨 Improve Appwrite Logging with New Relic Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4209]
# 💭 Introduction

Unexpected errors go hand-in-hand with any software. Whether they are caused by a bug in the code or downtime of service your code relies on, it’s important to get informed about it as soon as possible. Services such as Sentry help you overcome this problem by providing cloud solutions for your error logging and an amazing set of integrations to keep your engineering team informed about all that went wrong.

Appwrite uses the Utopia PHP logger library to automatically log any 500 errors into the cloud error logger of your choice.

The logger library supports multiple adapters such as Sentry, AppSignal, Raygun, Log Owl etc. but there is always space for more. 😎 Each provider implements a simple method `push()`, alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **New Relic** in the Utopia PHP logger library. We have prepared detailed documentation on [how to create a Utopia PHP logger adapter](https://github.com/utopia-php/logger/blob/main/docs/tutorials/add-logger-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **New Relic**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **New Relic**.
- [ ]  Submit a pull request in [utopia-php/logger](https://github.com/utopia-php/logger).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by boydbloemsma** [comment]
Can I give this a shot?

**Comment by PineappleIOnic** [comment]
@boydbloemsma, thanks for your interest! 🙏 Happy hacking!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by christyjacob4** [comment]
We are accepting submissions for this issue once again for Hacktoberfest 2023

**Comment by kh-2k** [comment]
I can work on this issue @christyjacob4

**Comment by tessamero** [comment]
hi @kh-2k , you've been assigned to the issue. You may now start working on it. :) Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by Mr2cool** [comment]
Let's work on this

**Comment by AryanParashar24** [comment]
Hey @tessamero can u assign this issue to me, i would luv to work on this😄😃

**Comment by aoamusat** [comment]
Kindly assign to me if no one's working on it

**Comment by Haimantika** [comment]
Hi @kh-2k are you still working on it? If not, it will be assigned to the next person tomorrow morning

**Comment by kh-2k** [comment]
Hi @Haimantika couldn't work on this issue, health reason. Couls have reported earlier. sorry for the inconvenience. unassigning

**Comment by aoamusat** [comment]
Kindly reassign to me

**Comment by KholoodS** [comment]
hello @christyjacob4 could you please assign this to me I have some experience with PHP and would love to try this out.

**Comment by Gilbishkosma** [comment]
@christyjacob4 I would like to work on this

**Comment by Haimantika** [comment]
> Let's work on this

Hi are you still interested to work on it?

**Comment by Haimantika** [comment]
Hi @aoamusat @Gilbishkosma @KholoodS @Tushar98644 we are assigning issues on a first-come, first-serve basis.

**Comment by mrkrash** [comment]
Sorry, I don't understand if this issue are assigned or not

**Comment by tessamero** [comment]
We are waiting to hear back from @Mr2cool if they are interested in working on this issue. If no response by tomorrow, I'll be assigning it to the next person @AryanParashar24

**Comment by mrkrash** [comment]
ah, ok. Thank you for your reply :-)

**Comment by trishanu-init** [comment]
@tessamero please assign this issue to me when available

**Comment by airwakz** [comment]
@eldadfux please assign this task to mw i will work on this as asap

**Comment by airwakz** [comment]
@christyjacob4  Hey I think I have enough skills to do this.Please assign me this

**Comment by Haimantika** [comment]
> Hey @tessamero can u assign this issue to me, i would luv to work on this😄😃

Hi, you are the next person in line, would you like to take it up?

**Comment by AryanParashar24** [comment]
> > Hey @tessamero can u assign this issue to me, i would luv to work on this😄😃
> 
> Hi, you are the next person in line, would you like to take it up?

Yup i would luv to work on it

**Comment by Haimantika** [comment]
> > > Hey @tessamero can u assign this issue to me, i would luv to work on this😄😃
> > 
> > 
> > Hi, you are the next person in line, would you like to take it up?
> 
> Yup i would luv to work on it

Assigned! Please remember to update us every 3 days about your progress. 😄

**Comment by AryanParashar24** [comment]
> > > > Hey @tessamero can u assign this issue to me, i would luv to work on this😄😃
> > > 
> > > 
> > > Hi, you are the next person in line, would you like to take it up?
> > 
> > 
> > Yup i would luv to work on it
> 
> Assigned! Please remember to update us every 3 days about your progress. 😄
Hey @Haimantika  just commenting to let u know i m still wokin on this amazing project have been experiencing some problems and soon be contacting via Discord as well, hope i get em solved soon as possible 😄💻

**Comment by Haimantika** [comment]
> > > > > Hey @tessamero can u assign this issue to me, i would luv to work on this😄😃
> > > > 
> > > > 
> > > > Hi, you are the next person in line, would you like to take it up?
> > > 
> > > 
> > > Yup i would luv to work on it
> > 
> > 
> > Assigned! Please remember to update us every 3 days about your progress. 😄
> 
> Hey @Haimantika just commenting to let u know i m still wokin on this amazing project have been experiencing some problems and soon be contacting via Discord as well, hope i get em solved soon as possible 😄💻

Yes please! Open a thread in the support forum :)

**Comment by tessamero** [comment]
Closing issue as PR is now closed.
