### ISSUE TITLE
🚨 Improve Appwrite Logging with Bugsnag Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4211]
# 💭 Introduction

Unexpected errors go hand-in-hand with any software. Whether they are caused by a bug in the code or downtime of service your code relies on, it’s important to get informed about it as soon as possible. Services such as Sentry help you overcome this problem by providing cloud solutions for your error logging and an amazing set of integrations to keep your engineering team informed about all that went wrong.

Appwrite uses the Utopia PHP logger library to automatically log any 500 errors into the cloud error logger of your choice.

The logger library supports multiple adapters such as Sentry, AppSignal, Raygun, Log Owl etc. but there is always space for more. 😎 Each provider implements a simple method `push()`, alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Bugsnag** in the Utopia PHP logger library. We have prepared detailed documentation on [how to create a Utopia PHP logger adapter](https://github.com/utopia-php/logger/blob/main/docs/tutorials/add-logger-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Bugsnag**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Bugsnag**.
- [ ]  Submit a pull request in [utopia-php/logger](https://github.com/utopia-php/logger).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by michizhou** [comment]
Hi @ christyjacob4, would it be alright if I take on this issue?

**Comment by michizhou** [comment]
Hi @christyjacob4, would it be alright if I take on this issue?

**Comment by Meldiron** [comment]
@michizhou , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by ChandanChainani** [comment]
@christyjacob4 are you still working on the issue if not can i take the issue?

**Comment by michizhou** [comment]
@ChandanChainani I'm working on this issue and plan to have a PR for it soon.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
