### ISSUE TITLE
🧑‍🏫 Help Developers by Coding Demo of Appwrite + Next JS

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4225]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to code a demo application showing how you can use **Appwrite with Next JS**. Your project should stay focused on the main feature of Next JS in which you showcase communication with Appwrite regarding Databases, Storage, Functions or Authentication. Do not worry too much about design if that is not something you are interested in, functionality is the most important.

To ensure all issues are quality contributions, please make sure you meet the requirements listed below 🙏

### 🎯 Requirements

- You must use the most iconic features of Next JS.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections, if you use any.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build demo application showcasing Appwrite with Next JS. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI, if you created any.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  Share your work on social media and tag @appwrite (Reddit / HackerNews / Twitter / Facebook / Linkedin)
- [ ]  (optional) Write an article about how you built demo app for Appwrite with Next JS on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by stnguyen90** [comment]
@SanjayDevTech, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Rinshin-Jalal** [comment]
This is repeatation  of #4224 

#4225 = #4224

**Comment by codercatdev** [comment]
@SanjayDevTech we have updated this issue to allow more than one person, so I have removed you from the assignee.

This task does not require any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

Happy Appwriting!

**Comment by SanjayDevTech** [comment]
> @SanjayDevTech we have updated this issue to allow more than one person, so I have removed you from the assignee.
> 
> This task does not require any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).
> 
> Happy Appwriting!

Great Ok 👍

**Comment by MishaAkram** [comment]
i would like to contribute to this issue

**Comment by RobRuizR** [comment]
I'd love to contribute to this as well!

**Comment by AVDiv** [comment]
Hi there, I'd like to be part of this.

**Comment by vyomaaverse** [comment]
Hi, I would like to work on this issue.

**Comment by vasucp1207** [comment]
Hey, I want to work on this issue.

**Comment by JohnGrisham** [comment]
I'm working on this, may the odds be ever in your favor.

**Comment by codercatdev** [comment]
> I'm working on this, may the odds be ever in your favor.

What would Hacktoberfest be like with a Hunger Games at the end of it?
