### ISSUE TITLE
🧑‍🏫 Help Developers by Coding Demo of Appwrite + Hugo

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4226]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to code a demo application showing how you can use **Appwrite with Hugo**. Your project should stay focused on the main feature of Hugo in which you showcase communication with Appwrite regarding Databases, Storage, Functions or Authentication. Do not worry too much about design if that is not something you are interested in, functionality is the most important.

To ensure all issues are quality contributions, please make sure you meet the requirements listed below 🙏

### 🎯 Requirements

- You must use the most iconic features of Hugo.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections, if you use any.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build demo application showcasing Appwrite with Hugo. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI, if you created any.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  Share your work on social media and tag @appwrite (Reddit / HackerNews / Twitter / Facebook / Linkedin)
- [ ]  (optional) Write an article about how you built demo app for Appwrite with Hugo on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by tessamero** [comment]
What would be interesting is a tutorial on using appwrite and hugo to create a simple business consultant website. Many people are trying to start freelancing and a tutorial on how they can make their business site would be used by many :)

**Comment by tessamero** [comment]
@Tushar-2003 Go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create. I am llooking forward to seeing your coding demo :)
