### ISSUE TITLE
🧑‍🏫 Help Developers by Coding Demo of Appwrite + Angular

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4238]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to code a demo application showing how you can use **Appwrite with Angular**. Your project should stay focused on the main feature of Angular in which you showcase communication with Appwrite regarding Databases, Storage, Functions or Authentication. Do not worry too much about design if that is not something you are interested in, functionality is the most important.

To ensure all issues are quality contributions, please make sure you meet the requirements listed below 🙏

### 🎯 Requirements

- You must use the most iconic features of Angular.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections, if you use any.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build demo application showcasing Appwrite with Angular. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI, if you created any.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  Share your work on social media and tag @appwrite (Reddit / HackerNews / Twitter / Facebook / Linkedin)
- [ ]  (optional) Write an article about how you built demo app for Appwrite with Angular on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by zwarag** [comment]
@christyjacob4 do you really mean AngularJS (https://angularjs.org/) or would an Angular (https://angular.io) application also do the trick?

Note: AngularJS is reffered to in the Angular community as the Angular v1. This version is not maintained anymore.

**Comment by mkubdev** [comment]
@codercatdev Hello 👋🏻 I would like to be assigned to this task if possible! I can do this issue with the latest Angular version (14).

**Comment by rahul-jamwal** [comment]
Hello @codercatdev ! I would like to be assigned this task

**Comment by Meldiron** [comment]
@rahul-jamwal Thanks for letting us know 😇 You can go ahead and start working on this - no need to be assigned.

**Comment by mkubdev** [comment]
I'm already on the task :p! Will make a PR today.

**Comment by Shahrukh-cyber** [comment]
can i work on this

**Comment by Meldiron** [comment]
Hey @mkubdev 👋 By mistake, we marked you as an assignee, so I changed it back to no assignee. No need to worry about it 😇 This issue is open to everyone, and any amount of people can work on it at the same time. I have unassigned you, but you can continue working on it. Can't wait to see what you build 🎃

**Comment by mkubdev** [comment]
Hey @Meldiron :wave: Sure! No problem! I know appwrite is ruled by first pull request accepted to not block issue for others contributors.

I started worked on it, but can't sure to be able to make the PR in the end of the day due to fulltime work. Will do my best! And if someone open a PR before me, that's the game 🥳

**Comment by gewenyu99** [comment]
@mkubdev Don't sweat it, we're probably going to take multiple PRs if we're allowing an issue to be open to all!

Looking forward to all of your demos!
