### ISSUE TITLE
🧑‍🏫 Help Developers by Coding Demo of Appwrite + jQuery

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4250]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to code a demo application showing how you can use **Appwrite with jQuery**. Your project should stay focused on the main feature of jQuery in which you showcase communication with Appwrite regarding Databases, Storage, Functions or Authentication. Do not worry too much about design if that is not something you are interested in, functionality is the most important.

To ensure all issues are quality contributions, please make sure you meet the requirements listed below 🙏

### 🎯 Requirements

- You must use the most iconic features of jQuery.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections, if you use any.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build demo application showcasing Appwrite with jQuery. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI, if you created any.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  Share your work on social media and tag @appwrite (Reddit / HackerNews / Twitter / Facebook / Linkedin)
- [ ]  (optional) Write an article about how you built demo app for Appwrite with jQuery on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by leonyangela** [comment]
Hi, I saw that this task is still open. Can I take this task? Thank you.

**Comment by stnguyen90** [comment]
@leonyangela, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by pratikashpanda** [comment]
Hi, I was looking forward to working on this issue. Can I work on this too?

**Comment by Meldiron** [comment]
@pratikashpanda Thanks for letting us know 😇 You can go ahead and start working on this.

**Comment by Meldiron** [comment]
Hey @leonyangela 👋 By mistake, we marked you as an assignee, so I changed it back to no assignee. No need to worry about it 😇 This issue is open to everyone, and any amount of people can work on it at the same time. I have unassigned you, but you can continue working on it. Can't wait to see what you build 🎃

**Comment by leonyangela** [comment]
Hi @Meldiron, okay, I'm sorry that I can't finish it asap. If I make a PR is it going to be count? since no one is assigned.

**Comment by gewenyu99** [comment]
@leonyangela Yep, it'll count. We're just not assigning the issue to any unique individual so that everyone can contribute.

Send a PR our way when you're ready.

Happy hacking!

**Comment by stnguyen90** [comment]
@DarshanDixit05 Go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.

**Comment by AVDiv** [comment]
Hey there, I'd like to work on this, I jzt started.
