### ISSUE TITLE
🧑‍🏫 Help Developers by Coding Demo of Appwrite + PReact

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4252]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to code a demo application showing how you can use **Appwrite with PReact**. Your project should stay focused on the main feature of PReact in which you showcase communication with Appwrite regarding Databases, Storage, Functions or Authentication. Do not worry too much about design if that is not something you are interested in, functionality is the most important.

To ensure all issues are quality contributions, please make sure you meet the requirements listed below 🙏

### 🎯 Requirements

- You must use the most iconic features of PReact.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections, if you use any.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build demo application showcasing Appwrite with PReact. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI, if you created any.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  Share your work on social media and tag @appwrite (Reddit / HackerNews / Twitter / Facebook / Linkedin)
- [ ]  (optional) Write an article about how you built demo app for Appwrite with PReact on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by akankshsinhaa** [comment]
Hey, I'd like to work on this. Let me know if there are some resources that might be useful for the same.

**Comment by Meldiron** [comment]
@akankshsinhaa Thanks for letting us know 😇 You can go ahead and start working on this. The best resource would be official [PReact website](https://preactjs.com/).

**Comment by Adithej** [comment]
Hi , can you assign me as I am interested to work on this

**Comment by iShelar** [comment]
Is this issue is open for everyone?

**Comment by Meldiron** [comment]
@Adithej Thanks for letting us know 😇 You can go ahead and start working on this.

**Comment by Meldiron** [comment]
@iShelar That is correct 🎃 If you are interested, feel free to go ahead and start working on demo application with PReact.

**Comment by iShelar** [comment]
Superb! Thanks @Meldiron

**Comment by rahul-jamwal** [comment]
Hey @Meldiron! I would like to work on this

**Comment by gewenyu99** [comment]
Hi @rahul-jamwal, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.

Make sure you take a close second look at the checklist we provided before you start!

Happy hacking!

**Comment by vasucp1207** [comment]
Key @Meldiron I am interested in working on this.

**Comment by Animesht1008** [comment]
hi @christyjacob4 can you please assign me this issue as a part of hacktoberfest?

**Comment by stnguyen90** [comment]
@vasucp1207, @Animesht1008 we won't be assigning this, but you can go ahead and work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.

**Comment by vasucp1207** [comment]
Hey, @stnguyen90, I completed the task and also write a [blog](https://3dweb.hashnode.dev/making-a-todolist-with-preact-js-using-appwrite-as-a-backend) about this please take a look into this and tell me what I have to do next in order to do PR.

**Comment by vasucp1207** [comment]
Okay , I done the PR.

**Comment by Sooraj-s-98** [comment]
I would like to work on this
