### ISSUE TITLE
🪄 Upgrade ’demo-todo-with-angular’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4258]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-todo-with-angular** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-todo-with-angular to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-todo-with-angular**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this too, kindly assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Asmit2952** [comment]
Can I work on this? @Meldiron

**Comment by stnguyen90** [comment]
@Asmit2952, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by kashif-raza2019** [comment]
I would like to add new features to this, please would you assign me this task. @Meldiron @stnguyen90 @christyjacob4 
Thanks and Regards

**Comment by Asmit2952** [comment]
> I would like to add new features to this, please would you assign me this task. @Meldiron @stnguyen90 @christyjacob4 
> Thanks and Regards

Hey, I'm working on this issue. Can you please find another one?

**Comment by aadyanthaya** [comment]
Can you assign work to me @christyjacob4

**Comment by Asmit2952** [comment]
I'm already working on it @kashif-raza2019 and @aadyanthaya .

**Comment by kashif-raza2019** [comment]
Okay @Asmit2952 I am withdrawing!

**Comment by codercatdev** [comment]
@kashif-raza2019 @aadyanthaya you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by aadyanthaya** [comment]
Okay !

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
