### ISSUE TITLE
🪄 Upgrade ’demo-quiz-with-flutter’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4259]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-quiz-with-flutter** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-quiz-with-flutter to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-quiz-with-flutter**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by VoidCupboard** [comment]
Can you assign this issue to me?

**Comment by Meldiron** [comment]
@VoidCupboard , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by devtayade** [comment]
can you please assign me this task

**Comment by VoidCupboard** [comment]
Hi @devtayade! I have actually asked for the issue, and already opened up the PR for the same 😅

**Comment by devtayade** [comment]
@VoidCupboard okay, can you suggest me some beginner friendly issues ? #newtoopensource

**Comment by VoidCupboard** [comment]
You can give this one a shot - https://github.com/appwrite/appwrite/issues/4220, though you must learn Gatsbay before that. 
With that, according to Appwrite's page, you can create tutorials and blog posts about Appwrite (Like you can show off a demo of creating an app using Appwrite (it's really simple + easy to use if you didnt know) with your favorite web framework).

All the best! It's not good to chat here about this, if you need any help, you can join Appwrite's Discord server - https://www.appwrite.io/discord or you can message me (VoidCupboard#7880)

**Comment by devtayade** [comment]
@VoidCupboard Thank you
