### ISSUE TITLE
🪄 Upgrade ’demo-almost-netflix-for-android’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4260]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-almost-netflix-for-android** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-almost-netflix-for-android to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-almost-netflix-for-android**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by loganSims** [comment]
Can I be assigned this one? Thanks!

**Comment by stnguyen90** [comment]
@loganSims, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by SaiRev0** [comment]
Is this issue open to be assigned?

**Comment by gewenyu99** [comment]
@SaiRev0 Looks like @loganSims is already on this issue. We assign these on a first come, first serve basis. If they're unable to complete this issue, we can reassign this to you.

For the moment, please look for other issues to contribute to :)

Thank you!
