### ISSUE TITLE
🪄 Upgrade ’demo-almost-netflix-for-apple’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4261]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-almost-netflix-for-apple** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade [appwrite/demo-almost-netflix-for-apple](https://github.com/appwrite/demo-almost-netflix-for-apple) to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-almost-netflix-for-apple**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by redromnon** [comment]
Hi there! 
I would like to try working on this issue.

**Comment by apelnar0517** [comment]
I'd like to work on this, please assign this issue to me :)

**Comment by Meldiron** [comment]
@apelnar0517 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by apelnar0517** [comment]
@Meldiron My apologies, I didn't realize it was in Swift. I guess I got a little too excited about Hacktoberfest! I'll un-assign myself and find a different issue.

**Comment by niyasmhdth** [comment]
Hey @Meldiron I can see that the previously assigned developer has been unassigned. I have little experience in working using swift. I would like to take up this issue. Thank you

**Comment by PineappleIOnic** [comment]
@niyasmhdth, thanks for your interest! 🙏 Happy hacking!

**Comment by stnguyen90** [comment]
@niyasmhdth, yes, your goal is to upgrade the dependency and fix all the breaking changes. The goal is to get the demo working with the latest version of Appwrite.

**Comment by niyasmhdth** [comment]
@stnguyen90 ok gotcha ✌🏼

**Comment by ashu-rb** [comment]
May you please assign this issue to me?

**Comment by stnguyen90** [comment]
@ashu-rb We're assigning people on a first come first serve basis. If @niyasmhdth isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by stnguyen90** [comment]
@niyasmhdth How's your progress on this? Are you still working on this or can it be reassigned? Please respond within 24 hours or we'll need to reassign the issue.

**Comment by niyasmhdth** [comment]
It's bern halfway. But I'm struggling with some break changes. I would suggest for a re assign

**Comment by stnguyen90** [comment]
@niyasmhdth thanks for the update! @ashu-rb, would you be interested in taking this on?

**Comment by ashu-rb** [comment]
Sorry...but not now!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
