### ISSUE TITLE
🪄 Upgrade ’demo-almost-netflix-for-web’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4262]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-almost-netflix-for-web** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-almost-netflix-for-web to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-almost-netflix-for-web**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this too, kindly assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by DevTomilola-OS** [comment]
I would like to work on this in place of the 'demo-job-portal-with-apple' issue i applied to earlier.

Thanks.

**Comment by Meldiron** [comment]
@DevTomilola-OS Assigning it to you now. Happy Hacktoberfest 🎃

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by codercatdev** [comment]
@anushagupta1312, we are assigning people on a first come first serve basis. If @DevTomilola-OS isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by DevTomilola-OS** [comment]
Kindly review and merge PR so i can take up another issue. Thanks admin.

**Comment by DevTomilola-OS** [comment]
Kindly review and merge PR so i can take up another issue. Thanks admin.

**Comment by tessamero** [comment]
@DevTomilola-OS Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
