### ISSUE TITLE
🪄 Upgrade ’demo-quiz-with-android’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4263]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-quiz-with-android** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-quiz-with-android to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-quiz-with-android**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this too, kindly assign this to me.

**Comment by letsintegreat** [comment]
Hey! I would like to work on this issue, can you please assign it to me?

**Comment by stnguyen90** [comment]
@letsintegreat, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by rahmatsyam** [comment]
I want to contribute, please assign to me

**Comment by gewenyu99** [comment]
Hi @rahmatsyam, we are assigning people on a first come, first serve basis. If @letsintegreat isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find other Hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

We'd love your help on other issues :)

**Comment by letsintegreat** [comment]
@gewenyu99 Actually, I have already submitted a [PR](https://github.com/appwrite/demo-quiz-with-android/pull/9) which solves this issue, and I am awaiting review :D
