### ISSUE TITLE
🪄 Upgrade ’demo-getstarted-with-android’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4264]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-getstarted-with-android** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-getstarted-with-android to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-getstarted-with-android**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this too, kindly assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by czlucius** [comment]
Hi there
I would like to contribute to this issue

**Comment by SanjayDevTech** [comment]
I would like to contribute to this issue

**Comment by letsintegreat** [comment]
Hey! I would like to work on this issue.

**Comment by stnguyen90** [comment]
@czlucius, thanks for your interest! 🙏 Happy hacking! 🎃 

@SanjayDevTech, we're assigning people on a first come first serve basis. If @czlucius isn't able to complete this issue, well reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by czlucius** [comment]
@stnguyen90
May I ask, this change only requires us to update the Appwrite version to 1.0 right?
Hence, I assume a gradle dependency version change is all that's needed?
If not, what else do I need to add?

**Comment by stnguyen90** [comment]
@czlucius, there are breaking changes with latest SDK, so you would need to fix the app to ensure it still works.

**Comment by czlucius** [comment]
Thanks
I did notice them when building the project 
Will go investigate them soon

**Comment by czlucius** [comment]
Hi @stnguyen90 
May I get a sample of the response object in v0.0.0?
Currently, Accounts uses an `Account` object, but long before, it used a `Response` object.

https://github.com/appwrite/sdk-for-android/blob/7644a1f952d767b1a8b750a2f19e4ff694fc5262/library/src/main/java/io/appwrite/services/Account.kt#L66

https://github.com/appwrite/sdk-for-android/blob/d5874c38a8807652e3515f16ca3dc6f7199d099c/library/src/main/java/io/appwrite/services/Account.kt#L54

Thanks

**Comment by stnguyen90** [comment]
@czlucius, what do you mean 0.0.0? Do you mean 1.0.x? I suggest you spin up an instance of Appwrite so you can see the response yourself.

**Comment by Mwakai** [comment]
Hi there, I would like to contribute to this issue.

**Comment by Meldiron** [comment]
@Mwakai , we're assigning people on a first come first serve basis. If @czlucius  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by rahmatsyam** [comment]
I want contribute it

**Comment by PineappleIOnic** [comment]
@rahmatsyam, we're assigning people on a first come first serve basis. If [@czlucius](https://github.com/czlucius) isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by czlucius** [comment]
Hi there
I have been quite busy the past few days, and may not be able to complete this fix. I think someone else can continue?
Thanks

**Comment by gewenyu99** [comment]
Thanks for letting us know @czlucius!

@SanjayDevTech, you're next inline, I'm gonna assign this to you for now :)

**Comment by SanjayDevTech** [comment]
@gewenyu99 thanks

**Comment by SanjayDevTech** [comment]
@gewenyu99 I have raised a PR: [https://github.com/appwrite/demo-getstarted-with-android/pull/10](https://github.com/appwrite/demo-getstarted-with-android/pull/10)

**Comment by stnguyen90** [comment]
@SanjayDevTech Thanks for the PR! 🤯 Please give us some time to review it.
