### ISSUE TITLE
🪄 Upgrade ’demos-for-vue’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4265]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demos-for-vue** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demos-for-vue to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demos-for-vue**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this too, kindly assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Meldiron** [comment]
@Goheljay Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by TheLearneer** [comment]
I would like to pick it up 🤚

**Comment by aparna2071** [comment]
Hi @christyjacob4 I would like to contribute, can you please assign this to me ?

**Comment by stnguyen90** [comment]
@aparna2071, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Adyasha28** [comment]
Hi @christyjacob4  I would like to contribute, can you please assign this to me

**Comment by Meldiron** [comment]
@Adyasha28 , we're assigning people on a first come first serve basis. If @aparna2071  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
