### ISSUE TITLE
🪄 Upgrade ’demos-for-angular’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4266]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demos-for-angular** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demos-for-angular to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demos-for-angular**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this too, kindly assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by sakshiisaxena** [comment]
I would like to work this issue. Please assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Vikki123** [comment]
@Meldiron Could i pick this up ?

**Comment by Meldiron** [comment]
@Vikki123 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Vikki123** [comment]
Thank you. Wil raise a PR soon.

**Comment by Vikki123** [comment]
@Meldiron @christyjacob4  Could you review the PR https://github.com/appwrite/demos-for-angular/pull/14. Thanks !

**Comment by Shahrukh-cyber** [comment]
could you assign it to me?

**Comment by Vikki123** [comment]
Hey @Meldiron . I have already raised a PR for the issue. Could you please review it when you find time. Thanks !

**Comment by gewenyu99** [comment]
@Vikki123 Can you link the PR here, please?

**Comment by Vikki123** [comment]
@gewenyu99 https://github.com/appwrite/demos-for-angular/pull/14 Here It is: https://github.com/appwrite/demos-for-angular/pull/14

**Comment by Vikki123** [comment]
Hey @gewenyu99 @christyjacob4 Could yo please merge the PR. Thank you !

**Comment by Meldiron** [comment]
@Vikki123 Hey there 👋 I noticed there is an approving review, so I also added `hacktoberfest-accepted` label. That should be enough to mark PR as valid for Hacktoberfest.

Regarding merging, that is done after a second review from an engineering team leader. Please be patient regarding the merge 🙏
