### ISSUE TITLE
🪄 Upgrade ’demos-for-svelte’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4267]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demos-for-svelte** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demos-for-svelte to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demos-for-svelte**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Meldiron** [comment]
@DevTomilola-OS Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by DevTomilola-OS** [comment]
Okay thank you, I'm working on them already.

**Comment by pushkaraj2007** [comment]
Can you please give a piece more information about the issue?

**Comment by stnguyen90** [comment]
@DevTomilola-OS, sounds good! Feel free to comment on another issue once you've completed one of the ones you're currently working on 😄

**Comment by Sooraj-s-98** [comment]
@stnguyen90 I would like to work on this too, kindly assign this to me.

**Comment by codercatdev** [comment]
@umaraj79, we are assigning people on a first come first serve basis. If @Sooraj-s-98 isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Sooraj-s-98** [comment]
@codercatdev can you check my PR ?

**Comment by tessamero** [comment]
@Sooraj-s-98, Thanks for the PR! 🤯 Please give us some time to review it.
