### ISSUE TITLE
🪄 Upgrade ’demo-job-portal-with-apple’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4268]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-job-portal-with-apple** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-job-portal-with-apple to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-job-portal-with-apple**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this too, kindly assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by DevTomilola-OS** [comment]
Hello @Meldiron I'm sorry i can't work on this because i don't use an apple device, can you assign me many more that doesn't have to do with me having an apple device.

Thanks.

**Comment by Meldiron** [comment]
@DevTomilola-OS That is understandable. Please write a new comment on an issue where you want to be assigned. I'll get notification and assign it to you

**Comment by vishnus17** [comment]
Hi @Meldiron. I'd like to take up this issue.

**Comment by stnguyen90** [comment]
@vishnus17, thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by vedant-z** [comment]
@stnguyen90 I would love to work on this.

**Comment by stnguyen90** [comment]
@vedant-z, assigned! Thanks for your interest! 🙏

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
