### ISSUE TITLE
🪄 Upgrade ’demo-almost-netflix-for-flutter’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4269]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-almost-netflix-for-flutter** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-almost-netflix-for-flutter to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-almost-netflix-for-flutter**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this too, kindly assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by sakshiisaxena** [comment]
I would like to work this issue. Please assign this to me.

**Comment by Meldiron** [comment]
@sakshiisaxena , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by letsintegreat** [comment]
Since it has been some time after @sakshiisaxena was assigned, I would like to take this one on in case she is not working on it.

**Comment by Meldiron** [comment]
@sakshiisaxena Hey there 👋 Are you still working on this issue? No need to rush, you have a whole month 😇 I just need to confirm with you if you are still active on this assignment.

**Comment by Wise-Wizard** [comment]
I would like to work on this issue too, kindly assign this to me.

**Comment by sakshiisaxena** [comment]
> @sakshiisaxena Hey there 👋 Are you still working on this issue? No need to rush, you have a whole month 😇 I just need to confirm with you if you are still active on this assignment.

yes, I am.

**Comment by skdotv** [comment]
hi @christyjacob4, I have upgraded the Appwrite SDK i.e (8.1.0) can you please review this, Thank you
issue: https://github.com/appwrite/demo-almost-netflix-for-flutter/issues/3

**Comment by codercatdev** [comment]
@skdotv Please create your PR after you've been assigned to an issue. With that said @sakshiisaxena could you take a look at https://github.com/appwrite/demo-almost-netflix-for-flutter/pull/4 if this works we could add you to another issue.

**Comment by skdotv** [comment]
@codercatdev understood, actually I opened the repo directly i.e (demo-almost-netflix-for-flutter) later I got to know that there is already an issue in the main repo i.e (appwrite).

**Comment by stnguyen90** [comment]
@sakshiisaxena, how's your progress on this? Please let us know if this needs to be reassigned.

**Comment by stnguyen90** [comment]
@letsintegreat, would you like to work on this since there's been no response from @sakshiisaxena?

**Comment by stnguyen90** [comment]
@letsintegreat assigned as mentioned on discord! Happy hacking! 🎃
