### ISSUE TITLE
🪄 Upgrade ’demo-todo-with-react’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4270]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-todo-with-react** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-todo-with-react to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-todo-with-react**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by kirtanchandak** [comment]
Can I work on this issue ?

**Comment by queen-x-vee** [comment]
can I work on this issue

**Comment by Meldiron** [comment]
@kirtanchandak , thanks for your interest! 🙏 Happy hacking! 🎃

@queen-x-vee , we're assigning people on a first come first serve basis. If @kirtanchandak  isn't able to complete this issue, well reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by SaiRev0** [comment]
Can I work on this issue if no one working on it??

**Comment by gewenyu99** [comment]
@SaiRev0, we are assigning people on a first come, first serve basis. If kirtanchandak isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

Thank you!

**Comment by stnguyen90** [comment]
Removing @kirtanchandak since no submission was made.

**Comment by sseth** [comment]
Hi! I'd like to work on this, can I be assigned please?

**Comment by stnguyen90** [comment]
@sseth assigned! Thanks 🙏🏼

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
