### ISSUE TITLE
🪄 Upgrade ’demo-todo-with-nextjs’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4271]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-todo-with-nextjs** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-todo-with-nextjs to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-todo-with-nextjs**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this too, kindly assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by sakshiisaxena** [comment]
I would like to work on this issue. It would be great if you could assign this to me.

**Comment by Meldiron** [comment]
@sakshiisaxena , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by paragkatoch** [comment]
I would like to work on this issue. Can you assign this to me

**Comment by codercatdev** [comment]
For now @sakshiisaxena has this issue, please let us know if you are stuck on anything 😄

**Comment by ashu-rb** [comment]
May you please assign this issue to me?

**Comment by stnguyen90** [comment]
@ashu-rb We're assigning people on a first come first serve basis. If @sakshiisaxena isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by stnguyen90** [comment]
Removing @sakshiisaxena since no submission was made

**Comment by byt3h3ad** [comment]
hi! i would like to be assigned this!

**Comment by ashu-rb** [comment]
Won't be able to do this right now
Sorry

**Comment by SachinSinghYadav** [comment]
Hi I would like work on this issue , Can you please assign to me ?

**Comment by tewarig** [comment]
@Meldiron if this issue is still open i would love to work on this issue.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
