### ISSUE TITLE
🪄 Upgrade ’demo-todo-with-svelte’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4273]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-todo-with-svelte** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-todo-with-svelte to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-todo-with-svelte**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this too, kindly assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by ananas-dev** [comment]
Hi, I'd like to assign this issue to myself

**Comment by Meldiron** [comment]
@ananas-dev , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by FarhanAliRaza** [comment]
Please assign this to me @Meldiron

**Comment by codercatdev** [comment]
Hey @FarhanAliRaza thank you for your interested ananas-dev has a PR open already.
