### ISSUE TITLE
🪄 Upgrade ’demos-for-react’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4274]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demos-for-react** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demos-for-react to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demos-for-react**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by omjikush09** [comment]
@christyjacob4  Hi, I would like to work on this. Can you assign this to me

**Comment by Meldiron** [comment]
@omjikush09 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by paragkatoch** [comment]
Hi,  I would love to work on this. Can you assign me to this

**Comment by anushagupta1312** [comment]
Hey I would like to work on this issue. Can you please assign me this?

**Comment by omjikush09** [comment]
Hey @Meldiron  created a pull request- https://github.com/appwrite/demos-for-react/pull/16

**Comment by SanifKandel** [comment]
@christyjacob4, Hey I would love to be assigned on this issue. Could you please do that ?

**Comment by tessamero** [comment]
@SanifKandel we're assigning people on a first come first serve basis and looks like this one is already assigned and a PR is submitted. In the meantime, you can find other hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by ksaravindakashyap** [comment]
@Meldiron I would like to work on this.

**Comment by ritik-prabhat** [comment]
Please assign me this, i would like to contribute.

**Comment by Meldiron** [comment]
@ksaravindakashyap @ritik-prabhat , we're assigning people on a first come first serve basis. If @omjikush09  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by DarshanDixit05** [comment]
Hello, I want to work on this.

**Comment by stnguyen90** [comment]
@DarshanDixit05, we're assigning people on a first come first serve basis. If @omjikush09 isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).
