### ISSUE TITLE
🪄 Upgrade ’demo-watertracker-with-flutter’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4275]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-watertracker-with-flutter** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-watertracker-with-flutter to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-watertracker-with-flutter**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DevTomilola-OS** [comment]
I would like to work on this, kindly assign this to me.

**Comment by Meldiron** [comment]
@DevTomilola-OS , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by DevTomilola-OS** [comment]
Hello @Meldiron i would also need your guidance on this, do i upgrade the sdk or the server?

**Comment by Meldiron** [comment]
@DevTomilola-OS No need to worry about upgrading the server. This demo app points to Appwrite's demo instance ( https://github.com/appwrite/demo-watertracker-with-flutter/blob/main/lib/res/app_constants.dart#L2 ) which is already running Appwrite 1.0. All you need to do is to set Flutter library version to latest, and fix all the errors that will pop up due to this change, as there were multiple breaking changes - such as permissions, queries or possibly even databaseId.

**Comment by Meldiron** [comment]
You can find out more about releases and breaking changes in SDK here: https://github.com/appwrite/sdk-for-flutter/releases

**Comment by codercatdev** [comment]
@mayurrkukreja, we are assigning people on a first come first serve basis. If @DevTomilola-OS isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by DevTomilola-OS** [comment]
Kindly review and merge PR so i can take up another issue. Thanks admin.

**Comment by DevTomilola-OS** [comment]
Kindly review and merge PR so i can take up another issue. Thanks admin.

**Comment by tessamero** [comment]
@DevTomilola-OS Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by codercatdev** [comment]
@DevTomilola-OS please see PR, needs updates.

**Comment by DevTomilola-OS** [comment]
Okay Working on it @codercatdev

**Comment by stnguyen90** [comment]
@DevTomilola-OS Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by stnguyen90** [comment]
@DevTomilola-OS can we keep you assigned on this since you worked on the PR?

**Comment by mustansirgodhrawala** [comment]
@Haimantika Can this be assigned to me?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
