### ISSUE TITLE
🪄 Upgrade ’demo-todo-with-flutter’ to Appwrite 1.0

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4276]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-todo-with-flutter** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-todo-with-flutter to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-todo-with-flutter**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by detronetdip** [comment]
Where I can find the current demo application?

**Comment by Meldiron** [comment]
@detronetdip You can find repository of the demo app here: https://github.com/appwrite/demo-todo-with-flutter

**Comment by detronetdip** [comment]
Thanks for help. though I am very new to fluetter and appwrite but I want to contribute in this project and I will try my best to do so.

**Comment by xinkin** [comment]
Hey,  I have been learning flutter for the last few months, would love to contribute in this project, can i be assigned to it

**Comment by tessamero** [comment]
> Hey, I have been learning flutter for the last few months, would love to contribute in this project, can I be assigned to it

@xinkin , we're assigning people on a first come first serve basis. If @detronetdip isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Aryanshh** [comment]
Please Assign the work to me

**Comment by karan-17** [comment]
I want to work and contribute to this issue, can I be assigned this issue?

**Comment by BhavnaMogha** [comment]
I want to work and contribute to this issue, can I be assigned this issue?

**Comment by tessamero** [comment]
@Aryanshh , @karan-17 , @zsiecr , we're assigning people on a first come first serve basis. If @detronetdip isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by kvndb** [comment]
i want to work on this can you please assign me ?

**Comment by tessamero** [comment]
@kvndb , we're assigning people on a first come first serve basis. If @detronetdip isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by hitchhicker007** [comment]
I want to work on this issue can you please assign it to me?

**Comment by gewenyu99** [comment]
@hitchhicker007 , we're assigning people on a first come, first serve basis. If @detronetdip isn't able to complete this issue, we will reassign it accordingly. 

We appreciate your participation, but we're holding ourselves to our procedures and giving@detronetdip their chance to make this contribution.

In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

Thanks!!

**Comment by Aryanshh** [comment]
I want to work and contribute to this issue, can I be assigned this issue?

**Comment by Meldiron** [comment]
@Aryanshh , we're assigning people on a first come first serve basis. If @detronetdip  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by letsintegreat** [comment]
Hey! As it has already been almost 3 weeks since this issue was assigned and it is still not solved, I would like to solve this issue.

**Comment by detronetdip** [comment]
@Meldiron  as I am very new tu flutter, it is taking a bit time for me to resolve the issue, I think you can assign @xinkin this issue and unassign me.

**Comment by stnguyen90** [comment]
@xinkin, are you still interested in working on this?

**Comment by stnguyen90** [comment]
@xinkin, @Aryanshh, @karan-17, @BhavnaMogha, @zsiecr, @kvndb, @hitchhicker007, @letsintegreat, or @detronetdip, are you still interested in working on this?

**Comment by letsintegreat** [comment]
@stnguyen90 Hey! Can I take up this one?

**Comment by karan-17** [comment]
yes, I am interested in working on this project!

**Comment by stnguyen90** [comment]
@karan-17, you were next up so I'm assigning this to you. Happy hacking! 🎃

**Comment by stnguyen90** [comment]
@karan-17, how's your progress on this?

**Comment by karan-17** [comment]
@stnguyen90 I was trying to resolve some bugs in the app functions, because the setState function isn't working as it should, and thus it is taking a bit longer.

**Comment by stnguyen90** [comment]
@karan-17 feel free to create a PR so you can preliminarily qualify for hacktoberfest

**Comment by karan-17** [comment]
@stnguyen90 if it still can be considered as a contribution to open source and the AppWrite organization, it would be worth investing the time for me!

**Comment by Mithran-04** [comment]
Hey, I would like to work on this issue, I have done projects using Dart/Flutter, and I am eager to work on this issue, So would be glad if the issue is assigned to me.

**Comment by karan-17** [comment]
@stnguyen90 i tried working on it, but couldn't resolve the bug which i was facing, you can assign someone else for this issue.
Thank you!

**Comment by stnguyen90** [comment]
@Mithran-04, thanks for your interest! There's actually a lot more changes I want to make with this so I think it would be best if I work on this and the redesign together.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
