### ISSUE TITLE
🧱 Build Almost Bitly. Be Creative!

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#4307]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to provide Appwriters with a **huge amount** of example projects that many use as learning resources.

We understand Appwrite’s tech stack might not be your cup of tea, so we decided to prepare a series of `Almost (something)` projects. This series of issues is here to let your creativity shine! ✨

Your task is to create **Almost Bitly**. This should be a website that copies the functionality of Bitly, but uses Appwrite as a backend. We understand that Bitly is a huge project, so don’t worry about implementing every single feature - make sure to only focus on the most well-known features of this platform. Regarding design, please try not to copy the official one - feel free to use UI libraries to help you out.

You can check out [Almost Reddit](https://github.com/Meldiron/almost-reddit-place) as a reference project. This project meets all the requirements.

### 🎯 Requirements

- You must replicate the most iconic features of Bitly.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be a web or Flutter application. Regarding the web, use any JavaScript technology.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build Almost Bitly as a web or Flutter app. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Write an article about how you built Almost Bitly on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by gewenyu99** [comment]
@Arpan-206 @Deepakv14 Looking forward to your contributions!

Good luck and happy hacking!

**Comment by DarshanDixit05** [comment]
Hello , I want to work on this !

**Comment by stnguyen90** [comment]
@DarshanDixit05 Go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.

**Comment by hridaya423** [comment]
I want to work on this too!

**Comment by Arpan-206** [comment]
Hey @Meldiron  I also want to work on a Discord bot version of the same URL shortener, so can you create a new issue for it?

**Comment by stnguyen90** [comment]
@hridaya423 Go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create. 

@Arpan-206 please comment in the https://github.com/appwrite/appwrite/issues/4024 issue with your request.

**Comment by Rinshin-Jalal** [comment]
I am working on this 
in solidjs

**Comment by stnguyen90** [comment]
@Rinshin-Jalal Go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.

**Comment by Arpan-206** [comment]
Added a PR in the Awesome-Appwrite repository over [here](https://github.com/appwrite/awesome-appwrite/pull/441).

**Comment by SiddharthShyniben** [comment]
I'd like to work on this!

**Comment by Meldiron** [comment]
@SiddharthShyniben , thanks for letting us know! 🙏 Go ahead, you can work on this issue 😇
