### ISSUE TITLE
🧑‍🏫 Help Developers by Coding Demo of Appwrite + Telegram (bot)

### ISSUE THREAD

**Issue by Meldiron** [appwrite/appwrite#4308]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to code a demo application showing how you can use **Appwrite with Telegram (bot)**. Your project should stay focused on the main feature of Telegram (bot) in which you showcase communication with Appwrite regarding Databases, Storage, Functions or Authentication. Do not worry too much about design if that is not something you are interested in, functionality is the most important.

To ensure all issues are quality contributions, please make sure you meet the requirements listed below 🙏

### 🎯 Requirements

- You must use the most iconic features of Telegram (bot).
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections, if you use any.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build demo application showcasing Appwrite with Telegram (bot). Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI, if you created any.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  Share your work on social media and tag @appwrite (Reddit / HackerNews / Twitter / Facebook / Linkedin)
- [ ]  (optional) Write an article about how you built demo app for Appwrite with Telegram (bot) on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by RobRuizR** [comment]
Hey! I'd like to take a look at this :)

**Comment by rohit1101** [comment]
Hey @Meldiron can i take a look at this ?

**Comment by harshit078** [comment]
Hey, @Meldiron is it possible for me to take a look at this ?

**Comment by ishan-siddiqui** [comment]
Hey! I would like to work on this..

**Comment by PineappleIOnic** [comment]
@rohit1101 @harshit078 @ishan-siddiqui , we're assigning people on a first come first serve basis. If @RobRuizR isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by gewenyu99** [comment]
@PineappleIOnic I think this issue actually does not require any assignment. 

@srini047 @rohit1101 @harshit078 @ishan-siddiqui, you can start working on this, but please comment on this issue and mention you are working on it.

@RobRuizR You can continue working on this as well, we're just not going to assign this issue :) Everyone can contribute.

Sorry for the confusion and looking forward to all of y'all's contributions!!! 

Happy hacking!

**Comment by mayurrkukreja** [comment]
Hello, I would like to work on this issue #4308 and contribute to an appwrite's demo application ✨😊

**Comment by shaishav06** [comment]
Hey, @Meldiron I'm Interested in working on this telegram bot feature can I work for it? @PineappleIOnic @RobRuizR

**Comment by abnegate** [comment]
@mayurrkukreja @shaishav06 You are both welcome to work on with this issue, it is open for everyone :grin:

**Comment by akarsh-jain-790** [comment]
@abnegate I am working on this issue.

**Comment by Meldiron** [comment]
@akarsh-jain-790 Thanks for letting us know 😇 Happy Hacking 🎃

**Comment by chiragbairwa** [comment]
@abnegate I am working on this issue. 🙌

**Comment by Meldiron** [comment]
@chiragbairwa Thanks for letting us know 😇
