### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/framework’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4347]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/framework](https://github.com/utopia-php/framework) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/framework](https://github.com/utopia-php/framework) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/framework](https://github.com/utopia-php/framework).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by om2137** [comment]
can i work on this issue?

**Comment by Meldiron** [comment]
@om2137 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by aaryan2134** [comment]
Can I work on this issue if it is still pending?

**Comment by om2137** [comment]
> Can I work on this issue if it is still pending?

I am working on this, just gt delayed because of my exams.

**Comment by Rutam21** [comment]
@Meldiron I have completed the previous tickets. As this issue seems to be inactive for the past 12 days, you can re-assign it to me.

**Comment by om2137** [comment]
sorry for the delay but i was not able to give time to this task.
just reassign it to some one. once again my apologies

**Comment by aaryan2134** [comment]
I would like to work on this if possible @Meldiron

**Comment by Rutam21** [comment]
@stnguyen90 But I had commented first 3 days back after seeing that there are no PRs for this issue even after 7 days.

**Comment by aaryan2134** [comment]
Thank you. Will get it done soon

**Comment by aaryan2134** [comment]
I have submitted my PR
https://github.com/utopia-php/framework/pull/81
Please have a look and let me know if there are any issues
