### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/cache’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4348]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/cache](https://github.com/utopia-php/cache) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/cache](https://github.com/utopia-php/cache) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/cache](https://github.com/utopia-php/cache).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by shtelzerartem** [comment]
I would also like to work on this issue! :)

**Comment by Meldiron** [comment]
@shtelzerartem , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by shtelzerartem** [comment]
@Meldiron I'm waiting for them to be reviewed 👀

**Comment by stnguyen90** [comment]
@shtelzerartem Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃
