### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/system’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4350]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/system](https://github.com/utopia-php/system) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/system](https://github.com/utopia-php/system) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/system](https://github.com/utopia-php/system).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by MagnaibayarMN** [comment]
Hello, i would like to be an assigned.

**Comment by Meldiron** [comment]
@MagnaibayarMN , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by MagnaibayarMN** [comment]
@Meldiron @christyjacob4  
Guys, Please check this PR 

https://github.com/utopia-php/system/pull/20

**Comment by codercatdev** [comment]
@MagnaibayarMN Thanks for the PR! 🤯 Please give us some time to review it.
