### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/demo’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4355]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/demo](https://github.com/utopia-php/demo) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/demo](https://github.com/utopia-php/demo) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/demo](https://github.com/utopia-php/demo).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aaryan2134** [comment]
I would like to work on this issue. Please assign it to me

**Comment by Meldiron** [comment]
@aaryan2134 , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by aadityaagrawal** [comment]
Hi @christyjacob4 can you please assign this issue to me?

**Comment by stnguyen90** [comment]
@aadityaagrawal Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by aaryan2134** [comment]
Can I work on this issue if it is still pending?

**Comment by ItsAdityaKSingh** [comment]
I would like to resolve this issue @stnguyen90!

**Comment by Rutam21** [comment]
@Meldiron I have completed the previous tickets. As this issue seems to be inactive for the past 10 days, you can re-assign it to me.

**Comment by Meldiron** [comment]
@aadityaagrawal Hey there 👋 Can you please confirm with me if you are working on this issue?

**Comment by vasucp1207** [comment]
@Meldiron assign this issue to me if it's pending.

**Comment by stnguyen90** [comment]
@aaryan2134, @ItsAdityaKSingh, or @Rutam21, are you still interested in working on this? Please respond within 24 hours so we can reassign accordingly.

**Comment by Rutam21** [comment]
@stnguyen90 I would love to work on this as well. Kindly assign this to me. I will complete these within a day. Thanks.

**Comment by ItsAdityaKSingh** [comment]
Yes, @stnguyen90, I would like to be assigned to this issue!

**Comment by stnguyen90** [comment]
Assigning to @ItsAdityaKSingh for being next in queue.

**Comment by ItsAdityaKSingh** [comment]
@stnguyen90 @Meldiron, I have made a PR for the issue @https://github.com/utopia-php/demo/pull/12
Please review :)
