### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/websocket’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4356]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/websocket](https://github.com/utopia-php/websocket) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/websocket](https://github.com/utopia-php/websocket) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/websocket](https://github.com/utopia-php/websocket).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by samarth2812** [comment]
can you assign me this issue??

**Comment by ItsAdityaKSingh** [comment]
I would like to be assigned to this issue!

**Comment by stnguyen90** [comment]
@samarth2812 Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃 

@ItsAdityaKSingh, we're assigning people on a first come first serve basis. If @samarth2812 isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by aaryan2134** [comment]
Can I work on this issue if it is still pending?

**Comment by ItsAdityaKSingh** [comment]
If this issue is still open, I would like to work on resolving it @stnguyen90!

**Comment by Rutam21** [comment]
@Meldiron I have completed the previous tickets. As this issue seems to be inactive for the past 10 days, you can re-assign it to me.

**Comment by Meldiron** [comment]
@samarth2812 Hey there 👋 Can you please confirm with me if you are working on this issue?

**Comment by vasucp1207** [comment]
Hey, @Meldiron assign this issue to me if it is pending.

**Comment by stnguyen90** [comment]
@ItsAdityaKSingh, @aaryan2134, or @Rutam21, are you still interested in working on this? Please let us know within 24 hours so we can reassign accordingly.

**Comment by Rutam21** [comment]
@stnguyen90 I would love to work on this. Please assign this to me. Thanks.

**Comment by ItsAdityaKSingh** [comment]
Yes @stnguyen90, I would like to be assigned to this :)

**Comment by stnguyen90** [comment]
@ItsAdityaKSingh, you have a lot of issues so I'm going to assign this to @Rutam21. 🙏

**Comment by Rutam21** [comment]
@stnguyen90 The PR has been raised for this. https://github.com/utopia-php/websocket/pull/19
