### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/orchestration’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4357]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/orchestration](https://github.com/utopia-php/orchestration) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/orchestration](https://github.com/utopia-php/orchestration) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/orchestration](https://github.com/utopia-php/orchestration).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aadityaagrawal** [comment]
I would love to work on this issue please assign this to me.

**Comment by toukirkhan** [comment]
assign me please

**Comment by stnguyen90** [comment]
@aadityaagrawal, @toukirkhan Please consider picking a different type of issue so other contributors can try this one. We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by vinayharwani13** [comment]
I would like to work on this issue.

**Comment by Meldiron** [comment]
@vinayharwani13 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by vinayharwani13** [comment]
Hi @Meldiron, I have raised the PR. Hoping to get reviewed soon.

**Comment by stnguyen90** [comment]
@vinayharwani13 Thanks for the PR! 🤯 Please give us some time to review it.
