### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/messaging’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4358]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/messaging](https://github.com/utopia-php/messaging) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/messaging](https://github.com/utopia-php/messaging) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by SanjayDevTech** [comment]
@christyjacob4 I would like to contribute to this issue 😄

**Comment by Meldiron** [comment]
@SanjayDevTech , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by amyra98** [comment]
Please assign me this

**Comment by stnguyen90** [comment]
@amyra98 Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by aaryan2134** [comment]
Can I work on this issue if it is still pending?

**Comment by ItsAdityaKSingh** [comment]
I would like to contribute to this issue @stnguyen90.

**Comment by Rutam21** [comment]
@Meldiron I have completed the previous tickets. As this issue seems to be inactive for the past 10 days, you can re-assign it to me.

**Comment by Rutam21** [comment]
@stnguyen90 Can you assign this one to me now as @aaryan2134 is already assigned with a similar type of issue a few minutes back?

**Comment by stnguyen90** [comment]
@amyra98, how's your progress on this? Please let us know if you're still working on this within 24 hours so we can reassign it accordingly.

**Comment by Rutam21** [comment]
@stnguyen90 I guess I am good to work on this one now.

**Comment by Rutam21** [comment]
@stnguyen90 Hello, the contributor has not responded yet and I have been waiting for a while now to work on this. Kindly assign this to me so that I can raise a PR today. Thanks.

**Comment by stnguyen90** [comment]
Assigning to @Rutam21 since @aaryan2134 already has 4 issues. 🙏

**Comment by Rutam21** [comment]
@stnguyen90 The PR has been raised for this. https://github.com/utopia-php/messaging/pull/11
