### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/abuse’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4359]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/abuse](https://github.com/utopia-php/abuse) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/abuse](https://github.com/utopia-php/abuse) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/abuse](https://github.com/utopia-php/abuse).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by PMohanJ** [comment]
Hi, I would like to work on this issue.

**Comment by Meldiron** [comment]
@PMohanJ , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by PMohanJ** [comment]
Hi @Meldiron, I have a small issue while pushing my branch to the origin. The error is as follows:
```
zettabyte-X541UAK:~/Desktop/abuse$ git push origin feat-code-formatter 
remote: Permission to utopia-php/abuse.git denied to PMohanJ.
fatal: unable to access 'https://github.com/utopia-php/abuse.git/': The requested URL returned error: 403
```
Would you mind helping a bit; mean while I'll also try to figure out something.

**Comment by stnguyen90** [comment]
> Hi @Meldiron, I have a small issue while pushing my branch to the origin. 

@PMohanJ, yes, you won't be able to push to a repo you don't own. The typical flow for collaborators is to fork a repo and then submit a pull request. For more info on forking, you can refer to GitHub's [docs](https://docs.github.com/en/get-started/quickstart/fork-a-repo).

**Comment by PMohanJ** [comment]
@stnguyen90 Thanks for the information! I've submitted the PR.
