### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/logger’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4360]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/logger](https://github.com/utopia-php/logger) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/logger](https://github.com/utopia-php/logger) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/logger](https://github.com/utopia-php/logger).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aaryan2134** [comment]
Please assign me this issue

**Comment by Meldiron** [comment]
@aaryan2134 , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by toukirkhan** [comment]
please assign this to me

**Comment by stnguyen90** [comment]
@ItsAdityaKSingh, @toukirkhan Please consider picking a different type of issue so other contributors can try this one. We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by harshsiri110** [comment]
Hi @christyjacob4, I would like to work on this task. Could you please assign it to me?

**Comment by Meldiron** [comment]
@harshsiri110 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by harshsiri110** [comment]
Hi @Meldiron, I have raised the PR. Hoping to hear your views on it soon.

**Comment by stnguyen90** [comment]
@harshsiri110 Thanks for the PR! 🤯 Please give us some time to review it.
