### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/pay’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4361]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/pay](https://github.com/utopia-php/pay) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/pay](https://github.com/utopia-php/pay) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/pay](https://github.com/utopia-php/pay).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aaryan2134** [comment]
I would like to work on this issue. Please assign it to me

**Comment by Meldiron** [comment]
@aaryan2134 , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by byt3h3ad** [comment]
hi! I would like to be assigned this issue.

**Comment by Meldiron** [comment]
@byt3h3ad , thanks for your interest! 🙏 Happy hacking! 🎃
