### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/platform’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4362]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/platform](https://github.com/utopia-php/platform) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/platform](https://github.com/utopia-php/platform) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/platform](https://github.com/utopia-php/platform).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by omjikush09** [comment]
Can you assign this to me? I would like to work on this.

**Comment by Meldiron** [comment]
@omjikush09 , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by omjikush09** [comment]
@Meldiron, I have completed all issues. So please assign this to me.

**Comment by omjikush09** [comment]
Hi, @Meldiron created a PR. Please review it. https://github.com/utopia-php/platform/pull/3

**Comment by stnguyen90** [comment]
@omjikush09 Thanks for the PR! 🤯 Please give us some time to review it.
