### ISSUE TITLE
💄 Add Code Linter To ‘utopia-php/cli’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4364]
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/cli](https://github.com/utopia-php/cli) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/cli](https://github.com/utopia-php/cli) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/cli](https://github.com/utopia-php/cli).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by vasucp1207** [comment]
Hey, I want to work on this issue.

**Comment by Meldiron** [comment]
@vasucp1207 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by ItsAdityaKSingh** [comment]
Hey @Meldiron, could I work on resolving this issue asap as I have resolved one assigned earlier?

**Comment by vasucp1207** [comment]
@ItsAdityaKSingh this issue is assigned to me.

**Comment by stnguyen90** [comment]
@ItsAdityaKSingh We're assigning people on a first come first serve basis. If @vasucp1207 isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by ItsAdityaKSingh** [comment]
Yup, @stnguyen90, I totally understand that. I just saw the issue dormant for the last 3 days, so asked if I could resolve it :)
