### ISSUE TITLE
🔎 Add Code Analyzer To ‘utopia-php/framework’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4370]
# 💭 Introduction

Code analyzer is one of the most valuable tools in the open source world. It not only ensures every high quality of the code but also allows CI/CD to ensure this. A code analyzer can find a potential bug, unexpected null value, or type mismatch. Having a code analyzer set up should be a high priority for every project as it makes the project more stable and bug-proof.

Your task is to update our library [utopia-php/framework](https://github.com/utopia-php/framework) and implement a code analyzer. We would like to use [PHPStan](https://phpstan.org/) as our analyzer.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement the analyzer into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code analyzer in [utopia-php/framework](https://github.com/utopia-php/framework) (use [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8) as template)
- [ ]  Run code analyzer to check existing code, and update it if required
- [ ]  Submit a pull request in [utopia-php/framework](https://github.com/utopia-php/framework).

> Please configure PHPStan to max level (9). If that gives you too many problems that you cannot solve, please drop to level 8. If you have trouble with level 8 as well, let us know, and we can consider a lower level on some repositories.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by alrz1999** [comment]
Hey, Can I work on this issue?

**Comment by Meldiron** [comment]
@alrz1999 , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones.

**Comment by Rutam21** [comment]
@Meldiron I would like to work on this. I haven't worked on this type of issue prior to this. Thanks.

**Comment by stnguyen90** [comment]
@Rutam21 Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by ItsAdityaKSingh** [comment]
@stnguyen90 the issue has been unresolved for the past 10 days. Could it be reassigned to me?

**Comment by Rutam21** [comment]
@stnguyen90 I will raise a PR today. We had talks regarding it on Discord to try with lower levels of PhpStan. Thanks.
