### ISSUE TITLE
🔎 Add Code Analyzer To ‘utopia-php/swoole’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4372]
# 💭 Introduction

Code analyzer is one of the most valuable tools in the open source world. It not only ensures every high quality of the code but also allows CI/CD to ensure this. A code analyzer can find a potential bug, unexpected null value, or type mismatch. Having a code analyzer set up should be a high priority for every project as it makes the project more stable and bug-proof.

Your task is to update our library [utopia-php/swoole](https://github.com/utopia-php/swoole) and implement a code analyzer. We would like to use [PHPStan](https://phpstan.org/) as our analyzer.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement the analyzer into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code analyzer in [utopia-php/swoole](https://github.com/utopia-php/swoole) (use [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8) as template)
- [ ]  Run code analyzer to check existing code, and update it if required
- [ ]  Submit a pull request in [utopia-php/swoole](https://github.com/utopia-php/swoole).

> Please configure PHPStan to max level (9). If that gives you too many problems that you cannot solve, please drop to level 8. If you have trouble with level 8 as well, let us know, and we can consider a lower level on some repositories.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by nooras** [comment]
Done with previous Author remove task. Interested in this issue. Please assign me. Thanks

**Comment by nooras** [comment]
HI @Meldiron 
Need help
I made changes in below files
![image](https://user-images.githubusercontent.com/30138146/195982458-8f193a43-f97c-4d6b-90c2-8ee2d970d927.png)

on running composer check
i am getting lots of error

![image](https://user-images.githubusercontent.com/30138146/195982498-fc49488d-5695-4b6a-9d1f-6c22d70bebbd.png)

Can you please help me how to resolve that ?
Thanks

**Comment by nooras** [comment]
HI can anyone please help me @Meldiron @stnguyen90 @christyjacob4 in above issues.

**Comment by DevMike123** [comment]
> HI @Meldiron 
> Need help
> I made changes in below files
> ![image](https://user-images.githubusercontent.com/30138146/195982458-8f193a43-f97c-4d6b-90c2-8ee2d970d927.png)
> 
> on running composer check
> i am getting lots of error
> 
> ![image](https://user-images.githubusercontent.com/30138146/195982498-fc49488d-5695-4b6a-9d1f-6c22d70bebbd.png)
> 
> Can you please help me how to resolve that ?
> Do i need to resolved each error manually or there is some direct command??
> Thanks
> 

@nooras can you make a pr in the repo of your current changes so I can look into the errors through gitpod.

**Comment by DevMike123** [comment]
> HI can anyone please help me @Meldiron @stnguyen90 @christyjacob4 in above issues.

How many errors are there?

**Comment by nooras** [comment]
> > HI can anyone please help me @Meldiron @stnguyen90 @christyjacob4 in above issues.
> 
> How many errors are there?

Total 53
![image](https://user-images.githubusercontent.com/30138146/196029784-a91c445f-f6b0-46e9-b3be-f83f9fb1d3c8.png)
![image](https://user-images.githubusercontent.com/30138146/196029796-ebc54dbb-9c72-459e-a2d0-6130be63ea8c.png)
![image](https://user-images.githubusercontent.com/30138146/196029817-adc6e5dc-2f1e-40e7-a479-4cdd4a936eb0.png)

**Comment by nooras** [comment]
> > HI can anyone please help me @Meldiron @stnguyen90 @christyjacob4 in above issues.
> 
> You can drop PHPstan to level 8 if you cannot solve so many errors.

How to do that @DevMike123 ?

**Comment by Meldiron** [comment]
@nooras PHPStan level can be configured in `composer.json`. The command you added mentions `--level max`, so that would become `--level 8`
