### ISSUE TITLE
🔎 Add Code Analyzer To ‘utopia-php/analytics’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4376]
# 💭 Introduction

Code analyzer is one of the most valuable tools in the open source world. It not only ensures every high quality of the code but also allows CI/CD to ensure this. A code analyzer can find a potential bug, unexpected null value, or type mismatch. Having a code analyzer set up should be a high priority for every project as it makes the project more stable and bug-proof.

Your task is to update our library [utopia-php/analytics](https://github.com/utopia-php/analytics) and implement a code analyzer. We would like to use [PHPStan](https://phpstan.org/) as our analyzer.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement the analyzer into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code analyzer in [utopia-php/analytics](https://github.com/utopia-php/analytics) (use [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8) as template)
- [ ]  Run code analyzer to check existing code, and update it if required
- [ ]  Submit a pull request in [utopia-php/analytics](https://github.com/utopia-php/analytics).

> Please configure PHPStan to max level (9). If that gives you too many problems that you cannot solve, please drop to level 8. If you have trouble with level 8 as well, let us know, and we can consider a lower level on some repositories.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aaheli8** [comment]
Can I be assigned this issue

**Comment by Meldiron** [comment]
@aaheli8 Please consider picking a different type of issue so other contributors can try this one.

**Comment by aaheli8** [comment]
@Meldiron Yes Sure.

**Comment by BabyElias** [comment]
Hey! I would like to work on this issue.

**Comment by stnguyen90** [comment]
@BabyElias Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by BabyElias** [comment]
Thanks! Will begin working on this right away.

**Comment by BabyElias** [comment]
Created a Pull Request for the issue. Do let me know if I have to implement the workflow and also correct the errors found in PHP Files.

**Comment by Meldiron** [comment]
@BabyElias Yes please, correct all errors found by code analyzer.

**Comment by BabyElias** [comment]
@Meldiron The Analyser found almost 100 errors, I might need help correcting some of them as mentioned in the PR.

**Comment by stnguyen90** [comment]
@BabyElias, if it's too difficult to correct, you can try lowering the level a little so it doesn't pick up as many problems.

**Comment by BabyElias** [comment]
Okay

**Comment by Meldiron** [comment]
@BabyElias thanks for the PR! 🤯 Please give us some time to review it.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
