### ISSUE TITLE
🔎 Add Code Analyzer To ‘utopia-php/image’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4377]
# 💭 Introduction

Code analyzer is one of the most valuable tools in the open source world. It not only ensures every high quality of the code but also allows CI/CD to ensure this. A code analyzer can find a potential bug, unexpected null value, or type mismatch. Having a code analyzer set up should be a high priority for every project as it makes the project more stable and bug-proof.

Your task is to update our library [utopia-php/image](https://github.com/utopia-php/image) and implement a code analyzer. We would like to use [PHPStan](https://phpstan.org/) as our analyzer.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement the analyzer into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code analyzer in [utopia-php/image](https://github.com/utopia-php/image) (use [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8) as template)
- [ ]  Run code analyzer to check existing code, and update it if required
- [ ]  Submit a pull request in [utopia-php/image](https://github.com/utopia-php/image).

> Please configure PHPStan to max level (9). If that gives you too many problems that you cannot solve, please drop to level 8. If you have trouble with level 8 as well, let us know, and we can consider a lower level on some repositories.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aaryan2134** [comment]
I would like to work on this issue. Please assign it to me

**Comment by neelshah2409** [comment]
Hey, could you please assign me I would like to work on it.

**Comment by Meldiron** [comment]
@neelshah2409 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by neelshah2409** [comment]
Hey @Meldiron could you please review my PR.  
https://github.com/utopia-php/image/pull/23

**Comment by stnguyen90** [comment]
@neelshah2409 Thanks for the PR! 🤯 Please give us some time to review it.
