### ISSUE TITLE
🔎 Add Code Analyzer To ‘utopia-php/demo’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4378]
# 💭 Introduction

Code analyzer is one of the most valuable tools in the open source world. It not only ensures every high quality of the code but also allows CI/CD to ensure this. A code analyzer can find a potential bug, unexpected null value, or type mismatch. Having a code analyzer set up should be a high priority for every project as it makes the project more stable and bug-proof.

Your task is to update our library [utopia-php/demo](https://github.com/utopia-php/demo) and implement a code analyzer. We would like to use [PHPStan](https://phpstan.org/) as our analyzer.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement the analyzer into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code analyzer in [utopia-php/demo](https://github.com/utopia-php/demo) (use [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8) as template)
- [ ]  Run code analyzer to check existing code, and update it if required
- [ ]  Submit a pull request in [utopia-php/demo](https://github.com/utopia-php/demo).

> Please configure PHPStan to max level (9). If that gives you too many problems that you cannot solve, please drop to level 8. If you have trouble with level 8 as well, let us know, and we can consider a lower level on some repositories.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aaryan2134** [comment]
I would like to work on this issue. Please assign it to me

**Comment by Meldiron** [comment]
@aaryan2134 , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by stnguyen90** [comment]
@Princeton21 Please consider picking a different type of issue so other contributors can try this one. We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by thinkverse** [comment]
Since no one is assigned this issue, I can take care of it. 🙂

**Comment by tessamero** [comment]
@thinkverse , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by thinkverse** [comment]
> thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

Not sure why this was needed in the demo app, but PR was submitted anyway. 👍

**Comment by Meldiron** [comment]
@thinkverse Hey there 👋 We decided we want to start lining all of the repositories since they all have some PHP code in them. No worries if the linter didn't find anything, it mainly added a test so that all future contributions will have proper code style.
