### ISSUE TITLE
🔎 Add Code Analyzer To ‘utopia-php/pay’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4384]
# 💭 Introduction

Code analyzer is one of the most valuable tools in the open source world. It not only ensures every high quality of the code but also allows CI/CD to ensure this. A code analyzer can find a potential bug, unexpected null value, or type mismatch. Having a code analyzer set up should be a high priority for every project as it makes the project more stable and bug-proof.

Your task is to update our library [utopia-php/pay](https://github.com/utopia-php/pay) and implement a code analyzer. We would like to use [PHPStan](https://phpstan.org/) as our analyzer.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement the analyzer into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code analyzer in [utopia-php/pay](https://github.com/utopia-php/pay) (use [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8) as template)
- [ ]  Run code analyzer to check existing code, and update it if required
- [ ]  Submit a pull request in [utopia-php/pay](https://github.com/utopia-php/pay).

> Please configure PHPStan to max level (9). If that gives you too many problems that you cannot solve, please drop to level 8. If you have trouble with level 8 as well, let us know, and we can consider a lower level on some repositories.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Sin-Sumit** [comment]
Please assign me this issue.

**Comment by Meldiron** [comment]
@Sin-Sumit I remember assigning issues to you last year! So happy to see you around this year too 🤩 Happy hacking 🎃

**Comment by ItsAdityaKSingh** [comment]
@Sin-Sumit Are you still working on this issue?

**Comment by Meldiron** [comment]
@Sin-Sumit Hey there 👋 Can you please confirm with me if you are working on this issue?

**Comment by byt3h3ad** [comment]
hi! i would like to be assigned this!

**Comment by stnguyen90** [comment]
@byt3h3ad assigned! Thanks for your interest!

**Comment by byt3h3ad** [comment]
running the analyzer at level 9 gives 100 problems and running it at level 8 gives 98 problems? can it be reduced further?

**Comment by stnguyen90** [comment]
> running the analyzer at level 9 gives 100 problems and running it at level 8 gives 98 problems? can it be reduced further?

Sure!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
