### ISSUE TITLE
🔎 Add Code Analyzer To ‘utopia-php/platform’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4385]
# 💭 Introduction

Code analyzer is one of the most valuable tools in the open source world. It not only ensures every high quality of the code but also allows CI/CD to ensure this. A code analyzer can find a potential bug, unexpected null value, or type mismatch. Having a code analyzer set up should be a high priority for every project as it makes the project more stable and bug-proof.

Your task is to update our library [utopia-php/platform](https://github.com/utopia-php/platform) and implement a code analyzer. We would like to use [PHPStan](https://phpstan.org/) as our analyzer.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement the analyzer into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code analyzer in [utopia-php/platform](https://github.com/utopia-php/platform) (use [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8) as template)
- [ ]  Run code analyzer to check existing code, and update it if required
- [ ]  Submit a pull request in [utopia-php/platform](https://github.com/utopia-php/platform).

> Please configure PHPStan to max level (9). If that gives you too many problems that you cannot solve, please drop to level 8. If you have trouble with level 8 as well, let us know, and we can consider a lower level on some repositories.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by SayuruRehan** [comment]
Hey, can I be assigned to this?

**Comment by Meldiron** [comment]
@SayuruRehan , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by mohith2883** [comment]
hey @Meldiron can you assign me ?

**Comment by Meldiron** [comment]
@SayuruRehan Hey there 👋 Can you please confirm with me if you are working on this issue?

**Comment by ItsAdityaKSingh** [comment]
@Meldiron, this issue has also been dormant for the past 10 days. Could I work on resolving this?

**Comment by Meldiron** [comment]
Reassigning due to inactivity.

**Comment by mohith2883** [comment]
Hey @Meldiron  I asked you first :-(

**Comment by ItsAdityaKSingh** [comment]
> Hey @Meldiron I asked you first :-(

If that is so then @Meldiron, could you reassign me with https://github.com/appwrite/appwrite/issues/4451 and reassign this to @mohith2883? If that's ok :)

**Comment by stnguyen90** [comment]
@mohith2883, I've assigned this to you in case you'll be able to work on this.

**Comment by stnguyen90** [comment]
@mohith2883 are you still working on this or should we unassign you?

**Comment by mohith2883** [comment]
Hey @stnguyen90 I am busy with my college stuff so I am not working on it

**Comment by byt3h3ad** [comment]
hi! i would like to be assigned this!

**Comment by stnguyen90** [comment]
> hi! i would like to be assigned this!

@byt3h3ad assigned! Thanks for your interest!

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
