### ISSUE TITLE
🔎 Add Code Analyzer To ‘utopia-php/cli’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4387]
# 💭 Introduction

Code analyzer is one of the most valuable tools in the open source world. It not only ensures every high quality of the code but also allows CI/CD to ensure this. A code analyzer can find a potential bug, unexpected null value, or type mismatch. Having a code analyzer set up should be a high priority for every project as it makes the project more stable and bug-proof.

Your task is to update our library [utopia-php/cli](https://github.com/utopia-php/cli) and implement a code analyzer. We would like to use [PHPStan](https://phpstan.org/) as our analyzer.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement the analyzer into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code analyzer in [utopia-php/cli](https://github.com/utopia-php/cli) (use [https://github.com/utopia-php/ab/pull/8](https://github.com/utopia-php/ab/pull/8) as template)
- [ ]  Run code analyzer to check existing code, and update it if required
- [ ]  Submit a pull request in [utopia-php/cli](https://github.com/utopia-php/cli).

> Please configure PHPStan to max level (9). If that gives you too many problems that you cannot solve, please drop to level 8. If you have trouble with level 8 as well, let us know, and we can consider a lower level on some repositories.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by StarTrooper08** [comment]
Hello Christy, I would love to work on this issue!

I've been assigned one issue. I have completed that task.
Can I work on this issue?

**Comment by Meldiron** [comment]
@StarTrooper08 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by ItsAdityaKSingh** [comment]
Hey @Meldiron, could I work on this issue if it's not resolved yet?
I have resolved my previous issue and would like to resolve a new one here.

**Comment by stnguyen90** [comment]
@ItsAdityaKSingh We're assigning people on a first come first serve basis. If @StarTrooper08 isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by ItsAdityaKSingh** [comment]
@Meldiron It's been 3 days since it was assigned so if there's no progress, I could resolve it asap. @StarTrooper08 have you worked on resolving the issue?

**Comment by stnguyen90** [comment]
@ItsAdityaKSingh Let's give the assignee at least a week. After that, we can consider a new assignee for inactivity.

**Comment by ItsAdityaKSingh** [comment]
@stnguyen90 Since the issue has been open since 9 days now, could I now work upon resolving it?

**Comment by ItsAdityaKSingh** [comment]
@stnguyen90 are there any updates regarding the reassignment of this issue?

**Comment by stnguyen90** [comment]
@StarTrooper08 How's your progress on this? Are you still working on this or can it be reassigned? Please respond within 24 hours or we'll need to reassign the issue.

**Comment by ItsAdityaKSingh** [comment]
Hey @stnguyen90! Since there's no response, could I start working on resolving this issue?

**Comment by stnguyen90** [comment]
Reassigning to @ItsAdityaKSingh due to inactivity.

**Comment by ItsAdityaKSingh** [comment]
Hey, I have put up a PR at - https://github.com/open-runtimes/examples/pull/100
Waiting for the review, @stnguyen90 @Meldiron :)

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
