### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/framework’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4393]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/framework](https://github.com/utopia-php/framework) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/framework](https://github.com/utopia-php/framework) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/framework](https://github.com/utopia-php/framework).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aadityaagrawal** [comment]
Hi, can you please assign it to me?

**Comment by Meldiron** [comment]
@aadityaagrawal , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Aadeesh11** [comment]
I would like to work on this issue, can you assign this to me?

**Comment by aaryan2134** [comment]
Can I be please assigned this issue?

**Comment by Yashsomalkar** [comment]
@Meldiron  
Can this be assigned to me?

**Comment by gaurav-iitb** [comment]
please assign this to me

**Comment by abnegate** [comment]
@Aadeesh11 Thanks for your interest! Happy hacking 🎃

**Comment by Aadeesh11** [comment]
@abnegate I have raised a PR making the required changes.

**Comment by codercatdev** [comment]
@Aadeesh11 Thanks for the PR! 🤯 Please give us some time to review it.
