### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/preloader’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4395]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/preloader](https://github.com/utopia-php/preloader) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/preloader](https://github.com/utopia-php/preloader) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/preloader](https://github.com/utopia-php/preloader).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Meldiron** [comment]
@samarth2812 I have assigned you an issue of this type already. I would love it if you look at different types of issues as well. You can learn more on out [website](https://hacktoberfest.appwrite.io/).

**Comment by aaryan2134** [comment]
Can I please be assigned this issue?

**Comment by Sanket1308** [comment]
Kindly assign me this issue. I would like to work on this. I'm not working on any issue in this repository🚀

**Comment by Ambareen09** [comment]
Hey! Can you please assign me this issue.

**Comment by aaryan2134** [comment]
Can I be please assigned this issue?

**Comment by adityaacse** [comment]
Hey @christyjacob4 , can you assign this to me?

**Comment by abnegate** [comment]
@Ambareen09 Thanks for your interest! Happy hacking 🎃
