### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/system’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4397]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/system](https://github.com/utopia-php/system) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/system](https://github.com/utopia-php/system) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/system](https://github.com/utopia-php/system).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by aadityaagrawal** [comment]
Hi, can you please assign it to me?

**Comment by Meldiron** [comment]
@aadityaagrawal , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by aadityaagrawal** [comment]
I created a PR please check.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
