### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/storage’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4398]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/storage](https://github.com/utopia-php/storage) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/storage](https://github.com/utopia-php/storage) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by omjikush09** [comment]
Hi, Can I work on this?

**Comment by Meldiron** [comment]
@omjikush09 , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by aadityaagrawal** [comment]
Hi, can you please assign it to me?

**Comment by omjikush09** [comment]
Hi, @Meldiron  Can now I work on this..? I have created PR for my previous assigned issue.  Ya, I want to take other issues but I don't know PHP. So I can't work 🥲🥲 on them.

**Comment by Meldiron** [comment]
@aadityaagrawal , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by samarth2812** [comment]
Hi, Can you please assign this to me?

**Comment by Meldiron** [comment]
@samarth2812 I have assigned you an issue of this type already. I would love it if you look at different types of issues as well. You can learn more on out [website](https://hacktoberfest.appwrite.io/).

**Comment by abhishekdd** [comment]
@Meldiron , could you please assign this to me?

**Comment by aaryan2134** [comment]
Can I be please assigned this issue?

**Comment by Yashsomalkar** [comment]
@Meldiron  
Can this be assigned to me?

**Comment by abnegate** [comment]
@abhishekdd Thanks for your interest! Happy hacking 🎃
