### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/database’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4399]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/database](https://github.com/utopia-php/database) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/database](https://github.com/utopia-php/database) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/database](https://github.com/utopia-php/database).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by rohitkori** [comment]
@christyjacob4 can you please assign it to me?

**Comment by Meldiron** [comment]
@rohitkori , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by aaryan2134** [comment]
Can I be please assigned this issue?

**Comment by maxslimb** [comment]
@Meldiron can I work on this, please?

**Comment by Yashsomalkar** [comment]
@Meldiron  
Can this be assigned to me?

**Comment by rym-oualha** [comment]
Can I help with this issue ?

**Comment by abnegate** [comment]
@samarth2812 @aaryan2134 @maxslimb It looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by abnegate** [comment]
@Yashsomalkar Happy hacking 🎃

**Comment by Yashsomalkar** [comment]
> @Yashsomalkar Happy hacking 🎃 

Thanks for assigning  I am working on it 😁. So happy to work with the org.

**Comment by Yashsomalkar** [comment]
@Meldiron  Would love to have your review :)

**Comment by Yashsomalkar** [comment]
@abnegate i made a PR

**Comment by stnguyen90** [comment]
@Yashsomalkar Thanks for the PR! 🤯 Please give us some time to review it.
