### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/analytics’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4400]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/analytics](https://github.com/utopia-php/analytics) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/analytics](https://github.com/utopia-php/analytics) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/analytics](https://github.com/utopia-php/analytics).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by rohitkori** [comment]
@christyjacob4 can you assign it to me?

**Comment by samarth2812** [comment]
Hi, Can you please assign this to me?

**Comment by aaryan2134** [comment]
Can I be please assigned this issue?

**Comment by aaheli8** [comment]
Can you please assign me this issue

**Comment by Yashsomalkar** [comment]
@Meldiron  can i work for this issue ?

**Comment by rym-oualha** [comment]
Can I still work on this ?

**Comment by Kunal-8789** [comment]
@Meldiron pls assign this issue to me. I am interested.

**Comment by abnegate** [comment]
As  this is a first-come first-served issue, @aaryan2134  has been assigned. Thanks for the interest and happy hacking 🎃

**Comment by aaryan2134** [comment]
> 

Thank you. Will get it done soon

**Comment by aaryan2134** [comment]
https://github.com/utopia-php/analytics/pull/25
I have added my pull request

**Comment by stnguyen90** [comment]
@aaryan2134 Thanks for the PR! 🤯 Please give us some time to review it.
