### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/image’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4401]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/image](https://github.com/utopia-php/image) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/image](https://github.com/utopia-php/image) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/image](https://github.com/utopia-php/image).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Tiansing** [comment]
please assign me to do this task

**Comment by Meldiron** [comment]
@Tiansing , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by samarth2812** [comment]
Hi, Can you please assign this to me?

**Comment by Meldiron** [comment]
@samarth2812 I have assigned you an issue of this type already. I would love it if you look at different types of issues as well. You can learn more on out [website](https://hacktoberfest.appwrite.io/).

**Comment by Tiansing** [comment]
@Meldiron Can I take this task now? I already done updating the previous assignment. Thank you!

**Comment by Sanket1308** [comment]
Kindly assign me this issue. I would like to work on this.🚀

**Comment by Ambareen09** [comment]
Hey! I'd be interested in this issue! Kindly assign me this.

**Comment by aaryan2134** [comment]
Can I be please assigned this issue?

**Comment by akarsh-jain-790** [comment]
Hey, Can you assign this issue to me?

**Comment by adityaacse** [comment]
Hey @christyjacob4, I want to work on this task. Can you assign this to me?

**Comment by rym-oualha** [comment]
Is help still needed ? I can work on this task

**Comment by abnegate** [comment]
As this is a first-come first-served issue, @Sanket1308 has been assigned. Thanks for the interest and happy hacking 🎃

**Comment by Sanket1308** [comment]
Thank you so much for assigning me this issue, @abnegate. I'm starting to work on it🚀

**Comment by Tiansing** [comment]
@abnegate if ever this is not accomplished yet, please assign this to me thank you

**Comment by stnguyen90** [comment]
@Tiansing Let's give @Sanket1308 at least 7 days to see if they are actively working on it. Hacktoberfest is a month-long event and we don't want to create any pressure on participants. In the meantime, you can also check our [website](https://hacktoberfest.appwrite.io/) for more issues

**Comment by Sanket1308** [comment]
Hey, I have created PR. You can check it [here](https://github.com/utopia-php/image/pull/24)🚀
