### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/demo’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4402]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/demo](https://github.com/utopia-php/demo) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/demo](https://github.com/utopia-php/demo) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/demo](https://github.com/utopia-php/demo).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Tiansing** [comment]
Can you assign me to do this task and kindly send the details

**Comment by Meldiron** [comment]
@Tiansing , thanks for your interest! 🙏 Happy hacking! 🎃

All details should be mentioned in the issue description. If you have any further questions, don't hesitate to ask 😇

**Comment by Tiansing** [comment]
Already submitted a PR https://github.com/utopia-php/demo/pull/10#issue-1403036760

**Comment by neelshah2409** [comment]
Could I work on it ??

**Comment by Meldiron** [comment]
@neelshah2409 , we're assigning people on a first come first serve basis. You can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).
