### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/orchestration’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4404]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/orchestration](https://github.com/utopia-php/orchestration) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/orchestration](https://github.com/utopia-php/orchestration) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/orchestration](https://github.com/utopia-php/orchestration).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by rohitkori** [comment]
can you assign it to me please?

**Comment by Meldiron** [comment]
@rohitkori , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Meldiron** [comment]
@diamant3 , thanks for your interest! 🙏 Happy hacking! 🎃
