### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/abuse’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4405]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/abuse](https://github.com/utopia-php/abuse) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/abuse](https://github.com/utopia-php/abuse) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/abuse](https://github.com/utopia-php/abuse).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Tiansing** [comment]
I can do this task please assign me and send the details

**Comment by nooras** [comment]
Interested :) Please assign me @Meldiron @christyjacob4

**Comment by Meldiron** [comment]
@nooras , we're assigning people on a first come first serve basis. If @Tiansing  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by ItsAdityaKSingh** [comment]
@Tiansing are you working on resolving this issue?

**Comment by biswadeep25** [comment]
Hey @Meldiron Can you assign this issue to me?

**Comment by Tiansing** [comment]
@Meldiron yes I'm about to submit a pull request regarding this issue. Thanks

**Comment by Tiansing** [comment]
Hey @Meldiron & @christyjacob4, I have already submitted a PR you can check it out here: https://github.com/utopia-php/abuse/pull/34
