### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/messaging’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4406]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/messaging](https://github.com/utopia-php/messaging) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/messaging](https://github.com/utopia-php/messaging) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DonBarbaro** [comment]
Hi, can u assign it to me? I can work on this

**Comment by Meldiron** [comment]
@DonBarbaro , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Ln11211** [comment]
hey @Meldiron , Looks like there is no PR yet, will it be possible to reassign this to me?

**Comment by stnguyen90** [comment]
@Ln11211 Let's give the assignee at least a week. After that, we can consier a new assignee for inactivity.

**Comment by Ln11211** [comment]
hello @stnguyen90 , can I begin my work? :)

**Comment by tessamero** [comment]
@Ln11211 i have assigned you the issue. Happy hacking :-)

**Comment by Ln11211** [comment]
here you go

**Comment by tessamero** [comment]
@Ln11211 Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by mohith2883** [comment]
hey @stnguyen90 can you assign me

**Comment by stnguyen90** [comment]
@mohith2883 Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by mohith2883** [comment]
@stnguyen90 Thanks for assigning me :-)

**Comment by mohith2883** [comment]
Hey @Meldiron @stnguyen90  can you review the PR

**Comment by mohith2883** [comment]
Hey @Meldiron @stnguyen90 I had committed the changes can you please review it :-)
Only 1 day is left 👀
