### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/pay’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4408]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/pay](https://github.com/utopia-php/pay) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/pay](https://github.com/utopia-php/pay) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/pay](https://github.com/utopia-php/pay).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Aishubalaji** [comment]
hey, can i take this issue.

**Comment by Meldiron** [comment]
@Aishubalaji , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by rohitkori** [comment]
@Meldiron can you assign it to me please?

**Comment by Meldiron** [comment]
@rohitkori , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by ItsAdityaKSingh** [comment]
Hey @rohitkori! Are you still working on this?

**Comment by stnguyen90** [comment]
@ItsAdityaKSingh, considering Hacktoberfest is the whole month, we can give people at least 7 days to work on issues.

@ItsAdityaKSingh please let us know if you can't work on the issue and we'll reassign it accordingly.

**Comment by rohitkori** [comment]
> Hey @rohitkori! Are you still working on this?

i have made a pr please look into it
