### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/platform’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4409]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/platform](https://github.com/utopia-php/platform) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/platform](https://github.com/utopia-php/platform) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/platform](https://github.com/utopia-php/platform).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Meldiron** [comment]
@omjikush09 , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by omjikush09** [comment]
@Meldiron  Created pull request https://github.com/utopia-php/platform/pull/2 . Please review...... 😊😊

**Comment by ChandanChainani** [comment]
@Meldiron please close the issue since it is complete
