### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/locale’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4410]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/locale](https://github.com/utopia-php/locale) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/locale](https://github.com/utopia-php/locale) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/locale](https://github.com/utopia-php/locale).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Aishubalaji** [comment]
hey, can i take this issue.

**Comment by Meldiron** [comment]
@Aishubalaji , looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by rohitkori** [comment]
@Meldiron can you assign it to me?

**Comment by Meldiron** [comment]
@rohitkori , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by mohith2883** [comment]
Hey @Meldiron can you reassign it to me

**Comment by Meldiron** [comment]
@rohitkori Hey there 👋 Can you please confirm with me if you are working on this issue?

**Comment by rohitkori** [comment]
> @rohitkori Hey there 👋 Can you please confirm with me if you are working on this issue?

I have made a pr could you please look into it.

**Comment by mohith2883** [comment]
hey @Meldiron can I do it since no PR is raised

**Comment by rohitkori** [comment]
my pull request is not accepted till now can you please look into it.

**Comment by ItsAdityaKSingh** [comment]
@Meldiron This issue has been dormant for the past ten days. I would like to be assigned to this if possible, as I want to resolve this :)

**Comment by ChandanChainani** [comment]
@Meldiron please close the issue since it is complete
