### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/cli’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4411]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/cli](https://github.com/utopia-php/cli) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/cli](https://github.com/utopia-php/cli) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/cli](https://github.com/utopia-php/cli).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by StarTrooper08** [comment]
can I work on this issue?

**Comment by StarTrooper08** [comment]
1. Authors in readme file of utopia-php/cli
![image](https://user-images.githubusercontent.com/72031540/194845357-72a12c8a-59c6-4601-80a4-d4efbd021562.png)

2. composer.json file

![image](https://user-images.githubusercontent.com/72031540/194845484-1813edad-b49d-4b06-8e53-404cee165d7e.png)

should I remove email of the author too from composer.json file?

**Comment by Meldiron** [comment]
@StarTrooper08 That is correct, please remove authors array from `composer.json`, and the whole Authors section from the README.

**Comment by Meldiron** [comment]
No need to be scared, I will review the PR once you submit it and guide you if there is anything wrong 😇

**Comment by StarTrooper08** [comment]
ok, thanks @Meldiron :+1:

**Comment by StarTrooper08** [comment]
:heavy_check_mark:   Done

**Comment by ChandanChainani** [comment]
@Meldiron please close the issue since it is complete
