### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/registry’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4413]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/registry](https://github.com/utopia-php/registry) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/registry](https://github.com/utopia-php/registry) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/registry](https://github.com/utopia-php/registry).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Ananthavijay** [comment]
Can I work on this issue?

**Comment by Meldiron** [comment]
@Ananthavijay , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by mohith2883** [comment]
hey @Meldiron can you reassign it to me

**Comment by byt3h3ad** [comment]
hey! is this up for reassignment?

**Comment by stnguyen90** [comment]
@mohith2883 Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by stnguyen90** [comment]
@byt3h3ad We're assigning people on a first come first serve basis. If @mohith2883 isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by mohith2883** [comment]
@stnguyen90  I raised a PR can you review and tell me if I missed any document

**Comment by mohith2883** [comment]
@stnguyen90  @Meldiron  can you review it
