### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/audit’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4414]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/audit](https://github.com/utopia-php/audit) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/audit](https://github.com/utopia-php/audit) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/audit](https://github.com/utopia-php/audit).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Aishubalaji** [comment]
Hey, assign me this issue.

**Comment by Meldiron** [comment]
@Aishubalaji , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Aishubalaji** [comment]
I have created a pull request. Check and ping me if there are any changes!

**Comment by Aishubalaji** [comment]
Hey, Sorry for late reply. I have created a pull request :) Kindly check and ping me if there are any changes needed.

**Comment by ChandanChainani** [comment]
@Meldiron please close the issue since it is complete.
