### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/domains’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4415]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/domains](https://github.com/utopia-php/domains) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/domains](https://github.com/utopia-php/domains) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/domains](https://github.com/utopia-php/domains).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Aishubalaji** [comment]
Hey, assign me this issue.

**Comment by Meldiron** [comment]
@Aishubalaji , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Medhanshverma** [comment]
Hey can you assign this issue to me.

**Comment by Tiansing** [comment]
Can I take over this issue? I think there's no update with @Aishubalaji

**Comment by Meldiron** [comment]
@Medhanshverma , we're assigning people on a first come first serve basis. If @Aishubalaji  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

@Tiansing Let's give @Aishubalaji at least 7 days to see if he is actively working on it. Hacktoberfest is a month-long event, we don't want to create any pressure on participants. In the meantime, you can also check our [website](https://hacktoberfest.appwrite.io/) for more issues

**Comment by Aishubalaji** [comment]
Hey, Sorry for late reply. I have created a pull request. Ping me if there are any changes needed :)

**Comment by Tiansing** [comment]
> @Medhanshverma , we're assigning people on a first come first serve basis. If @Aishubalaji isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).
> 
> @Tiansing Let's give @Aishubalaji at least 7 days to see if he is actively working on it. Hacktoberfest is a month-long event, we don't want to create any pressure on participants. In the meantime, you can also check our [website](https://hacktoberfest.appwrite.io/) for more issues

**okay, just notify me if there's a need of my help to resolve this issue**

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
