### ISSUE TITLE
🤝 Update Authors in ‘utopia-php/config’

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4416]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to remove all authors from our libraries. This will display that all of our open source work is a collective effort by the Appwrite team and community. Individual credits make no sense!

Your task is to update our library [utopia-php/config](https://github.com/utopia-php/config) and remove all mentions of authors.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Remove authors from [utopia-php/config](https://github.com/utopia-php/config) in `README.md` , `composer.json`, and possibly some `.php` files ([example](https://github.com/utopia-php/framework/blob/810c707e0a7cc686e95f80f6a9845b5a18cb5cfb/tests/Validator/WhiteListTest.php#L3-L13) of php file author)
- [ ]  Submit a pull request in [utopia-php/config](https://github.com/utopia-php/config).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by maxslimb** [comment]
Hey, I'll do this task

**Comment by Meldiron** [comment]
@maxslimb , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by maxslimb** [comment]
Hey, I have put a pull Request - https://github.com/utopia-php/config/pull/8
Please Review 🙏

**Comment by curranConcepts** [comment]
hey, I would like to be assigned to this issue.

**Comment by Meldiron** [comment]
@curranConcepts , we're assigning people on a first come first serve basis. You can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by ChandanChainani** [comment]
@Meldiron seems the issue is resolved please can you close the issue
