### ISSUE TITLE
🐛 Bug Report: Invalid Timestamp in Realtime Payload

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4446]
### 👟 Reproduction steps

1. Subscribe to `documents` channel
2. Update an accessible document

For more info on our Realtime API, refer to our [docs](https://appwrite.io/docs/realtime).

### 👍 Expected behavior

The `timestamp` is an ISO string like `2022-10-10T13:37:13.780+00:00`.

### 👎 Actual Behavior

The `timestamp` is missing the timezone. For example:

```json
{
  "type": "event",
  "data": {
    "events": [
      "databases.default.collections.usernames.documents.63419a9e214ec9b7c5a4.update",
      "databases.*.collections.*.documents.*.update",
      "databases.default.collections.*.documents.63419a9e214ec9b7c5a4.update",
      "databases.*.collections.*.documents.63419a9e214ec9b7c5a4.update",
      "databases.*.collections.usernames.documents.63419a9e214ec9b7c5a4.update",
      "databases.default.collections.usernames.documents.*.update",
      "databases.*.collections.usernames.documents.*.update",
      "databases.default.collections.*.documents.*.update",
      "databases.default.collections.usernames.documents.63419a9e214ec9b7c5a4",
      "databases.*.collections.*.documents.*",
      "databases.default.collections.*.documents.63419a9e214ec9b7c5a4",
      "databases.*.collections.*.documents.63419a9e214ec9b7c5a4",
      "databases.*.collections.usernames.documents.63419a9e214ec9b7c5a4",
      "databases.default.collections.usernames.documents.*",
      "databases.*.collections.usernames.documents.*",
      "databases.default.collections.*.documents.*",
      "databases.default.collections.usernames",
      "databases.*.collections.*",
      "databases.default.collections.*",
      "databases.*.collections.usernames",
      "databases.default",
      "databases.*"
    ],
    "channels": [
      "documents",
      "databases.default.collections.usernames.documents",
      "databases.default.collections.usernames.documents.63419a9e214ec9b7c5a4"
    ],
    "timestamp": "2022-10-13 18:19:34.967",
    "payload": {
      "username": "hello",
      "$id": "63419a9e214ec9b7c5a4",
      "$createdAt": "2022-10-08T15:43:26.136+00:00",
      "$updatedAt": "2022-10-13T18:19:34.958+00:00",
      "$permissions": [
        "delete(\"user:632235088a84d5fbdb45\")",
        "read(\"user:632235088a84d5fbdb45\")",
        "update(\"user:632235088a84d5fbdb45\")"
      ],
      "$collectionId": "usernames",
      "$databaseId": "default"
    }
  }
}
```

In addition, the [Realtime docs](https://appwrite.io/docs/realtime#payload) need to be updated as it says timestamp is:

> The [UNIX timestamp](https://en.wikipedia.org/wiki/Unix_time) from the server to ensure consistency across all client platforms and real-time technologies.

## Tasks

1. [ ] Update the timestamp format [here](https://github.com/appwrite/appwrite/blob/b6eef3a88659bac99d262530c77223590b933b85/app/realtime.php#L240)
2. [ ] Update the timestamp format [here](https://github.com/appwrite/appwrite/blob/b6eef3a88659bac99d262530c77223590b933b85/app/realtime.php#L267)
4. [ ] Update the timestamp format [here](https://github.com/appwrite/appwrite/blob/b6eef3a88659bac99d262530c77223590b933b85/src/Appwrite/Messaging/Adapter/Realtime.php#L152)
5. [ ] Update the docs [here](https://github.com/appwrite/docs/blob/main/app/views/docs/realtime.phtml#L411)
6. [ ] Update the docs [here](https://github.com/appwrite/docs/blob/main/app/views/docs/realtime.phtml#L451)

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I tested against Appwrite Version 1.0.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by toukirkhan** [comment]
@stnguyen90 assign this to me

**Comment by stnguyen90** [comment]
@toukirkhan Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by Akshay-Rana-Gujjar** [comment]
@toukirkhan buddy are you still working on this issue, as I can see you have removed yourself from this issue.
If you are not working I would like to work on this.

cc: @stnguyen90

**Comment by toukirkhan** [comment]
> @toukirkhan buddy are you still working on this issue, as I can see you have removed yourself from this issue.
> If you are not working I would like to work on this.
> 
> cc: @stnguyen90 

Yeah sure you can work on this my friend.

**Comment by Akshay-Rana-Gujjar** [comment]
Thanks

@stnguyen90 could you please assign this to me?
