### ISSUE TITLE
⚡ Write a deepgramAudioSummary() Function using Dart

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4451]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramAudioSummary()` function using **Dart**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a summary text from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Dart**.
- Knowledge to implement **deepgramAudioSummary** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramAudioSummary()` in `Dart/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by GunjanDhanuka** [comment]
Hey @christyjacob4  can you assign me this issue?

**Comment by vj-codes** [comment]
I would like to work on this please!

**Comment by tessamero** [comment]
@GunjanDhanuka , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by tessamero** [comment]
@vj-codes , we are assigning people on a first come first serve basis. If @GunjanDhanuka  isn't able to complete this issue, we will reassign accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by ItsAdityaKSingh** [comment]
@GunjanDhanuka, are you still working on this?

**Comment by Meldiron** [comment]
@GunjanDhanuka Hey there 👋 Can you please confirm with me if you are working on this issue?

**Comment by ItsAdityaKSingh** [comment]
If unresolved, could you please reassign it to me @Meldiron?

**Comment by stnguyen90** [comment]
@vj-codes, are you still interested in working on this? If not, we'll reassign it to @ItsAdityaKSingh. Please respond within 24 hours.

**Comment by ItsAdityaKSingh** [comment]
Could this now be assigned to me @stnguyen90?

**Comment by stnguyen90** [comment]
@ItsAdityaKSingh assigned! Thanks for your patience! Happy hacking!

**Comment by ItsAdityaKSingh** [comment]
Hey @Meldiron @stnguyen90, I have made a PR @https://github.com/open-runtimes/examples/pull/122
Please review the changes :)
