### ISSUE TITLE
⚡ Write a deepgramTopicDetection() Function using PHP

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4456]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramTopicDetection()` function using **PHP**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Detect list of topic from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **PHP**.
- Knowledge to implement **deepgramTopicDetection** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramTopicDetection()` in `PHP/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by neelshah2409** [comment]
Hey,I want to work on it .

**Comment by neelshah2409** [comment]
> Hey,I want to work on it .

@christyjacob4 may I start working on it .

**Comment by tessamero** [comment]
@neelshah2409 Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by CoderGaurav01** [comment]
hi, I would like to work on this issue.

**Comment by tessamero** [comment]
@CoderGaurav01 , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by sebabratakundu** [comment]
Hi @stnguyen90, I would like to work on this issue. can you please assign this issue to me?
