### ISSUE TITLE
⚡ Write a deepgramTopicDetection() Function using Python

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4457]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramTopicDetection()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Detect list of topic from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **deepgramTopicDetection** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramTopicDetection()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Rinshin-Jalal** [comment]
I CAN DO THIS

**Comment by toukirkhan** [comment]
please assign me this one

**Comment by neelshah2409** [comment]
I wanted to work on this issue !!

**Comment by tessamero** [comment]
@Rinshin-Jalal, @toukirkhan , and @neelshah2409 Looks like you all have some issues assigned to you already (just recently). We request you complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by vj-codes** [comment]
@tessamero heyyo I would like to work on this please!

**Comment by Rinshin-Jalal** [comment]
ok @tessamero 
Actually, I have done this already ( only need to add a pull request )

So can you assign me to this one instead of  #4465

**Comment by gagandeepp** [comment]
@christyjacob4 @Meldiron Interested,please assign

**Comment by tessamero** [comment]
@gagandeepp  Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.


@vj-codes , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by vj-codes** [comment]
Thanks @tessamero

**Comment by vj-codes** [comment]
update : I am working on it

**Comment by arsh-anwr** [comment]
@stnguyen90 can i work on this issue ?

**Comment by stnguyen90** [comment]
> @stnguyen90 can i work on this issue ?

@arsh-anwr, assigned! Thanks for your interest! 🙏

**Comment by arsh-anwr** [comment]
@arsh-anwr I have raised a PR implementing the required function. please review it and I'll be happy if you can assign me some other issues to work on 
![https://github.com/open-runtimes/examples/pull/129](url)

**Comment by Rinshin-Jalal** [comment]
> @stnguyen90  I have raised a PR implementing the required function. please review it and I'll be happy if you can assign me some other issues to work on.

I think @stnguyen90 means :`it is already assigned to ... ( Me, PR is in review stage😅 ) .... So thank for your interest`

**Comment by arsh-anwr** [comment]
@Rinshin-Jalal but @stnguyen90 really assigned it to me 🥲 and in the comments it says you’ve other issues assigned to you

**Comment by Rinshin-Jalal** [comment]
> @Rinshin-Jalal but @stnguyen90 really assigned it to me 🥲 and in the comments it says you’ve other issues assigned to you 

Ok that was funny
I got confused
I have been working for a lot of similar ( just 5 ) issues

**Comment by arsh-anwr** [comment]
@Rinshin-Jalal it’s my first pr i hope it gets accepted 🤞
