### ISSUE TITLE
⚡ Write a deepgramTopicDetection() Function using Java

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4460]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramTopicDetection()` function using **Java**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Detect list of topic from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Java**.
- Knowledge to implement **deepgramTopicDetection** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramTopicDetection()` in `Java/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by akarsh-jain-790** [comment]
@christyjacob4 can u assign this issue to me?

**Comment by tessamero** [comment]
@akarsh-jain-790  Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by dakshbhardwaj** [comment]
@christyjacob4 can u assign this to me?

**Comment by PineappleIOnic** [comment]
@dakshbhardwaj thanks for your interest! 🙏 Happy hacking!

**Comment by dakshbhardwaj** [comment]
@PineappleIOnic thanks for assigning the issue, I have raised the Pr for it.

**Comment by jaspreet7037** [comment]
@christyjacob4 can u assign this issue to me?

**Comment by Meldiron** [comment]
@jaspreet7037 , we're assigning people on a first come first serve basis. You can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by dakshbhardwaj** [comment]
@Meldiron @christyjacob4 can you check the pr and assign `hackoctoberfest-accepted` label to it

**Comment by dakshbhardwaj** [comment]
@PineappleIOnic can you please review this pr?

**Comment by IMPranshu** [comment]
Please assign this to me. Will finish it up by today itself.

**Comment by CloudInnovator** [comment]
@IMPranshu Please what is the progress on this?

**Comment by IMPranshu** [comment]
> @IMPranshu Please what is the progress on this?

A PR is already submitted for this by me.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
