### ISSUE TITLE
⚡ Write a deepgramLanguageDetection() Function using Deno

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4465]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramLanguageDetection()` function using **Deno**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Detect a language from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Deno**.
- Knowledge to implement **deepgramLanguageDetection** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramLanguageDetection()` in `Deno/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Rinshin-Jalal** [comment]
I can do this

**Comment by Rinshin-Jalal** [comment]
> @Rinshin-Jalal , thanks for your interest! You may work on this issue pray Happy hacking! jack_o_lantern

Hi it is very easy to make these function deepgram

What if we make it by combining all of these like the send_message function which includes SMS, email, discord, and twitter?

**Comment by stnguyen90** [comment]
@Rinshin-Jalal, thanks for the suggestion! 🙏 It makes sense, but we'd like to give several people opportunities to contribute
