### ISSUE TITLE
⚡ Write a deepgramLanguageDetection() Function using Node

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4466]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramLanguageDetection()` function using **Node**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Detect a language from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Node**.
- Knowledge to implement **deepgramLanguageDetection** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramLanguageDetection()` in `Node/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by caramelmelmel** [comment]
Hi @christyjacob4 can I be assigned to this issue?

**Comment by caramelmelmel** [comment]
but may I ask why is a wav file a first consideration?

**Comment by tessamero** [comment]
@caramelmelmel , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

For your question I will have @Meldiron answer this one

**Comment by ItsAdityaKSingh** [comment]
@caramelmelmel, are you still working on this?

**Comment by caramelmelmel** [comment]
@ItsAdityaKSingh I am still working on it! What's the deadline?

**Comment by ItsAdityaKSingh** [comment]
Nope! There's no deadline as such :)
Just wanted to know if you are still working on resolving this or not 👍🏻

**Comment by stnguyen90** [comment]
@caramelmelmel are you still working on this or should we unassign you?

**Comment by caramelmelmel** [comment]
Can I ask some questions?

**Comment by caramelmelmel** [comment]
For the unit test stated here, what's the test coverage? Will you need instructions to run it on your local machine?

**Comment by stnguyen90** [comment]
@caramelmelmel, no need to write unit tests. Just manually test it to make sure it works. Also make sure to manually test for failures too to confirm the correct helpful error response is returned.

**Comment by caramelmelmel** [comment]
I'll submit the screenshots if it's as such

**Comment by caramelmelmel** [comment]
ok basically making a PR to the [examples](https://github.com/open-runtimes/examples) directory now that I have gotten clear of the req

**Comment by sebabratakundu** [comment]
@caramelmelmel are you still working on this?

**Comment by Player256** [comment]
hey @stnguyen90 please give a look at my pr

**Comment by stnguyen90** [comment]
@sebabratakundu, did you want to work on this issue?

@Player256, please be wary of submitting a PR without being assigned to an issue, especially if others want to work on the issue.

**Comment by sebabratakundu** [comment]
> @sebabratakundu, did you want to work on this issue?
> 
> @Player256, please be wary of submitting a PR without being assigned to an issue, especially if others want to work on the issue.

Yes, @stnguyen90

**Comment by Player256** [comment]
@stnguyen90 I got too excited about it and did it.

**Comment by sebabratakundu** [comment]
> @stnguyen90 I got too excited about it and did it. You can assign @sebabratakundu

Hi @Player256, since you have done the hard work. @stnguyen90 please assign this to @Player256

**Comment by stnguyen90** [comment]
Thanks, @sebabratakundu! I'll assign to @Player256
