### ISSUE TITLE
⚡ Write a deepgramLanguageDetection() Function using PHP

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4467]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramLanguageDetection()` function using **PHP**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Detect a language from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **PHP**.
- Knowledge to implement **deepgramLanguageDetection** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramLanguageDetection()` in `PHP/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by neelshah2409** [comment]
Hey I would like to work on it!!

**Comment by tessamero** [comment]
@neelshah2409 Looks like you have some issues assigned to you already. We request you complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Rutam21** [comment]
@tessamero Please assign this to me as I have not worked with this type of issues previously. Also, I am ready with the PRs for my other assignments, just waiting for minor clarifications before I raise them. So, in the meantime I can work on this one. Thanks.

**Comment by Meldiron** [comment]
@Rutam21 Please raise PRs for other issues first 🙏 It helps us keep things moving.

**Comment by Meldiron** [comment]
@Rutam21 I notice you have 2 issues assigned, one of them without a PR yet. Let's first focus on getting this PR done, then I am more than happy to assign you some more 😇

**Comment by Ian-Yy** [comment]
Hi @Meldiron, can I work on this?

**Comment by neelshah2409** [comment]
> @neelshah2409 Looks like you have some issues assigned to you already. We request you complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

@tessamero  I have completed my other PR's and also made this function so if you assign me then I will just make a PR.

**Comment by PineappleIOnic** [comment]
@Ian-Yy thanks for your interest! 🙏 Happy hacking!

**Comment by PineappleIOnic** [comment]
@nishant-giri @neelshah2409 , we're assigning people on a first come first serve basis. If @Ian-Yy isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Ian-Yy** [comment]
Hi @PineappleIOnic, I have created the PR. Please review and let me know if you need anything else. Thanks
