### ISSUE TITLE
⚡ Write a deepgramLanguageDetection() Function using Kotlin

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4472]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramLanguageDetection()` function using **Kotlin**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Detect a language from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Kotlin**.
- Knowledge to implement **deepgramLanguageDetection** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramLanguageDetection()` in `Kotlin/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Yashsomalkar** [comment]
I would like to work on this !

**Comment by Meldiron** [comment]
@Yashsomalkar , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Yashsomalkar** [comment]
ok , thanks for assigning .

**Comment by Rutam21** [comment]
@Meldiron I have completed the previous tickets. If this issue is still needed to be worked upon, you can re-assign it to me. Thanks.

**Comment by Meldiron** [comment]
@Yashsomalkar Hey there 👋 Can you please confirm with me if you are working on this issue?

**Comment by Yashsomalkar** [comment]
> @Yashsomalkar Hey there 👋 Can you please confirm with me if you are working on this issue?

No please assign it to someone else , I'm quite packed these days 😇

**Comment by Rutam21** [comment]
@Meldiron I can take this up. Thanks.

**Comment by sdrdh** [comment]
Can I work on this? Thanks

**Comment by IMPranshu** [comment]
Please assign this to me I am working on it and will open a PR soon

**Comment by stnguyen90** [comment]
@sdrdh, would you still like to work on this?

**Comment by stnguyen90** [comment]
@Rutam21, I just noticed you wanted to work on this too. Would you still like to despite there being PRs from others?

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
