### ISSUE TITLE
⚡ Write a deepgramTranscribeVideo() Function using Java

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4482]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramTranscribeVideo()` function using **Java**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Transcribe a video into written text. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://rawcdn.githack.com/deepgram-devs/transcribe-videos/62fc7769d6e2bf38e420ee5224060922af4546f7/deepgram.mp4"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Java**.
- Knowledge to implement **deepgramTranscribeVideo** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramTranscribeVideo()` in `Java/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by tanishk-23** [comment]
@christyjacob4 can you assign this issue to me?

**Comment by codingmickey** [comment]
hi @christyjacob4, can I work on this issue?

**Comment by tessamero** [comment]
@tanishk-23 , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

@codingmickey , we are assigning people on a first come first serve basis. If @tanishk-23  isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Faizan711** [comment]
Is this issue still unassigned, if so i would like to be assigned for it.

**Comment by stnguyen90** [comment]
@Faizan711, assigned! Thank you for your interest!

**Comment by ANUSHRAV01** [comment]
@stnguyen90  I feel this issue  still exist 
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class AppwriteFunction {
  public static JsonObject deepgramTranscribeVideo(JsonObject data) throws Exception {
    String fileUrl = data.get("fileUrl").getAsString();

    if (fileUrl == null || fileUrl.isEmpty()) {
      return errorResponse("Please provide a valid file URL.");
    }

    String deepgramApiKey = System.getenv("DEEPGRAM_API_KEY"); // Set your Deepgram API key as an environment variable
    if (deepgramApiKey == null || deepgramApiKey.isEmpty()) {
      return errorResponse("Please set your Deepgram API key as an environment variable.");
    }

    OkHttpClient client = new OkHttpClient();

    Request request = new Request.Builder()
        .url("https://proxy.deepgram.com/v1/listen")
        .post(RequestBody.create("{\n  \"url\": \"" + fileUrl + "\",\n  \"metadata\": {\n    \"client_name\": \"appwrite\",\n    \"client_version\": \"v1\",\n    \"api_key\": \"" + deepgramApiKey + "\"\n  }\n}", okhttp3.MediaType.parse("application/json")))
        .build();

    Response response = client.newCall(request).execute();
    String responseBody = response.body().string();

    if (response.isSuccessful()) {
      JsonObject deepgramData = JsonParser.parseString(responseBody).getAsJsonObject();
      return successResponse(deepgramData);
    } else {
      return errorResponse("Failed to transcribe video. " + responseBody);
    }
  }

  private static JsonObject successResponse(JsonObject data) {
    JsonObject response = new JsonObject();
    response.addProperty("success", true);
    response.add("deepgramData", data);
    return response;
  }

  private static JsonObject errorResponse(String message) {
    JsonObject response = new JsonObject();
    response.addProperty("success", false);
    response.addProperty("message", message);
    return response;
  }
}
This implementation uses the OkHttp library to make an HTTP request to the Deepgram API and transcribe the video. You'll need to set your Deepgram API key as an environment variable called DEEPGRAM_API_KEY. You can then call the deepgramTranscribeVideo() function with a JSON payload containing the fileUrl parameter to transcribe the video.This implementation uses the OkHttp library to make an HTTP request to the Deepgram API and transcribe the video. You'll need to set your Deepgram API key as an environment variable called DEEPGRAM_API_KEY. You can then call the deepgramTranscribeVideo() function with a JSON payload containing the fileUrl parameter to transcribe the video.

**Comment by ANUSHRAV01** [comment]
can u review this .I feel this can be the solution to your problem

**Comment by stnguyen90** [comment]
@Faizan711, are you still working on this? If there's no response, I'll have to assign this to someone else.

**Comment by Faizan711** [comment]
Sorry @stnguyen90  i am currently unable to work on this, you can assign it to anybody else.

**Comment by stnguyen90** [comment]
@ANUSHRAV01, if you're still interested in working on this please submit a PR

**Comment by ANUSHRAV01** [comment]
Done ,@stnguyen90

**Comment by IMPranshu** [comment]
Please assign this to me. I have successfully implemented the function by taking reference from `ruby` folder.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
