### ISSUE TITLE
⚡ Write a deepgramTranscribeVideo() Function using Kotlin

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4483]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramTranscribeVideo()` function using **Kotlin**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Transcribe a video into written text. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://rawcdn.githack.com/deepgram-devs/transcribe-videos/62fc7769d6e2bf38e420ee5224060922af4546f7/deepgram.mp4"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Kotlin**.
- Knowledge to implement **deepgramTranscribeVideo** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramTranscribeVideo()` in `Kotlin/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by maxslimb** [comment]
Hey, can i work on this issue?

**Comment by tessamero** [comment]
@maxslimb , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by Rutam21** [comment]
@Meldiron I have completed the previous tickets. If this issue is still needed to be worked upon, you can re-assign it to me. Thanks.

**Comment by Meldiron** [comment]
@maxslimb Hey there 👋 Can you please confirm with me if you are working on this issue?

**Comment by TheSwarnim** [comment]
Hi @stnguyen90, can you assign this task to me if anyone not working on this issue. I've experience in kotlin, can implement the functionality mentioned in this task!

**Comment by stnguyen90** [comment]
@TheSwarnim, assigned! Thanks for your interest! 🙏🏼

**Comment by TheSwarnim** [comment]
Thanks, Steven you bro for assigning this task to me! 😇 I was forget about this issue as I don't get any reply for quite some time. Sure I'll add pr as soon as possible.

**Comment by yash10019coder** [comment]
Hi I would like to work on this issue. Please assign it to me.

**Comment by IMPranshu** [comment]
Please assign this to me. Will open a PR soon for this.

**Comment by stnguyen90** [comment]
@TheSwarnim will you still be able to submit a PR for this?

**Comment by stnguyen90** [comment]
@yash10019coder, would you still like to work on this?

**Comment by yash10019coder** [comment]
Yes @stnguyen90 will like to work on this

**Comment by stnguyen90** [comment]
@yash10019coder, assigned! Thanks for your interest! 🙏🏼

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
