### ISSUE TITLE
⚡ Write a deepgramAudioSummary() Function using Python

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4485]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramAudioSummary()` function using **Python**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a summary text from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Python**.
- Knowledge to implement **deepgramAudioSummary** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramAudioSummary()` in `Python/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by jerempy** [comment]
would you assign this one to me plz?

**Comment by stnguyen90** [comment]
@jerempy Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by jerempy** [comment]
@stnguyen90 thanks for respondng so fast. Something came up though and I probably won’t be able to contribute so I wanted to let you know quickly so it can be re opened for someone else

**Comment by stnguyen90** [comment]
@jerempy thanks for letting us know! I'll unassign you now. 🙏

**Comment by shivendoodeshmukh** [comment]
Can you please assign this to me? I'll give it a try

**Comment by vj-codes** [comment]
@stnguyen90 hey can you assign this to me please?

**Comment by tessamero** [comment]
@shivendoodeshmukh , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

@stnguyen90 , we are assigning people on a first come first serve basis. If @shivendoodeshmukh isn't able to complete this issue, we will reassign it accordingly. In the meantime, you can find other Hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by Azanul** [comment]
It seems this issue has been inactive since 14 days, can I please be assigned this issue as a part of hacktoberfest?

**Comment by stnguyen90** [comment]
@shivendoodeshmukh are you still working on this? Please let us know so we can reassign accordingly.

**Comment by stnguyen90** [comment]
@Azanul, I've assigned this issue to you. Hopefully, you have time to finish this.

**Comment by Azanul** [comment]
> @Azanul, I've assigned this issue to you. Hopefully, you have time to finish this.

Let's see how fast I can do.
