### ISSUE TITLE
⚡ Write a deepgramTranscribeAudio() Function using Deno

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4487]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramTranscribeAudio()` function using **Deno**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Transcribe an audio into written text. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgramm should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Deno**.
- Knowledge to implement **deepgramTranscribeAudio** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramTranscribeAudio()` in `Deno/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by MoskalykA** [comment]
I would like to do this

**Comment by tessamero** [comment]
@MoskalykA , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by MoskalykA** [comment]
Hi, I can't find this part on their documentation, can someone help me please

**Comment by Meldiron** [comment]
@MoskalykA I think this would go under their pre-recorded audio docs: https://developers.deepgram.com/documentation/getting-started/prerecorded/

**Comment by Rutam21** [comment]
@Meldiron I have completed the previous tickets. If this issue is still needed to be worked upon, you can re-assign it to me. Thanks.

**Comment by Meldiron** [comment]
@MoskalykA Hey there 👋 Can you please confirm with me if you are working on this issue?
