### ISSUE TITLE
⚡ Write a deepgramTranscribeAudio() Function using Node

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4488]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramTranscribeAudio()` function using **Node**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Transcribe an audio into written text. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgramm should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Node**.
- Knowledge to implement **deepgramTranscribeAudio** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramTranscribeAudio()` in `Node/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by caramelmelmel** [comment]
Hi @christyjacob4 Can I take this issue?

**Comment by toukirkhan** [comment]
can I work on this one?

**Comment by tessamero** [comment]
@caramelmelmel , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by tessamero** [comment]
@toukirkhan , we are assigning people on a first come first serve basis. If @caramelmelmel  isn't able to complete this issue, we will reassign accordingly. In the meantime, you can find other hacktoberfest issues via our [website](https://hacktoberfest.appwrite.io/).

**Comment by aloks98** [comment]
Hey @tessamero, if this is still not complete can I take this issue?

**Comment by stnguyen90** [comment]
@caramelmelmel, how's your progress on this? Please let us know within 24 hours so we can reassign accordingly. 

@toukirkhan, are you still interested in working on this?

@aloks98, if @caramelmelmel and @toukirkhan aren't able to work on this, we'll assign it to you.

**Comment by toukirkhan** [comment]
Yes am interested

**Comment by caramelmelmel** [comment]
@stnguyen90 yes am almost done writing some test cases

**Comment by caramelmelmel** [comment]
alright @stnguyen90 i cant seem to resolve seems like4 someone can take this on

**Comment by stnguyen90** [comment]
@caramelmelmel, thanks for the update.

Since Hacktoberfest is over, I'll be closing this issue.
