### ISSUE TITLE
⚡ Write a deepgramTranscribeAudio() Function using Swift

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4492]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramTranscribeAudio()` function using **Swift**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Transcribe an audio into written text. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgramm should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Swift**.
- Knowledge to implement **deepgramTranscribeAudio** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramTranscribeAudio()` in `Swift/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by caramelmelmel** [comment]
@christyjacob4 Can I also take on this issue if it's possible?

**Comment by tessamero** [comment]
@caramelmelmel , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by stnguyen90** [comment]
Unassigning @caramelmelmel due to inactivity.

**Comment by sajdakabir** [comment]
@stnguyen90 can you please assign it to me?

**Comment by stnguyen90** [comment]
@sajdakabir assigned! Thanks for your interest! 🙏

**Comment by stnguyen90** [comment]
@sajdakabir how's your progress on this? If there's no response, I'll have to unassign you so that someone else can pick this up.

**Comment by sajdakabir** [comment]
You can unassign me. I have assigned two tasks .I am working on the other one . Thank you.

**Comment by asmitrai** [comment]
import Foundation
import Appwrite

let client = Client()
let functions = Functions(client)

let functionId = "your_function_id_here"
let fileUrl = "https://static.deepgram.com/examples/interview_speech-analytics.wav"
let apiKey = "your_deepgram_api_key_here"

func deepgramTranscribeAudio() {
    let options = [
        "url": fileUrl,
        "apikey": apiKey
    ]
    
    let payload = [
        "fileUrl": fileUrl
    ]
    
    functions.execute(
        functionId: functionId,
        data: payload,
        options: options,
        completion: { (result: Result<[String: Any], AppwriteError>) in
            switch result {
            case .success(let data):
                print("Deepgram transcription success: \(data)")
            case .failure(let error):
                print("Deepgram transcription error: \(error)")
            }
    })
}

deepgramTranscribeAudio()



// replace your_function_id_here and your_deepgram_api_key_here with your actual values

**Comment by darkcheftar** [comment]
Hey, @stnguyen90 Can I work on this?

**Comment by stnguyen90** [comment]
@darkcheftar, assigned! Thanks for your interest! 🙏🏼 If you cannot work on this, please let me know so I can unassign you.

**Comment by darkcheftar** [comment]
Hey, I wanted to approach this the following way
Step 1: Make a basic Proof of Concept of swift function
Step 2: Modify the previous function to take necessary variables and payload
Step 3: Modify the above to make a post request to deepgram

**Comment by darkcheftar** [comment]
@stnguyen90 
I tried to complete `Step 1` 
Where I installed Appwrite on my Ubuntu 22.04, using docker
Created a sample project
Created a sample function using `appwrite init function`
deployed it `appwrite deploy function`
I have not changed anything from the default function made by appwrite-cli
Still Its not building  Could someone please help me get this working
![image](https://github.com/appwrite/appwrite/assets/54063851/733ea019-79ba-4e7b-8624-75c9c72e8569)

**Comment by darkcheftar** [comment]
Figured Out How to do `Step 1` without directly using `appwrite-cli`

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.

**Comment by darkcheftar** [comment]
Hey, I'm working on this!
Will this be reopened?

**Comment by eldadfux** [comment]
This issue in no longer relevant.
