### ISSUE TITLE
⚡ Write a deepgramTranscribeAudio() Function using Java

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4493]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramTranscribeAudio()` function using **Java**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Transcribe an audio into written text. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgramm should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Java**.
- Knowledge to implement **deepgramTranscribeAudio** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramTranscribeAudio()` in `Java/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by akarsh-jain-790** [comment]
@christyjacob4 can u assign this issue to me?

**Comment by tessamero** [comment]
@akarsh-jain-790 , thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃

**Comment by Azanul** [comment]
It seems this issue has been inactive since 15 days, can I please be assigned this issue as a part of hacktoberfest?

**Comment by stnguyen90** [comment]
Unassigning @akarsh-jain-790 due to inactivity.

**Comment by PriyanshuAhlawat** [comment]
@stnguyen90 I will like to work on it, pls assign🙂

**Comment by rukundob451** [comment]
@stnguyen90 how far with the people working on the issue?

**Comment by stnguyen90** [comment]
@PriyanshuAhlawat how's your progress on this?

**Comment by rukundob451** [comment]
> @stnguyen90 sorry got busy with university exams, will give you an update soon.

Alright, will be waiting in on the update.

**Comment by IMPranshu** [comment]
Hi. Please assign this to me. Will be finishing this up in the weekend IST.

**Comment by IMPranshu** [comment]
### ✅ Task Summary
* [x]   Ask to be assigned to the issue.
* [x]   Implement function `deepgramTranscribeAudio()` in `Java/` folder.
* [x]   Manually execute the newly implemented function to ensure it works.
* [x]   Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
