### ISSUE TITLE
⚡ Write a deepgramAudioSummary() Function using Swift

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4497]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramAudioSummary()` function using **Swift**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a summary text from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Swift**.
- Knowledge to implement **deepgramAudioSummary** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramAudioSummary()` in `Swift/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by caramelmelmel** [comment]
Hi @christyjacob4 I can take this too!

**Comment by ishaanbedi** [comment]
Hey! I'd like to work on this! Can you please assign it to me?

**Comment by stnguyen90** [comment]
@caramelmelmel Thanks for your interest! You may work on this issue 🙏 Happy hacking! 🎃 

@ishaanbedi We're assigning people on a first come first serve basis. If @caramelmelmel isn't able to complete this issue, we'll reassign it accordingly. In the meantime, you can find another Hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by stnguyen90** [comment]
Unassigning @caramelmelmel due to inactivity.

**Comment by stnguyen90** [comment]
@ishaanbedi, yes, we welcome contributions! However, this won't be counted for Hacktoberfest since the event is over now.

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
