### ISSUE TITLE
⚡ Write a deepgramAudioSummary() Function using Kotlin

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4499]
# 💭 Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more in our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

The backbone of Appwrite Functions is [Open Runtimes](https://github.com/open-runtimes/open-runtimes), an environment for serverless cloud computing. Since all Open Runtime functions are valid Appwrite functions, we are looking for contributors to extend the [Open Runtimes Examples](https://github.com/open-runtimes/examples) repository.

Your task is to implement `deepgramAudioSummary()` function using **Kotlin**. Please make sure to look at [existing function examples](https://github.com/open-runtimes/examples) and use them as a template for your function. This will help you keep the proper structure as well as provide information on how to test the function.

### ⚡ Function Details

Generate a summary text from spoken audio. If necessary, introduce Deepgram API secret keys as function variables. The payload must accept a WAV file URL, and the response from Deepgram should be returned.

Example function payload:

```jsx
{"fileUrl":"https://static.deepgram.com/examples/interview_speech-analytics.wav"}
```

Successful function response:

```jsx
{"success":true,"deepgramData":{}}
```

Error function response:

```jsx
{"success":false,"message":"Please provide a valid file URL."}
```

### 🎯 Requirements

- Experience with Appwrite.
- Experience with **Kotlin**.
- Knowledge to implement **deepgramAudioSummary** function.
- Experience with **Docker**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Implement function `deepgramAudioSummary()` in `Kotlin/` folder.
- [ ]  Manually execute the newly implemented function to ensure it works.
- [ ]  Submit a pull request in [open-runtimes/examples](https://github.com/open-runtimes/examples) and include screenshots of successful execution.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by tanishk-23** [comment]
@christyjacob4 can you assign this issue to me?

**Comment by tessamero** [comment]
@tanishk-23 Yea you can work on it. Happy hacking :-)

**Comment by Rutam21** [comment]
@Meldiron I have completed the previous tickets. If this issue is still needed to be worked upon, you can re-assign it to me. Thanks.

**Comment by zeus2611** [comment]
@christyjacob4 
@stnguyen90 

Hey, I would like to work on this issue.
Can you please assign this to me??

**Comment by stnguyen90** [comment]
@zeus2611, assigned! Thanks for your interest! 🙏🏼

**Comment by zeus2611** [comment]
There already exists a [deepgram-transcribe-audio](https://github.com/open-runtimes/examples/tree/main/kotlin/deepgram-transcribe-audio) function with its implementation and documentation.

**Comment by stnguyen90** [comment]
@zeus2611, transcribe audio and summarize audio are actually slightly different 😅.

**Comment by SharmaAkshat007** [comment]
@christyjacob4 @stnguyen90 I would like to work on this issue

**Comment by SharmaAkshat007** [comment]
@christyjacob4 @stnguyen90 I have created a PR for this issue https://github.com/open-runtimes/examples/pull/147

**Comment by eldadfux** [comment]
Thank you everyone for celebrating Hacktoberfest 22 with us! This issue will now be closed as we're getting ready to celebrate Hacktoberfest 23.
