### ISSUE TITLE
🏗️ Build ‘Podcast transcription form‘ Demo App!

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#4504]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to provide Appwriters with a **huge amount** of example projects that many use as learning resources. Not only that, we know it’s an amazing feeling to find a learning resource for connecting two technologies, so you don’t need to figure it out on your own.

Your task is to create ‘**Podcast transcription form**‘ demo application. When building the demo app, make sure to use [Deepgram](https://deepgram.com/) to help you out with the task. There are no specifications regarding design and features, but make sure to make it look nice and user friendly 😇 If you are not into design, feel free to use UI libraries.

You can check out [Almost Kialo](https://github.com/Meldiron/almost-kialo) as a reference project. This project showcases proper documentation of Appwrite-based application.

### 🎯 Requirements

- You must create ‘Podcast transcription form‘ demo application
- You must use technology [Deepgram](https://deepgram.com/)
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be a web or Flutter application. Regarding the web, use any JavaScript technology.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build ‘Podcast transcription form‘ demo app as a web or Flutter app. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  Share your work on social media and tag @appwrite (Reddit / HackerNews / Twitter / Facebook / Linkedin)
- [ ]  (optional) Write an article about how you built ‘Podcast transcription form‘ demo app on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by ayushpaharia** [comment]
Interested in working on it

**Comment by Tejs1** [comment]
Can multiple people work on same issue?

**Comment by tessamero** [comment]
@ayushpaharia @Tejs1 Go ahead, you can all start working on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.

**Comment by timothee-durand** [comment]
Hello I think i'll work on it to

**Comment by stnguyen90** [comment]
@timothee-durand Go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.

**Comment by jonny-lake** [comment]
Can I work on this as well?:)

**Comment by ffex** [comment]
can I do also this? :) it's funny build this type of demo.

**Comment by stnguyen90** [comment]
@ffex yup! Go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.
