### ISSUE TITLE
🧱 Build Almost Whatsapp. Be Creative!

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4508]
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to provide Appwriters with a **huge amount** of example projects that many use as learning resources.

We understand Appwrite’s tech stack might not be your cup of tea, so we decided to prepare a series of `Almost (something)` projects. This series of issues is here to let your creativity shine! ✨

Your task is to create **Almost Whatsapp**. This should be a website that copies the functionality of Whatsapp, but uses Appwrite as a backend. We understand that Whatsapp is a huge project, so don’t worry about implementing every single feature - make sure to only focus on the most well-known features of this platform. Regarding design, please try not to copy the official one - feel free to use UI libraries to help you out.

You can check out [Almost Reddit](https://github.com/Meldiron/almost-reddit-place) as a reference project. This project meets all the requirements.

### 🎯 Requirements

- You must replicate the most iconic features of Whatsapp.
- You must use [Appwrite](https://appwrite.io/) as a backend and use [Appwrite CLI](https://appwrite.io/docs/command-line) for storing functions/collections.
- You must write a proper README file to explain the deployment process. Make sure to include screenshots or videos too.
- The project must be a web or Flutter application. Regarding the web, use any JavaScript technology.
- The project must be open sourced under an MIT license on GitHub or GitLab.

### ✅ Task Summary

- [ ]  Drop a comment on this issue indicating that you’re working on it.
- [ ]  Create a public repository on GitHub or GitLab with an MIT license.
- [ ]  Build Almost Whatsapp as a web or Flutter app. Ensure to use Appwrite CLI if you use Appwrite Functions.
- [ ]  Write a proper README and include screenshots.
- [ ]  Make sure to pull collections schema using Appwrite CLI.
- [ ]  Submit a pull request in [appwrite/awesome-appwrite](https://github.com/appwrite/awesome-appwrite).
- [ ]  (optional) Write an article about how you built Almost Whatsapp on [Dev.to](http://Dev.to), [Hashnode](https://hashnode.com/) or [Medium](https://medium.com/).

This task **does not require** any assignment but please comment on this issue mentioning you are working on it. If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by mintbomb27** [comment]
I'd like to work on this!

**Comment by amarjeet987** [comment]
@mintbomb27 want to work on it together?

**Comment by mintbomb27** [comment]
Hey @amarjeet987 sure! I'll make the repo and add you? Mail me at alokme123@gmail.com

**Comment by ShivamTyagi12345** [comment]
Would like to help.

**Comment by Saloni098** [comment]
@mintbomb27 I too would like to contribute to it. Can I join you guys as well?

**Comment by tessamero** [comment]
@mintbomb27 @amarjeet987 @ShivamTyagi12345 @Saloni098 Go ahead, you can all start working on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.

**Comment by mintbomb27** [comment]
@amarjeet987 @ShivamTyagi12345 @Saloni098 
https://github.com/mintbomb27/almost-whatsapp/ Check the repo out. Everyone can contribute to the same!

**Comment by PrabeshPP** [comment]
@stnguyen90  I want to work on this issue. But do I have to create a separate repo for this issue or I can work on someone else repo.

**Comment by mintbomb27** [comment]
@PrabeshPP It's up to you. We've already started working on this at https://github.com/mintbomb27/almost-whatsapp/

**Comment by yaakov123** [comment]
I've already created a complete clone in a separate repo here - https://github.com/yaakov123/whatsapp-clone

**Comment by yaakov123** [comment]
Here's the PR for awesome-appwrite - https://github.com/appwrite/awesome-appwrite/pull/435/files

**Comment by divyesh1099** [comment]
I would like to work on this.

**Comment by PineappleIOnic** [comment]
@divyesh1099 Feel free to work on it, This issue is open for everyone, and we want as many quality PRs as our community can create.

**Comment by Adnan-Jindani** [comment]
I would like to work on this

**Comment by Esther-Wavinya** [comment]
Sounds like a good project. I will work on it.

**Comment by divyesh1099** [comment]
> @divyesh1099 Feel free to work on it, This issue is open for everyone, and we want as many quality PRs as our community can create.

Yuss ... On It 🤟

**Comment by faiz-gh** [comment]
> @PrabeshPP It's up to you. We've already started working on this at https://github.com/mintbomb27/almost-whatsapp/ . Do try and contribute!

sure will do

**Comment by tushar-sublaik** [comment]
I am working on this issue.

**Comment by Chetnagupta27** [comment]
can you assign this issue to me?

**Comment by Netizen02** [comment]
I would like to work on this!

**Comment by stnguyen90** [comment]
@Esther-Wavinya, @faiz-gh, @Chetnagupta27, and @Netizen02 Go ahead, you can start work on this issue 😊 This issue is open for everyone and we want as many quality PRs as our community can create.

**Comment by magic-peach** [comment]
Hey @stnguyen90 , I’m participating in Hacktoberfest! and I'm new to open source contributions. Can I work on this issue?
