### ISSUE TITLE
🐛 Bug Report: Incorrect Error When Creating Duplicate Domain

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#4519]
### 👟 Reproduction steps

1. Create a custom domain for a project
2. Create another custom domain that's the same as in step 1

### 👍 Expected behavior

Error indicates domain already exists

### 👎 Actual Behavior

Error says duplicate ID:

```json
{
    "message": "A Domain with the requested ID already exists.",
    "code": 409,
    "type": "domain_already_exists",
    "version": "dev"
}
```

### 📝 Tasks

1. [ ] Update error:

https://github.com/appwrite/appwrite/blob/6c220467b8cb33e3784dc99a580cc322b370f9f1/app/config/errors.php#L534

2. [ ] Add a test case:

https://github.com/appwrite/appwrite/blob/939f974d19f30a30c204fa8a7108b857e88673e7/tests/e2e/Services/Projects/ProjectsConsoleClientTest.php#L2158-L2203

3. [ ] Create PR w/ a screenshot of the updated error message

### 🎲 Appwrite version

Version 1.0.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by 20RitikSingh** [comment]
I want to contribute to this.

**Comment by Atharvk7** [comment]
Could you assign this issue to me
I want to contribute

**Comment by Meldiron** [comment]
@20RitikSingh , thanks for your interest! 🙏 Happy hacking! 🎃

**Comment by Meldiron** [comment]
@Atharvk7 , we're assigning people on a first come first serve basis. If @20RitikSingh  isn't able to complete this issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue via our [website](https://hacktoberfest.appwrite.io/).

**Comment by yeya** [comment]
The error type says: `domain_already_exists`. Isn't it the expected behavior? You need the message say that too? Or maybe each domain has `name` field AND `id` filed?

**Comment by stnguyen90** [comment]
@yeya it's just misleading that it says the `ID` already exists but it's the `name` that's causing the error.

**Comment by vedant-z** [comment]
@stnguyen90 If you allow me I am working on this issue.

**Comment by mustansirgodhrawala** [comment]
Can this be assigned to me? @stnguyen90

**Comment by stnguyen90** [comment]
@mustansirgodhrawala, assigned! Thanks for your interest!

**Comment by mustansirgodhrawala** [comment]
Thanks, I'm on it!!

**Comment by joeyouss** [comment]
Hi @mustansirgodhrawala thank you for the PR, our team will take a look and leave reviews but since we have 1.4 coming up, this PR if compatible won't be merged until after 1.4

**Comment by mustansirgodhrawala** [comment]
@joeyouss I would love to work on some high impact issues which can help closer releases, can you please assign me to a more serious issue. I'll do my best to close it as soon as possible.
