### ISSUE TITLE
🚀 Feature: Improving the Select Query

### ISSUE THREAD

**Issue by moshOntong-IT** [appwrite/appwrite#5376]
### 👟 Reproduction steps

1.  Query the vocabulary collection with relationship in language collection.

>Vocabulary -> language
>vocabulary can contain one language
>language can belong to many vocabulary

Sample code:
```
      final documents = await databases.listDocuments(
          databaseId: kDatabaseId,
          collectionId: kVocabularyCollectionId,
          queries: [
            Query.equal("language", languageSelected.languageId),
          ]);
```

The payload code of this is this:
![image](https://user-images.githubusercontent.com/57244338/232107712-7560a17b-b3e1-48ea-89d2-126895ab6565.png)

**Please observe that in our data key with the index of 6 namely language key**. It provide all the attributes of our language object/document.  Now trying to query by using the new Queries `Query.select(['language.\$id'])` though the new queries is not yet supported in Appwrite 1.3 version, hence it is expected it gives me an error output. But if I use only this `Query.select([])`. The whole code:

```
      final documents = await databases.listDocuments(
          databaseId: kDatabaseId,
          collectionId: kVocabularyCollectionId,
          queries: [
            Query.select([]),
            Query.equal("language", languageSelected.languageId),
          ]);
 ```
 
 The payload output of the code:
 
![image](https://user-images.githubusercontent.com/57244338/232108974-ce46944a-efa7-4f06-87b2-a7cc8f7e8e6c.png)

**Please observe on the encircle of the attach picture above**. It is weird right? it only provide the language ID, though the Query select is not yet available on current version of Appwrite.

### 👍 Expected behavior

If we use this query `Query.select(['language.\$id'])` the output should provide only the language ID in our language payload.

### 👎 Actual Behavior

> Not working

But I understand, this query is not available yet, But its weird that by using this ``Query.select([])`` it successfully give me the only `$id` attribute of language.

>Note that without using this Query.select it does give me all the attributes in my language object within payload returned from listDocuments

### 📝 Tasks

- [ ] Selecting a relationship should return the IDs. See https://github.com/appwrite/appwrite/issues/5657.
- [ ] System attributes should not be returned if they're not included in the `select()`
- [ ] `select(["relationshipA.*"])` should only return `relationshipA` attributes and no other relationship on the same document. See https://github.com/appwrite/appwrite/issues/5657
- [ ] `select(["relationshipA.attribute"])` should return that relationship's attribute and no other relationship's attribute. See https://github.com/appwrite/appwrite/issues/5657
- [ ] Multiple selects should return all of the attributes selected. See https://github.com/appwrite/appwrite/issues/5376#issuecomment-1535486082

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Thank you for opening this

**Comment by stnguyen90** [comment]
Another odd thing:

Given:

```json
{
  "$id": "64542e0a4656d6d829d5",
  "$createdAt": "2023-05-04T22:13:30.299+00:00",
  "$updatedAt": "2023-05-04T22:13:30.299+00:00",
  "$permissions": [
    "read(\"user:joe\")",
    "update(\"user:joe\")",
    "delete(\"user:joe\")"
  ],
  "answerChoice": {
    "value": "A",
    "text": "Facebook",
    "$id": "64542d132dbfa638c95f",
    "$createdAt": "2023-05-04T22:09:23.207+00:00",
    "$updatedAt": "2023-05-04T22:09:23.207+00:00",
    "$permissions": [],
    "question": {
      "text": "Who created Flutter?",
      "$id": "64542d132d90428be1d5",
      "$createdAt": "2023-05-04T22:09:23.207+00:00",
      "$updatedAt": "2023-05-04T22:09:23.411+00:00",
      "$permissions": [],
      "$databaseId": "default",
      "$collectionId": "questions"
    },
    "correctAnswer": null,
    "$databaseId": "default",
    "$collectionId": "answer-choices"
  },
  "$databaseId": "default",
  "$collectionId": "answers"
}
```

a select query like:

```
select(["answerChoice.question.text", "answerChoice.value", "answerChoice.text"])
```

should return something like:

```json
{
  "answerChoice": {
    "value": "A",
    "text": "Facebook",
    "question": {
      "text": "Who created Flutter?"
    }
  }
}
```

but it returns:

```json
{
  "$id": "64542e0a4656d6d829d5",
  "$createdAt": "2023-05-04T22:13:30.299+00:00",
  "$updatedAt": "2023-05-04T22:13:30.299+00:00",
  "$permissions": [
    "read(\"user:joe\")",
    "update(\"user:joe\")",
    "delete(\"user:joe\")"
  ],
  "answerChoice": {
    "value": "A",
    "text": "Facebook",
    "$id": "64542d132dbfa638c95f",
    "$createdAt": "2023-05-04T22:09:23.207+00:00",
    "$updatedAt": "2023-05-04T22:09:23.207+00:00",
    "$permissions": [],
    "$databaseId": "default",
    "$collectionId": "answer-choices"
  },
  "$databaseId": "default",
  "$collectionId": "answers"
}
```

**Comment by byawitz** [comment]
I think the load of the other default fields is still set to be returned when there is a specific select 

https://github.com/utopia-php/database/blob/main/src/Database/Adapter/MariaDB.php#L1190

**Comment by Musta-Pollo** [comment]
Any update?

**Comment by Musta-Pollo** [comment]
Currently, with `select([]),` there is an option to load only the id of a related document or nothing if there is a list of related documents. This behavior should be persistent, as we should have the option to disable the loading of relations if we don't need them without the need to specify everything except relations.

**Comment by abnegate** [comment]
This behaviour has changed a bit since the official introduction of select query support. Soon, relationships will not be loaded by default, and you will be required to explicitly include it in the select query to resolve it, otherwise you'll get only the ID.
