### ISSUE TITLE
🐛 Bug Report: Some Pattern Input Validation Aren't Working

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#5936]
### 👟 Reproduction steps

1. Open a modal to create a Database
2. Type `Default` for Name
3. Type in `inv@lid` for Database ID
4. Click Create

### 👍 Expected behavior

Client-side validation should run and the user should see a warning in the modal.

### 👎 Actual Behavior

The API request is made and there is a server-side error.

Looking at the console logs, it looks like the pattern is invalid:

![image](https://github.com/appwrite/appwrite/assets/1477010/f8d15524-c27e-4a6f-b27b-5351b3ef8525)

> Pattern attribute value ^[a-zA-Z0-9][a-zA-Z0-9._-]*$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^[a-zA-Z0-9][a-zA-Z0-9._-]*$/v: Invalid character in character class

You can reproduce this by running:

```javascript
pattern = String.raw`^[a-zA-Z0-9][a-zA-Z0-9._-]*$`;
r = new RegExp(pattern, 'v');
```

I think the problem is the pattern's last dash (`-`).

### Tasks

- [x] [src/lib/elements/forms/inputId.svelte](https://github.com/appwrite/console/pull/702) by @amanpatel23
- [ ] src/lib/elements/forms/inputDomain.svelte

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by webAbhi** [comment]
I would like to work on this, can you please assign this to me !!

**Comment by stnguyen90** [comment]
@Ayushpanditmoto, did you want to work on this?

@webAbhi, we assign on a first come first serve basis so I'll assign it to you if @Ayushpanditmoto doesn't want to work on it.

**Comment by Ayushpanditmoto** [comment]
@stnguyen90 yeah i want to work on this issue can you tell where exactly this line is placed in which folder i can fix it

**Comment by abdulmannans** [comment]
@stnguyen90 any updates on this issue?

**Comment by stnguyen90** [comment]
@Ayushpanditmoto, are you still working on this or should I unassign you?

**Comment by Ayushpanditmoto** [comment]
I am working on this issue @stnguyen90

**Comment by Prithvi101** [comment]
Hi can i get this issue assigned to me I have Figured out where is exactly is cause

**Comment by Haimantika** [comment]
> Hi can i get this issue assigned to me I have Figured out where is exactly is cause

Hi Prithvi, thanks for your interest. Looks like Ayush is working on it.

**Comment by 0xchikku** [comment]
If it gets unassigned, can I take it up?

**Comment by Ayushpanditmoto** [comment]
@0xchikku currently working bro

**Comment by perryHV** [comment]
Hii @stnguyen90 can I work on this issue? I would love to contribute.

**Comment by Haimantika** [comment]
> @0xchikku currently working bro

Hi Ayush, do you have any updates? We will have to reassign the issue to the next person if you are not working on it :)

**Comment by Ayushpanditmoto** [comment]
@Haimantika working

**Comment by Haimantika** [comment]
> @Haimantika i stuck somewhere i will resolve this in a week

Cool, do not hesitate to reach out to us on [Discord](https://appwrite.io/discord)

**Comment by iamabhiCH** [comment]
Hey @stnguyen90, I read this issue and I found I can fix it. Please assign this task to me.

**Comment by nick2432** [comment]
can I work on this issue?

**Comment by nick2432** [comment]
@stnguyen90 the person who is assigned is inactive for a long time can i take over this issue?

**Comment by nick2432** [comment]
@Haimantika can i work on this ??

**Comment by Kajanan02** [comment]
@Haimantika can you assign me?

**Comment by Haimantika** [comment]
> @Haimantika can i work on this ??

Are you still interested to work on it?

**Comment by nick2432** [comment]
> > @Haimantika can i work on this ??
> 
> Are you still interested to work on it?

yes

**Comment by nick2432** [comment]
@Haimantika  can you please assign this issue to me

**Comment by Kajanan02** [comment]
@Haimantika can you assign me?

**Comment by webAbhi** [comment]
@stnguyen90 I can take this up, feel free to assign this to me.

**Comment by stnguyen90** [comment]
@webAbhi, how's your progress on this?

**Comment by dev-spectre** [comment]
@stnguyen90 I would like to work on this, I have figured out the solution. Can you assign this to me?

**Comment by Kajanan02** [comment]
@stnguyen90 can you assign me?

**Comment by abdul-rehman-2050** [comment]
@stnguyen90 or @Haimantika it's been a month since the it was assigned to @webAbhi. Is it available to be re assigned?

**Comment by nick2432** [comment]
@TorstenDittmann  it seems like the problem wasn't just with the database ID validation; there are issues with the user ID, function ID, and buckets ID validation as well.

**Comment by stnguyen90** [comment]
@nick2432, they should all be using the InputId component, right?

**Comment by nick2432** [comment]
> @nick2432, they should all be using the InputId component, right?

yes

**Comment by nick2432** [comment]
> @nick2432, they should all be using the InputId component, right?

i can work on this
