### ISSUE TITLE
💬 Improve Appwrite Messaging with Airship Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6379]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Airship** in the Utopia PHP messaging library. This goes under **Push** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Airship**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Push/Airship**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by thexahmed00** [comment]
hello @christyjacob4 please assign me this issue i would like to work on it..

**Comment by LunarMarathon** [comment]
Hi, I would like to work on this, please assign this task to me. Thanks!

**Comment by tessamero** [comment]
hi @LunarMarathon , you've been assigned to the issue. You may now start working on it. :) Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by Aryan8912** [comment]
can you assign to me please, so I can work on it

**Comment by NAMAN547** [comment]
@tessamero I would like to work on this issue if it's not executed, thanks!

**Comment by RudRaj-Patel** [comment]
@tessamero I would like to work on this issue (if available)

**Comment by Haimantika** [comment]
Hi @LunarMarathon do you have an update to share?

**Comment by tessamero** [comment]
Hi @LunarMarathon , with no update that you are still working on it or not, we will reassign it first thing tomorrow, so please let us know, as @Haimantika mentioned :)

**Comment by LunarMarathon** [comment]
Hey @Haimantika, @tessamero Please re-assign this to the someone else. I've got stuck so I'll learn from the next person's PR. Thanks for opportunity!

**Comment by biswajit287** [comment]
Hi @tessamero, 
Since @LunarMarathon  is unable to work on this, I would like to work on this issue. Can you please assign this to me?
Thanks!

**Comment by rishidyno** [comment]
Hi, I have experience in open-source contribution in Oppia-Foundation.

I want to learn something new and gain experience. Please assign me this issue.

**Comment by rishidyno** [comment]
Hey, I want to work on this issue. Please assign me this.

**Comment by Haimantika** [comment]
Hi @NAMAN547 would you like to work on this? I have already assigned one issue to you, let me know if you are still interested in this one

**Comment by VrajPatelGitHub** [comment]
@Haimantika I would really like to work on this issue please assign these to me.

**Comment by shubhampaliwal3011** [comment]
Hi, I would like to work on this issue if this is not assigned to anyone.

**Comment by parthksingh1** [comment]
@tessamero  I would like to work on this issue if it's not executed, thanks

**Comment by Tushar98644** [comment]
Hi , i would like to contribute to this issue ...

**Comment by Haimantika** [comment]
@biswajit287 you are next in line, are you still interested in working on this issue?

**Comment by Haimantika** [comment]
> @Haimantika Yes I'm interested in working on this issue as well.

Assigned the issue to you now. Please update us every 3 days

**Comment by Haimantika** [comment]
HI @VrajPatelGitHub @Tushar98644 @parthksingh1 @shubhampaliwal3011 we are assigning issues on a first-come,first-serve basis if the assigned person gets idle, we will assign the issue to you.

**Comment by RedWing0021** [comment]
Hi, @Haimantika, it seems no progress has been made on this issue. I'm interested in working on this issue. Please assign this to me, if this issue is still open.

**Comment by NAMAN547** [comment]
@Haimantika the same update for this as well. I have tested the adapter and I will be raising a pull request for code review

**Comment by Haimantika** [comment]
Hi @NAMAN547 any update? You have two issues assigned to you, let us know if you have the bandwidth to work on them
