### ISSUE TITLE
💬 Improve Appwrite Messaging with Amazon SES Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6380]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Amazon SES** in the Utopia PHP messaging library. This goes under **Email** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Amazon SES**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Email/Amazon SES**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Jaishree2310** [comment]
@christyjacob4 can you please assign this issue to me?

**Comment by thinkverse** [comment]
Duplicate of https://github.com/appwrite/appwrite/issues/6377?

**Comment by tessamero** [comment]
hi @Jaishree2310 , you've been assigned to the issue. You may now start working on it. :) Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by NAMAN547** [comment]
@tessamero Can you assign me this issue if it's not completed?

**Comment by HarshAggarwal1** [comment]
@tessamero Hi please assign me this issue

**Comment by thinkverse** [comment]
@NAMAN547, @HarshAggarwal1 the issue has already been assigned, you can see the assignee in the top section of the sidebar.

**Comment by Haimantika** [comment]
Hi @Jaishree2310 reassigning this issue to the next person due to inactivity from your end. @NAMAN547 the issue is yours now

**Comment by NAMAN547** [comment]
@Haimantika Thanks I'll start working on it

**Comment by navneetbz** [comment]
@tessamero @Haimantika I would like to take it up if there is no progress.

**Comment by Haimantika** [comment]
> @Haimantika Thanks I'll start working on it

Hi, is there an update? If not, I will assign the issue to the next person tomorrow, due to inactivity

**Comment by Akshay-21** [comment]
Hi @christyjacob4 could you assign me this issue?

**Comment by NAMAN547** [comment]
@Haimantika  I have tested the adapter and I’ll be raising a pull request for code review today

**Comment by Haimantika** [comment]
> Hi @christyjacob4 could you assign me this issue?

Hi, we are assigning issues on a first-come, first-serve basis, the issue will go to you, if the assigned user drops

**Comment by Haimantika** [comment]
Hi @NAMAN547 are you still working on it? If not, let us know, we will be reassigning the issue to the next person.

**Comment by akshbswas98** [comment]
@Haimantika Can you assign this issue to me?

**Comment by tessamero** [comment]
Closing this issue as hacktoberfest is now over. There's no PR linked to this issue as well. Thank you to everyone who participated this year :)
