### ISSUE TITLE
💬 Improve Appwrite Messaging with Bandwidth Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6383]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Bandwidth** in the Utopia PHP messaging library. This goes under **SMS** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Bandwidth**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **SMS/Bandwidth**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by professorabhay** [comment]
Hey, @christyjacob4 ! I would like to work on this issue and resolve it. 
Please assign it to me.
Thanks

**Comment by Haimantika** [comment]
> Hey, @christyjacob4 ! I would like to work on this issue and resolve it.
> Please assign it to me.
> Thanks

Hi @professorabhay have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by professorabhay** [comment]
Hey @Haimantika, Thanks for assigning. 
I am working on it but as my mid-sems are ongoing, I'm busy with them also. I'll definitely raise a PR till the end of the next week !

**Comment by biswajit287** [comment]
Hello @Haimantika,

If @professorabhay is unable to make the PR, I'd like to work on this issue next.

Thanks.

**Comment by professorabhay** [comment]
Hey @biswajit287, I'm working on it. 
But if not then I'll let you know. Till you find some other issues plz

**Comment by Yash-sudo-web** [comment]
heyy @Haimantika, if this issue is not being worked upon right now, let me know if i can be assigned to it, would get to work right away, thanks.

**Comment by professorabhay** [comment]
@Yash-sudo-web, Dude why don't you find something else. If this is already assigned to someone recently then why are you guys commenting again n again. 

For your kind info, I'm working on it and will raise
PR in the commitment period. Please look for something else !

**Comment by Haimantika** [comment]
> @Yash-sudo-web, Dude why don't you find something else. If this is already assigned to someone recently then why are you guys commenting again n again.
> 
> For your kind info, I'm working on it and will raise PR in the commitment period. Please look for something else !

Hi, is there any update? If you are not working on it, we will assign it to the next person tomorrow

**Comment by professorabhay** [comment]
Hey @Haimantika, It's almost done. 
I'll create PR tommorow

**Comment by professorabhay** [comment]
Hey @Haimantika, [PR](https://github.com/utopia-php/messaging/pull/55)

**Comment by Haimantika** [comment]
> Hey @Haimantika, [PR](https://github.com/utopia-php/messaging/pull/55)

Thanks, our team will take a look at it soon. Also, please link the issue to the PR.

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
