### ISSUE TITLE
💬 Improve Appwrite Messaging with CM Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6386]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **CM** in the Utopia PHP messaging library. This goes under **SMS** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **CM**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **SMS/CM**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by ayan-joshi** [comment]
Hello sir I would like to work on this issue , please assign me this

**Comment by ayan-joshi** [comment]
> > Hello sir I would like to work on this issue , please assign me this @christyjacob4
> 
> Hi @ayan-joshi have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃
> 
> Notes:
> 
> Please update us with your progress every 3 days, so that we know that you are working on it. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

Okay sure

**Comment by ayan-joshi** [comment]
@Haimantika I have a request can you unassign me this issue and assigned the Vue Documentation , I'll work better and easily on that one as you said at a moment we can work on two.

**Comment by VividhPandey003** [comment]
Hey, I would like to try my hands on this issue, could you please assign it to me. I'll update you regarding any issues I face, if that is fine with you. Thanks

**Comment by Haimantika** [comment]
> Hey, I would like to try my hands on this issue, could you please assign it to me. I'll update you regarding any issues I face, if that is fine with you. Thanks

Hi @VividhPandey003  have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by VividhPandey003** [comment]
update: still working on it

**Comment by VividhPandey003** [comment]
Update: still working on it

**Comment by Haimantika** [comment]
> Update: still working on it

Great! If you need any help, do not hesitate to reach out to us on [Discord](https://appwrite.io/discord)

**Comment by VividhPandey003** [comment]
still working on it. I am kinda new to PHP honestly but this issue has made me learn it much better. Thank you for being this patient

**Comment by VividhPandey003** [comment]
@Haimantika I am kinda stuck on this issue. Could you please tell me where in discord (which channel) can I ask for some help.

**Comment by Haimantika** [comment]
> @Haimantika I am kinda stuck on this issue. Could you please tell me where in discord (which channel) can I ask for some help.

Hi, you can ask in the support forum

**Comment by VividhPandey003** [comment]
working on it

**Comment by VividhPandey003** [comment]
Still working on it

**Comment by VividhPandey003** [comment]
@Haimantika Could you please review my PR once.

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
