### ISSUE TITLE
💬 Improve Appwrite Messaging with ElasticEmail Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6387]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **ElasticEmail** in the Utopia PHP messaging library. This goes under **Email** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **ElasticEmail**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Email/ElasticEmail**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Udaay** [comment]
I want to work on this task , please assign it to me

**Comment by tessamero** [comment]
hi @Udaay , you've been assigned to the issue. You may now start working on it. :) Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by Vishalk91-4** [comment]
@tessamero, could you assign this issue to me

**Comment by Haimantika** [comment]
Hi @Udaay reassigning this issue to the next person due to inactivity from your end. @Vishalk91-4 the issue is yours

**Comment by utkershrajvenshi** [comment]
Hi @Haimantika . I'd like to work on it next in case of inactivity from current assignee

**Comment by Vishalk91-4** [comment]
@Haimantika, after submitting PR to utopia what do i need to do to get it done and accepted for Hacktober Fest

**Comment by Haimantika** [comment]
> @christyjacob4, can you tell me what do i have to do after I've raised a PR for this issue, the PR has also not been reviewed yet

Hi, not yet. Our team will review (it can take upto 15 days) and get back to you if any changes are required

**Comment by Vishalk91-4** [comment]
@Haimantika, I've got that PR hacktoberfest-accepted label, so does it mean that I've PR merged for Appwrite

**Comment by Vishalk91-4** [comment]
@christyjacob4, I've got the hacktoberfest-accepted label for a PR, I've referenced here, do I need to do anything else

**Comment by Haimantika** [comment]
> @Haimantika, I've got that PR hacktoberfest-accepted label, so does it mean that I've PR merged for Appwrite

Nope. Merging will take some time.

**Comment by Vishalk91-4** [comment]
@Haimantika, Does this mean that I have one PR accepted in Appwrite for Hacktoberfest, for that do I need to write Blog or this is enough

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
