### ISSUE TITLE
💬 Improve Appwrite Messaging with Mailchimp Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6388]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Mailchimp** in the Utopia PHP messaging library. This goes under **Email** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Mailchimp**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Email/Mailchimp**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by ng169** [comment]
Hi @christyjacob4 , I would like to work on this issue.

**Comment by tessamero** [comment]
hi @ng169 , you've been assigned to the issue. Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by ng169** [comment]
Hey! Quick question. Mailchimp offers a marketing campaign API for sending emails in bulk from one sender to many recipients. However, I'm wondering if Mailchimp also provides an option for sending one-to-one emails from a sender to a specific receiver, like some other email API clients do. Am I just overlooking this option in Mailchimp?

**Comment by Manancode** [comment]
@tessamero ,  Would like to try it after @GOYALAYUSH782 if unresponsive

**Comment by AVDiv** [comment]
I like to work on this, if unresponsive.

**Comment by AVDiv** [comment]
@tessamero I submitted a PR as I couldn't wait, please check if it's good to go.

**Comment by Haimantika** [comment]
> @tessamero I submitted a PR as I couldn't wait, please check if it's good to go.

Hi, the issue is not assigned to you. Please raise a PR only if it is assigned to you.

**Comment by Haimantika** [comment]
Hi @ng169 is there an update? Will reassign it to the next person if there is no response from you.

**Comment by tessamero** [comment]
I'm assigning it to the next person @AVDiv on the list.

Please link this issue to the PR if you've already done it, and keep in mind to only work on an issue if it's been assigned to you. I know you were really excited. :) 

Thank you for contributing :)

**Comment by AVDiv** [comment]
I have submitted a PR already

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
