### ISSUE TITLE
💬 Improve Appwrite Messaging with Netcore Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6394]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Netcore** in the Utopia PHP messaging library. This goes under **Email** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Netcore**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Email/Netcore**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by codingmickey** [comment]
Hey @christyjacob4 I would like to work on this! :)

**Comment by Haimantika** [comment]
> Hey @christyjacob4 I would like to work on this! :)

Hi @codingmickey have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by dishantzaveri** [comment]
Pls assign me

**Comment by Haimantika** [comment]
@codingmickey is there an update?

**Comment by codingmickey** [comment]
yes I've been working on figuring out implementing the actual message adapter in PHP. getting some common syntax errors trying to fix them! Wasn't getting to much time over the week.. will put in efforts during this weekend 🚀

**Comment by VrajPatelGitHub** [comment]
@Haimantika  I would like to work on these issue, if it's not executed.

**Comment by codingmickey** [comment]
hey @VrajPatelGitHub I was working on this and am almost done, am trying my best to drop a PR by today!

**Comment by dishantzaveri** [comment]
> hey @VrajPatelGitHub I was working on this and am almost done, am trying my best to drop a PR by today!

@codingmickey How do you get so much time?

**Comment by codingmickey** [comment]
Hey @Haimantika I've created a draft PR as of now, because

> As I'm still yet to receive the test account and credits from Netcore I'm making this a draft PR, as I wrote the code and tests by referring to their [API docs](https://cpaasdocs.netcorecloud.com/docs/pepipost-api/c2d895762f832-send-an-email)

**Comment by Haimantika** [comment]
> Hey @Haimantika I've created a draft PR as of now, because
> 
> > As I'm still yet to receive the test account and credits from Netcore I'm making this a draft PR, as I wrote the code and tests by referring to their [API docs](https://cpaasdocs.netcorecloud.com/docs/pepipost-api/c2d895762f832-send-an-email)

Hi @codingmickey any update on your PR?
