### ISSUE TITLE
💬 Improve Appwrite Messaging with OneSignal Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6395]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **OneSignal** in the Utopia PHP messaging library. This goes under **Push** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **OneSignal**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Push/OneSignal**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by meetagrawal09** [comment]
@christyjacob4 I would like to work on this issue. Can you please assign it to me.

**Comment by Haimantika** [comment]
> @christyjacob4 I would like to work on this issue. Can you please assign it to me.

Hi @meetagrawal09 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by trishanu-init** [comment]
@christyjacob4 I would like to work on this issue as well. Could you please assign this to me.

**Comment by Haimantika** [comment]
Hi @meetagrawal09 is there any update on your PR?

**Comment by meetagrawal09** [comment]
Hey @Haimantika, I will complete the code and push it soon.

**Comment by Haimantika** [comment]
> Hey @Haimantika, I will complete the code and push it soon.

Hi, any update on your PR?

**Comment by Tushar98644** [comment]
@Haimantika I would like to take up the issue

**Comment by meetagrawal09** [comment]
@Haimantika I am busy with my other commitments and thus won't be able to get on this one anytime soon. You can assign it someone else.

**Comment by Haimantika** [comment]
> @christyjacob4 I would like to work on this issue as well. Could you please assign this to me.

Hi, are you still interested?

**Comment by shriVATSA54** [comment]
@Haimantika 
I'm a beginner, I'll attempt the task for 24 hours.If I encounter challenges, I'll promptly inform you and step out.

Please consider assigning this to me.

**Comment by maxslimb** [comment]
Hello @Haimantika, I have already contributed to the utopia PHP repository last year and would like to take up this issue.

**Comment by Haimantika** [comment]
Okay @Tushar98644 you are next. Would you like to take this up? I remember you have expressed your interest in another issue, let me know if you will have the bandwidth to solve this as well.

**Comment by Haimantika** [comment]
@shriVATSA54 @maxslimb we are assigning issues on a first-come,first-serve basis, you will need to wait until your time comes :)

**Comment by Haimantika** [comment]
@shriVATSA54 do you want to work on this?

**Comment by shriVATSA54** [comment]
@Haimantika 
Yess, Assign this to me.
I'm a beginner, I'll attempt the task for 24 hours.If I encounter challenges, I'll promptly inform you and step out.

**Comment by Haimantika** [comment]
> @Haimantika Yess, Assign this to me. I'm a beginner, I'll attempt the task for 24 hours.If I encounter challenges, I'll promptly inform you and step out.

You can also ask for help in our [Discord server](https://appwrite.io/discord)

**Comment by shriVATSA54** [comment]
@Haimantika
I regret that I was unable to finish the assignment, as it was taking me a considerable amount of time. 
**I also reached out for assistance in Discord, but unfortunately, I did not receive a response.**

**Comment by tessamero** [comment]
Hi @shriVATSA54 , unfortunately you posted your support question in the wrong channel and really never followed up with anyone about where to ask questions, which is why it wasn't seen. We also had 2 PR review events twice a week where we answer hacktoberfest questions, but haven't seen you participate in any. In the future, you can ask support questions in the support channel, and our team can immediately help, as we've never left any questions unanswered. :) We are constantly trying our best to improve everyone's hacktoberfest experience, and next time we will make this more clear/known on where to ask for support.

I appreciate your participation with hacktoberfest and maybe next year will be more of a success.
