### ISSUE TITLE
💬 Improve Appwrite Messaging with SMSApi Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6402]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **SMSApi** in the Utopia PHP messaging library. This goes under **SMS** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **SMSApi**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **SMS/SMSApi**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by nooras** [comment]
Hi
Can you please assign this task to me. I would like to give a try.

**Comment by tessamero** [comment]
hi @nooras , you've been assigned to the issue. Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by Haimantika** [comment]
> i want to contribute to this one. can you assign it to me.

Hi @RohanSharma4792 we are assigning issues on a first-come, first-serve basis, if @35C4n0r decides to drop, we will assign it to you.

**Comment by nooras** [comment]
HI @christyjacob4 & @Haimantika 

As SMSApi is not available in INDIA. I am not able to test cases. Shall i just make code changes as given in example and push the changes ?
![image](https://github.com/appwrite/appwrite/assets/30138146/c9a430cf-434e-4666-adb0-aaafd6080e0a)

**Comment by satyampostapi** [comment]
Hi
Can you please assign this task to me. I would like to give a try.

**Comment by manish7017** [comment]
Hey, Can you please assign this issue to me? I would like to work on it.

**Comment by Haimantika** [comment]
> HI @christyjacob4 & @Haimantika
> 
> As SMSApi is not available in INDIA. I am not able to test cases. Shall i just make code changes as given in example and push the changes ? ![image](https://user-images.githubusercontent.com/30138146/272331255-c9a430cf-434e-4666-adb0-aaafd6080e0a.png)

I think that should be fine, please raise a PR

**Comment by tessamero** [comment]
@nooras please follow up on the PR :)

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
