### ISSUE TITLE
💬 Improve Appwrite Messaging with SMTP2GO Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6404]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **SMTP2GO** in the Utopia PHP messaging library. This goes under **Email** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **SMTP2GO**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Email/SMTP2GO**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Ayaan49** [comment]
Hey, I would like to try working on this.

**Comment by Haimantika** [comment]
> Hey, I would like to try working on this.

Hi @Ayaan49 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Ayaan49** [comment]
Hey @Haimantika, thanks for assigning this to me. It will take me some time and guidance to complete it. Please bear with me.

**Comment by monhelnog** [comment]
I wanted to work on this issue

**Comment by Haimantika** [comment]
> I wanted to work on this issue

Hi, we are assigning issues on first-come, first-serve basis, if @Ayaan49 is decides to drop off, we will assign it to you.

**Comment by Ayaan49** [comment]
Hey @Haimantika , I am already working on it. Kind of stuck in the testing process but I think I will make it.

**Comment by Haimantika** [comment]
> Hey @Haimantika , I am already working on it. Kind of stuck in the testing process but I think I will make it.

No problem, feel free to ask us questions on Discord :)

**Comment by Ayaan49** [comment]
Hello @Haimantika , I have added the Smtp2go messaging adapter which uses the PHPMailer library to send an email via SMTP. I have tested it and it works fine. However, I must inform you that I tried using it with utopia-php/smt2go library but it was unable to locate such library. So, is that I problem if I use PHPMailer library instead of the utopia-php/smt2go library?

**Comment by Haimantika** [comment]
> Hello @Haimantika , I have added the Smtp2go messaging adapter which uses the PHPMailer library to send an email via SMTP. I have tested it and it works fine. However, I must inform you that I tried using it with utopia-php/smt2go library but it was unable to locate such library. So, is that I problem if I use PHPMailer library instead of the utopia-php/smt2go library?

Hi, it has been a week without any updates. Please let us know the status, if you are not working on it, we will assign the issue to the next person in queus

**Comment by Ayaan49** [comment]
Hey @Haimantika ,  I am done with the task. I will be creating a PR by the end of today. Just left with the test plan.

**Comment by Ayaan49** [comment]
Hello @Haimantika , I created the PR. Please look into it.

**Comment by Haimantika** [comment]
> Hello @Haimantika , I created the PR. Please look into it.

Thanks, our team will take a look at it soon. You can also get it reviewed on spot during our PR review parties on Discord :)

**Comment by Ayaan49** [comment]
Hello @Haimantika , I want to know when my PR is going to be reviewed.

**Comment by Haimantika** [comment]
> Hello @Haimantika , I want to know when my PR is going to be reviewed.

PR reviews can take upto 15 days. Would recommend you to attend our PR review calls on Discord and get it reviewed live :)

**Comment by Ayaan49** [comment]
Hey @Haimantika , it's been more than 15 days since my PR was created. Also, it's almost the end of Hacktoberfest season. May I know when my PR is getting reviewed?

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
