### ISSUE TITLE
💬 Improve Appwrite Messaging with WebPush Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6407]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **WebPush** in the Utopia PHP messaging library. This goes under **Push** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **WebPush**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Push/WebPush**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).
- [ ]  Write a blog post on the platform of your choosing on how to integrate and use the adapter you just created. 

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by SoNiC-HeRE** [comment]
Hi @christyjacob4 I'm interested in working upon this issue. Can you assign me this pls?

**Comment by tessamero** [comment]
hi @SoNiC-HeRE , you've been assigned to the issue. Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by SoNiC-HeRE** [comment]
Thanks, Ill keep that in mind

> hi @SoNiC-HeRE , you've been assigned to the issue. Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)
> 
> happy coding 😃

Thanks, I'll keep that in mind

**Comment by Haimantika** [comment]
Hi @SoNiC-HeRE is there any update from your end?

**Comment by SoNiC-HeRE** [comment]
> Hi @SoNiC-HeRE is there any update from your end?

Hi, I'm working on other issue at the moment, if someone's willing to take this up you can assign them.

**Comment by Palakiew** [comment]
Hi @christyjacob4 ...I'm interested in working on this issue..Can you assign it to me so i can help out? Thanks!

**Comment by Luchyba** [comment]
Hello @christyjacob4 Please assign this to me. Thanks

**Comment by biswajit287** [comment]
Hi @tessamero @Haimantika,
I would like to work on this if no one is working on it. Thanks!

**Comment by Haimantika** [comment]
> Hi @christyjacob4 ...I'm interested in working on this issue..Can you assign it to me so i can help out? Thanks!

Thanks @SoNiC-HeRE for the update. @Palakiew the issue is yours now

**Comment by Haimantika** [comment]
Hi @Luchyba @biswajit287 we are assigning issues on a first-come first-server basis, if the other user gets idle, it will go to you

**Comment by Palakiew** [comment]
Hey, that's awesome! Thank you so much for assigning me. I'm really excited to get started and contribute to the project. let me know if there's anything specific you'd like me to focus on. Thanks again!

**Comment by Palakiew** [comment]
Hey @Haimantika due to health issues, i was unable to complete this task.

**Comment by mschandana16** [comment]
Hi @Haimantika @christyjacob4, please assign it to me in case the other users drop this issue. Thanks!

**Comment by AmruthaSri852** [comment]
Can you please assign this to me? @christyjacob4 @Haimantika

**Comment by nuwan94** [comment]
I'm interested in working on this issue @christyjacob4 @Haimantika

**Comment by shivanshu814** [comment]
Hi @christyjacob4  I'm interested in working on this issue. Can you assign me this pls?

**Comment by adarsh-jha-dev** [comment]
Hi @christyjacob4 , could you please assign this issue to me if anyone is not working on it ?

**Comment by Haimantika** [comment]
> Hi @Haimantika @christyjacob4, please assign it to me in case the other users drop this issue. Thanks!

We just have 1 day left. Would you still like to work on it? I am assigning it to you

**Comment by mschandana16** [comment]
Sure, I would like to work on it even after HF. Thanks for assigning me this issue @Haimantika!!
Also, could you please let me know approximately how much time I would be given to work on this issue?

**Comment by Haimantika** [comment]
> Sure, I would like to work on it even after HF. Thanks for assigning me this issue @Haimantika!! Also, could you please let me know approximately how much time I would be given to work on this issue?

You can work on it in your own pace

**Comment by tessamero** [comment]
Hello @mschandana16 , would love to know your update on this issue and if you're still working on it. We have removed the hacktoberfest label for now as the event is over.

**Comment by mschandana16** [comment]
> Hello @mschandana16 , would love to know your update on this issue and if you're still working on it. We have removed the hacktoberfest label for now as the event is over.

Hello, I'm working on this issue. I've just started because I was held up with a few college assignments.

**Comment by mschandana16** [comment]
> Hello @mschandana16 , would love to know your update on this issue and if you're still working on it. We have removed the hacktoberfest label for now as the event is over.

Hello, I'm working on this issue. I've just started cause I held up with a few college assignments.

**Comment by eldadfux** [comment]
Closing this issue due to lack of activity. We still plan to add web push notifications as a new adapter for messaging. If anyone wants to pick this up, I'd be happy to re-open.
