### ISSUE TITLE
🗄️ Extend Appwrite Storage with Azure Blob Storage Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6409]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`...

Your task is to implement support for **Azure Blob Storage** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Azure Blob Storage**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Azure Blob Storage**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Azure Blob Storage**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).
- [ ]  Write a blog post on any platform of your choosing to demonstrate the usage of your adapter!

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by thexahmed00** [comment]
@christyjacob4  please assign me this issue I would like to give it a try

**Comment by tessamero** [comment]
hi @thexahmed00 , you've been assigned to the issue. Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by KanniShashankh** [comment]
Happy to work on this if @thexahmed00 drops off

**Comment by dishantzaveri** [comment]
@thexahmed00 any updates?

**Comment by RashmiNirasha** [comment]
@christyjacob4 I'd like to take on this issue. Can you assign it to me?

**Comment by Haimantika** [comment]
Hi @RashmiNirasha @HARSHALJETHWA19  we are assigning issues on a first-come, first-serve basis, if @thexahmed00  decides to drop off, we will assign it to you.

**Comment by KanniShashankh** [comment]
> Hi @RashmiNirasha @HARSHALJETHWA19 we are assigning issues on a first-come, first-serve basis, if @thexahmed00 decides to drop off, we will assign it to you.

Hey @Haimantika, i am in line too 😅

**Comment by Haimantika** [comment]
Hi @thexahmed00 reassigning the issue to the next person due to inactivity from your end. @KanniShashankh the issue is yours

**Comment by KanniShashankh** [comment]
https://github.com/utopia-php/storage/pull/93
Created a draft PR, continuing to work on the issue

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
