### ISSUE TITLE
🗄️ Extend Appwrite Storage with Ceph Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6410]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`...

Your task is to implement support for **Ceph** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Ceph**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Ceph**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Ceph**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).
- [ ]  Write a blog post on any platform of your choosing to demonstrate the usage of your adapter!

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by mugdha273** [comment]
@christyjacob4 I'd love to take up this issue. Could you please assign me this issue?

**Comment by Haimantika** [comment]
> @christyjacob4 I'd love to take up this issue. Could you please assign me this issue?

Hi @mugdha273 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by gewenyu99** [comment]
Hey can I be assigned to this issue?? I'd love to contribute!

**Comment by trishanu-init** [comment]
@Haimantika Could you assign this issue to me , I will begin work ASAP

**Comment by Haimantika** [comment]
> @Haimantika Could you assign this issue to me , I will begin work ASAP

The assigned user has already raised a PR, please find issues that are not being worked on.

**Comment by tessamero** [comment]
@mugdha273 the PR is awaiting your follow up
