### ISSUE TITLE
🗄️ Extend Appwrite Storage with Cloudian Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6411]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`...

Your task is to implement support for **Cloudian** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Cloudian**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Cloudian**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Cloudian**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).
- [ ]  Write a blog post on any platform of your choosing to demonstrate the usage of your adapter!

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by nooras** [comment]
Hi, Can you please assign me this task. I would like to give a try on this.

**Comment by tessamero** [comment]
hi @nooras , you've been assigned to the issue. Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by nooras** [comment]
Hi @tessamero @christyjacob4 

Need to some help/suggestion!!

[how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md)

Here in this point 2.1,

[2.1] Add new adapter and implement it](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md#21-add-new-adapter-and-implement-it)
In order to start implementing new storage adapter, add new file inside src/Storage/Device/YYY.php where YYY is the name of the storage provider in PascalCase. Inside the file you should create a class that extends the basic Device abstract class. Note that the class name should start with a capital letter, as PHP FIG standards suggest.

Always use properly named environment variables if any credentials are required.

In this only need to create a class like "class Cloudian extends Device { }" ?
Do we need to write some code inside of that Cloudian class block? If yes like what kind of code need to write inside that ? Can you guys please help me on this.

Thanks

**Comment by nooras** [comment]
2.1 I have created class Cloudian in Device folder and extended Device class
2.2 Added const DEVICE_CLOUDIAN in storage file
3.1 I created file CloudianTest file but not sure what will be there inside of that class. As in 2.1 I have created only file as per instructions

Can you please help me on this @tessamero @christyjacob4

**Comment by stnguyen90** [comment]
> 3.1 I created file CloudianTest file but not sure what will be there inside of that class

@nooras, look at [similar tests](https://github.com/utopia-php/storage/tree/main/tests/Storage/Device) for reference.

Please submit a draft PR if you need more assistance.

**Comment by utkershrajvenshi** [comment]
Hi @tessamero , in case @nooras is not able to complete this issue I'd like to try it next.

**Comment by nooras** [comment]
Hi @utkershrajvenshi I am working in this task. Thanks

**Comment by nooras** [comment]
Hi @tessamero @stnguyen90 @christyjacob4 
I have created PR for Phase 1.
For Phase 2 in note its written "Note for this to happen, your PR in the first phase should have been merged and a new version of [utopia-php/storage](https://github.com/utopia-php/storage) library released."

**Can I proceed for Phase 2 Step or need to wait for merge this PR ?**
Let me know if i made any mistakes in this PR or need to make some changes. I have referred others file present in ./storage ./test folder

Thanks

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
