### ISSUE TITLE
🗄️ Extend Appwrite Storage with Exoscale Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6412]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`...

Your task is to implement support for **Exoscale** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Exoscale**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Exoscale**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Exoscale**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).
- [ ]  Write a blog post on any platform of your choosing to demonstrate the usage of your adapter!

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by anjiattri** [comment]
Assign to me

**Comment by Haimantika** [comment]
> Assign to me

Hi @anjiattri have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by HARSHALJETHWA19** [comment]
Assign to me

**Comment by 0xSaikat** [comment]
I'd love to take up this issue. Could you please assign me this issue?

**Comment by Haimantika** [comment]
Hi @anjiattri assigning this issue to the next person due to inactivity from your end. @HARSHALJETHWA19 the issue is yours now, please update us every 3 day

**Comment by Haimantika** [comment]
Hi @HARSHALJETHWA19 is there any update? If not, we will reassign the issue to the next person tomorrow morning

**Comment by Haimantika** [comment]
Hi @HARSHALJETHWA19 due to inactivity from your end, will have to assign the issue to the next person. @0xSaikat the issue is yours now, please update us every 3 days about your progress or if you are stuck somewhere.

**Comment by Atharva1723** [comment]
Please assign me this issue ?

**Comment by Haimantika** [comment]
@0xSaikat are you working on this? If not, we will reassign the issue to the next person due to inactivity from your end.

**Comment by Haimantika** [comment]
> Please assign me this issue ?

Will be assigning the issue to you, if @0xSaikat is not working on it, as we assign issues on a first-come, first-serve basis.

**Comment by Haimantika** [comment]
> Please assign me this issue ?

@Atharva1723 assign the issue to you. Please update us every 3 days.

@0xSaikat we are unassigning the issue from you due to inactivity and to give everyone a fair chance to contribute :)

**Comment by Atharva1723** [comment]
I have a doubt about the testing for requests to the storage service of exoscale i have to purchase their subscription? Then how will I test it? Please correct me if I am wrong ?

**Comment by tessamero** [comment]
@Atharva1723 we are awaiting your response on the PR fyi

**Comment by adityaoberai** [comment]
Closing this issue. Thank you so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
