### ISSUE TITLE
🗄️ Extend Appwrite Storage with IBM Cloud Object Storage Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6413]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`...

Your task is to implement support for **IBM Cloud Object Storage** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **IBM Cloud Object Storage**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **IBM Cloud Object Storage**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **IBM Cloud Object Storage**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).
- [ ]  Write a blog post on any platform of your choosing to demonstrate the usage of your adapter!

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Harsh3305** [comment]
Hi @christyjacob4 I would like to work on this.
Please assign this issue to me 😄

**Comment by Haimantika** [comment]
> Hi @christyjacob4 I would like to work on this.
> Please assign this issue to me 😄

Hi @Harsh3305 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Mannxxx** [comment]
Hi @christyjacob4 I would also like to work on this.
Could you please assign this issue to me also?

**Comment by RajdeepDey010** [comment]
> Hi @christyjacob4 I would like to work on this. Please assign this issue to me 😄

Hey @Harsh3305 , seems this issue is quite challenging to me from a beginner point of view. Will you able to disuss your solution and how you approach to this kind of issue once you have done a successful submission?

**Comment by Harsh3305** [comment]
Hi @RajdeepDey010 
I am currently going through the code base in order to understand the architecture of project.
Once I solve this issue, I will add a generalize solution in the description of PR. 😃

**Comment by Harsh3305** [comment]
# Progress
- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned.
- [ ] Implement Utopia PHP storage adapter for IBM Cloud Object Storage.
- [ ] Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ] Implement Appwrite support for IBM Cloud Object Storage.
- [ ] Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).
- [ ] Write a blog post on any platform of your choosing to demonstrate the usage of your adapter!

**Comment by RajdeepDey010** [comment]
> Hi @RajdeepDey010 I am currently going through the code base in order to understand the architecture of project. Once I solve this issue, I will add a generalize solution in the description of PR. 😃

Sounds good! :)

**Comment by adityaoberai** [comment]
Closing this issue. Thank you all so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
