### ISSUE TITLE
🗄️ Extend Appwrite Storage with NetApp Storage Grid Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6414]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`...

Your task is to implement support for **NetApp Storage Grid** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **NetApp Storage Grid**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **NetApp Storage Grid**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **NetApp Storage Grid**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).
- [ ]  Write a blog post on any platform of your choosing to demonstrate the usage of your adapter!

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by pratiksardar** [comment]
Hi, Can you please assign me this task. I would like to work on this.

**Comment by Haimantika** [comment]
> Hi, Can you please assign me this task. I would like to work on this.

Hi @pratiksardar have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by trishanu-init** [comment]
@christyjacob4 Please assign this issue to me!!

**Comment by Haimantika** [comment]
> I am contuning to work on this, WIP going through documentation and will be starting implementation soon

It is been more than 3 days since you last gave an update. Are you still working on it? If not, I will assign it to the next person in queue tomorrow morning

**Comment by pratiksardar** [comment]
https://github.com/utopia-php/storage/pull/96 - Kindly review, it has been a week

**Comment by adityaoberai** [comment]
Closing this issue. Thank you all so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
