### ISSUE TITLE
🗄️ Extend Appwrite Storage with Oracle Object Storage Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6415]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`...

Your task is to implement support for **Oracle Object Storage** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Oracle Object Storage**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Oracle Object Storage**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Oracle Object Storage**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).
- [ ]  Write a blog post on any platform of your choosing to demonstrate the usage of your adapter!

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by KunalSin9h** [comment]
@christyjacob4 can you assign to me, i am excited to work on it.

**Comment by SaketKaswa20** [comment]
I would like to work on this, but this will take some time and I will require some guidance too.

**Comment by Sreejit-Sengupto** [comment]
What I understood here is that, we need to implement Oracle Object Storage and Utopia PHP storage library. First we need to create an adapter on Utopia PHP storage for OOS and then create a PR there. After the PR has been merged we need to implement it in the appwrite. If I am somewhat correct I would love to give this issue a try.

**Comment by Haimantika** [comment]
> I would like to work on this, but this will take some time and I will require some guidance too.

Hi @SaketKaswa20 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:
1. Please update us with your progress every 3 days, so that we know that you are working on it.
2. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
> What I understood here is that, we need to implement Oracle Object Storage and Utopia PHP storage library. First we need to create an adapter on Utopia PHP storage for OOS and then create a PR there. After the PR has been merged we need to implement it in the appwrite. If I am somewhat correct I would love to give this issue a try.

Hi, we assign issues on first-come first-serve basis, if Saket is unresponsive, we will assign it to you.

**Comment by Sreejit-Sengupto** [comment]
> somewhat

No problem, I'll try another issue.

**Comment by SaketKaswa20** [comment]
Hello, 
I went through the documentation and the Code of Conduct and Contributing Guidelines. Will do the needful and will surely let you know if any help is required.

**Comment by SaketKaswa20** [comment]
I am confused with the Oracle Object Storage part. It would be great if someone could help me😶‍🌫️

**Comment by Sreejit-Sengupto** [comment]
> I am confused with the Oracle Object Storage Adapter part. It would be great if someone could help me😶‍🌫️

Have you tried understanding the docs?

**Comment by SaketKaswa20** [comment]
Yes, I did read them and understood them well enough.

**Comment by SaketKaswa20** [comment]
Got it!

**Comment by SaketKaswa20** [comment]
Made a PR in utopia-php/storage, it is yet to be reviewed.

**Comment by SaketKaswa20** [comment]
My PR is not reviewed yet!

**Comment by Haimantika** [comment]
> My PR is not reviewed yet!

Can you link the issue to the PR?

**Comment by SaketKaswa20** [comment]
https://github.com/utopia-php/storage/pull/91

**Comment by Haimantika** [comment]
> [utopia-php/storage#91](https://github.com/utopia-php/storage/pull/91)

Thanks, please also update the description in the PR for easy review :)

**Comment by SaketKaswa20** [comment]
Sure :)

**Comment by tessamero** [comment]
Closing issue, as the PR was closed. Thank you for participating in Hacktoberfest this year.

**Comment by iSuslov** [comment]
@christyjacob4 should it be reopened? Supporting Oracle Cloud is still a thing
