### ISSUE TITLE
🗄️ Extend Appwrite Storage with Swiftstack Adapter

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/appwrite#6416]
# 💭 Introduction

Appwrite Storage lets you upload images, videos, or any kind of file and store it for later. This comes with support for encryption, compression, chunk upload, resumable upload, and much more! 💪 To learn more, check out our official [Appwrite Storage docs](https://appwrite.io/docs/storage).

Every file uploaded to Appwrite Storage needs to be stored somewhere, whether that is your server’s hard drive or cloud provider. To make this possible, Appwrite uses storage adapters that each implement simple methods such as `read()`, `move()`, `delete()`...

Your task is to implement support for **Swiftstack** in Appwrite and the Utopia PHP storage library. We have prepared detailed documentation on [how to create Utopia PHP storage adapter](https://github.com/utopia-php/storage/blob/main/docs/adding-new-storage-adapter.md), and [how to use Utopia PHP adapter in Appwrite](https://github.com/appwrite/appwrite/blob/master/docs/tutorials/add-storage-adapter.md). Please read these documents and ensure you understand it before working on this issue.

### 🎯 Requirements

- Experience with Appwrite.
- Experience with PHP.
- Experience with **Swiftstack**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP storage adapter for **Swiftstack**.
- [ ]  Submit a pull request in [utopia-php/storage](https://github.com/utopia-php/storage).
- [ ]  Implement Appwrite support for **Swiftstack**.
- [ ]  Submit a pull request in [appwrite/appwrite](https://github.com/appwrite/appwrite).
- [ ]  Write a blog post on any platform of your choosing to demonstrate the usage of your adapter!

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by kanugurajesh** [comment]
can you assign me the issue

**Comment by tessamero** [comment]
hi @kanugurajesh , you've been assigned to the issue. Please keep us updated every 3 days so we know you are still working on it, so the issue doesn't get reassigned :)

happy coding 😃

**Comment by Madhesh-V** [comment]
can you assign me the issue 😊

**Comment by anmol957** [comment]
hi, can you assign me the issue? ready to work on it.

**Comment by arishma108** [comment]
hi, can I get an issue assigned to me.

**Comment by Aryan9592** [comment]
@arishma108 It's good that many people show their interest in solving issues and making their contributions in these Amazing repositories, But the main thing you need to keep in mind is how to do this all in a professional way. That comes along with open-source contributions, it's not like just making a Pull Request..it's more than that. Try keeping a presence of mind and not being a trouble for the maintainers.
This wasn't just for you @arishma108, it was for both @Madhesh-V  and @anmol957. You three were well aware that this issue is been assigned and still you asked for it. Always keep integrity while typing or commenting on something when you are in a professional workspace.
Just take it as a learning opportunity..Have fun and Enjoy this hacktoberfest!

**Comment by rsowdepalli** [comment]
Can I assigned to work on it? ?

**Comment by Mannxxx** [comment]
Hey, can I get an issue assigned to me?

**Comment by nathanussk** [comment]
Hey, can I get an issue assigned to me?

**Comment by djv03** [comment]
cant agree more with what @Aryan9592 said. It is simply stated that this issue is already "assigned", even after that people are commenting for assignment of issue.
Please give a few a minute before making any comment. Dont just follow any youtube guru advice of "Just spam in all repos for assign the issue". This  is not how open source works folks.

**Comment by parthasarathy27** [comment]
can you assign me the issue

**Comment by Haimantika** [comment]
Hi @kanugurajesh is there an update from your end? It has been 4 days already. Will be assigning this issue to the next person in queue if you are not working on it :)

**Comment by djv03** [comment]
Hey @Haimantika  if @kanugurajesh is not continuing on this then I am willing to take this.

**Comment by Haimantika** [comment]
Hi @kanugurajesh reassigning this issue to the next person due to inactivity from your end. @Madhesh-V the issue is yours now, please update us every 3 days with your progress

**Comment by Madhesh-V** [comment]
thank you!

**Comment by FelixFelicis555** [comment]
I would like to work on this issue,Please assign the issue to me if either of them didn't respond?

**Comment by Haimantika** [comment]
> I would like to work on this issue,Please assign the issue to me if either of them didn't respond?

Hi, there's a queue for this issue and we are assigning on a first-come, first-serve basis.

**Comment by Haimantika** [comment]
> @Haimantika Day-3 Update: While working on the development of the Appwrite Storage with SwiftStack Adapter, I've made significant progress on the project. I've successfully created the **Swiftstack.php** and **SwiftstackTest.php** files, and I'm currently in the process of adding and testing additional functionality.
Hi, any updates?

**Comment by tessamero** [comment]
closing issue as hacktoberfest is over, thank you everyone who participated :)
