### ISSUE TITLE
💬 Improve Appwrite Messaging with 46elks

### ISSUE THREAD

**Issue by Haimantika** [appwrite/appwrite#6861]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **46elks** in the Utopia PHP messaging library. This goes under **SMS** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **46elks**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **SMS/46elks**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by DhairyaMajmudar** [comment]
@Haimantika  I would like to work on this. Can you assign it to me?

**Comment by Haimantika** [comment]
> @Haimantika I would like to work on this. Can you assign it to me?

Hi @DhairyaMajmudar have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by DhairyaMajmudar** [comment]
> > @Haimantika I would like to work on this. Can you assign it to me?
> 
> Hi @DhairyaMajmudar have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃
> 
> Notes:
> 
> Please update us with your progress every 3 days, so that we know that you are working on it. Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

Thank You so much for assigning me this issue 🙏

**Comment by DhairyaMajmudar** [comment]
I am a bit unfamiliar to 46elks It would be so nice of you if some are provided

**Comment by DhairyaMajmudar** [comment]
> @Haimantika Would like to work on this if it is unsolved

Sorry But I am working on this issue pls. check another one

**Comment by Haimantika** [comment]
> > @Haimantika Would like to work on this if it is unsolved
> 
> Sorry But I am working on this issue pls. check another one

Are you still working on it? I remember you mentioned that it is not supported in India

**Comment by DhairyaMajmudar** [comment]
> > > @Haimantika Would like to work on this if it is unsolved
> > 
> > 
> > Sorry But I am working on this issue pls. check another one
> 
> Are you still working on it? I remember you mentioned that it is not supported in India

Yes ma'am I have cloned the repo in my local system and also wrote the structural code as given in the docs. provided along with that I also emailed the 46elks support team for a dummy account. and below is their reply. Please suggest what requirement should I reply them back 

![image](https://github.com/appwrite/appwrite/assets/124715224/44e7500c-4508-4774-a26c-2b5dda13a541)

**Comment by DhairyaMajmudar** [comment]
> > > > > @Haimantika Would like to work on this if it is unsolved
> > > > 
> > > > 
> > > > Sorry But I am working on this issue pls. check another one
> > > 
> > > 
> > > Are you still working on it? I remember you mentioned that it is not supported in India
> > 
> > 
> > Yes ma'am I have cloned the repo in my local system and also wrote the structural code as given in the docs. provided along with that I also emailed the 46elks support team for a dummy account. and below is their reply. Please suggest what requirement should I reply them back
> > ![image](https://user-images.githubusercontent.com/124715224/274204896-44e7500c-4508-4774-a26c-2b5dda13a541.png)
> 
> I think they are asking for your personal details. Send them accordingly

And is there any specific countries where these SMS will be sent ?

**Comment by DhairyaMajmudar** [comment]
@Haimantika ma'am I have created a PR https://github.com/utopia-php/messaging/pull/54  pls. review it.

**Comment by DhairyaMajmudar** [comment]
@Haimantika ma'am my PR has been reviewed by @wess pls. consider merging it in the codebase 🙏

**Comment by adityaoberai** [comment]
Closing this issue. Thank you all so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
