### ISSUE TITLE
💬 Improve Appwrite Messaging with Gupshup

### ISSUE THREAD

**Issue by Haimantika** [appwrite/appwrite#6863]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Gupshup** in the Utopia PHP messaging library. This goes under **SMS** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Gupshup*.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **SMS/Gupshup**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by HarshitVashisht11** [comment]
I want to contribute in this can you assign this to me pls

**Comment by Haimantika** [comment]
> I want to contribute in this can you assign this to me pls

Hi @HarshitVashisht11 have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by biswajit287** [comment]
Hi, @Haimantika, I would like to go next. Thanks!

**Comment by Haimantika** [comment]
> hi @Haimantika i have made a PR . Please review my PR

Hi, we will take a look soon. Will request you to add a proper commit message.

**Comment by iamabhiCH** [comment]
Hello @Haimantika  I want to contribute to fix this issue. Please assign this to me.

**Comment by nick2432** [comment]
Hi, I would like to work on this, please assign this task to me. Thanks!

**Comment by Haimantika** [comment]
Hi @iamabhiCH @nick2432 , this issue has already been assigned and the assignee have raised a PR, please look for other issues

**Comment by HarshitVashisht11** [comment]
Hi @Haimantika Please review my PR

**Comment by umiloop** [comment]
@Haimantika can you please assign me to this issue

**Comment by adityaoberai** [comment]
Closing this issue. Thank you all so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
