### ISSUE TITLE
💬 Improve Appwrite Messaging with Termii

### ISSUE THREAD

**Issue by Haimantika** [appwrite/appwrite#6864]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Termii** in the Utopia PHP messaging library. This goes under **SMS** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Termii*.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **SMS/Termii**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by HarshitVashisht11** [comment]
I want to contribute so can you assign this to me

**Comment by biswajit287** [comment]
Hi @Haimantika, I would like to work on this. Can you please assign this to me. Thanks

**Comment by Haimantika** [comment]
> Hi @Haimantika, I would like to work on this. Can you please assign this to me. Thanks

Hi @biswajit287  have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

- Please update us with your progress every 3 days, so that we know that you are working on it.
- Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by IftequarIffu** [comment]
@Haimantika  Would like to take it up if unsolved

**Comment by VrajPatelGitHub** [comment]
@Haimantika I would like to work on this issue please assign these to me

**Comment by Haimantika** [comment]
Hi @biswajit287 do you have an update? I see you have made a draft PR with commits made last week. Are you still working on it?

**Comment by biswajit287** [comment]
Hey @Haimantika, 
I've made good progress on the integration and have completed the initial work. However, I am currently waiting for approval of the sender ID from Termii. I've already submitted the request, and once it's approved, I'll be ready to proceed with testing. I'll keep you updated on the progress.

**Comment by Haimantika** [comment]
> Hey @Haimantika, I've made good progress on the integration and have completed the initial work. However, I am currently waiting for approval of the sender ID from Termii. I've already submitted the request, and once it's approved, I'll be ready to proceed with testing. I'll keep you updated on the progress.

Cool, maybe you can raise a draft PR and keep working on it, that way we will know that you are actively working on it. :)

**Comment by tessamero** [comment]
@biswajit287 your PR is awaiting a follow up, time sensitive :)

**Comment by adityaoberai** [comment]
Closing this issue. Thank you all so much for participating in Hacktoberfest 2023! We can't wait to welcome you all during HF 2024! Stay tuned for a lot more amazing issues from the Appwrite team!
