### ISSUE TITLE
💬 Improve Appwrite Messaging with Telnyx

### ISSUE THREAD

**Issue by Haimantika** [appwrite/appwrite#6865]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Telnyx** in the Utopia PHP messaging library. This goes under **SMS** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Telnyx**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **SMS/Telnyx**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by 35C4n0r** [comment]
@Haimantika I would like to work on this Issue.

**Comment by ManasMadan** [comment]
Hi Please assign this to me under Hacktoberfest 2023.

**Comment by IftequarIffu** [comment]
I would like to work on this issue.

**Comment by kasrsu** [comment]
Hi..!  I would like to work on this issue well assign me to this issue

**Comment by Haimantika** [comment]
> @Haimantika I would like to work on this Issue.

Hi @35C4n0r  have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
Hi @ManasMadan @IftequarIffu @kasrsu we are assigning issues on a first-come, first-serve basis, if @35C4n0r decides to drop, the issue will go to you.

**Comment by nick2432** [comment]
Hi, I would like to work on this, please assign this task to me. Thanks!

**Comment by Haimantika** [comment]
> Hi, I would like to work on this, please assign this task to me. Thanks!

Hi, we are assigning issues on a first-come, first-serve basis. If the other users drop, we will assign it to you.

**Comment by 35C4n0r** [comment]
@Haimantika I think the integration for Telynx is already there under `SMS/` https://github.com/utopia-php/messaging/blob/main/src/Utopia/Messaging/Adapters/SMS/Telnyx.php

**Comment by Haimantika** [comment]
> @Haimantika I think the integration for Telynx is already there under `SMS/` https://github.com/utopia-php/messaging/blob/main/src/Utopia/Messaging/Adapters/SMS/Telnyx.php

Oh good catch! Thanks for bringing it up. Will be closing it :)
