### ISSUE TITLE
💬 Improve Appwrite Messaging with Infobip

### ISSUE THREAD

**Issue by Haimantika** [appwrite/appwrite#6867]
# 💭 Introduction

Having an app is cool, but having integrations is even cooler! 😎 It always brings a smile to my face when a website has the option to sign in with my GitHub account, so I don't have to go over the lengthy process of creating an account… The same can be said about messages! Every app with the option to enable push notifications, email, or SMS notifications gives the users confidence they won't miss anything important. We all have our channels we check the most, and having the ability to connect some app directly in there is always a positive.

Appwrite will use Utopia PHP messaging library to allow developers to get in touch with users using one of its many messaging adapters, such as Email, Discord, or Slack.

Since the messaging library supports adapters, there is always space for more. 😎 Each provider implements a method to send the message to the correct channel (usually using an HTTP request or a library) alongside a few configuration variables and methods to set what the adapter allows.

Your task is to implement support for **Infobip** in the Utopia PHP messaging library. This goes under **Email** category, so feel free to look at existing ones in the [adapters folder](https://github.com/utopia-php/messaging/tree/main/src/Utopia/Messaging/Adapters). We have prepared detailed documentation on [how to add a new messaging adapter](https://github.com/utopia-php/messaging/blob/main/docs/add-new-adapter.md). Please read the document and ensure you understand them before working on this issue.

### 🎯 Requirements

- Experience with PHP.
- Experience with **Infobip**.
- Experience with **[Docker](https://www.docker.com/)** and **[Docker Compose](https://docs.docker.com/compose/)**.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement Utopia PHP logger adapter for **Email/Infobip**.
- [ ]  Submit a pull request in [utopia-php/messaging](https://github.com/utopia-php/messaging/).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

**Comment by Cioraz** [comment]
Hey,
Can you assign me to this issue

**Comment by biswajit287** [comment]
hi @Haimantika, can you please assign this to me. Thanks

**Comment by Haimantika** [comment]
> Hey, Can you assign me to this issue

Hi @Cioraz have assigned the issue to you! Thank you for showing interest in contributing to Appwrite! Happy Hacktoberfest 🎃

Notes:

Please update us with your progress every 3 days, so that we know that you are working on it.
Join us on Discord - https://appwrite.io/discord to chat about Hacktoberfest and Appwrite!

**Comment by Haimantika** [comment]
> hi @Haimantika, can you please assign this to me. Thanks

We are assigning issues on a first-come, first-serve basis, if the other user goes idle, we will assign it to you.

**Comment by Cioraz** [comment]
Just a doubt,
For the headers 
![image](https://github.com/appwrite/appwrite/assets/76161837/b28a3ee7-a26a-4c5f-bc9c-901b5d2f7a22)

This is what the docs says
![image](https://github.com/appwrite/appwrite/assets/76161837/aad443d4-c7d3-4bd5-ad49-9f61344a0361)
So should all these be included in the headers of the API call? Or can i just include any of them?

**Comment by Haimantika** [comment]
> Just a doubt, For the headers ![image](https://user-images.githubusercontent.com/76161837/273689227-b28a3ee7-a26a-4c5f-bc9c-901b5d2f7a22.png)
> 
> This is what the docs says ![image](https://user-images.githubusercontent.com/76161837/273689152-aad443d4-c7d3-4bd5-ad49-9f61344a0361.png) So should all these be included in the headers of the API call? Or can i just include any of them?
You should be adding the required ones :)

**Comment by hasbullah-mughniy** [comment]
Assign me please

**Comment by nick2432** [comment]
Hi, I would like to work on this, please assign this task to me. Thanks!

**Comment by Haimantika** [comment]
Hi @hasbullah-mughniy 

> Hey I have sent a PR on the utopia messaging branch I'm not able to tag this issue here as it's in appwrite/appwrite but the PR is in the appwrite/messaging

Can you add the link here in the comments? Or attend our PR reviews on Discord :)

**Comment by Haimantika** [comment]
Hi @nick2432 @hasbullah-mughniy the assigned user has already raised a PR, please look for other issues

**Comment by Cioraz** [comment]
> Hi @hasbullah-mughniy
> 
> > Hey I have sent a PR on the utopia messaging branch I'm not able to tag this issue here as it's in appwrite/appwrite but the PR is in the appwrite/messaging
> 
> Can you add the link here in the comments? Or attend our PR reviews on Discord :)

Here,
https://github.com/utopia-php/messaging/pull/50

**Comment by readforgit** [comment]
Assign me please

**Comment by Haimantika** [comment]
> Assign me please

Hi, the assigned user has already worked on this issue. Please find a different one :)

**Comment by tessamero** [comment]
closing issue as hacktoberfest is over, thank you everyone who participated :)
