### ISSUE TITLE
🚀 Feature: Add Resend as a Messaging provider

### ISSUE THREAD

**Issue by third-eye-cyborg** [appwrite/appwrite#7721]
### 🔖 Feature description

Adding Resend for an SMTP provider integrations.

### 🎤 Pitch

Adding integrations to Appwrite Messaging. 

### Tasks

- [ ] Add an adapter in [utopia-php/messaging](https://github.com/utopia-php/messaging)
- [ ] Add create and update endpoints in Appwrite
- [ ] Update the worker in Appwrite to include the new provider
- [ ] Update the Console to include the new provider

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@third-eye-cyborg, thanks for creating this issue! 🙏🏼 It's best to use separate issues for each provider so that we can track it better. Feel free to create another one for OneSignal.

As for Resend, we do support [custom SMTP servers](https://appwrite.io/docs/products/messaging/smtp), so you should be able to use Resend with that.

**Comment by 7777chaitanya** [comment]
@stnguyen90 @third-eye-cyborg created [this issue](https://github.com/appwrite/appwrite/issues/7726) to track OneSignal intergration for Messaging.

**Comment by Crystora** [comment]
@stnguyen90 Can I pick this up? I can do it perfectly. please assign me.
thank you
