### ISSUE TITLE
🐛 Bug Report: Manually uploading file to bucket without permissions still adds permissions

### ISSUE THREAD

**Issue by BlackyWolf** [appwrite/appwrite#8250]
### 👟 Reproduction steps

1. Ensure a bucket and team have been created and the team given create access to the bucket
2. Register a user using the `appwrite` npm library
3. Sign user in
4. Add user to team manually through cloud.appwrite.io
5. Use the `appwrite` npm library to upload a file to the bucket with update, read, and delete permissions specifically for that user ID
6. Upload a file manually through cloud.appwrite.io without any permissions

I did manually upload the same file twice through cloud to see how appwrite would handle it, but I don't know if that would effect it.

### 👍 Expected behavior

The file added via user should be restricted to that user with the delete, update, and read permissions.
The manual file should not have any permissions on it whatsoever.

### 👎 Actual Behavior

The snippet below shows permissions have been added for the last user to upload a file via the npm library. In fact, I deleted the user to see if that would fix it and it did not, so a user with that ID doesn't exist anymore.

![image](https://github.com/appwrite/appwrite/assets/16546603/812766a7-3c52-427c-8df6-6c7822c89915)

### Tasks

- [ ] Update document creation to prevent Console user ID from being added to the document
- [ ] Update file creation to prevent Console user ID from being added to the file

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

Hosting: Cloud Appwrite 1.5.7
NPM: appwrite@^15.0.0
Framework: React@^18.2.0 w/ Vite@^5.2.0
IDE: VS Code 1.90

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@BlackyWolf, thanks for creating this issue! 🙏🏼 What you're describing seems like the expected behavior as described by our [docs](https://appwrite.io/docs/advanced/platform/permissions#default-values):

> If you create a resource using a Client SDK without explicit permissions, the creator will be granted read, update, and delete permissions on that resource by default.

If you don't want to grant the user permissions, you may pass an empty array.

Is there anything else you need or can this be closed?

**Comment by BlackyWolf** [comment]
I apologize for not being clear. I am manually uploading a file using the cloud.appwrite.io UI and it is being assigned a specific user's permissions from when I uploaded a file using a local react app.

**Comment by stnguyen90** [comment]
@BlackyWolf, are you using the same ID for both cases?

**Comment by BlackyWolf** [comment]
When I upload the file to the bucket from the local react app, I use the currently logged in user's ID.
When I log into the cloud.appwrite.io admin portal to upload the file, I leave the permissions blank.

If it's easier to show, I can record a screen capture of the process.

**Comment by BlackyWolf** [comment]
Here's the screen capture:

https://github.com/appwrite/appwrite/assets/16546603/7e52ee66-ed7e-40b1-b152-e24d3e3b6fa4

**Comment by stnguyen90** [comment]
@BlackyWolf, I'm pretty sure that's the ID of your Console account user since that's the user that created the file.

**Comment by BlackyWolf** [comment]
Ah, I see. I was able to confirm this on a separate project. Is there any way to prevent this without having to disable file security? My expectation was manipulating data by going through the cloud admin console would not affect permissions on said data by automatically applying permissions.

If not, since this is expected behavior, please feel free to close the issue.

**Comment by stnguyen90** [comment]
@BlackyWolf, it would definitely be cleaner if we don't add the Console user's ID to the permissions so I'll leave this open to address that.

That said, it shouldn't have much of an impact as without that added permission, no one would have access to the file (assuming they're not granted access at the bucket level).

**Comment by Souptik2001** [comment]
Hey @stnguyen90 I can take a shot at this.

**Comment by Souptik2001** [comment]
I already raised a PR, as this issue was abandoned for a long time. 😅

**Comment by itaeziosfw** [comment]
Hi! Can I take this issue?
I’m new to contributing and would love to help. Thanks

**Comment by HarshMN2345** [comment]
This works on main now. Closing, but reopen it if you still hit it.
